<!-- wp:wdl/paid-block-fv-10 {"mainTitle":"料金のご案内","backgroundImage":"https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/salon_04.webp","backgroundImageSp":"","filterBackgroundColor":"#e6dfe8","filterOpacity":1,"innerFilterBg":"#ffffff","innerFilterBorderColor":"#e2d8e4","innerFilterBorderWidth":1,"innerFilterBorderRadius":4,"innerFilterShadowColor":"rgba(61,34,63,0.10)","innerFilterShadowOffsetY":4,"innerFilterShadowBlur":12,"textColor":"#3d223f","minHeightPc":"min-h-pc-340px","minHeightTb":"min-h-tb-300px","minHeightSp":"min-h-sp-240px","titleFontSizeClass":"font_size_m"} -->
<div class="wp-block-wdl-paid-block-fv-10 paid-block-fv-10 min-h-pc-340px min-h-tb-300px min-h-sp-240px"><div class="fv-10_inner"><h1 class="ttl font_size_m" style="color:#3d223f"><span class="main" style="color:#3d223f">料金のご案内</span></h1><div class="inner_filter" style="background-color:#ffffff;border-color:#e2d8e4;border-width:1px;border-style:solid;border-radius:4px;box-shadow:0px 4px 12px 0px rgba(61,34,63,0.10)"></div></div><div class="filter" style="background-color:#e6dfe8;opacity:1"></div><picture class="bg_image"><source srcSet="" media="(max-width: 800px)"/><source srcSet="https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/salon_04.webp" media="(min-width: 801px)"/><img src="https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/salon_04.webp" alt="" loading="eager" fetchpriority="high"/></picture></div>
<!-- /wp:wdl/paid-block-fv-10 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":80,"tbHeight":64,"spHeight":40} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:80px"></div><div class="tb" style="height:64px"></div><div class="sp" style="height:40px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/custom-title-5 {"subTitle":"MENU","mainTitle":"施術の料金","headingLevel":2} -->
<h2 class="wp-block-wdl-custom-title-5 custom-title-5" style="border-color:var(--color-main)"><span class="sub" style="color:var(--color-main)">MENU</span><span class="main">施術の料金</span></h2>
<!-- /wp:wdl/custom-title-5 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":16,"tbHeight":16,"spHeight":12} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:16px"></div><div class="tb" style="height:16px"></div><div class="sp" style="height:12px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:paragraph {"align":"center","style":{"color":{"text":"#3c3540"},"typography":{"fontSize":"16px","lineHeight":"2"},"spacing":{"margin":{"top":"28px","bottom":"24px"}}}} -->
<p class="has-text-align-center has-text-color" style="color:#3c3540;font-size:16px;line-height:2;margin-top:28px;margin-bottom:24px">すべて税込みです。初回だけ、カウンセリングの30分が加わります（無料）。</p>
<!-- /wp:paragraph -->
<!-- wp:wdl/lw-pr-table-2 {"dtFixedPc":true,"dtWidthPc":260,"clm1FrPc":1,"clm2FrPc":2,"defaultSpClm1":true,"dlBorderColor":"#e2d8e4","dlBorderWidth":1,"rowBorderColor":"#e2d8e4","rowBorderWidth":1,"dtBorderColor":"#e2d8e4","dtBorderWidth":1,"dtBgColor":"#f5f0f6","dtTextColor":"#3d223f","ddTextColor":"#3c3540","cellPaddingPc":18,"fontSizePc":16,"fontSizeSp":15,"dtFontWeight":"600","rows":[{"dtText":"全身 60分","ddText":"\u003cstrong\u003e6,600円\u003c/strong\u003e　いちばん多く選ばれています。肩と腰を中心に、全身をひととおり。","pcClm1":null,"spClm1":null,"bgColor":"","textColor":""},{"dtText":"全身 90分","ddText":"\u003cstrong\u003e9,900円\u003c/strong\u003e　足のむくみや、頭のこわばりまで含めて。","pcClm1":null,"spClm1":null,"bgColor":"","textColor":""},{"dtText":"肩と首 40分","ddText":"\u003cstrong\u003e4,400円\u003c/strong\u003e　デスクワークの方向け。短い時間で肩まわりだけ。","pcClm1":null,"spClm1":null,"bgColor":"","textColor":""},{"dtText":"腰 40分","ddText":"\u003cstrong\u003e4,400円\u003c/strong\u003e　立ち仕事の方向け。腰から脚のつけ根まで。","pcClm1":null,"spClm1":null,"bgColor":"","textColor":""},{"dtText":"産後の方 60分","ddText":"\u003cstrong\u003e6,600円\u003c/strong\u003e　産後2か月以降から。お子さま連れでお越しいただけます。","pcClm1":null,"spClm1":null,"bgColor":"","textColor":""},{"dtText":"回数券（6回分）","ddText":"\u003cstrong\u003e36,300円\u003c/strong\u003e　60分6回ぶん（1回あたり6,050円）。期限は6か月です。","pcClm1":null,"spClm1":null,"bgColor":"","textColor":""}]} -->
<div class="wp-block-wdl-lw-pr-table-2 lw-pr-table-2" style="--table-2-dl-width-pc:100%;--table-2-dl-width-sp:100%;--table-2-grid-columns-pc:260px calc(100% - 260px);--table-2-grid-columns-sp:1fr 1fr;--table-2-dl-border-color:#e2d8e4;--table-2-dl-border-style:solid;--table-2-dl-border-width:1px;--table-2-dl-border-individual:0;--table-2-dl-border-top-color:#e2d8e4;--table-2-dl-border-top-style:solid;--table-2-dl-border-top-width:1px;--table-2-dl-border-bottom-color:#e2d8e4;--table-2-dl-border-bottom-style:solid;--table-2-dl-border-bottom-width:1px;--table-2-dl-border-left-color:#e2d8e4;--table-2-dl-border-left-style:solid;--table-2-dl-border-left-width:1px;--table-2-dl-border-right-color:#e2d8e4;--table-2-dl-border-right-style:solid;--table-2-dl-border-right-width:1px;--table-2-row-border-color:#e2d8e4;--table-2-row-border-style:solid;--table-2-row-border-width:1px;--table-2-dt-border-color:#e2d8e4;--table-2-dt-border-style:solid;--table-2-dt-border-width:1px;--table-2-dt-bg-color:#f5f0f6;--table-2-cell-padding-pc:18px;--table-2-cell-padding-sp:18px;--table-2-font-size-pc:16px;--table-2-font-size-sp:15px;--table-2-dt-align-pc:left;--table-2-dt-align-sp:left;--table-2-dd-align-pc:left;--table-2-dd-align-sp:left;--table-2-dt-text-color:#3d223f;--table-2-dd-text-color:#3c3540"><dl class="table-2__dl"><div class="table-2__row sp_clm_1"><dt class="table-2__dt"><p data-lw_font_set="" style="font-weight:600">全身 60分</p></dt><dd class="table-2__dd"><p data-lw_font_set=""><strong>6,600円</strong>　いちばん多く選ばれています。肩と腰を中心に、全身をひととおり。</p></dd></div><div class="table-2__row sp_clm_1"><dt class="table-2__dt"><p data-lw_font_set="" style="font-weight:600">全身 90分</p></dt><dd class="table-2__dd"><p data-lw_font_set=""><strong>9,900円</strong>　足のむくみや、頭のこわばりまで含めて。</p></dd></div><div class="table-2__row sp_clm_1"><dt class="table-2__dt"><p data-lw_font_set="" style="font-weight:600">肩と首 40分</p></dt><dd class="table-2__dd"><p data-lw_font_set=""><strong>4,400円</strong>　デスクワークの方向け。短い時間で肩まわりだけ。</p></dd></div><div class="table-2__row sp_clm_1"><dt class="table-2__dt"><p data-lw_font_set="" style="font-weight:600">腰 40分</p></dt><dd class="table-2__dd"><p data-lw_font_set=""><strong>4,400円</strong>　立ち仕事の方向け。腰から脚のつけ根まで。</p></dd></div><div class="table-2__row sp_clm_1"><dt class="table-2__dt"><p data-lw_font_set="" style="font-weight:600">産後の方 60分</p></dt><dd class="table-2__dd"><p data-lw_font_set=""><strong>6,600円</strong>　産後2か月以降から。お子さま連れでお越しいただけます。</p></dd></div><div class="table-2__row sp_clm_1"><dt class="table-2__dt"><p data-lw_font_set="" style="font-weight:600">回数券（6回分）</p></dt><dd class="table-2__dd"><p data-lw_font_set=""><strong>36,300円</strong>　60分6回ぶん（1回あたり6,050円）。期限は6か月です。</p></dd></div></dl></div>
<!-- /wp:wdl/lw-pr-table-2 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":80,"tbHeight":64,"spHeight":40} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:80px"></div><div class="tb" style="height:64px"></div><div class="sp" style="height:40px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/custom-title-5 {"subTitle":"OPTION","mainTitle":"追加でかかるもの","headingLevel":2} -->
<h2 class="wp-block-wdl-custom-title-5 custom-title-5" style="border-color:var(--color-main)"><span class="sub" style="color:var(--color-main)">OPTION</span><span class="main">追加でかかるもの</span></h2>
<!-- /wp:wdl/custom-title-5 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":16,"tbHeight":16,"spHeight":12} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:16px"></div><div class="tb" style="height:16px"></div><div class="sp" style="height:12px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/paid-block-lw-company-3 {"dtBackgroundColor":"#583559","borderColor":"#e2d8e4","ddTextColor":"#3c3540","spFullDt":true,"maxWidth":1040} -->
<div class="wp-block-wdl-paid-block-lw-company-3 paid-block-lw-company-3 font_size_m"><dl class="lw-company-3__inner" style="max-width:1040px;line-height:1.6"><div class="lw-company-3__row dt_width_m sp_clm_1"><dt class="lw-company-3__dt" style="background:#583559"><div class="lw-company-3__dt_text" data-lw_font_set="Murecho" style="font-weight:600;line-height:1.6">延長 10分</div><div class="lw-company-3__dt_arrow" style="background:#583559"></div></dt><dd class="lw-company-3__dd" data-lw_font_set="" style="color:#3c3540;border-color:#e2d8e4;line-height:1.6"><strong>1,100円</strong>　当日その場で決められます。前もってのお申し出は要りません。</dd></div><div class="lw-company-3__row dt_width_m sp_clm_1"><dt class="lw-company-3__dt" style="background:#583559"><div class="lw-company-3__dt_text" data-lw_font_set="Murecho" style="font-weight:600;line-height:1.6">お着替え</div><div class="lw-company-3__dt_arrow" style="background:#583559"></div></dt><dd class="lw-company-3__dd" data-lw_font_set="" style="color:#3c3540;border-color:#e2d8e4;line-height:1.6"><strong>無料</strong>　Tシャツとハーフパンツをご用意しています。手ぶらでお越しいただけます。</dd></div><div class="lw-company-3__row dt_width_m sp_clm_1"><dt class="lw-company-3__dt" style="background:#583559"><div class="lw-company-3__dt_text" data-lw_font_set="Murecho" style="font-weight:600;line-height:1.6">土日祝の指名</div><div class="lw-company-3__dt_arrow" style="background:#583559"></div></dt><dd class="lw-company-3__dd" data-lw_font_set="" style="color:#3c3540;border-color:#e2d8e4;line-height:1.6"><strong>550円</strong>　平日の指名は無料です。ご指名がなければどの日も追加はありません。</dd></div></dl></div>
<!-- /wp:wdl/paid-block-lw-company-3 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":24,"tbHeight":20,"spHeight":16} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:24px"></div><div class="tb" style="height:20px"></div><div class="sp" style="height:16px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:paragraph {"align":"center","style":{"color":{"text":"#5a5260"},"typography":{"fontSize":"14px","lineHeight":"1.9"},"spacing":{"margin":{"top":"16px","bottom":"0px"}}}} -->
<p class="has-text-align-center has-text-color" style="color:#5a5260;font-size:14px;line-height:1.9;margin-top:16px;margin-bottom:0px">※ 上記のほかにかかる費用はありません。物販のおすすめもしていません。</p>
<!-- /wp:paragraph -->
<!-- wp:wdl/lw-space-1 {"pcHeight":80,"tbHeight":64,"spHeight":40} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:80px"></div><div class="tb" style="height:64px"></div><div class="sp" style="height:40px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/custom-title-5 {"subTitle":"Q & A","mainTitle":"お金まわりのご質問","headingLevel":2} -->
<h2 class="wp-block-wdl-custom-title-5 custom-title-5" style="border-color:var(--color-main)"><span class="sub" style="color:var(--color-main)">Q & A</span><span class="main">お金まわりのご質問</span></h2>
<!-- /wp:wdl/custom-title-5 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":16,"tbHeight":16,"spHeight":12} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:16px"></div><div class="tb" style="height:16px"></div><div class="sp" style="height:12px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-pr-qa-2 {"maxWidth":900,"qTextFontSizePc":24,"qTextFontSizeSp":24} -->
<div class="wp-block-wdl-lw-pr-qa-2 lw-pr-qa-2" style="--qa-2-max-w:900px;--qa-2-dt-image-bd-color:#3c7fc3;--qa-2-dt-text-bg:#eaf4ff;--qa-2-dt-text-fontsize-pc:24px;--qa-2-dt-text-fontsize-sp:24px;--qa-2-dd-image-bd-color:#3c7fc3"><dl class="lw-pr-qa-2__wrap"><!-- wp:wdl/lw-pr-qa-2-item {"qImage":"https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/qa_q_01.webp","aImage":"https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/qa_a_01.webp","qText":"支払いに使えるものを教えてください"} -->
<div class="wp-block-wdl-lw-pr-qa-2-item lw-pr-qa-2__wrap__inner"><dt class="lw-pr-qa-2__q_wrap"><div class="lw-pr-qa-2__q_image"><img src="https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/qa_q_01.webp" alt=""/></div><div class="lw-pr-qa-2__q_text"><p class="text">支払いに使えるものを教えてください</p></div></dt><dd class="lw-pr-qa-2__a_wrap"><div class="lw-pr-qa-2__a_text"><!-- wp:paragraph {"style":{"color":{"text":"#3c3540"},"typography":{"fontSize":"16px","lineHeight":"1.9"}}} -->
<p class="has-text-color" style="color:#3c3540;font-size:16px;line-height:1.9">現金・クレジットカード・電子マネー・QRコード決済が使えます。回数券は現金かカードのみです。</p>
<!-- /wp:paragraph --></div><div class="lw-pr-qa-2__a_image"><img src="https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/qa_a_01.webp" alt=""/></div></dd></div>
<!-- /wp:wdl/lw-pr-qa-2-item -->
<!-- wp:wdl/lw-pr-qa-2-item {"qImage":"https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/qa_q_02.webp","aImage":"https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/qa_a_02.webp","qText":"回数券の期限が切れたらどうなりますか"} -->
<div class="wp-block-wdl-lw-pr-qa-2-item lw-pr-qa-2__wrap__inner"><dt class="lw-pr-qa-2__q_wrap"><div class="lw-pr-qa-2__q_image"><img src="https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/qa_q_02.webp" alt=""/></div><div class="lw-pr-qa-2__q_text"><p class="text">回数券の期限が切れたらどうなりますか</p></div></dt><dd class="lw-pr-qa-2__a_wrap"><div class="lw-pr-qa-2__a_text"><!-- wp:paragraph {"style":{"color":{"text":"#3c3540"},"typography":{"fontSize":"16px","lineHeight":"1.9"}}} -->
<p class="has-text-color" style="color:#3c3540;font-size:16px;line-height:1.9">6か月を過ぎた分は使えなくなりますが、事情がある場合はご相談ください。入院・出産・転勤の場合は期限を延ばしています。</p>
<!-- /wp:paragraph --></div><div class="lw-pr-qa-2__a_image"><img src="https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/qa_a_02.webp" alt=""/></div></dd></div>
<!-- /wp:wdl/lw-pr-qa-2-item -->
<!-- wp:wdl/lw-pr-qa-2-item {"qImage":"https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/qa_q_03.webp","aImage":"https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/qa_a_03.webp","qText":"保険は使えますか"} -->
<div class="wp-block-wdl-lw-pr-qa-2-item lw-pr-qa-2__wrap__inner"><dt class="lw-pr-qa-2__q_wrap"><div class="lw-pr-qa-2__q_image"><img src="https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/qa_q_03.webp" alt=""/></div><div class="lw-pr-qa-2__q_text"><p class="text">保険は使えますか</p></div></dt><dd class="lw-pr-qa-2__a_wrap"><div class="lw-pr-qa-2__a_text"><!-- wp:paragraph {"style":{"color":{"text":"#3c3540"},"typography":{"fontSize":"16px","lineHeight":"1.9"}}} -->
<p class="has-text-color" style="color:#3c3540;font-size:16px;line-height:1.9">使えません。当店は医療機関ではないため、すべて自費です。痛みが強い場合は、先に整形外科の受診をおすすめしています。</p>
<!-- /wp:paragraph --></div><div class="lw-pr-qa-2__a_image"><img src="https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/qa_a_03.webp" alt=""/></div></dd></div>
<!-- /wp:wdl/lw-pr-qa-2-item --></dl></div>
<!-- /wp:wdl/lw-pr-qa-2 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":80,"tbHeight":64,"spHeight":40} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:80px"></div><div class="tb" style="height:64px"></div><div class="sp" style="height:40px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-bg-1 {"backgroundType":"image","imagePc":"","imageSp":"","isFullWidth":true,"maxWidth":1040,"minHeightPc":"min-h-pc-150px","minHeightTb":"min-h-tb-160px","minHeightSp":"min-h-sp-160px","innerPaddingTopPc":80,"innerPaddingBottomPc":80,"innerPaddingLeftPc":40,"innerPaddingRightPc":40,"innerPaddingTopTb":64,"innerPaddingBottomTb":64,"innerPaddingLeftTb":32,"innerPaddingRightTb":32,"innerPaddingTopSp":48,"innerPaddingBottomSp":48,"innerPaddingLeftSp":20,"innerPaddingRightSp":20,"filterTypePc":"solid","filterColorPc":"#3d223f","opacityPc":1,"filterTypeTb":"solid","filterColorTb":"#3d223f","opacityTb":1,"filterTypeSp":"solid","filterColorSp":"#3d223f","opacitySp":1} -->
<div class="wp-block-wdl-lw-bg-1 lw-bg-1 min-h-pc-150px min-h-tb-160px min-h-sp-160px bg_all" style="--lw-bg-color-filter-pc:#3d223f;--lw-bg-opacity-pc:1;--lw-bg-color-filter-tb:#3d223f;--lw-bg-opacity-tb:1;--lw-bg-color-filter-sp:#3d223f;--lw-bg-opacity-sp:1;--lw-bg-position-pc:50% 50%;--lw-bg-position-sp:50% 50%;--lw-bg-wrap-centering-pc:center;--lw-bg-wrap-align-pc:center;--lw-bg-wrap-centering-tb:center;--lw-bg-wrap-align-tb:center;--lw-bg-wrap-centering-sp:center;--lw-bg-wrap-align-sp:center"><div class="lw-bg-1-wrap" style="--lw-bg-padding-top-pc:80px;--lw-bg-padding-bottom-pc:80px;--lw-bg-padding-left-pc:40px;--lw-bg-padding-right-pc:40px;--lw-bg-padding-top-tb:64px;--lw-bg-padding-bottom-tb:64px;--lw-bg-padding-left-tb:32px;--lw-bg-padding-right-tb:32px;--lw-bg-padding-top-sp:48px;--lw-bg-padding-bottom-sp:48px;--lw-bg-padding-left-sp:20px;--lw-bg-padding-right-sp:20px;--lw-bg-max-width:1040px"><!-- wp:heading {"level":3,"style":{"color":{"text":"#ffffff"},"typography":{"fontSize":"26px","lineHeight":"1.6"},"spacing":{"margin":{"top":"0px","bottom":"16px"}}},"textAlign":"center"} -->
<h3 class="has-text-align-center has-text-color" style="color:#ffffff;font-size:26px;line-height:1.6;margin-top:0px;margin-bottom:16px">はじめての方は、まず60分をお試しください</h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"style":{"color":{"text":"#e6dcea"},"typography":{"fontSize":"16px","lineHeight":"2"}},"align":"center"} -->
<p class="has-text-align-center has-text-color" style="color:#e6dcea;font-size:16px;line-height:2">体の状態をうかがう時間（30分）を無料でお付けしています。合わなければ1回で結構です。</p>
<!-- /wp:paragraph -->
<!-- wp:wdl/lw-space-1 {"pcHeight":24,"tbHeight":20,"spHeight":16} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:24px"></div><div class="tb" style="height:20px"></div><div class="sp" style="height:16px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-pr-button-4 {"textMain":"000-000-0000","textSub":"受付時間 9:00〜20:00（木曜定休）","btnUrl":"tel:0000000000","btnAlign":"center","bgColor":"#7a4a7c","bgColorHover":"#5d3760","textColorMain":"#ffffff","borderWidth":0,"borderRadius":6} -->
<div class="wp-block-wdl-lw-pr-button-4 lw-pr-button-4"><div class="wrap_btn center"><a href="tel:0000000000" class="lw_btn_a " style="--hover-bg:#5d3760;--transition-duration:0.3s;--max-width-sp:480px;--shake-interval:3s;--font-size-main:28px;--font-size-main-sp:18px;--font-size-sub:14px;--letter-spacing:0.05em;max-width:580px;padding:1.2em 1.5em;background:#7a4a7c;border:0px solid #000000;border-radius:6px;box-shadow:0px 0px 6px rgba(0, 0, 0, 0.2)"><span class="text_main" style="color:#ffffff;font-weight:500;font-size:28px;letter-spacing:0.05em" data-lw_font_set=""><span class="icon" style="fill:#ffffff;width:32px;margin-right:8px;margin-left:-8px"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M164.9 24.6c-7.7-18.6-28-28.5-47.4-23.2l-88 24C12.1 30.2 0 46 0 64C0 311.4 200.6 512 448 512c18 0 33.8-12.1 38.6-29.5l24-88c5.3-19.4-4.6-39.7-23.2-47.4l-96-40c-16.3-6.8-35.2-2.1-46.3 11.6L304.7 368C234.3 334.7 177.3 277.7 144 207.3L193.3 167c13.7-11.2 18.4-30 11.6-46.3l-40-96z"/></svg></span>000-000-0000</span><span class="text_sub" style="color:#ffffff;font-weight:500;font-size:14px" data-lw_font_set="">受付時間 9:00〜20:00（木曜定休）</span></a></div></div>
<!-- /wp:wdl/lw-pr-button-4 --></div></div>
<!-- /wp:wdl/lw-bg-1 -->