<!-- wp:wdl/lw-pr-fv-23 {"backgroundType":"image","imageUrlPc":"https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/yg_fv.webp","imageUrlSp":"","imageAlt":"朝の光が入るヨガスタジオ","bgColor":"#17342a","filterColor":"#17342a","filterOpacity":0.86,"maxWidth":1120,"cardWidth":340,"showEyebrow":true,"eyebrow":"5日間・1本5分・無料","eyebrowColor":"#bfcac5","headingLevel":1,"mainTitle":"朝の5分を、\u003cbr\u003e5日間だけ試しませんか","titleColor":"#ffffff","titleFontWeight":"700","titleFontSizePc":40,"titleFontSizeSp":27,"description":"毎朝1本、5分の動画が届きます。5日目で終わりです。続きをお買い求めくださいとは申しません。","descriptionColor":"#dde3e0","showBenefits":true,"benefitItems":[{"text":"1本5分。マットが無くてもできます"},{"text":"体がかたい方から始められる順です"},{"text":"5日で終わります。延長はありません"}],"benefitTextColor":"#ffffff","benefitMarkColor":"#17342a","benefitMarkBgColor":"#aebbb6","buttonText":"無料で受け取る","buttonSub":"登録は30秒で終わります","buttonUrl":"#uketoru","buttonLinkType":"url","buttonPageId":0,"buttonCategoryId":0,"buttonOpenNewTab":false,"ctaBgColor":"#ffffff","ctaTextColor":"#1b3229","ctaSubColor":"#1b3229","ctaBorderRadius":8,"cardBgColor":"#ffffff","cardTextColor":"#2f342f","cardBorderColor":"#dde5df","cardBorderRadius":12,"showQr":true,"qrUrl":"https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/qr_sample_01.webp","qrAlt":"登録用のQRコード（見本）","qrSize":180,"qrCaption":"スマホのカメラをかざしてください","showQrOnSp":false,"showAccount":true,"accountLabel":"ID","accountName":"@your-studio","noteText":"登録は無料です。5日目のあとは自動で終わります。","noteColor":"#aab8b2","minHeightPc":"min-h-pc-520px","minHeightTb":"min-h-tb-440px","minHeightSp":""} -->
<div class="wp-block-wdl-lw-pr-fv-23 lw-pr-fv-23 bg_image qr_off_sp" style="--fv23-bg:#17342a;--fv23-filter-color:#17342a;--fv23-filter-opacity:0.86;--fv23-max-width:1120px;--fv23-card-width:340px;--fv23-eyebrow-color:#bfcac5;--fv23-title-color:#ffffff;--fv23-title-weight:700;--fv23-title-size-pc:40px;--fv23-title-size-sp:27px;--fv23-description-color:#dde3e0;--fv23-benefit-color:#ffffff;--fv23-benefit-mark:#17342a;--fv23-benefit-mark-bg:#aebbb6;--fv23-cta-bg:#ffffff;--fv23-cta-text:#1b3229;--fv23-cta-sub:#1b3229;--fv23-cta-radius:8px;--fv23-card-bg:#ffffff;--fv23-card-text:#2f342f;--fv23-card-border:#dde5df;--fv23-card-radius:12px;--fv23-qr-size:180px;--fv23-note-color:#aab8b2"><div class="bg_filter"><div class="bg_filter_inner"></div><picture><source srcSet="https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/yg_fv.webp" media="(max-width: 800px)"/><source srcSet="https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/yg_fv.webp" media="(min-width: 801px)"/><img src="https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/yg_fv.webp" alt="朝の光が入るヨガスタジオ"/></picture></div><div class="fv23_inner min-h-pc-520px min-h-tb-440px"><div class="lead_side"><p class="eyebrow">5日間・1本5分・無料</p><h1 class="main_ttl" data-lw_font_set="">朝の5分を、<br>5日間だけ試しませんか</h1><p class="description">毎朝1本、5分の動画が届きます。5日目で終わりです。続きをお買い求めくださいとは申しません。</p><ul class="benefit_list"><li><i>✓</i><span>1本5分。マットが無くてもできます</span></li><li><i>✓</i><span>体がかたい方から始められる順です</span></li><li><i>✓</i><span>5日で終わります。延長はありません</span></li></ul><a class="cta_btn" href="#uketoru">無料で受け取る<small>登録は30秒で終わります</small></a><p class="note">登録は無料です。5日目のあとは自動で終わります。</p></div><div class="join_card"><span class="qr_box"><img src="https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/qr_sample_01.webp" alt="登録用のQRコード（見本）" width="180" height="180"/></span><p class="qr_caption">スマホのカメラをかざしてください</p><p class="account"><b>ID</b><span>@your-studio</span></p></div></div></div>
<!-- /wp:wdl/lw-pr-fv-23 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":80,"tbHeight":64,"spHeight":40} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:80px"></div><div class="tb" style="height:64px"></div><div class="sp" style="height:40px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/paid-block-custom-title-9 {"subTitle":"TIMETABLE","mainTitle":"5日間の時間割","headingLevel":2,"mainTitleColor":"#17342a","borderTopColor":"#2a4d3f","borderBottomColor":"#2a4d3f","borderTopOpacity":100,"borderBottomOpacity":25,"borderRadius":8,"sizeClass":"size_m"} -->
<div class="wp-block-wdl-paid-block-custom-title-9 paid-block-custom-title-9 size_m"><h2 class="ttl"><span class="sub" style="color:#17342a">TIMETABLE</span><span class="main">5日間の時間割</span><span class="border_wrap" style="border-radius:8px"><span class="border_inner"><span class="border top" style="background-color:#2a4d3f;opacity:1"></span><span class="border bottom" style="background-color:#2a4d3f;opacity:0.25"></span></span></span></h2></div>
<!-- /wp:wdl/paid-block-custom-title-9 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":16,"tbHeight":16,"spHeight":12} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:16px"></div><div class="tb" style="height:16px"></div><div class="sp" style="height:12px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:paragraph {"align":"center","style":{"color":{"text":"#2f342f"},"typography":{"fontSize":"16px","lineHeight":"2"},"spacing":{"margin":{"top":"28px","bottom":"24px"}}}} -->
<p class="has-text-align-center has-text-color" style="color:#2f342f;font-size:16px;line-height:2;margin-top:28px;margin-bottom:24px">何日目に何が届くかを、先に全部お見せします。<span class="lw-br on_500px"></span>見てから決めていただいて構いません。</p>
<!-- /wp:paragraph -->
<!-- wp:wdl/paid-block-history-1 {"yearText":"朝6時","yearTag":"h3","pointColor":"#ffffff","pointBorderColor":"#2a4d3f","colorDt":"#17342a","colorDd":"#2f342f"} -->
<div class="wp-block-wdl-paid-block-history-1 paid-block-history-1" id="jikanwari"><div class="history__year" aria-labelledby="y6"><div class="history__point" style="background:#ffffff;border-color:#2a4d3f"></div><h3 class="history__year-heading" data-lw_font_set="">朝6時</h3><dl class="history__events"><div class="history__events_row"><dt class="history__dt"><time datetime="①" data-lw_font_set="" style="color:#17342a">①</time></dt><dd class="history__dd" data-lw_font_set="" style="color:#2f342f">1日目｜呼吸だけ（5分）。動きはありません。座ったままで大丈夫です。</dd></div><div class="history__events_row"><dt class="history__dt"><time datetime="②" data-lw_font_set="" style="color:#17342a">②</time></dt><dd class="history__dd" data-lw_font_set="" style="color:#2f342f">2日目｜肩と首（6分）。机に向かう時間が長い方から、いちばん反応があります。</dd></div><div class="history__events_row"><dt class="history__dt"><time datetime="③" data-lw_font_set="" style="color:#17342a">③</time></dt><dd class="history__dd" data-lw_font_set="" style="color:#2f342f">3日目｜腰まわり（5分）。床に寝られない方のために、椅子でできる形も入れています。</dd></div><div class="history__events_row"><dt class="history__dt"><time datetime="④" data-lw_font_set="" style="color:#17342a">④</time></dt><dd class="history__dd" data-lw_font_set="" style="color:#2f342f">4日目｜股関節（6分）。ここがいちばんかたい方が多い場所です。無理に開きません。</dd></div><div class="history__events_row"><dt class="history__dt"><time datetime="⑤" data-lw_font_set="" style="color:#17342a">⑤</time></dt><dd class="history__dd" data-lw_font_set="" style="color:#2f342f">5日目｜4日ぶんを通して（8分）。ここで終わりです。6日目は届きません。</dd></div></dl></div></div>
<!-- /wp:wdl/paid-block-history-1 -->
<!-- wp:paragraph {"align":"center","style":{"color":{"text":"#566058"},"typography":{"fontSize":"14px","lineHeight":"1.9"},"spacing":{"margin":{"top":"24px","bottom":"0px"}}}} -->
<p class="has-text-align-center has-text-color" style="color:#566058;font-size:14px;line-height:1.9;margin-top:24px;margin-bottom:0px">※ 動画は届いたあともいつでもご覧いただけます。日数・時間はすべて架空の記載です。</p>
<!-- /wp:paragraph -->
<!-- wp:wdl/lw-space-1 {"pcHeight":80,"tbHeight":64,"spHeight":40} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:80px"></div><div class="tb" style="height:64px"></div><div class="sp" style="height:40px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/paid-block-custom-title-9 {"subTitle":"FOR YOU","mainTitle":"向いている方・向いていない方","headingLevel":2,"mainTitleColor":"#17342a","borderTopColor":"#2a4d3f","borderBottomColor":"#2a4d3f","borderTopOpacity":100,"borderBottomOpacity":25,"borderRadius":8,"sizeClass":"size_m"} -->
<div class="wp-block-wdl-paid-block-custom-title-9 paid-block-custom-title-9 size_m"><h2 class="ttl"><span class="sub" style="color:#17342a">FOR YOU</span><span class="main">向いている方・向いていない方</span><span class="border_wrap" style="border-radius:8px"><span class="border_inner"><span class="border top" style="background-color:#2a4d3f;opacity:1"></span><span class="border bottom" style="background-color:#2a4d3f;opacity:0.25"></span></span></span></h2></div>
<!-- /wp:wdl/paid-block-custom-title-9 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":16,"tbHeight":16,"spHeight":12} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:16px"></div><div class="tb" style="height:16px"></div><div class="sp" style="height:12px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-pr-goodbad-1 {"goodTitle":"向いています","goodItems":["体がかたいと思っている","運動をやめて何年も経っている","朝の時間なら5分だけ取れる","いきなりスタジオに行くのは気が重い"],"badTitle":"向いていません","badItems":["いま痛みがあり、治療を受けている","短い期間で体を絞りたい","強度の高い運動を探している","妊娠中・産後まもない（別のご案内があります）"],"goodMark":"○","badMark":"!","layout":"side","maxWidth":940,"fontSize":15.5,"titleFontSize":17,"textColor":"#2f342f","goodBgColor":"#f1f6f2","goodBorderColor":"#cfe0d5","goodTitleColor":"#2a4d3f","badBgColor":"#f7f4f0","badBorderColor":"#e2d9cd","badTitleColor":"#7a5a34"} -->
<div class="wp-block-wdl-lw-pr-goodbad-1 lw-pr-goodbad-1 is-side" style="margin-top:0px;margin-bottom:0px;--gb1-max-width:940px;--gb1-radius:10px;--gb1-border-w:1px;--gb1-size:15.5px;--gb1-size-sp:14px;--gb1-title-size:17px"><div class="lw-pr-goodbad-1__cols"><div class="lw-pr-goodbad-1__col is-good" style="background-color:#f1f6f2;border-color:#cfe0d5"><p class="lw-pr-goodbad-1__title" style="color:#2a4d3f" data-lw_font_set="">向いています</p><ul class="lw-pr-goodbad-1__list"><li><span class="lw-pr-goodbad-1__mark" style="color:#2a4d3f">○</span><span class="lw-pr-goodbad-1__text" style="color:#2f342f">体がかたいと思っている</span></li><li><span class="lw-pr-goodbad-1__mark" style="color:#2a4d3f">○</span><span class="lw-pr-goodbad-1__text" style="color:#2f342f">運動をやめて何年も経っている</span></li><li><span class="lw-pr-goodbad-1__mark" style="color:#2a4d3f">○</span><span class="lw-pr-goodbad-1__text" style="color:#2f342f">朝の時間なら5分だけ取れる</span></li><li><span class="lw-pr-goodbad-1__mark" style="color:#2a4d3f">○</span><span class="lw-pr-goodbad-1__text" style="color:#2f342f">いきなりスタジオに行くのは気が重い</span></li></ul></div><div class="lw-pr-goodbad-1__col is-bad" style="background-color:#f7f4f0;border-color:#e2d9cd"><p class="lw-pr-goodbad-1__title" style="color:#7a5a34" data-lw_font_set="">向いていません</p><ul class="lw-pr-goodbad-1__list"><li><span class="lw-pr-goodbad-1__mark" style="color:#7a5a34">!</span><span class="lw-pr-goodbad-1__text" style="color:#2f342f">いま痛みがあり、治療を受けている</span></li><li><span class="lw-pr-goodbad-1__mark" style="color:#7a5a34">!</span><span class="lw-pr-goodbad-1__text" style="color:#2f342f">短い期間で体を絞りたい</span></li><li><span class="lw-pr-goodbad-1__mark" style="color:#7a5a34">!</span><span class="lw-pr-goodbad-1__text" style="color:#2f342f">強度の高い運動を探している</span></li><li><span class="lw-pr-goodbad-1__mark" style="color:#7a5a34">!</span><span class="lw-pr-goodbad-1__text" style="color:#2f342f">妊娠中・産後まもない（別のご案内があります）</span></li></ul></div></div></div>
<!-- /wp:wdl/lw-pr-goodbad-1 -->
<!-- wp:paragraph {"align":"center","style":{"color":{"text":"#566058"},"typography":{"fontSize":"14px","lineHeight":"1.9"},"spacing":{"margin":{"top":"24px","bottom":"0px"}}}} -->
<p class="has-text-align-center has-text-color" style="color:#566058;font-size:14px;line-height:1.9;margin-top:24px;margin-bottom:0px">※ 痛みのある方は、まずお医者さんにご相談ください。この講座は治療ではありません。</p>
<!-- /wp:paragraph -->
<!-- wp:wdl/lw-message-1 {"subTitle":"message","mainTitle":"この5日間をつくった理由","leadText":"「かたいから、まだ行けません」と\n何年もおっしゃる方がいます。","bodyText":"スタジオに来ていただく前に、家で5分だけ試せるものがあればいいのに、とずっと思っていました。かたいまま来ていただいて構わないのですが、そう申し上げても、その一歩は重いままです。\nだから、いちばん軽い5日間だけを切り出しました。5日で終わりますし、このあとに何かをお売りすることもありません。合わないと思われたら、そのままにしていただいて大丈夫です。","imgUrl":"https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/voice_01.webp","imgAlt":"講師の写真","captionSub":"インストラクター","captionMain":"佐藤 めぐみ（見本）","colorMain":"#2a4d3f","filterOpacity":0.06,"maxWidth":1040,"alignLeft":false} -->
<div class="wp-block-wdl-lw-message-1 lw-message-1"><div class="lw-message-1__wrap" style="max-width:1040px"><div class="text__in"><h3 class="title"><div class="sub" style="color:#2a4d3f">message</div><div class="main">この5日間をつくった理由</div></h3><p class="lead" style="color:#2a4d3f">「かたいから、まだ行けません」と<br />何年もおっしゃる方がいます。</p><p class="description">スタジオに来ていただく前に、家で5分だけ試せるものがあればいいのに、とずっと思っていました。かたいまま来ていただいて構わないのですが、そう申し上げても、その一歩は重いままです。<br />だから、いちばん軽い5日間だけを切り出しました。5日で終わりますし、このあとに何かをお売りすることもありません。合わないと思われたら、そのままにしていただいて大丈夫です。</p></div><div class="image"><figure class="img"><img loading="lazy" src="https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/voice_01.webp" alt="講師の写真"/></figure><figcaption class="img_caption"><span class="sub">インストラクター</span><span class="main">佐藤 めぐみ（見本）</span></figcaption></div></div><div class="bg_filter" style="opacity:0.06;background-color:#2a4d3f"></div></div>
<!-- /wp:wdl/lw-message-1 -->
<!-- wp:wdl/lw-voice-1 {"h2Title":"受け取った方から","h2TextColor":"#17342a","h2FontWeight":"600","nameTextColor":"#ffffff","nameBackgroundColor":"#2a4d3f","h3TextColor":"#17342a","pTextColor":"#2f342f","backgroundColor":"#f1f6f2"} -->
<div class="wp-block-wdl-lw-voice-1 lw-voice-1" style="background-color:#f1f6f2"><h2 class="lw-voice-1__title" style="font-weight:600;color:#17342a" data-lw_font_set="Noto Sans JP">受け取った方から</h2><ul class="lw-voice-1__ul"><li class="lw-voice-1__li"><div class="lw-voice-1__name" style="background-color:#2a4d3f;color:#ffffff;font-weight:500" data-lw_font_set="Noto Sans JP">40代 女性</div><div class="lw-voice-1__text"><h3 style="color:#17342a;font-weight:500" data-lw_font_set="Noto Sans JP">1日目が呼吸だけで安心しました。</h3><p style="color:#2f342f;font-weight:500" data-lw_font_set="Noto Sans JP">初日から動かされると思っていたので、座ったままで終わったのが逆に良かったです。2日目からは自然に続けられました。</p></div></li><li class="lw-voice-1__li"><div class="lw-voice-1__name" style="background-color:#2a4d3f;color:#ffffff;font-weight:500" data-lw_font_set="Noto Sans JP">50代 男性</div><div class="lw-voice-1__text"><h3 style="color:#17342a;font-weight:500" data-lw_font_set="Noto Sans JP">5日で終わると書いてあったので登録しました。</h3><p style="color:#2f342f;font-weight:500" data-lw_font_set="Noto Sans JP">いつまで届くか分からないものは登録しないようにしています。終わりが決まっていたので気楽でした。実際、6日目は届きませんでした。</p></div></li><li class="lw-voice-1__li"><div class="lw-voice-1__name" style="background-color:#2a4d3f;color:#ffffff;font-weight:500" data-lw_font_set="Noto Sans JP">30代 女性</div><div class="lw-voice-1__text"><h3 style="color:#17342a;font-weight:500" data-lw_font_set="Noto Sans JP">椅子でできる形が入っていたのが助かりました。</h3><p style="color:#2f342f;font-weight:500" data-lw_font_set="Noto Sans JP">床に寝るのが億劫で続かなかったのですが、椅子の形なら朝の支度の合間にできました。</p></div></li></ul></div>
<!-- /wp:wdl/lw-voice-1 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":80,"tbHeight":64,"spHeight":40} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:80px"></div><div class="tb" style="height:64px"></div><div class="sp" style="height:40px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/paid-block-custom-title-9 {"subTitle":"FAQ","mainTitle":"よくあるご質問","headingLevel":2,"mainTitleColor":"#17342a","borderTopColor":"#2a4d3f","borderBottomColor":"#2a4d3f","borderTopOpacity":100,"borderBottomOpacity":25,"borderRadius":8,"sizeClass":"size_m"} -->
<div class="wp-block-wdl-paid-block-custom-title-9 paid-block-custom-title-9 size_m"><h2 class="ttl"><span class="sub" style="color:#17342a">FAQ</span><span class="main">よくあるご質問</span><span class="border_wrap" style="border-radius:8px"><span class="border_inner"><span class="border top" style="background-color:#2a4d3f;opacity:1"></span><span class="border bottom" style="background-color:#2a4d3f;opacity:0.25"></span></span></span></h2></div>
<!-- /wp:wdl/paid-block-custom-title-9 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":16,"tbHeight":16,"spHeight":12} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:16px"></div><div class="tb" style="height:16px"></div><div class="sp" style="height:12px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-pr-qa-3 {"maxWidth":900,"qLabelColor":"#1e372d","aLabelColor":"#566058","lineColor":"#dde5df"} -->
<div class="wp-block-wdl-lw-pr-qa-3 lw-pr-qa-3" style="--qa3-max-w:900px;--qa3-gap:24px;--qa3-label-w:32px;--qa3-q-color:#1e372d;--qa3-a-color:#566058;--qa3-line:#dde5df;--qa3-label-size-pc:18px;--qa3-label-size-sp:16px;--qa3-q-size-pc:17px;--qa3-q-size-sp:15px;--qa3-a-size-pc:15px;--qa3-a-size-sp:14px"><dl class="qa-3__item"><dt><span class="label" data-lw_font_set="Roboto">Q</span><p class="qa-3__q_text">本当に無料ですか。あとから請求されませんか。</p></dt><dd><span class="label" data-lw_font_set="Roboto">A</span><p class="qa-3__a_text">無料です。お支払いの手続きはどこにもありません。クレジットカードの番号もうかがいません。</p></dd></dl><dl class="qa-3__item"><dt><span class="label" data-lw_font_set="Roboto">Q</span><p class="qa-3__q_text">5日が終わったら、勧誘が来ますか。</p></dt><dd><span class="label" data-lw_font_set="Roboto">A</span><p class="qa-3__a_text">5日目のあとに1通だけ「スタジオのご案内」をお送りします。それで終わりです。不要とお知らせいただければ、その1通も止めます。</p></dd></dl><dl class="qa-3__item"><dt><span class="label" data-lw_font_set="Roboto">Q</span><p class="qa-3__q_text">見られなかった日があっても大丈夫ですか。</p></dt><dd><span class="label" data-lw_font_set="Roboto">A</span><p class="qa-3__a_text">大丈夫です。届いた動画はあとからでもご覧いただけます。順番どおりでなくても構いません。</p></dd></dl><dl class="qa-3__item"><dt><span class="label" data-lw_font_set="Roboto">Q</span><p class="qa-3__q_text">マットや道具が要りますか。</p></dt><dd><span class="label" data-lw_font_set="Roboto">A</span><p class="qa-3__a_text">要りません。バスタオル1枚があれば十分です。椅子でできる形も一緒に入れています。</p></dd></dl></div>
<!-- /wp:wdl/lw-pr-qa-3 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":80,"tbHeight":64,"spHeight":40} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:80px"></div><div class="tb" style="height:64px"></div><div class="sp" style="height:40px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-bg-1 {"backgroundType":"image","imagePc":"","imageSp":"","isFullWidth":true,"maxWidth":1040,"minHeightPc":"min-h-pc-150px","minHeightTb":"min-h-tb-160px","minHeightSp":"min-h-sp-160px","innerPaddingTopPc":80,"innerPaddingBottomPc":80,"innerPaddingLeftPc":40,"innerPaddingRightPc":40,"innerPaddingTopTb":64,"innerPaddingBottomTb":64,"innerPaddingLeftTb":32,"innerPaddingRightTb":32,"innerPaddingTopSp":48,"innerPaddingBottomSp":48,"innerPaddingLeftSp":20,"innerPaddingRightSp":20,"filterTypePc":"solid","filterColorPc":"#f1f6f2","opacityPc":1,"filterTypeTb":"solid","filterColorTb":"#f1f6f2","opacityTb":1,"filterTypeSp":"solid","filterColorSp":"#f1f6f2","opacitySp":1} -->
<div class="wp-block-wdl-lw-bg-1 lw-bg-1 min-h-pc-150px min-h-tb-160px min-h-sp-160px bg_all" style="--lw-bg-color-filter-pc:#f1f6f2;--lw-bg-opacity-pc:1;--lw-bg-color-filter-tb:#f1f6f2;--lw-bg-opacity-tb:1;--lw-bg-color-filter-sp:#f1f6f2;--lw-bg-opacity-sp:1;--lw-bg-position-pc:50% 50%;--lw-bg-position-sp:50% 50%;--lw-bg-wrap-centering-pc:center;--lw-bg-wrap-align-pc:center;--lw-bg-wrap-centering-tb:center;--lw-bg-wrap-align-tb:center;--lw-bg-wrap-centering-sp:center;--lw-bg-wrap-align-sp:center"><div class="lw-bg-1-wrap" style="--lw-bg-padding-top-pc:80px;--lw-bg-padding-bottom-pc:80px;--lw-bg-padding-left-pc:40px;--lw-bg-padding-right-pc:40px;--lw-bg-padding-top-tb:64px;--lw-bg-padding-bottom-tb:64px;--lw-bg-padding-left-tb:32px;--lw-bg-padding-right-tb:32px;--lw-bg-padding-top-sp:48px;--lw-bg-padding-bottom-sp:48px;--lw-bg-padding-left-sp:20px;--lw-bg-padding-right-sp:20px;--lw-bg-max-width:1040px"><!-- wp:wdl/paid-block-custom-title-9 {"subTitle":"START","mainTitle":"受け取る","headingLevel":2,"mainTitleColor":"#17342a","borderTopColor":"#2a4d3f","borderBottomColor":"#2a4d3f","borderTopOpacity":100,"borderBottomOpacity":25,"borderRadius":8,"sizeClass":"size_m"} -->
<div class="wp-block-wdl-paid-block-custom-title-9 paid-block-custom-title-9 size_m"><h2 class="ttl"><span class="sub" style="color:#17342a">START</span><span class="main">受け取る</span><span class="border_wrap" style="border-radius:8px"><span class="border_inner"><span class="border top" style="background-color:#2a4d3f;opacity:1"></span><span class="border bottom" style="background-color:#2a4d3f;opacity:0.25"></span></span></span></h2></div>
<!-- /wp:wdl/paid-block-custom-title-9 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":16,"tbHeight":16,"spHeight":12} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:16px"></div><div class="tb" style="height:16px"></div><div class="sp" style="height:12px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:paragraph {"style":{"color":{"text":"#2f342f"},"typography":{"fontSize":"16px","lineHeight":"2"}},"align":"center"} -->
<p class="has-text-align-center has-text-color" style="color:#2f342f;font-size:16px;line-height:2">パソコンでご覧の方はQRコードから、<span class="lw-br on_500px"></span>スマホでご覧の方は下のボタンからどうぞ。30秒で終わります。</p>
<!-- /wp:paragraph -->
<!-- wp:wdl/lw-space-1 {"pcHeight":40,"tbHeight":32,"spHeight":24} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:40px"></div><div class="tb" style="height:32px"></div><div class="sp" style="height:24px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-button-02 {"btnText":"5日間の動画を無料で受け取る","bgGradient":"#2a4d3f","textColor":"#ffffff","fontWeight":"600","btnUrl":"#","btnLinkType":"url","iconColor":"#ffffff","borderWidth":0,"borderColor":"#2a4d3f"} -->
<div class="wp-block-wdl-lw-button-02 lw-button-02" id="uketoru"><div class="a_inner" style="border-width:0px;border-color:#2a4d3f;border-style:solid"><a href="#" target="_self" style="color:#ffffff;font-weight:600" data-lw_font_set="">5日間の動画を無料で受け取る</a><div class="icon-svg" style="fill:#ffffff"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 512"><!--!Font Awesome Free 6.6.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M310.6 233.4c12.5 12.5 12.5 32.8 0 45.3l-192 192c-12.5 12.5-32.8 12.5-45.3 0s-12.5-32.8 0-45.3L242.7 256 73.4 86.6c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0l192 192z"/></svg></div><div class="a_background" style="background:#2a4d3f"></div></div></div>
<!-- /wp:wdl/lw-button-02 -->
<!-- wp:paragraph {"align":"center","style":{"color":{"text":"#566058"},"typography":{"fontSize":"14px","lineHeight":"1.9"},"spacing":{"margin":{"top":"24px","bottom":"0px"}}}} -->
<p class="has-text-align-center has-text-color" style="color:#566058;font-size:14px;line-height:1.9;margin-top:24px;margin-bottom:0px">※ このページは見本です。ボタンとQRコードの飛び先は、ご自身のアカウントのものに差し替えてください。日数・お名前もすべて架空です。</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:wdl/lw-bg-1 -->