<!-- wp:wdl/fv-4 {"backgroundImage":"https://lite-word.com/wp-content/uploads/2025/05/LiteWord_Cafesample_top.png","mainTitle":"\u003cspan class=\u0022custom-font-settings custom-font-settings fs-0-8 ls-0 mb\u002d\u002d0-5\u0022 data-lw_font_set=\u0022sora\u0022\u003eun \u003cmark style=\u0022background-color:rgba(0, 0, 0, 0);color:#bd9598\u0022 class=\u0022has-inline-color\u0022\u003edoux\u003c/mark\u003e temps\u003c/span\u003e","subTitle":"\u003cspan data-lw_font_set=\u0022sora\u0022 class=\u0022custom-font-settings custom-font-settings\u0022\u003e\u003cmark style=\u0022background-color:rgba(0, 0, 0, 0)\u0022 class=\u0022has-inline-color has-white-color\u0022\u003eTokyo\u003c/mark\u003e Jiyugaoka\u003c/span\u003e","description":"\u003cspan data-lw_font_set=\u0022\u0022 class=\u0022custom-font-settings custom-font-settings mt\u002d\u002d0-5\u0022\u003e東京・自由が丘 カフェ\u003cmark style=\u0022background-color:rgba(0, 0, 0, 0)\u0022 class=\u0022has-inline-color has-white-color\u0022\u003e「アン・ドゥ・トン」\u003c/mark\u003e\u003c/span\u003e","filterBackgroundColor":"#ffffff","filterOpacity":0,"minHeightPc":"min-h-pc-500px"} -->
<div class="wp-block-wdl-fv-4 fv-4 min-h-pc-500px min-h-tb-400px min-h-sp-360px"><div class="fv-4_inner pc_left sp_left" style="max-width:1040px"><h1 style="color:#fff"><span class="sub" style="color:#fff"><span data-lw_font_set="sora" class="custom-font-settings custom-font-settings"><mark style="background-color:rgba(0, 0, 0, 0)" class="has-inline-color has-white-color">Tokyo</mark> Jiyugaoka</span></span><span class="main" style="color:#fff"><span class="custom-font-settings custom-font-settings fs-0-8 ls-0 mb--0-5" data-lw_font_set="sora">un <mark style="background-color:rgba(0, 0, 0, 0);color:#bd9598" class="has-inline-color">doux</mark> temps</span></span></h1><p style="color:#fff"><span data-lw_font_set="" class="custom-font-settings custom-font-settings mt--0-5">東京・自由が丘 カフェ<mark style="background-color:rgba(0, 0, 0, 0)" class="has-inline-color has-white-color">「アン・ドゥ・トン」</mark></span></p></div><div class="filter" style="background-color:#ffffff;opacity:0"></div><picture class="bg_image"><source srcset="" media="(max-width: 800px)"/><source srcset="https://lite-word.com/wp-content/uploads/2025/05/LiteWord_Cafesample_top.png" media="(min-width: 801px)"/><img src="https://lite-word.com/wp-content/uploads/2025/05/LiteWord_Cafesample_top.png" alt="背景画像" loading="eager" fetchpriority="high"/></picture></div>
<!-- /wp:wdl/fv-4 -->

<!-- wp:wdl/lw-space-1 {"pcHeight":50,"tbHeight":25,"spHeight":15} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:50px"></div><div class="tb" style="height:25px"></div><div class="sp" style="height:15px"></div></div>
<!-- /wp:wdl/lw-space-1 -->

<!-- wp:image {"id":3346,"width":"203px","height":"auto","sizeSlug":"full","linkDestination":"none","align":"center","className":"lw_pc_only","trigger":"lw_anime lw_scroll","animationClass":"lw-fade-up","animationDurationClass":"dur-1-0s"} -->
<figure class="wp-block-image aligncenter size-full is-resized lw_pc_only lw_anime lw_scroll lw-fade-up dur-1-0s"><img src="https://lite-word.com/wp-content/uploads/2025/05/LiteWord_Cafesample_headerlogo.svg" alt="" class="wp-image-3346" style="width:203px;height:auto"/></figure>
<!-- /wp:image -->

<!-- wp:paragraph {"align":"center","className":"lw_pc_only","trigger":"lw_anime lw_scroll","animationClass":"lw-fade-up","animationDurationClass":"dur-1-0s"} -->
<p class="has-text-align-center lw_pc_only lw_anime lw_scroll lw-fade-up dur-1-0s"><span class="custom-font-settings custom-font-settings lh-2-3" data-lw_font_set="">自由が丘の一角で、日常にそっとよりそうカフェ<strong><mark style="background-color:rgba(0, 0, 0, 0);color:#6f6b63" class="has-inline-color">「</mark></strong></span><strong><mark style="background-color:rgba(0, 0, 0, 0);color:#6f6b63" class="has-inline-color"><span class="custom-font-settings custom-font-settings fs-1-3 lh-1-3" data-lw_font_set="">un doux temps</span></mark></strong><span class="custom-font-settings custom-font-settings lh-2-3" data-lw_font_set=""><strong><mark style="background-color:rgba(0, 0, 0, 0);color:#6f6b63" class="has-inline-color">」</mark></strong>（アン・ドゥ・タン）<br>ふらっと立ち寄るだけで、気持ちがほどけていくような時間を、やさしいコーヒーとともにお届けします。</span></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"align":"center","className":"lw_sp_only","trigger":"lw_anime lw_scroll","animationClass":"lw-fade-up","animationDurationClass":"dur-1-0s"} -->
<p class="has-text-align-center lw_sp_only lw_anime lw_scroll lw-fade-up dur-1-0s">自由が丘の一角で、<br>日常にそっとよりそうカフェ<br><br><strong><mark style="background-color:rgba(0, 0, 0, 0);color:#6f6b63" class="has-inline-color"><span class="custom-font-settings custom-font-settings fs-1-3" data-lw_font_set="sora">「un doux temps」</span></mark></strong><br>（アン・ドゥ・タン）<br><br>ふらっと立ち寄るだけで、<br>気持ちがほどけていくような時間を、<br>やさしいコーヒーとともにお届けします。</p>
<!-- /wp:paragraph -->

<!-- wp:wdl/lw-space-1 {"pcHeight":50,"tbHeight":40,"spHeight":5} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:50px"></div><div class="tb" style="height:40px"></div><div class="sp" style="height:5px"></div></div>
<!-- /wp:wdl/lw-space-1 -->

<!-- wp:cover {"customOverlayColor":"#f5f2ef","isUserOverlayColor":true,"isDark":false,"className":"lw_padding_top_tb_0","layout":{"type":"constrained"},"trigger":"lw_anime lw_scroll","animationClass":"lw-fade-up","animationDurationClass":"dur-1-0s","marginTopPc":"lw_margin_top_pc_0","paddingTopSp":"lw_padding_top_sp_0","maxWidthType":"100vw"} -->
<div class="wp-block-cover is-light lw_padding_top_tb_0 lw_anime lw_scroll lw-fade-up dur-1-0s lw_margin_top_pc_0 lw_padding_top_sp_0 lw_max_width_100vw"><span aria-hidden="true" class="wp-block-cover__background has-background-dim-100 has-background-dim" style="background-color:#f5f2ef"></span><div class="wp-block-cover__inner-container">
<!-- wp:wdl/paid-block-content-5 {"pcImage":"https://lite-word.com/wp-content/uploads/2025/05/LiteWord_Cafesample_about.png","pcTitle":"\u003cspan class=\u0022custom-font-settings custom-font-settings\u0022 data-lw_font_set=\u0022Noto Sans JP\u0022\u003e\u003cstrong\u003e\u003cmark style=\u0022background-color:rgba(0, 0, 0, 0);color:#6f6b63\u0022 class=\u0022has-inline-color\u0022\u003eコーヒーと光が心地良い空間\u003c/mark\u003e\u003c/strong\u003e\u003c/span\u003e","spTitle":"コーヒーと光が\n心地良い空間","pcBody":"あわただしい毎日から少し離れて、深呼吸したくなる午後。\u003cbr\u003e\u003cbr\u003eやわらかな自然光と、コーヒーの香りに包まれて、ふっと肩の力が抜けるようなひとときを。\u003cbr\u003eun doux temps は、そんな時間のためのカフェです。\u003cbr\u003e\u003cbr\u003e季節の素材を取り入れたドリンクや焼き菓子とともに、\u003cbr\u003e自由が丘の一角で、あなたの“リラックスできる時間”をお迎えします。","textColumns":"1","aspectRatioHeight":610,"spTitleFont":"Noto Sans JP","spTitleFontWeight":"600","spTitleColor":"#e3e1de","className":"lw_margin_top_sp_0","trigger":"lw_anime lw_scroll","animationClass":"lw-fade-up","animationDurationClass":"dur-1-0s","marginTopSp":"lw_margin_top_sp_0","maxWidthType":"100vw"} -->
<div class="wp-block-wdl-paid-block-content-5 paid-block-content-5 lw_margin_top_sp_0 lw_anime lw_scroll lw-fade-up dur-1-0s lw_margin_top_sp_0 lw_max_width_100vw"><div class="conts"><figure class="image"><img class="none_800px" style="aspect-ratio:500 / 610" src="https://lite-word.com/wp-content/uploads/2025/05/LiteWord_Cafesample_about.png" alt="<span class=&quot;custom-font-settings custom-font-settings&quot; data-lw_font_set=&quot;Noto Sans JP&quot;&gt;<strong&gt;<mark style=&quot;background-color:rgba(0, 0, 0, 0);color:#6f6b63&quot; class=&quot;has-inline-color&quot;&gt;コーヒーと光が心地良い空間</mark&gt;</strong&gt;</span&gt;"/><img class="on_800px" src="https://lite-word.com/wp-content/uploads/2025/05/LiteWord_Cafesample_about.png" alt="<span class=&quot;custom-font-settings custom-font-settings&quot; data-lw_font_set=&quot;Noto Sans JP&quot;&gt;<strong&gt;<mark style=&quot;background-color:rgba(0, 0, 0, 0);color:#6f6b63&quot; class=&quot;has-inline-color&quot;&gt;コーヒーと光が心地良い空間</mark&gt;</strong&gt;</span&gt;"/><h2 class="ttl" style="font-weight:600;color:#e3e1de" data-lw_font_set="Noto Sans JP">コーヒーと光が<br>心地良い空間</h2></figure><div class="cont"><h2 class="ttl" style="color:"><span class="custom-font-settings custom-font-settings" data-lw_font_set="Noto Sans JP"><strong><mark style="background-color:rgba(0, 0, 0, 0);color:#6f6b63" class="has-inline-color">コーヒーと光が心地良い空間</mark></strong></span></h2><div class="in"><p style="column-count:1;column-gap:1.5em">あわただしい毎日から少し離れて、深呼吸したくなる午後。<br><br>やわらかな自然光と、コーヒーの香りに包まれて、ふっと肩の力が抜けるようなひとときを。<br>un doux temps は、そんな時間のためのカフェです。<br><br>季節の素材を取り入れたドリンクや焼き菓子とともに、<br>自由が丘の一角で、あなたの“リラックスできる時間”をお迎えします。</p></div></div></div></div>
<!-- /wp:wdl/paid-block-content-5 -->
</div></div>
<!-- /wp:cover -->

<!-- wp:wdl/lw-space-1 {"pcHeight":35,"tbHeight":25,"spHeight":15} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:35px"></div><div class="tb" style="height:25px"></div><div class="sp" style="height:15px"></div></div>
<!-- /wp:wdl/lw-space-1 -->

<!-- wp:wdl/custom-title-4 {"mainTitle":"\u003cstrong\u003e\u003cspan class=\u0022custom-font-settings custom-font-settings fs-1-2\u0022 data-lw_font_set=\u0022sora\u0022\u003e\u003cmark style=\u0022background-color:rgba(0, 0, 0, 0);color:#6f6b63\u0022 class=\u0022has-inline-color\u0022\u003eM\u003c/mark\u003e\u003c/span\u003e\u003cspan class=\u0022custom-font-settings custom-font-settings\u0022 data-lw_font_set=\u0022sora\u0022\u003e\u003cmark style=\u0022background-color:rgba(0, 0, 0, 0);color:#6f6b63\u0022 class=\u0022has-inline-color\u0022\u003eenu\u003c/mark\u003e\u003c/span\u003e\u003c/strong\u003e","subTitle":"\u003cstrong\u003e\u003cspan class=\u0022custom-font-settings custom-font-settings fw-100\u0022 data-lw_font_set=\u0022\u0022\u003e\u003cmark style=\u0022background-color:rgba(0, 0, 0, 0);color:#6f6b63\u0022 class=\u0022has-inline-color\u0022\u003eメニュー\u003c/mark\u003e\u003c/span\u003e\u003c/strong\u003e"} -->
<h2 class="wp-block-wdl-custom-title-4 custom-title-4"><span class="sub"><strong><span class="custom-font-settings custom-font-settings fw-100" data-lw_font_set=""><mark style="background-color:rgba(0, 0, 0, 0);color:#6f6b63" class="has-inline-color">メニュー</mark></span></strong></span><span class="main"><strong><span class="custom-font-settings custom-font-settings fs-1-2" data-lw_font_set="sora"><mark style="background-color:rgba(0, 0, 0, 0);color:#6f6b63" class="has-inline-color">M</mark></span><span class="custom-font-settings custom-font-settings" data-lw_font_set="sora"><mark style="background-color:rgba(0, 0, 0, 0);color:#6f6b63" class="has-inline-color">enu</mark></span></strong></span></h2>
<!-- /wp:wdl/custom-title-4 -->

<!-- wp:wdl/lw-banner-info-03 {"filterBackgroundColor":"#d7c7b7","titleFontFamily":"sora","titleFontWeight":"700","items":[{"title":"\u003cspan data-lw_font_set=\u0022sora\u0022 class=\u0022custom-font-settings custom-font-settings fs-1-3\u0022\u003eLunch\u003c/span\u003e","description":"","imgUrl":"https://lite-word.com/wp-content/uploads/2025/05/LiteWord_Cafesample1.png","linkUrl":"","openInNewTab":false},{"title":"\u003cspan data-lw_font_set=\u0022sora\u0022 class=\u0022custom-font-settings custom-font-settings fs-1-3\u0022\u003eCafe\u003c/span\u003e","description":"","imgUrl":"https://lite-word.com/wp-content/uploads/2025/05/LiteWord_Cafesample3.png","linkUrl":"","openInNewTab":false},{"title":"\u003cspan data-lw_font_set=\u0022sora\u0022 class=\u0022custom-font-settings custom-font-settings fs-1-3\u0022\u003eTakeout\u003c/span\u003e","description":"","imgUrl":"https://lite-word.com/wp-content/uploads/2025/05/LiteWord_Cafesample2.png","linkUrl":"","openInNewTab":false}]} -->
<nav class="wp-block-wdl-lw-banner-info-03 lw-banner-info-03"><ul class="lw-banner-info-03__wrap" style="max-width:800px"><li><a href="" data-open-in-new-tab="false"><img src="https://lite-word.com/wp-content/uploads/2025/05/LiteWord_Cafesample1.png" alt=""/><h3 class="title" style="font-weight:700" data-lw_font_set="sora"><span><span data-lw_font_set="sora" class="custom-font-settings custom-font-settings fs-1-3">Lunch</span></span></h3><p class="description" style="font-weight:400" data-lw_font_set="Noto Sans JP"><span></span></p><div class="filter" style="background-color:#d7c7b7;opacity:0.45"></div></a></li><li><a href="" data-open-in-new-tab="false"><img src="https://lite-word.com/wp-content/uploads/2025/05/LiteWord_Cafesample3.png" alt=""/><h3 class="title" style="font-weight:700" data-lw_font_set="sora"><span><span data-lw_font_set="sora" class="custom-font-settings custom-font-settings fs-1-3">Cafe</span></span></h3><p class="description" style="font-weight:400" data-lw_font_set="Noto Sans JP"><span></span></p><div class="filter" style="background-color:#d7c7b7;opacity:0.45"></div></a></li><li><a href="" data-open-in-new-tab="false"><img src="https://lite-word.com/wp-content/uploads/2025/05/LiteWord_Cafesample2.png" alt=""/><h3 class="title" style="font-weight:700" data-lw_font_set="sora"><span><span data-lw_font_set="sora" class="custom-font-settings custom-font-settings fs-1-3">Takeout</span></span></h3><p class="description" style="font-weight:400" data-lw_font_set="Noto Sans JP"><span></span></p><div class="filter" style="background-color:#d7c7b7;opacity:0.45"></div></a></li></ul></nav>
<!-- /wp:wdl/lw-banner-info-03 -->

<!-- wp:wdl/lw-space-1 {"pcHeight":35,"tbHeight":25,"spHeight":15} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:35px"></div><div class="tb" style="height:25px"></div><div class="sp" style="height:15px"></div></div>
<!-- /wp:wdl/lw-space-1 -->

<!-- wp:cover {"customOverlayColor":"#f5f2ef","isUserOverlayColor":true,"isDark":false,"layout":{"type":"constrained"},"maxWidthType":"100vw"} -->
<div class="wp-block-cover is-light lw_max_width_100vw" style="min-height:undefined"><span aria-hidden="true" class="wp-block-cover__background has-background-dim-100 has-background-dim" style="background-color:#f5f2ef"></span><div class="wp-block-cover__inner-container"><!-- wp:wdl/paid-block-content-4 {"mainTitle":"\u003cspan class=\u0022custom-font-settings custom-font-settings fs-1-2\u0022 data-lw_font_set=\u0022sora\u0022\u003e\u003cmark style=\u0022background-color:rgba(0, 0, 0, 0);color:#6f6b63\u0022 class=\u0022has-inline-color\u0022\u003eS\u003c/mark\u003e\u003c/span\u003e\u003cspan class=\u0022custom-font-settings custom-font-settings fs-1-1\u0022 data-lw_font_set=\u0022sora\u0022\u003e\u003cmark style=\u0022background-color:rgba(0, 0, 0, 0);color:#6f6b63\u0022 class=\u0022has-inline-color\u0022\u003eeasonal\u003c/mark\u003e\u003c/span\u003e","subTitle":"\u003cmark style=\u0022background-color:rgba(0, 0, 0, 0);color:#6f6b63\u0022 class=\u0022has-inline-color\u0022\u003e\u003cspan data-lw_font_set=\u0022\u0022 class=\u0022custom-font-settings custom-font-settings fs-1-3 fw-200\u0022\u003e季節限定\u003c/span\u003e\u003c/mark\u003e","bottomText":"\u003cspan data-lw_font_set=\u0022\u0022 class=\u0022custom-font-settings custom-font-settings fw-400\u0022\u003e季節に合わせたスイーツとコーヒーをお楽しみください。\u003c/span\u003e\u003cbr\u003e","ctaText":"\u003cstrong\u003e季節限定メニュー\u003c/strong\u003e","ctaBorderColor":"#6f6b63","ctaTextColor":"#6f6b63","ctaBorderWidth":1,"images":[{"url":"https://lite-word.com/wp-content/uploads/2025/05/LiteWord_Cafesample4.png","alt":""},{"url":"https://lite-word.com/wp-content/uploads/2025/05/LiteWord_Cafesample5.png","alt":""},{"url":"https://lite-word.com/wp-content/uploads/2025/05/LiteWord_Cafesample6.png","alt":""},{"url":"https://lite-word.com/wp-content/uploads/2025/05/LiteWord_Cafesample7.png","alt":""},{"url":"https://lite-word.com/wp-content/uploads/2025/05/LiteWord_Cafesample8.png","alt":""},{"url":"https://lite-word.com/wp-content/uploads/2025/05/LiteWord_Cafesample9.png","alt":""},{"url":"https://lite-word.com/wp-content/uploads/2025/05/LiteWord_Cafesample10.png","alt":""},{"url":"https://lite-word.com/wp-content/uploads/2025/05/LiteWord_Cafesample11.png","alt":""}]} -->
<div class="wp-block-wdl-paid-block-content-4 paid-block-content-4"><section class="conts"><div class="cont"><h2 class="ttl"><div style="color:#333"><span class="custom-font-settings custom-font-settings fs-1-2" data-lw_font_set="sora"><mark style="background-color:rgba(0, 0, 0, 0);color:#6f6b63" class="has-inline-color">S</mark></span><span class="custom-font-settings custom-font-settings fs-1-1" data-lw_font_set="sora"><mark style="background-color:rgba(0, 0, 0, 0);color:#6f6b63" class="has-inline-color">easonal</mark></span></div><span class="sub" style="color:#0AA8C9"><mark style="background-color:rgba(0, 0, 0, 0);color:#6f6b63" class="has-inline-color"><span data-lw_font_set="" class="custom-font-settings custom-font-settings fs-1-3 fw-200">季節限定</span></mark></span></h2><p class="ttl_btm_p"><span><span data-lw_font_set="" class="custom-font-settings custom-font-settings fw-400">季節に合わせたスイーツとコーヒーをお楽しみください。</span><br></span></p><a class="cont_btn" href="#" style="border-color:#6f6b63;border-width:1px;border-radius:0px;color:#6f6b63"><span><strong>季節限定メニュー</strong></span><div class="btn_bg" style="background:#6f6b63;border-radius:0px"></div></a></div><div class="gallery_in"><div class="image" style="border-radius:0px;overflow:hidden"><img src="https://lite-word.com/wp-content/uploads/2025/05/LiteWord_Cafesample4.png" alt="" style="border-radius:0px"/></div><div class="image" style="border-radius:0px;overflow:hidden"><img src="https://lite-word.com/wp-content/uploads/2025/05/LiteWord_Cafesample5.png" alt="" style="border-radius:0px"/></div><div class="image" style="border-radius:0px;overflow:hidden"><img src="https://lite-word.com/wp-content/uploads/2025/05/LiteWord_Cafesample6.png" alt="" style="border-radius:0px"/></div><div class="image" style="border-radius:0px;overflow:hidden"><img src="https://lite-word.com/wp-content/uploads/2025/05/LiteWord_Cafesample7.png" alt="" style="border-radius:0px"/></div><div class="image" style="border-radius:0px;overflow:hidden"><img src="https://lite-word.com/wp-content/uploads/2025/05/LiteWord_Cafesample8.png" alt="" style="border-radius:0px"/></div><div class="image" style="border-radius:0px;overflow:hidden"><img src="https://lite-word.com/wp-content/uploads/2025/05/LiteWord_Cafesample9.png" alt="" style="border-radius:0px"/></div><div class="image" style="border-radius:0px;overflow:hidden"><img src="https://lite-word.com/wp-content/uploads/2025/05/LiteWord_Cafesample10.png" alt="" style="border-radius:0px"/></div><div class="image" style="border-radius:0px;overflow:hidden"><img src="https://lite-word.com/wp-content/uploads/2025/05/LiteWord_Cafesample11.png" alt="" style="border-radius:0px"/></div></div></section></div>
<!-- /wp:wdl/paid-block-content-4 --></div></div>
<!-- /wp:cover -->

<!-- wp:wdl/lw-space-1 {"pcHeight":50,"tbHeight":25,"spHeight":15} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:50px"></div><div class="tb" style="height:25px"></div><div class="sp" style="height:15px"></div></div>
<!-- /wp:wdl/lw-space-1 -->

<!-- wp:wdl/custom-title-4 {"mainTitle":"\u003cstrong\u003e\u003cspan class=\u0022custom-font-settings custom-font-settings\u0022 data-lw_font_set=\u0022sora\u0022\u003e\u003cmark style=\u0022background-color:rgba(0, 0, 0, 0);color:#6f6b63\u0022 class=\u0022has-inline-color\u0022\u003eWhat's new\u003c/mark\u003e\u003c/span\u003e\u003c/strong\u003e","subTitle":"\u003cspan class=\u0022custom-font-settings custom-font-settings fw-100\u0022 data-lw_font_set=\u0022\u0022\u003e\u003cmark style=\u0022background-color:rgba(0, 0, 0, 0);color:#6f6b63\u0022 class=\u0022has-inline-color\u0022\u003e新着情報\u003c/mark\u003e\u003c/span\u003e"} -->
<h2 class="wp-block-wdl-custom-title-4 custom-title-4"><span class="sub"><span class="custom-font-settings custom-font-settings fw-100" data-lw_font_set=""><mark style="background-color:rgba(0, 0, 0, 0);color:#6f6b63" class="has-inline-color">新着情報</mark></span></span><span class="main"><strong><span class="custom-font-settings custom-font-settings" data-lw_font_set="sora"><mark style="background-color:rgba(0, 0, 0, 0);color:#6f6b63" class="has-inline-color">What's new</mark></span></strong></span></h2>
<!-- /wp:wdl/custom-title-4 -->

<!-- wp:wdl/lw-news-list-1 {"catBgColor":"#6f6b63"} -->
<div class="wp-block-wdl-lw-news-list-1"><div class="news-list-1" data-number="4" data-category="" data-type="post" data-date-font="Noto Sans JP" data-date-font-weight="400" data-cat-font="Noto Sans JP" data-cat-font-weight="400" data-cat-bg-color="#6f6b63" data-title-font="Noto Sans JP" data-title-font-weight="400"><ul class="news-list-1__wrap"></ul></div><script>
                        document.addEventListener('DOMContentLoaded', () => {
                            const newsList1Container = document.querySelector('.news-list-1');
                            
                            if (newsList1Container) {
                                const newsList1NumberOfPosts = newsList1Container.getAttribute('data-number') || 4;
                                const newsList1CategoryId = newsList1Container.getAttribute('data-category');
                                const newsList1PostType = newsList1Container.getAttribute('data-type') || 'post';

                                const newsList1DateFont = newsList1Container.getAttribute('data-date-font');
                                const newsList1DateFontWeight = newsList1Container.getAttribute('data-date-font-weight');
                                const newsList1CatFont = newsList1Container.getAttribute('data-cat-font');
                                const newsList1CatFontWeight = newsList1Container.getAttribute('data-cat-font-weight');
                                const newsList1CatBgColor = newsList1Container.getAttribute('data-cat-bg-color');
                                const newsList1TitleFont = newsList1Container.getAttribute('data-title-font');
                                const newsList1TitleFontWeight = newsList1Container.getAttribute('data-title-font-weight');

                                let newsList1ApiUrl = `${MyThemeSettings.home_Url}/wp-json/wp/v2/${newsList1PostType === 'post' ? 'posts' : newsList1PostType}?per_page=${newsList1NumberOfPosts}&orderby=date&order=desc&_embed`;
                                if (newsList1CategoryId) {
                                    newsList1ApiUrl += `&categories=${newsList1CategoryId}`;
                                }

                                fetch(newsList1ApiUrl)
                                    .then(response => {
                                        if (!response.ok) {
                                            throw new Error('投稿の取得に失敗しました');
                                        }
                                        return response.json();
                                    })
                                    .then(posts => {
                                        let newsList1Html = '<ul class="news-list-1__wrap">';

                                        posts.forEach(post => {
                                            const newsList1Date = new Date(post.date).toLocaleDateString();
                                            const newsList1Title = post.title.rendered;
                                            const newsList1Link = post.link;
                                            const newsList1Category = post._embedded && post._embedded['wp:term'] && post._embedded['wp:term'][0]
                                                ? post._embedded['wp:term'][0][0].name
                                                : 'カテゴリーなし';

                                            newsList1Html += `
                                                <li>
                                                    <a href="${newsList1Link}">
                                                        <div class="data">
                                                            <div class="date" style="font-weight: ${newsList1DateFontWeight};" data-lw_font_set="${newsList1DateFont}">
                                                                <span>${newsList1Date}</span>
                                                            </div>
                                                            <div class="cat" style="background-color: ${newsList1CatBgColor}; font-weight: ${newsList1CatFontWeight};" data-lw_font_set="${newsList1CatFont}">
                                                                <span>${newsList1Category}</span>
                                                            </div>
                                                        </div>
                                                        <div class="post_title">
                                                            <h3 style="font-weight: ${newsList1TitleFontWeight};" data-lw_font_set="${newsList1TitleFont}">${newsList1Title}</h3>
                                                        </div>
                                                    </a>
                                                </li>
                                            `;
                                        });

                                        newsList1Html += '</ul>';
                                        newsList1Container.innerHTML = newsList1Html;
                                    })
                                    .catch(error => {
                                        console.error('投稿を取得できませんでした:', error);
                                        newsList1Container.innerHTML = '<p>投稿を読み込めませんでした。</p>';
                                    });
                            }
                        });
                        </script></div>
<!-- /wp:wdl/lw-news-list-1 -->

<!-- wp:wdl/lw-space-1 {"tbHeight":30,"spHeight":20} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:80px"></div><div class="tb" style="height:30px"></div><div class="sp" style="height:20px"></div></div>
<!-- /wp:wdl/lw-space-1 -->

<!-- wp:wdl/paid-block-cta-4 {"mainTitle1":"\u003cstrong\u003e\u003cspan class=\u0022custom-font-settings custom-font-settings\u0022 data-lw_font_set=\u0022sora\u0022\u003e\u003cmark style=\u0022background-color:rgba(0, 0, 0, 0);color:#6f6b63\u0022 class=\u0022has-inline-color\u0022\u003eReservation\u003c/mark\u003e\u003c/span\u003e\u003c/strong\u003e","subTitle1":"\u003cmark style=\u0022background-color:rgba(0, 0, 0, 0);color:#6f6b63\u0022 class=\u0022has-inline-color\u0022\u003eご予約はこちら\u003c/mark\u003e","desc1":"","backgroundImage1":"https://lite-word.com/wp-content/uploads/2025/05/LiteWord_Cafesample_reservation.png","filterColor1":"#ffffff","filterOpacity1":0,"btnText1":"\u003cspan class=\u0022custom-font-settings custom-font-settings\u0022 data-lw_font_set=\u0022sora\u0022\u003e\u003cstrong\u003eMore\u003c/strong\u003e\u003c/span\u003e","bgColor1":"#6f6b63","mainTitle2":"\u003cstrong\u003e\u003cspan class=\u0022custom-font-settings custom-font-settings\u0022 data-lw_font_set=\u0022sora\u0022\u003e\u003cstrong\u003e\u003cspan class=\u0022custom-font-settings custom-font-settings\u0022 data-lw_font_set=\u0022sora\u0022\u003e\u003cmark style=\u0022background-color:rgba(0, 0, 0, 0);color:#6f6b63\u0022 class=\u0022has-inline-color\u0022\u003eAccess\u003c/mark\u003e\u003c/span\u003e\u003c/strong\u003e\u003c/span\u003e\u003c/strong\u003e","subTitle2":"\u003cmark style=\u0022background-color:rgba(0, 0, 0, 0);color:#6f6b63\u0022 class=\u0022has-inline-color\u0022\u003eアクセス詳細\u003c/mark\u003e","desc2":"","backgroundImage2":"https://lite-word.com/wp-content/uploads/2025/05/LiteWord_Cafesample_Access.png","filterColor2":"#d7c7b7","filterOpacity2":49,"btnText2":"\u003cspan class=\u0022custom-font-settings custom-font-settings\u0022 data-lw_font_set=\u0022sora\u0022\u003e\u003cstrong\u003e\u003cmark style=\u0022background-color:rgba(0, 0, 0, 0);color:#6f6b63\u0022 class=\u0022has-inline-color\u0022\u003eMore\u003c/mark\u003e\u003c/strong\u003e\u003c/span\u003e","bgColor2":"#ffffff","textColor2":"#6f6b63"} -->
<div class="wp-block-wdl-paid-block-cta-4 paid-block-cta-4"><ul><li><a href="#"><h2 class="ttl parts_page_ttl_main" data-lw_font_set="Lato"><div class="main"><strong><span class="custom-font-settings custom-font-settings" data-lw_font_set="sora"><mark style="background-color:rgba(0, 0, 0, 0);color:#6f6b63" class="has-inline-color">Reservation</mark></span></strong></div><div class="sub"><mark style="background-color:rgba(0, 0, 0, 0);color:#6f6b63" class="has-inline-color">ご予約はこちら</mark></div></h2><p></p><div class="btn"><div style="color:#ffffff"><span class="custom-font-settings custom-font-settings" data-lw_font_set="sora"><strong>More</strong></span></div><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512" style="fill:#ffffff"><path d="M342.6 233.4c12.5 12.5 
 12.5 32.8 0 45.3l-192 192c-12.5 
 12.5-32.8 12.5-45.3 0s-12.5-32.8 
 0-45.3L274.7 256 105.4 86.6c-12.5-12.5-12.5-32.8 
 0-45.3s32.8-12.5 45.3 0l192 192z"></path></svg><div class="btn_bg" style="background-color:#6f6b63;color:#ffffff"></div></div></a><div class="this_filter" style="background:#ffffff;opacity:0%"></div><div class="bg_img"><img src="https://lite-word.com/wp-content/uploads/2025/05/LiteWord_Cafesample_reservation.png" alt="CTA1背景"/></div></li><li><a href="#"><h2 class="ttl parts_page_ttl_main"><div class="main" data-lw_font_set="Lato"><strong><span class="custom-font-settings custom-font-settings" data-lw_font_set="sora"><strong><span class="custom-font-settings custom-font-settings" data-lw_font_set="sora"><mark style="background-color:rgba(0, 0, 0, 0);color:#6f6b63" class="has-inline-color">Access</mark></span></strong></span></strong></div><div class="sub"><mark style="background-color:rgba(0, 0, 0, 0);color:#6f6b63" class="has-inline-color">アクセス詳細</mark></div></h2><p></p><div class="btn"><div style="color:#6f6b63"><span class="custom-font-settings custom-font-settings" data-lw_font_set="sora"><strong><mark style="background-color:rgba(0, 0, 0, 0);color:#6f6b63" class="has-inline-color">More</mark></strong></span></div><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512" style="fill:#6f6b63"><path d="M342.6 233.4c12.5 12.5 
 12.5 32.8 0 45.3l-192 192c-12.5 
 12.5-32.8 12.5-45.3 0s-12.5-32.8 
 0-45.3L274.7 256 105.4 86.6c-12.5-12.5-12.5-32.8 
 0-45.3s32.8-12.5 45.3 0l192 192z"></path></svg><div class="btn_bg" style="background-color:#ffffff;color:#6f6b63"></div></div></a><div class="this_filter" style="background:#d7c7b7;opacity:49%"></div><div class="bg_img"><img src="https://lite-word.com/wp-content/uploads/2025/05/LiteWord_Cafesample_Access.png" alt="CTA2背景"/></div></li></ul></div>
<!-- /wp:wdl/paid-block-cta-4 -->