<?php
if ( !defined( 'ABSPATH' ) ) exit;

function lw_block_arr() {
    $lw_active_template_ids = lw_active_template_ids();

    $shop_url = lw_shop_url();
    $url = get_template_directory_uri() . '/my-blocks/block_sample_list/';

    // lw_shop_login_idを取得
    $lw_shop_login_id = get_option('lw_shop_login_id', '');

    //有料ブロックの場合は、IDの先頭に必ず「paid-block-」をつける
    $lw_block_arr = [
        [
            'type' => 'h2',
            'id' => 'lw-fv',
            'title' => 'FV（固定ページタイトル）',
        ],
        [
            'type' => 'block',
            'id' => 'fv-1',
            'title' => '固定ページメインタイトル 01',
            'file' => $url . 'fv-1.php',
            'image' => $url . 'fv-1.webp',
            'description' => 'トップページに最適な背景に画像、中央にキャッチフレーズとボタンが配置されたシンプルなメインビジュアルです。',
        ],
        [
            'type' => 'block',
            'id' => 'fv-2',
            'title' => '固定ページメインタイトル 02 - 下層ページ用',
            'file' => $url . 'fv-2.php',
            'image' => $url . 'fv-2.webp',
            'description' => '下層ページに最適なページタイトルのみのシンプルなメインビジュアルです。背景に画像を設定できます。',
        ],
        [
            'type' => 'block',
            'id' => 'fv-3',
            'title' => '固定ページメインタイトル 03',
            'file' => $url . 'fv-3.php',
            'image' => $url . 'fv-3.webp',
            'description' => '画像をシンプルに表示するメインビジュアルです。PCとスマホの切り替え表示が可能です。',
        ],
        [
            'type' => 'block',
            'id' => 'fv-4',
            'title' => '固定ページメインタイトル 04',
            'file' => $url . 'fv-4.php',
            'image' => $url . 'fv-4.webp',
            'description' => 'トップページに最適な背景に画像、左にキャッチフレーズが配置されたシンプルなFVです。',
        ],
        [
            'type' => 'block',
            'id' => 'fv-5',
            'title' => '固定ページメインタイトル 05 - 下層ページ用',
            'file' => $url . 'fv-5.php',
            'image' => $url . 'fv-5.webp',
            'description' => '下層ページに最適なページタイトルのみのシンプルなメインビジュアルです。背景に画像を設定できます。',
        ],
        [
            'type' => 'block',
            'id' => 'fv-6',
            'title' => '固定ページメインタイトル 06 - 下層ページ用',
            'file' => $url . 'fv-6.php',
            'image' => $url . 'fv-6.webp',
            'description' => '下層ページに最適なページタイトルのみのシンプルなメインビジュアルです。背景に画像を設定できます。',
        ],
        [
            'type' => 'block',
            'id' => 'fv-7',
            'title' => '固定ページメインタイトル 07',
            'file' => $url . 'fv-7.php',
            'image' => $url . 'fv-7.webp',
            'description' => 'トップページに最適な背景に動画、中央にキャッチフレーズとボタンが配置されたシンプルなFVです。',
        ],
        [
            'type' => 'paid_block',
            'id' => 'paid-block-fv-8',
            'title' => '固定ページメインタイトル 08',
            'file' => $url . 'fv-8.php',
            'image' => $url . 'fv-8.webp',
            'description' => 'LPなどに最適な、2カラムのデザインのメインビジュアルです。画像とテキストを横並びで表示します。',
            'price' => 4400,
            'switch' => in_array( 'paid-block-fv-8', $lw_active_template_ids, true ), // 条件に応じて設定
            'shop_url' => 'https://shop.lite-word.com/shop_template/paid-block-fv-8/',
        ],
        [
            'type' => 'paid_block',
            'id' => 'paid-block-fv-9',
            'title' => '固定ページメインタイトル 09 -画像スライド用',
            'file' => $url . 'fv-9.php',
            'image' => $url . 'fv-9.webp',
            'description' => '画像スライドショーを簡単に設定できるブロックです。※このイメージ画像はCanvaで作ったサンプル画像です。',
            'price' => 4400,
            'switch' => in_array( 'paid-block-fv-9', $lw_active_template_ids, true ), // 条件に応じて設定
            'shop_url' => 'https://shop.lite-word.com/shop_template/paid-block-fv-9/',
        ],
        [
            'type' => 'paid_block',
            'id' => 'paid-block-fv-10',
            'title' => '固定ページメインタイトル 10- 下層ページ用',
            'file' => $url . 'fv-10.php',
            'image' => $url . 'fv-10.webp',
            'description' => 'シンプルな下層ページ用のFVです。',
            'price' => 1500,
            'switch' => in_array( 'paid-block-fv-10', $lw_active_template_ids, true ), // 条件に応じて設定
            'shop_url' => 'https://shop.lite-word.com/shop_template/paid-block-fv-10/',
        ],
        [
            'type' => 'paid_block',
            'id' => 'paid-block-fv-11',
            'title' => '固定ページメインタイトル 11 - スライド画像用',
            'file' => $url . 'fv-11.php',
            'image' => $url . 'fv-11.webp',
            'description' => '背景画像をスライドさせることができる、トップページ用のメインビジュアルです。画像をスライドさせることで、より動きのあるデザインに仕上げることができます。',
            'price' => 4400,
            'switch' => in_array( 'paid-block-fv-11', $lw_active_template_ids, true ), // 条件に応じて設定
            'shop_url' => 'https://shop.lite-word.com/shop_template/paid-block-fv-11/',
        ],
        [
            'type' => 'paid_block',
            'id' => 'paid-block-fv-12',
            'title' => '固定ページメインタイトル 12 - TOPページ用',
            'file' => $url . 'fv-12.php',
            'image' => $url . 'fv-12.webp',
            'description' => 'ヘッダーまで回り込む全画背景 + お知らせ表示が一体化したメインビジュアルです。ヘッダーのロゴやナビゲーションが背景画像に溶け込むようなデザインで、視覚的にインパクトがあります。',
            'price' => 3500,
            'switch' => in_array( 'paid-block-fv-12', $lw_active_template_ids, true ), // 条件に応じて設定
            'shop_url' => 'https://shop.lite-word.com/shop_template/paid-block-fv-12/',
        ],
        [
            'type' => 'pr_block',
            'id' => 'lw-pr-fv-13',
            'title' => '固定ページメインタイトル 13',
            'file' => $url . 'fv-13.php',
            'image' => $url . 'fv-13.webp',
            'description' => '',
        ],
        [
            'type' => 'pr_block',
            'id' => 'lw-pr-fv-14',
            'title' => '固定ページメインタイトル 14',
            'file' => $url . 'fv-14.php',
            'image' => $url . 'fv-14.webp',
            'description' => '',
        ],
        [
            'type' => 'pr_block',
            'id' => 'lw-pr-fv-15',
            'title' => '固定ページメインタイトル 15',
            'file' => $url . 'fv-15.php',
            'image' => $url . 'fv-15.webp',
            'description' => '',
        ],
        [
            'type' => 'pr_block',
            'id' => 'lw-pr-fv-16',
            'title' => '固定ページメインタイトル 16',
            'file' => $url . 'fv-16.php',
            'image' => $url . 'fv-16.webp',
            'description' => '',
        ],
 
        [
            'type' => 'h2',
            'id' => 'lw-post-list',
            'title' => '最新投稿・記事一覧',
        ],
        [
            'type' => 'block',
            'id' => 'lw-post-list-1',
            'title' => '最新投稿・記事一覧 01',
            'file' => $url . 'lw-post-list-1.php',
            'image' => $url . 'lw-post-list-1.webp',
            'description' => '',
        ],
        [
            'type' => 'block',
            'id' => 'lw-post-list-2',
            'title' => '最新投稿・記事一覧 02',
            'file' => $url . 'lw-post-list-2.php',
            'image' => $url . 'lw-post-list-2.webp',
            'description' => '',
        ],
        [
            'type' => 'block',
            'id' => 'lw-post-list-3',
            'title' => '最新投稿・記事一覧 03',
            'file' => $url . 'lw-post-list-3.php',
            'image' => $url . 'lw-post-list-3.webp',
            'description' => '',
        ],
        [
            'type' => 'block',
            'id' => 'lw-news-list-1',
            'title' => 'お知らせ一覧 01',
            'file' => $url . 'lw-news-list-1.php',
            'image' => $url . 'lw-news-list-1.webp',
            'description' => '',
        ],
           
        [
            'type' => 'h2',
            'id' => 'lw-button',
            'title' => 'LINK LIST（リンク一覧系）',
        ],
        [
            'type' => 'block',
            'id' => 'lw-link-list-1',
            'title' => 'リンクリスト 01',
            'file' => $url . 'lw-link-list-1.php',
            'image' => $url . 'lw-link-list-1.webp',
            'description' => '',
        ],
        [
            'type' => 'paid_block',
            'id' => 'paid-block-link-2',
            'title' => 'リンクリスト 02',
            'file' => $url . 'lw-link-list-2.php',
            'image' => $url . 'lw-link-list-2.webp',
            'description' => '背景に画像が設定できる、PCの時は３カラム、スマホの時は1カラムのシンプルなインフォメーションデザインです。',
            'price' => 1500,
            'switch' => in_array( 'paid-block-link-2', $lw_active_template_ids, true ), // 条件に応じて設定
            'shop_url' => 'https://shop.lite-word.com/shop_template/paid-block-link-2/',
        ],
        [
            'type' => 'h2',
            'id' => 'cta',
            'title' => 'CTA（コールトゥーアクション）',
        ],
        [
            'type' => 'block',
            'id' => 'cta-1',
            'title' => 'CTA 01',
            'file' => $url . 'cta-1.php',
            'image' => $url . 'cta-1.webp',
            'description' => '真ん中にCTAボタンを一つだけ設置できる、よくあるシンプルなCTAブロックです。背景に画像を設定する事ができます。',
        ],
        [
            'type' => 'block',
            'id' => 'cta-2',
            'title' => 'CTA 02',
            'file' => $url . 'cta-2.php',
            'image' => $url . 'cta-2.webp',
            'description' => '電話番号とメールフォームへのリンクボタンを横並びで設定できる、よくあるシンプルなCTAブロックです。背景に画像を設定する事ができます。',
        ],
        [
            'type' => 'paid_block',
            'id' => 'paid-block-cta-3',
            'title' => 'CTA 03',
            'file' => $url . 'lw-block-cta-3.php',
            'image' => $url . 'lw-block-cta-3.webp',
            'description' => '電話番号専用のCTAブロックです。PCの時だけ右側に画像が表示されます。',
            'price' => 2500,
            'switch' => in_array( 'paid-block-cta-3', $lw_active_template_ids, true ), // 条件に応じて設定
            'shop_url' => 'https://shop.lite-word.com/shop_template/paid-block-cta-3/',
        ],
        [
            'type' => 'paid_block',
            'id' => 'paid-block-cta-4',
            'title' => 'CTA 04',
            'file' => $url . 'lw-block-cta-4.php',
            'image' => $url . 'lw-block-cta-4.webp',
            'description' => '背景に画像を設定できる２カラムタイプのCTAです。 ちょっとお洒落だけど、シンプルなCTAが欲しいという方にお勧め。',
            'price' => 2500,
            'switch' => in_array( 'paid-block-cta-4', $lw_active_template_ids, true ), // 条件に応じて設定
            'shop_url' => 'https://shop.lite-word.com/shop_template/paid-block-cta-4/',
        ],
        [
            'type' => 'h2',
            'id' => 'contact-form',
            'title' => 'お問い合わせフォーム',
        ],
        [
            'type' => 'paid_block',
            'id' => 'paid-block-contact-2',
            'title' => 'お問い合わせフォーム 02',
            'file' => $url . 'lw-block-contact-2.php',
            'image' => $url . 'lw-block-contact-2.webp',
            'description' => '背景に画像や色を設定できる、ちょっとシックなお問い合わせフォームのデザインです。背景の画像を自分好みにすることでイメージをガラリと変えることができます。',
            'price' => 1500,
            'switch' => in_array( 'paid-lw-parts-sub-hbjkjhkljh', $lw_active_template_ids, true ), // 条件に応じて設定
            'shop_url' => 'https://shop.lite-word.com/shop_template/paid-block-contact-2/',
        ],
        [
            'type' => 'block',
            'id' => 'lw-contact-3',
            'title' => 'お問い合わせフォーム 03-1（シンプルワンカラム）',
            'file' => $url . 'lw-block-contact-3.php',
            'image' => $url . 'lw-block-contact-3.webp',
            'description' => '',
        ],
        [
            'type' => 'block',
            'id' => 'lw-contact-4',
            'title' => 'お問い合わせフォーム 03-2（背景あり）',
            'file' => $url . 'lw-block-contact-4.php',
            'image' => $url . 'lw-block-contact-4.webp',
            'description' => '「お問い合わせフォーム 03」とWordPressのカラムブロックを組み合わせて、背景を設定したお問い合わせフォームです。カラム設定をしっかり理解している方には重宝するブロックです。',
        ],
        [
            'type' => 'h2',
            'id' => 'lw-banner-info',
            'title' => 'BANNER（バナー系）',
        ],
        [
            'type' => 'block',
            'id' => 'lw-banner-info-01',
            'title' => 'バナー 01',
            'file' => $url . 'lw-banner-info-01.php',
            'image' => $url . 'lw-banner-info-01.webp',
            'description' => '',
        ],
        [
            'type' => 'block',
            'id' => 'lw-banner-info-02',
            'title' => 'バナー 02',
            'file' => $url . 'lw-banner-info-02.php',
            'image' => $url . 'lw-banner-info-02.webp',
            'description' => '',
        ],
        [
            'type' => 'block',
            'id' => 'lw-banner-info-03',
            'title' => 'バナー 03',
            'file' => $url . 'lw-banner-info-03.php',
            'image' => $url . 'lw-banner-info-03.webp',
            'description' => '',
        ],
        [
            'type' => 'block',
            'id' => 'lw-banner-info-04',
            'title' => 'バナー 04',
            'file' => $url . 'lw-banner-info-04.php',
            'image' => $url . 'lw-banner-info-04.webp',
            'description' => '',
        ],
        [
            'type' => 'block',
            'id' => 'lw-banner-info-05',
            'title' => 'バナー 05',
            'file' => $url . 'lw-banner-info-05.php',
            'image' => $url . 'lw-banner-info-05.webp',
            'description' => '',
        ],
                [
            'type' => 'h2',
            'id' => 'lw-image',
            'title' => '画像系',
        ],
        [
            'type' => 'paid_block',
            'id' => 'paid-block-image-1',
            'title' => '画像 01',
            'file' => $url . 'lw-image-1.php',
            'image' => $url . 'lw-image-1.webp',
            'description' => '',
            'price' => 1200,
            'switch' => in_array( 'paid-block-before-after-2', $lw_active_template_ids, true ), // 条件に応じて設定
            'shop_url' => 'https://shop.lite-word.com/shop_template/paid-block-image-1/',
        ],
        [
            'type' => 'h2',
            'id' => 'lw-gallery',
            'title' => 'GALLERY（画像一覧系）',
        ],
        [
            'type' => 'block',
            'id' => 'lw-gallery-01',
            'title' => '画像ギャラリー 01',
            'file' => $url . 'lw-gallery-01.php',
            'image' => $url . 'lw-gallery-01.webp',
            'description' => '',
        ],
                [
            'type' => 'block',
            'id' => 'lw-gallery-02',
            'title' => '画像ギャラリー 02',
            'file' => $url . 'lw-gallery-02.php',
            'image' => $url . 'lw-gallery-02.webp',
            'description' => '',
        ],
        [
            'type' => 'paid_block',
            'id' => 'paid-block-lw-gallery-3',
            'title' => '画像ギャラリー 03',
            'file' => $url . 'lw-gallery-3.php',
            'image' => $url . 'lw-gallery-3.webp',
            'description' => '',
            'price' => 2000,
            'switch' => in_array( 'paid-block-lw-gallery-3', $lw_active_template_ids, true ), // 条件に応じて設定
            'shop_url' => 'https://shop.lite-word.com/shop_template/paid-block-lw-gallery-3/',
        ],
        [
            'type' => 'h2',
            'id' => 'lw-comment',
            'title' => 'COMMENT（コメント系）',
        ],
        [
            'type' => 'block',
            'id' => 'lw-comment-1',
            'title' => 'コメント 01',
            'file' => $url . 'lw-comment-1.php',
            'image' => $url . 'lw-comment-1.webp',
            'description' => '',
        ],
        [
            'type' => 'h2',
            'id' => 'lw-step',
            'title' => 'STEP（ステップ系）',
        ],
        [
            'type' => 'block',
            'id' => 'lw-step-1',
            'title' => 'ステップ 01',
            'file' => $url . 'lw-step-1.php',
            'image' => $url . 'lw-step-1.webp',
            'description' => '',
        ],
        [
            'type' => 'block',
            'id' => 'lw-step-2',
            'title' => 'ステップ 02',
            'file' => $url . 'lw-step-2.php',
            'image' => $url . 'lw-step-2.webp',
            'description' => '',
        ],
        [
            'type' => 'paid_block',
            'id' => 'paid-block-lw-step-3',
            'title' => 'ステップ 03',
            'file' => $url . 'lw-step-3.php',
            'image' => $url . 'lw-step-3.webp',
            'description' => '',
            'price' => 1500,
            'switch' => in_array( 'paid-block-lw-step-3', $lw_active_template_ids, true ), // 条件に応じて設定
            'shop_url' => 'https://shop.lite-word.com/shop_template/paid-block-lw-step-3/',
        ],
        [
            'type' => 'paid_block',
            'id' => 'paid-block-lw-step-4',
            'title' => 'ステップ 04',
            'file' => $url . 'lw-step-4.php',
            'image' => $url . 'lw-step-4.webp',
            'description' => '',
            'price' => 1500,
            'switch' => in_array( 'paid-block-lw-step-4', $lw_active_template_ids, true ), // 条件に応じて設定
            'shop_url' => 'https://shop.lite-word.com/shop_template/paid-block-lw-step-4/',
        ],
        [
            'type' => 'paid_block',
            'id' => 'paid-block-lw-step-5',
            'title' => 'ステップ 05',
            'file' => $url . 'lw-step-5.php',
            'image' => $url . 'lw-step-5.webp',
            'description' => '',
            'price' => 1500,
            'switch' => in_array( 'paid-block-lw-step-5', $lw_active_template_ids, true ), // 条件に応じて設定
            'shop_url' => 'https://shop.lite-word.com/shop_template/paid-block-lw-step-5/',
        ],
        [
            'type' => 'paid_block',
            'id' => 'paid-block-lw-step-6',
            'title' => 'ステップ 06',
            'file' => $url . 'lw-step-6.php',
            'image' => $url . 'lw-step-6.webp',
            'description' => '',
            'price' => 2500,
            'switch' => in_array( 'paid-block-lw-step-6', $lw_active_template_ids, true ), // 条件に応じて設定
            'shop_url' => 'https://shop.lite-word.com/shop_template/paid-block-lw-step-6/',
        ],
        [
            'type' => 'h2',
            'id' => 'lw-company',
            'title' => 'COMPANY（会社概要系）',
        ],
        [
            'type' => 'block',
            'id' => 'lw-company-1',
            'title' => '会社概要系 01',
            'file' => $url . 'lw-company-1.php',
            'image' => $url . 'lw-company-1.webp',
            'description' => '',
        ],
        [
            'type' => 'block',
            'id' => 'lw-company-2',
            'title' => '会社概要系 02',
            'file' => $url . 'lw-company-2.php',
            'image' => $url . 'lw-company-2.webp',
            'description' => '',
        ],
        [
            'type' => 'paid_block',
            'id' => 'paid-block-lw-company-3',
            'title' => '会社概要 03',
            'file' => $url . 'lw-company-3.php',
            'image' => $url . 'lw-company-3.webp',
            'description' => '',
            'price' => 1500,
            'switch' => in_array( 'paid-block-lw-company-3', $lw_active_template_ids, true ), // 条件に応じて設定
            'shop_url' => 'https://shop.lite-word.com/shop_template/paid-block-lw-company-3/',
        ],
        [
            'type' => 'h2',
            'id' => 'lw-step',
            'title' => '沿革系',
        ],
        [
            'type' => 'paid_block',
            'id' => 'paid-block-history-1',
            'title' => '沿革 01',
            'file' => $url . 'lw-history-1.php',
            'image' => $url . 'lw-history-1.webp',
            'description' => '',
            'price' => 1500,
            'switch' => in_array( 'paid-block-history-1', $lw_active_template_ids, true ), // 条件に応じて設定
            'shop_url' => 'https://shop.lite-word.com/shop_template/paid-block-history-1/',
        ],
        [
            'type' => 'h2',
            'id' => 'lw-before-after',
            'title' => 'ビフォーアフター系',
        ],
        [
            'type' => 'paid_block',
            'id' => 'paid-block-before-after-1',
            'title' => 'ビフォーアフター 01',
            'file' => $url . 'lw-block-before-after-1.php',
            'image' => $url . 'lw-block-before-after-1.webp',
            'description' => 'とてもシンプルなbefore-afterデザインです。スマホの時は右にスライドさせるタイプになります。',
            'price' => 1500,
            'switch' => in_array( 'paid-block-before-after-1', $lw_active_template_ids, true ), // 条件に応じて設定
            'shop_url' => 'https://shop.lite-word.com/shop_template/paid-block-before-after-1/',
        ],
        [
            'type' => 'paid_block',
            'id' => 'paid-block-before-after-2',
            'title' => 'ビフォーアフター 02',
            'file' => $url . 'lw-block-before-after-2.php',
            'image' => $url . 'lw-block-before-after-2.webp',
            'description' => 'ビフォーアフター時によく利用されているパーツです。特長としては、真ん中に線が入っていて、線を左右に動かすと、ビフォーアフターの画像が切り替わるようなデザインになっています。',
            'price' => 1500,
            'switch' => in_array( 'paid-block-before-after-2', $lw_active_template_ids, true ), // 条件に応じて設定
            'shop_url' => 'https://shop.lite-word.com/shop_template/paid-block-before-after-2/',
        ],
        [
            'type' => 'h2',
            'id' => 'lw-list',
            'title' => 'LIST（リスト系）',
        ],
        [
            'type' => 'block',
            'id' => 'lw-list-1',
            'title' => 'リスト 01',
            'file' => $url . 'lw-list-1.php',
            'image' => $url . 'lw-list-1.webp',
            'description' => '',
        ],
        [
            'type' => 'block',
            'id' => 'lw-list-2',
            'title' => 'リスト 02',
            'file' => $url . 'lw-list-2.php',
            'image' => $url . 'lw-list-2.webp',
            'description' => '',
        ],
        [
            'type' => 'block',
            'id' => 'lw-list-3',
            'title' => 'リスト 03',
            'file' => $url . 'lw-list-3.php',
            'image' => $url . 'lw-list-3.webp',
            'description' => '',
        ],
        [
            'type' => 'block',
            'id' => 'lw-list-4',
            'title' => 'リスト 04',
            'file' => $url . 'lw-list-4.php',
            'image' => $url . 'lw-list-4.webp',
            'description' => '',
        ],
        [
            'type' => 'h2',
            'id' => 'lw-message',
            'title' => 'MESSAGE（メッセージ系）',
        ],
        [
            'type' => 'block',
            'id' => 'lw-message-1',
            'title' => 'メッセージ 01',
            'file' => $url . 'lw-message-1.php',
            'image' => $url . 'lw-message-1.webp',
            'description' => '',
        ],
        [
            'type' => 'h2',
            'id' => 'lw-qa',
            'title' => 'QA（よくある質問系）',
        ],
        [
            'type' => 'block',
            'id' => 'lw-qa-1',
            'title' => 'よくある質問 01',
            'file' => $url . 'lw-qa-1.php',
            'image' => $url . 'lw-qa-1.webp',
            'description' => '',
        ],
        [
            'type' => 'h2',
            'id' => 'lw-voice',
            'title' => 'VOICE（お客様の声系）',
        ],
        [
            'type' => 'block',
            'id' => 'lw-voice-1',
            'title' => 'お客様の声 01',
            'file' => $url . 'lw-voice-1.php',
            'image' => $url . 'lw-voice-1.webp',
            'description' => '',
        ],
        [
            'type' => 'paid_block',
            'id' => 'paid-block-voice-2',
            'title' => 'お客様の声 02',
            'file' => $url . 'lw-voice-2.php',
            'image' => $url . 'lw-voice-2.webp',
            'description' => '角を丸くした、ちょっとお洒落な女性向けデザインのお客様の声ブロックです。PCの時は2カラムで、スマホの時は1カラムとなります。',
            'price' => 1500,
            'switch' => in_array( 'paid-block-voice-2', $lw_active_template_ids, true ), // 条件に応じて設定
            'shop_url' => 'https://shop.lite-word.com/shop_template/paid-block-voice-2/',
        ],
        [
            'type' => 'paid_block',
            'id' => 'paid-block-voice-3',
            'title' => 'お客様の声 03',
            'file' => $url . 'lw-voice-3.php',
            'image' => $url . 'lw-voice-3.webp',
            'description' => 'スライド+ポップアップでお客様の声を表示するデザインのブロックです。スマホの時もスライド表示になります。',
            'price' => 3500,
            'switch' => in_array( 'paid-block-voice-3', $lw_active_template_ids, true ), // 条件に応じて設定
            'shop_url' => 'https://shop.lite-word.com/shop_template/paid-block-voice-3/',
        ],
        [
            'type' => 'h2',
            'id' => 'lw-profile',
            'title' => 'PROFILE（プロフィール系）',
        ],
        [
            'type' => 'block',
            'id' => 'profile-1',
            'title' => 'プロフィール 01',
            'file' => $url . 'profile-1.php',
            'image' => $url . 'profile-1.webp',
            'description' => '',
        ],
        [
            'type' => 'h2',
            'id' => 'lw-content',
            'title' => 'CONTENT（コンテンツ系）',
        ],
        [
            'type' => 'block',
            'id' => 'solution-1',
            'title' => 'solution-1',
            'file' => $url . 'solution-1.php',
            'image' => $url . 'solution-1.webp',
            'description' => '',
        ],
        [
            'type' => 'paid_block',
            'id' => 'paid-block-solution-2',
            'title' => 'solution-2',
            'file' => $url . 'solution-2.php',
            'image' => $url . 'solution-2.webp',
            'description' => 'PCの時も、スマホの時も3カラムの横並びのブロックです。短い文章でシンプルに伝える時に最適です。',
            'price' => 2200,
            'switch' => in_array( 'paid-block-solution-2', $lw_active_template_ids, true ), // 条件に応じて設定
            'shop_url' => 'https://shop.lite-word.com/shop_template/paid-block-solution-2',
        ],
        [
            'type' => 'block',
            'id' => 'lw-content-1',
            'title' => 'コンテンツ 01',
            'file' => $url . 'lw-content-1.php',
            'image' => $url . 'lw-content-1.webp',
            'description' => '',
        ],
        [
            'type' => 'block',
            'id' => 'lw-content-2',
            'title' => 'コンテンツ 02',
            'file' => $url . 'lw-content-2.php',
            'image' => $url . 'lw-content-2.webp',
            'description' => '',
        ],
        [
            'type' => 'paid_block',
            'id' => 'paid-block-content-3',
            'title' => 'コンテンツ 03',
            'file' => $url . 'lw-content-3.php',
            'image' => $url . 'lw-content-3.webp',
            'description' => 'PCの時は画像とテキストが横並び、スマホの時は縦並びになるよく使うデザインのブロックです。色々な場面で使えるので、1つ持っておくと便利です。',
            'price' => 1000,
            'switch' => in_array( 'paid-block-content-3', $lw_active_template_ids, true ), // 条件に応じて設定
            'shop_url' => 'https://shop.lite-word.com/shop_template/paid-block-content-3',
        ],
        [
            'type' => 'paid_block',
            'id' => 'paid-block-content-4',
            'title' => 'コンテンツ 04',
            'file' => $url . 'lw-content-4.php',
            'image' => $url . 'lw-content-4.webp',
            'description' => '短い説明テキストと横並び画像で、1セクションで教室や商材のイメージが伝わるブロックです。PCの時は横並び、スマホの時は縦並びになります。',
            'price' => 1500,
            'switch' => in_array( 'paid-block-content-4', $lw_active_template_ids, true ), // 条件に応じて設定
            'shop_url' => 'https://shop.lite-word.com/shop_template/paid-block-content-4',
        ],
        [
            'type' => 'paid_block',
            'id' => 'paid-block-content-5',
            'title' => 'コンテンツ 05',
            'file' => $url . 'lw-content-5.php',
            'image' => $url . 'lw-content-5.webp',
            'description' => 'PCの時は画像の横に文章が２カラムで表示される、ちょっと新聞のような雰囲気のパーツです。スマホの時はワンカラムとなります。',
            'price' => 1500,
            'switch' => in_array( 'paid-block-content-5', $lw_active_template_ids, true ), // 条件に応じて設定
            'shop_url' => 'https://shop.lite-word.com/shop_template/paid-block-content-5',
        ],
        [
            'type' => 'paid_block',
            'id' => 'paid-block-content-6',
            'title' => 'コンテンツ 06',
            'file' => $url . 'lw-content-6.php',
            'image' => $url . 'lw-content-6.webp',
            'description' => '正方形の画像の背景に重なるグレーのボックスが大人のお洒落さを引き立てている、横並びのコンテンツブロックです。スマホの時は縦並びになります。',
            'price' => 1500,
            'switch' => in_array( 'paid-block-content-6', $lw_active_template_ids, true ), // 条件に応じて設定
            'shop_url' => 'https://shop.lite-word.com/shop_template/paid-block-content-6',
        ],
        [
            'type' => 'paid_block',
            'id' => 'paid-block-content-7',
            'title' => 'コンテンツ 07',
            'file' => $url . 'lw-content-7.php',
            'image' => $url . 'lw-content-7.webp',
            'description' => '',
            'price' => 1500,
            'switch' => in_array( 'paid-block-content-7', $lw_active_template_ids, true ), // 条件に応じて設定
            'shop_url' => 'https://shop.lite-word.com/shop_template/paid-block-content-7',
        ],
        [
            'type' => 'paid_block',
            'id' => 'paid-block-content-8',
            'title' => 'コンテンツ 08',
            'file' => $url . 'lw-content-8.php',
            'image' => $url . 'lw-content-8.webp',
            'description' => '',
            'price' => 1500,
            'switch' => in_array( 'paid-block-content-8', $lw_active_template_ids, true ), // 条件に応じて設定
            'shop_url' => 'https://shop.lite-word.com/shop_template/paid-block-content-8',
        ],
        [
            'type' => 'pr_block',
            'id' => 'lw-pr-calendar-1',
            'title' => 'カレンダー 1（診療日）',
            'file' => $url . 'lw-pr-calendar-1.php',
            'image' => $url . 'lw-pr-calendar-1.webp',
            'description' => '',
            'price' => 1500,
            'switch' => in_array( 'lw-pr-calendar-1', $lw_active_template_ids, true ), // 条件に応じて設定
            'shop_url' => 'https://shop.lite-word.com/shop_template/lw-pr-calendar-1',
        ],
        [
            'type' => 'pr_block',
            'id' => 'lw-pr-table-1',
            'title' => '価格表 01',
            'file' => $url . 'lw-pr-table-1.php',
            'image' => $url . 'lw-pr-table-1.webp',
            'description' => '',
            'price' => 1500,
            'switch' => in_array( 'lw-pr-table-1', $lw_active_template_ids, true ), // 条件に応じて設定
            'shop_url' => 'https://shop.lite-word.com/shop_template/lw-pr-table-1',
        ],
        
    ];
    // 'type'が'paid_block'の場合のみ'switch'を設定する
    foreach ( $lw_block_arr as &$block ) {
        if ( $block[ 'type' ] === 'paid_block' ) {
            $block[ 'switch' ] = in_array( $block[ 'id' ], $lw_active_template_ids, true );
            
            // shop_urlにlw_shop_login_idパラメータを追加
            if ( !empty($lw_shop_login_id) && isset($block['shop_url']) ) {
                $separator = strpos($block['shop_url'], '?') !== false ? '&' : '?';
                $block['shop_url'] .= $separator . 'lw_shop_login_id=' . urlencode($lw_shop_login_id);
            }
        }
    }
    unset( $block );
    // 参照解除

    return $lw_block_arr;
}