<?php
if ( !defined( 'ABSPATH' ) ) exit;
function LwTemplateItems($page_template_url="",$shop_url=""){
    $items = [
        [
            'type' => 'item',
            'title' => '白紙',
            'img' => "$page_template_url/blank.webp",
            'img_size' => '',
            'class' => 'CloseLwTemplatePopup',
        ],
        [   
            'type' => 'h2',
            'id' => 'title_only',
            'title' => 'ページタイトルのみ',
        ],
        [   
            'type' => 'item',
            'title' => 'ページタイトル 01<br>トップページ用',
            'img' => "$page_template_url/fv_only/ptn_1.webp",
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => 'ページタイトル 01<br>トップページ用',
                'paid' => false,
                'img' => "$page_template_url/fv_only/ptn_1.webp",
                'code_url' => "$page_template_url/fv_only/ptn_1.php",
                'designer' => '',
                'message' => '',
            ],
        ],
        [   
            'type' => 'item',
            'title' => 'ページタイトル 02<br>下層ページ用',
            'img' => "$page_template_url/fv_only/ptn_2.webp",
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => 'ページタイトル 02<br>下層ページ用',
                'paid' => false,
                'img' => "$page_template_url/fv_only/ptn_2.webp",
                'code_url' => "$page_template_url/fv_only/ptn_2.php",
                'designer' => '',
                'message' => '',
            ],
        ],
        [   
            'type' => 'item',
            'title' => 'ページタイトル 03<br>画像を設置する場合',
            'img' => "$page_template_url/fv_only/ptn_3.webp",
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => 'ページタイトル 03<br>画像を設置する場合',
                'paid' => false,
                'img' => "$page_template_url/fv_only/ptn_3.webp",
                'code_url' => "$page_template_url/fv_only/ptn_3.php",
                'designer' => '',
                'message' => '',
            ],
        ],
        [   
            'type' => 'item',
            'title' => 'ページタイトル 04<br>トップページ用',
            'img' => "$page_template_url/fv_only/ptn_4.webp",
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => 'ページタイトル 04<br>トップページ用',
                'paid' => false,
                'img' => "$page_template_url/fv_only/ptn_4.webp",
                'code_url' => "$page_template_url/fv_only/ptn_4.php",
                'designer' => '',
                'message' => '',
            ],
        ],
        [   
            'type' => 'item',
            'title' => 'ページタイトル 05<br>下層ページ用',
            'img' => "$page_template_url/fv_only/ptn_5.webp",
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => 'ページタイトル 05<br>下層ページ用',
                'paid' => false,
                'img' => "$page_template_url/fv_only/ptn_5.webp",
                'code_url' => "$page_template_url/fv_only/ptn_5.php",
                'designer' => '',
                'message' => '',
            ],
        ],
        [   
            'type' => 'item',
            'title' => 'ページタイトル 06<br>下層ページ用',
            'img' => "$page_template_url/fv_only/ptn_6.webp",
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => 'ページタイトル 06<br>下層ページ用',
                'paid' => false,
                'img' => "$page_template_url/fv_only/ptn_6.webp",
                'code_url' => "$page_template_url/fv_only/ptn_6.php",
                'designer' => '',
                'message' => '',
            ],
        ],
        [   
            'type' => 'item',
            'title' => 'ページタイトル 07<br>トップページ用（動画背景）',
            'img' => "$page_template_url/fv_only/ptn_7.webp",
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => 'ページタイトル 07<br>トップページ用（動画背景）',
                'paid' => false,
                'img' => "$page_template_url/fv_only/ptn_7.webp",
                'code_url' => "$page_template_url/fv_only/ptn_7.php",
                'designer' => '',
                'message' => '',
            ],
        ],
        [
            'type' => 'h2',
            'id' => 'fv_industry',
            'title' => '業種別ファーストビュー',
        ],
        [
            'type' => 'item',
            'title' => '整体・接骨院｜中央に一言＋予約ボタン',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/seitai_fv01.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '整体・接骨院｜中央に一言＋予約ボタン',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/seitai_fv01.webp',
                'code_url' => "$page_template_url/fv_only/seitai_fv01.php",
                'designer' => '',
                'message' => '中央に短い言葉を置いて予約に繋ぐ、いちばん素直な形。写真1枚で成立する。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '下層ページ｜タイトルだけの帯',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/common_fv02.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '下層ページ｜タイトルだけの帯',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/common_fv02.webp',
                'code_url' => "$page_template_url/fv_only/common_fv02.php",
                'designer' => '',
                'message' => 'お知らせ・記事一覧など、中身が主役のページに。いちばん軽い。',
            ],
        ],
        [
            'type' => 'item',
            'title' => 'フォトスタジオ｜写真だけを見せる',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/photo_fv03.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => 'フォトスタジオ｜写真だけを見せる',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/photo_fv03.webp',
                'code_url' => "$page_template_url/fv_only/photo_fv03.php",
                'designer' => '',
                'message' => '文字を一切乗せず写真だけで見せる形。作品が主役の業種に。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '税理士・士業｜左寄せで落ち着いた印象',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/zeirishi_fv04.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '税理士・士業｜左寄せで落ち着いた印象',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/zeirishi_fv04.webp',
                'code_url' => "$page_template_url/fv_only/zeirishi_fv04.php",
                'designer' => '',
                'message' => '左寄せで文字量を確保できる。堅い業種・説明が要る業種に。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '下層ページ｜タイトル＋ひとこと説明',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/common_fv05.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '下層ページ｜タイトル＋ひとこと説明',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/common_fv05.webp',
                'code_url' => "$page_template_url/fv_only/common_fv05.php",
                'designer' => '',
                'message' => 'サービス詳細など、ページの目的を一行そえたいときに。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '下層ページ｜白い箱にタイトル',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/common_fv06.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '下層ページ｜白い箱にタイトル',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/common_fv06.webp',
                'code_url' => "$page_template_url/fv_only/common_fv06.php",
                'designer' => '',
                'message' => '白い箱が入るので、写真が明るくても暗くても文字が読める。いちばん使われている形。',
            ],
        ],
        [
            'type' => 'item',
            'title' => 'カフェ・飲食店｜動画を背景に流す',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/cafe_fv07.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => 'カフェ・飲食店｜動画を背景に流す',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/cafe_fv07.webp',
                'code_url' => "$page_template_url/fv_only/cafe_fv07.php",
                'designer' => '',
                'message' => '動画が背景で動く。空気感で選ばれる業種に。動画は利用者が差し替える。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '【買切り】学習塾・教室｜選ばれる理由を3つ先に出す',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/juku_fv08.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '【買切り】学習塾・教室｜選ばれる理由を3つ先に出す',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/juku_fv08.webp',
                'code_url' => "$page_template_url/fv_only/juku_fv08.php",
                'designer' => '',
                'message' => '丸いバッジに3つの強みが入る。🚨 バッジは3〜5文字まで（長いと溢れる）。　※このサンプルは買切り専用ブロック（¥4,400・SHOPで個別購入）を使っています。プレミアムプランには含まれません。購入していないとフロントに表示されません。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '【プレミアム】美容室・サロン｜写真だけのスライダー',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/salon_fv09.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '【プレミアム】美容室・サロン｜写真だけのスライダー',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/salon_fv09.webp',
                'code_url' => "$page_template_url/fv_only/salon_fv09.php",
                'designer' => '',
                'message' => '文字を持たず写真だけが切り替わる。🚨 blockId 必須（空だと真っ白になる）。　※このサンプルはプレミアムブロックを使っています。無料プランのままだとフロントに表示されません。プレミアムに入らない場合は、SHOPで単体購入（¥4,400）もできます。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '【プレミアム】下層ページ｜色の帯にタイトル（プレミアム）',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/common_fv10.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '【プレミアム】下層ページ｜色の帯にタイトル（プレミアム）',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/common_fv10.webp',
                'code_url' => "$page_template_url/fv_only/common_fv10.php",
                'designer' => '',
                'message' => '色の帯が入るぶん、下層でも印象が締まる。　※このサンプルはプレミアムブロックを使っています。無料プランのままだとフロントに表示されません。プレミアムに入らない場合は、SHOPで単体購入（¥1,500）もできます。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '【プレミアム】工務店・建設｜背景が切り替わるスライダー＋文字',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/koumuten_fv11.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '【プレミアム】工務店・建設｜背景が切り替わるスライダー＋文字',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/koumuten_fv11.webp',
                'code_url' => "$page_template_url/fv_only/koumuten_fv11.php",
                'designer' => '',
                'message' => '施工事例が複数ある業種に。文字は固定で背景だけ動く。🚨 blockId 必須。　※このサンプルはプレミアムブロックを使っています。無料プランのままだとフロントに表示されません。プレミアムに入らない場合は、SHOPで単体購入（¥4,400）もできます。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '【プレミアム】ネイル・まつげ｜ヘッダーごと全画面＋お知らせ',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/nail_fv12.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '【プレミアム】ネイル・まつげ｜ヘッダーごと全画面＋お知らせ',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/nail_fv12.webp',
                'code_url' => "$page_template_url/fv_only/nail_fv12.php",
                'designer' => '',
                'message' => 'ロゴ・ナビ・CTA・最新のお知らせまで1画面に収まる。🚨 ページのヘッダー設定は「非表示」にする。　※このサンプルはプレミアムブロックを使っています。無料プランのままだとフロントに表示されません。プレミアムに入らない場合は、SHOPで単体購入（¥3,500）もできます。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '【プレミアム】ペットサロン・動物病院｜左に文章・右に写真',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/pet_fv13.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '【プレミアム】ペットサロン・動物病院｜左に文章・右に写真',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/pet_fv13.webp',
                'code_url' => "$page_template_url/fv_only/pet_fv13.php",
                'designer' => '',
                'message' => '左が地色なので文字が必ず読める。説明を丁寧に置きたい業種に。　※このサンプルはプレミアムブロックを使っています。無料プランのままだとフロントに表示されません。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '【プレミアム】不動産・住宅｜ヘッダーごと全画面＋CTA2つ',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/fudosan_fv14.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '【プレミアム】不動産・住宅｜ヘッダーごと全画面＋CTA2つ',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/fudosan_fv14.webp',
                'code_url' => "$page_template_url/fv_only/fudosan_fv14.php",
                'designer' => '',
                'message' => 'サイトの顔になる形。🚨 ページのヘッダー設定は「非表示」に。スマホの高さは560px以上にする。　※このサンプルはプレミアムブロックを使っています。無料プランのままだとフロントに表示されません。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '【プレミアム】カフェ・物販｜色の面に写真を帯で乗せる',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/cafe_fv15.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '【プレミアム】カフェ・物販｜色の面に写真を帯で乗せる',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/cafe_fv15.webp',
                'code_url' => "$page_template_url/fv_only/cafe_fv15.php",
                'designer' => '',
                'message' => '写真が1枚でも締まって見える。落ち着いた印象にしたいときに。　※このサンプルはプレミアムブロックを使っています。無料プランのままだとフロントに表示されません。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '【プレミアム】美容室・飲食｜写真の上に半透明の箱',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/salon_fv16.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '【プレミアム】美容室・飲食｜写真の上に半透明の箱',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/salon_fv16.webp',
                'code_url' => "$page_template_url/fv_only/salon_fv16.php",
                'designer' => '',
                'message' => '写真がどんなに明るくても文字が読める。写真を大きく見せたいときに。　※このサンプルはプレミアムブロックを使っています。無料プランのままだとフロントに表示されません。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '【プレミアム】下層ページ｜左右に装飾を添えた明るい帯',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/seitai_fv17.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '【プレミアム】下層ページ｜左右に装飾を添えた明るい帯',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/seitai_fv17.webp',
                'code_url' => "$page_template_url/fv_only/seitai_fv17.php",
                'designer' => '',
                'message' => '紙の質感の上に、左右へ水彩の飾りを置いた下層タイトル。たかしデンタルクリニック（実際の制作サイト）と同じ組み方。　※このサンプルはプレミアムブロックを使っています。無料プランのままだとフロントに表示されません。',
            ],
        ],
        [
            'type' => 'item',
            'title' => 'ヨガ・ピラティス｜中央に一言＋体験予約',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/yoga_fv01.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => 'ヨガ・ピラティス｜中央に一言＋体験予約',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/yoga_fv01.webp',
                'code_url' => "$page_template_url/fv_only/yoga_fv01.php",
                'designer' => '',
                'message' => '1巡目の整体と同じブロック。緑と余白の多い写真にすると、まったく違う印象になる。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '司法書士・法律事務所｜左寄せで硬質に',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/shihou_fv04.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '司法書士・法律事務所｜左寄せで硬質に',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/shihou_fv04.webp',
                'code_url' => "$page_template_url/fv_only/shihou_fv04.php",
                'designer' => '',
                'message' => '1巡目の税理士と同じブロック。暗い写真＋高いフィルタで、より硬い印象にした。',
            ],
        ],
        [
            'type' => 'item',
            'title' => 'クリーニング｜下層・清潔感のある帯',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/cleaning_fv05.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => 'クリーニング｜下層・清潔感のある帯',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/cleaning_fv05.webp',
                'code_url' => "$page_template_url/fv_only/cleaning_fv05.php",
                'designer' => '',
                'message' => '明るい写真にうすいフィルタ。清潔感が要る業種の下層ページに。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '保育園・学童｜下層・白い箱にタイトル',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/hoiku_fv06.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '保育園・学童｜下層・白い箱にタイトル',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/hoiku_fv06.webp',
                'code_url' => "$page_template_url/fv_only/hoiku_fv06.php",
                'designer' => '',
                'message' => '1巡目の汎用と同じブロック。明るくにぎやかな写真でも、白い箱があるので文字が読める。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '農園・直売所｜写真だけを大きく',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/nouen_fv03.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '農園・直売所｜写真だけを大きく',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/nouen_fv03.webp',
                'code_url' => "$page_template_url/fv_only/nouen_fv03.php",
                'designer' => '',
                'message' => '文字を乗せず風景だけで見せる。景色が売りの業種に。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '【買切り】自動車整備・板金｜強みを3つ先に出す',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/seibi_fv08.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '【買切り】自動車整備・板金｜強みを3つ先に出す',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/seibi_fv08.webp',
                'code_url' => "$page_template_url/fv_only/seibi_fv08.php",
                'designer' => '',
                'message' => '1巡目の学習塾と同じブロック。バッジは2文字＋改行＋2文字、メダルは「ラベル/数値/単位」。　※このサンプルは買切り専用ブロック（¥4,400・SHOPで個別購入）を使っています。プレミアムプランには含まれません。購入していないとフロントに表示されません。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '【プレミアム】パン屋・物販｜写真だけのスライダー',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/bakery_fv09.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '【プレミアム】パン屋・物販｜写真だけのスライダー',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/bakery_fv09.webp',
                'code_url' => "$page_template_url/fv_only/bakery_fv09.php",
                'designer' => '',
                'message' => '商品や店内の写真を順番に見せる。🚨 blockId 必須。　※このサンプルはプレミアムブロックを使っています。無料プランのままだとフロントに表示されません。プレミアムに入らない場合は、SHOPで単体購入（¥4,400）もできます。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '【プレミアム】下層｜布地のような静かな帯',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/yoga_fv10.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '【プレミアム】下層｜布地のような静かな帯',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/yoga_fv10.webp',
                'code_url' => "$page_template_url/fv_only/yoga_fv10.php",
                'designer' => '',
                'message' => '抽象的な背景にすると、業種を選ばず落ち着いた下層ページになる。　※このサンプルはプレミアムブロックを使っています。無料プランのままだとフロントに表示されません。プレミアムに入らない場合は、SHOPで単体購入（¥1,500）もできます。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '【プレミアム】リフォーム｜施工事例が切り替わる',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/reform_fv11.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '【プレミアム】リフォーム｜施工事例が切り替わる',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/reform_fv11.webp',
                'code_url' => "$page_template_url/fv_only/reform_fv11.php",
                'designer' => '',
                'message' => '1巡目の工務店と同じブロック。ビフォーアフターがある業種に向く。🚨 blockId 必須。　※このサンプルはプレミアムブロックを使っています。無料プランのままだとフロントに表示されません。プレミアムに入らない場合は、SHOPで単体購入（¥4,400）もできます。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '【プレミアム】夜のカフェ・バー｜ヘッダーごと全画面',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/cafe_fv12.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '【プレミアム】夜のカフェ・バー｜ヘッダーごと全画面',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/cafe_fv12.webp',
                'code_url' => "$page_template_url/fv_only/cafe_fv12.php",
                'designer' => '',
                'message' => '同じブロックでも背景を動画にすると印象が変わる。暗い映像なのでフィルタ35%で文字が読める。　※このサンプルはプレミアムブロックを使っています。無料プランのままだとフロントに表示されません。プレミアムに入らない場合は、SHOPで単体購入（¥3,500）もできます。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '【プレミアム】歯科医院｜左に説明・右に写真',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/shika_fv13.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '【プレミアム】歯科医院｜左に説明・右に写真',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/shika_fv13.webp',
                'code_url' => "$page_template_url/fv_only/shika_fv13.php",
                'designer' => '',
                'message' => '1巡目のペットサロンと同じブロック。説明を丁寧に置きたい医療系に向く。　※このサンプルはプレミアムブロックを使っています。無料プランのままだとフロントに表示されません。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '【プレミアム】パーソナルジム｜ヘッダーごと全画面・力強く',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/gym_fv14.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '【プレミアム】パーソナルジム｜ヘッダーごと全画面・力強く',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/gym_fv14.webp',
                'code_url' => "$page_template_url/fv_only/gym_fv14.php",
                'designer' => '',
                'message' => '1巡目の不動産と同じブロックを動画背景で。暗い映像なのでフィルタは40%で足りる。　※このサンプルはプレミアムブロックを使っています。無料プランのままだとフロントに表示されません。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '【プレミアム】花屋・雑貨｜色の面に写真を帯で',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/hanaya_fv15.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '【プレミアム】花屋・雑貨｜色の面に写真を帯で',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/hanaya_fv15.webp',
                'code_url' => "$page_template_url/fv_only/hanaya_fv15.php",
                'designer' => '',
                'message' => '1巡目のカフェと同じブロック。地色を業種の色にすると空気が決まる。　※このサンプルはプレミアムブロックを使っています。無料プランのままだとフロントに表示されません。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '【プレミアム】居酒屋・和食｜写真の上に半透明の箱',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/izakaya_fv16.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '【プレミアム】居酒屋・和食｜写真の上に半透明の箱',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/izakaya_fv16.webp',
                'code_url' => "$page_template_url/fv_only/izakaya_fv16.php",
                'designer' => '',
                'message' => '1巡目の美容室と同じブロックを動画背景で。半透明の箱が映像になじんで落ち着く。　※このサンプルはプレミアムブロックを使っています。無料プランのままだとフロントに表示されません。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '【プレミアム】美容室（下層）｜色の帯に飾りだけ（背景写真なし）',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/salon_fv17.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '【プレミアム】美容室（下層）｜色の帯に飾りだけ（背景写真なし）',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/salon_fv17.webp',
                'code_url' => "$page_template_url/fv_only/salon_fv17.php",
                'designer' => '',
                'message' => '同じ fv-17。**背景写真を1枚も持っていなくても**、色の帯に左右の飾りを添えれば成立する。背景を空にしたときだけ bg_color がそのまま帯の色になる（このブロックで色が見える唯一の形）。　※このサンプルはプレミアムブロックを使っています。無料プランのままだとフロントに表示されません。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '下層｜暗い地のタイトル帯',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/common_fv02b.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '下層｜暗い地のタイトル帯',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/common_fv02b.webp',
                'code_url' => "$page_template_url/fv_only/common_fv02b.php",
                'designer' => '',
                'message' => '1巡目の明るい帯と対になる、締まった印象の下層タイトル。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '教室・スクール｜動画を背景に流す',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/juku_fv07.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '教室・スクール｜動画を背景に流す',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/juku_fv07.webp',
                'code_url' => "$page_template_url/fv_only/juku_fv07.php",
                'designer' => '',
                'message' => '1巡目のカフェと同じブロック。動画は利用者が自分のものに差し替える前提。',
            ],
        ],
        [
            'type' => 'item',
            'title' => 'ブックカフェ｜枠線だけのボタンで静かに',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/book_fv01.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => 'ブックカフェ｜枠線だけのボタンで静かに',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/book_fv01.webp',
                'code_url' => "$page_template_url/fv_only/book_fv01.php",
                'designer' => '',
                'message' => '同じ fv-1。ボタンを「塗りつぶし」から「枠線だけ・角丸なし」に変えると、一気に静かな店の空気になる。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '弁当・仕出し｜説明文なしの短い帯',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/bento_fv01.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '弁当・仕出し｜説明文なしの短い帯',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/bento_fv01.webp',
                'code_url' => "$page_template_url/fv_only/bento_fv01.php",
                'designer' => '',
                'message' => '同じ fv-1。説明文を空にして高さを 440px まで下げると、注文導線だけの短い帯になる。ボタンはピル型。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '鍼灸院｜720pxの大きな面＋半透明ボタン',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/shinkyu_fv01.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '鍼灸院｜720pxの大きな面＋半透明ボタン',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/shinkyu_fv01.webp',
                'code_url' => "$page_template_url/fv_only/shinkyu_fv01.php",
                'designer' => '',
                'message' => '同じ fv-1。高さを 720px まで上げ、ボタンを半透明（不透明度0.25）にした。スクロールさせる前に一度止めたいトップ向け。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '下層ページ｜黒文字で明るい帯',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/saiyo_fv02.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '下層ページ｜黒文字で明るい帯',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/saiyo_fv02.webp',
                'code_url' => "$page_template_url/fv_only/saiyo_fv02.php",
                'designer' => '',
                'message' => '同じ fv-2。1・2巡目はすべて白文字だったが、明るい写真＋薄いフィルタ＋黒文字にすると印象が反転する。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '下層ページ｜480pxの厚い帯',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/tenji_fv02.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '下層ページ｜480pxの厚い帯',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/tenji_fv02.webp',
                'code_url' => "$page_template_url/fv_only/tenji_fv02.php",
                'designer' => '',
                'message' => '同じ fv-2。高さを 480px まで上げると、下層の帯ではなく1枚絵のような扉ページになる。下線は金にした。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '下層ページ｜220pxのごく薄い帯',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/faq_fv02.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '下層ページ｜220pxのごく薄い帯',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/faq_fv02.webp',
                'code_url' => "$page_template_url/fv_only/faq_fv02.php",
                'designer' => '',
                'message' => '同じ fv-2。220px まで下げると、本文をすぐ読ませたいページ（Q&A・利用規約）に向く。いちばん軽い使い方。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '建築設計事務所｜右寄せ・幅1280',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/sekkei_fv04.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '建築設計事務所｜右寄せ・幅1280',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/sekkei_fv04.webp',
                'code_url' => "$page_template_url/fv_only/sekkei_fv04.php",
                'designer' => '',
                'message' => '同じ fv-4。1・2巡目は左寄せだったが、右寄せ（pc_right）＋幅1280にすると写真の左側を大きく空けられる。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '保険代理店｜中央寄せ・特大の見出し',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/hoken_fv04.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '保険代理店｜中央寄せ・特大の見出し',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/hoken_fv04.webp',
                'code_url' => "$page_template_url/fv_only/hoken_fv04.php",
                'designer' => '',
                'message' => '同じ fv-4。中央寄せ（pc_center）＋見出し88pxにすると、fv-1 のような一言型のトップに化ける。',
            ],
        ],
        [
            'type' => 'item',
            'title' => 'システム開発｜幅860に絞って濃い面',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/it_fv04.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => 'システム開発｜幅860に絞って濃い面',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/it_fv04.webp',
                'code_url' => "$page_template_url/fv_only/it_fv04.php",
                'designer' => '',
                'message' => '同じ fv-4。左寄せのまま幅を860に絞り、フィルタを0.78まで濃くすると、文章を読ませる硬い面になる。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '和菓子店｜260pxまで削った細い帯',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/wagashi_fv05.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '和菓子店｜260pxまで削った細い帯',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/wagashi_fv05.webp',
                'code_url' => "$page_template_url/fv_only/wagashi_fv05.php",
                'designer' => '',
                'message' => '同じ fv-5。トップ用のブロックを260pxまで削ると、写真の帯として下層にも使える。いちばん薄い使い方。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '学童保育｜橙の濃いフィルタ',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/gakudo_fv05.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '学童保育｜橙の濃いフィルタ',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/gakudo_fv05.webp',
                'code_url' => "$page_template_url/fv_only/gakudo_fv05.php",
                'designer' => '',
                'message' => '同じ fv-5。写真をほぼ橙で塗りつぶす（0.72）と、写真の質に左右されない明るい面になる。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '旅館・料亭｜720pxの一枚絵',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/ryokan_fv05.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '旅館・料亭｜720pxの一枚絵',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/ryokan_fv05.webp',
                'code_url' => "$page_template_url/fv_only/ryokan_fv05.php",
                'designer' => '',
                'message' => '同じ fv-5。720px まで上げてフィルタを0.4に落とすと、写真そのものを見せる扉になる。文字は最小限に。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '造園・庭づくり｜720pxの深緑',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/zoen_fv06.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '造園・庭づくり｜720pxの深緑',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/zoen_fv06.webp',
                'code_url' => "$page_template_url/fv_only/zoen_fv06.php",
                'designer' => '',
                'message' => '同じ fv-6。高さを720pxにして深緑を濃く乗せると、面積で見せるトップになる。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '料理教室｜黒文字・下層の帯として',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/keiko_fv06.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '料理教室｜黒文字・下層の帯として',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/keiko_fv06.webp',
                'code_url' => "$page_template_url/fv_only/keiko_fv06.php",
                'designer' => '',
                'message' => '同じ fv-6。320pxまで下げて白フィルタ＋黒文字にすると、トップ用のブロックが下層の帯として使える。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '相続のご相談｜500pxの中くらいの面',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/souzoku_fv06.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '相続のご相談｜500pxの中くらいの面',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/souzoku_fv06.webp',
                'code_url' => "$page_template_url/fv_only/souzoku_fv06.php",
                'designer' => '',
                'message' => '同じ fv-6。500pxはトップにも下層にも使える中間。サブタイトルを日本語の一文にすると説明が一行増える。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '【買切り】まつげエクステ｜数字を出さない形',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/matsuge_fv08.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '【買切り】まつげエクステ｜数字を出さない形',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/matsuge_fv08.webp',
                'code_url' => "$page_template_url/fv_only/matsuge_fv08.php",
                'designer' => '',
                'message' => '同じ fv-8。showPoint をオフにすると右上の数字が消え、3つの短いキーワードだけの静かな形になる。　※このサンプルは買切り専用ブロック（¥4,400・SHOPで個別購入）を使っています。プレミアムプランには含まれません。購入していないとフロントに表示されません。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '【買切り】外壁塗装｜見出しを1行に、数字を大きく',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/tosou_fv08.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '【買切り】外壁塗装｜見出しを1行に、数字を大きく',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/tosou_fv08.webp',
                'code_url' => "$page_template_url/fv_only/tosou_fv08.php",
                'designer' => '',
                'message' => '同じ fv-8。noLineBreakMain をオンにして見出しを1行にし、数字（施工実績）を主役にした攻めた形。　※このサンプルは買切り専用ブロック（¥4,400・SHOPで個別購入）を使っています。プレミアムプランには含まれません。購入していないとフロントに表示されません。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '【買切り】訪問介護｜数字を「%」ではなく年数で',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/kaigo_fv08.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '【買切り】訪問介護｜数字を「%」ではなく年数で',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/kaigo_fv08.webp',
                'code_url' => "$page_template_url/fv_only/kaigo_fv08.php",
                'designer' => '',
                'message' => '同じ fv-8。数字の単位を年に変えるだけで、実績自慢ではなく「長く続けている安心」の見せ方になる。　※このサンプルは買切り専用ブロック（¥4,400・SHOPで個別購入）を使っています。プレミアムプランには含まれません。購入していないとフロントに表示されません。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '【プレミアム】採用特設（下層）｜白い内枠・角丸ゼロ',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/kyujin_fv10.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '【プレミアム】採用特設（下層）｜白い内枠・角丸ゼロ',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/kyujin_fv10.webp',
                'code_url' => "$page_template_url/fv_only/kyujin_fv10.php",
                'designer' => '',
                'message' => '同じ fv-10。内枠を白・角丸0にすると、写真の上に紙を置いたような硬い見出しになる。　※このサンプルはプレミアムブロックを使っています。無料プランのままだとフロントに表示されません。プレミアムに入らない場合は、SHOPで単体購入（¥1,500）もできます。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '【プレミアム】アクセス（下層）｜写真を使わず淡い色だけで作る',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/access_fv10.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '【プレミアム】アクセス（下層）｜写真を使わず淡い色だけで作る',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/access_fv10.webp',
                'code_url' => "$page_template_url/fv_only/access_fv10.php",
                'designer' => '',
                'message' => '同じ fv-10。写真を敷かず、背景を淡いクリーム・内枠を桜色にすると、角丸と白い枠がそのまま活きて優しい下層になる。介護・保育・クリニックなど、やわらかく見せたい業種に。これがこのブロックの既定の配色。　※このサンプルはプレミアムブロックを使っています。無料プランのままだとフロントに表示されません。プレミアムに入らない場合は、SHOPで単体購入（¥1,500）もできます。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '【プレミアム】お客様の声（下層）｜影を落として浮かせる',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/voice_fv10.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '【プレミアム】お客様の声（下層）｜影を落として浮かせる',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/voice_fv10.webp',
                'code_url' => "$page_template_url/fv_only/voice_fv10.php",
                'designer' => '',
                'message' => '同じ fv-10。内枠に影（ぼかし24px）を落とすと、帯が写真から浮いて見える。文字は小さめにした。　※このサンプルはプレミアムブロックを使っています。無料プランのままだとフロントに表示されません。プレミアムに入らない場合は、SHOPで単体購入（¥1,500）もできます。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '【プレミアム】エステサロン｜固定幅＋横スライド・CTAなし',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/esthe_fv11.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '【プレミアム】エステサロン｜固定幅＋横スライド・CTAなし',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/esthe_fv11.webp',
                'code_url' => "$page_template_url/fv_only/esthe_fv11.php",
                'designer' => '',
                'message' => '同じ fv-11。幅を固定（1200px）にして左右に余白を作り、切り替えも横スライドに変えた。CTAは出さない。　※このサンプルはプレミアムブロックを使っています。無料プランのままだとフロントに表示されません。プレミアムに入らない場合は、SHOPで単体購入（¥4,400）もできます。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '【プレミアム】ブライダル装花｜全幅＋フェード・濃いフィルタ',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/bridal_fv11.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '【プレミアム】ブライダル装花｜全幅＋フェード・濃いフィルタ',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/bridal_fv11.webp',
                'code_url' => "$page_template_url/fv_only/bridal_fv11.php",
                'designer' => '',
                'message' => '同じ fv-11。全幅・フェード・フィルタ0.6にすると、写真が主役ではなく文字が主役の面になる。　※このサンプルはプレミアムブロックを使っています。無料プランのままだとフロントに表示されません。プレミアムに入らない場合は、SHOPで単体購入（¥4,400）もできます。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '【プレミアム】自転車店｜固定幅1440・フェード',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/jitensha_fv11.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '【プレミアム】自転車店｜固定幅1440・フェード',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/jitensha_fv11.webp',
                'code_url' => "$page_template_url/fv_only/jitensha_fv11.php",
                'designer' => '',
                'message' => '同じ fv-11。幅1440はほぼ全幅だが左右に少しだけ余白が残る。写真をきっちり見せたい物販向け。　※このサンプルはプレミアムブロックを使っています。無料プランのままだとフロントに表示されません。プレミアムに入らない場合は、SHOPで単体購入（¥4,400）もできます。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '【プレミアム】バーバー｜お知らせ欄を出さない形',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/barber_fv12.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '【プレミアム】バーバー｜お知らせ欄を出さない形',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/barber_fv12.webp',
                'code_url' => "$page_template_url/fv_only/barber_fv12.php",
                'designer' => '',
                'message' => '同じ fv-12。newsListVisible をオフにすると下のお知らせ欄が消え、写真と見出しだけの潔い全画面になる。　※このサンプルはプレミアムブロックを使っています。無料プランのままだとフロントに表示されません。プレミアムに入らない場合は、SHOPで単体購入（¥3,500）もできます。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '【プレミアム】ダイニングバー｜グラデーションのフィルタ',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/dining_fv12.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '【プレミアム】ダイニングバー｜グラデーションのフィルタ',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/dining_fv12.webp',
                'code_url' => "$page_template_url/fv_only/dining_fv12.php",
                'designer' => '',
                'message' => '同じ fv-12。フィルタを単色からグラデーションに変えると、上は写真が見えて下だけ暗くなり文字が読める。　※このサンプルはプレミアムブロックを使っています。無料プランのままだとフロントに表示されません。プレミアムに入らない場合は、SHOPで単体購入（¥3,500）もできます。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '【プレミアム】歯科医院｜明るい背景・CTAを1つに',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/shika_fv12.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '【プレミアム】歯科医院｜明るい背景・CTAを1つに',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/shika_fv12.webp',
                'code_url' => "$page_template_url/fv_only/shika_fv12.php",
                'designer' => '',
                'message' => '同じ fv-12。薄いフィルタ（22）で明るいまま使い、CTAを1つに減らすと医療系らしい落ち着いた形になる。　※このサンプルはプレミアムブロックを使っています。無料プランのままだとフロントに表示されません。プレミアムに入らない場合は、SHOPで単体購入（¥3,500）もできます。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '【プレミアム】動物病院｜丸ゴシックでやわらかく',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/doubutsu_fv13.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '【プレミアム】動物病院｜丸ゴシックでやわらかく',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/doubutsu_fv13.webp',
                'code_url' => "$page_template_url/fv_only/doubutsu_fv13.php",
                'designer' => '',
                'message' => '同じ fv-13。フォントを M PLUS Rounded 1c にして太さを500まで落とすと、同じ形でも角が取れる。　※このサンプルはプレミアムブロックを使っています。無料プランのままだとフロントに表示されません。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '【プレミアム】ピラティス｜袋文字（ストローク）で抜く',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/pilates_fv13.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '【プレミアム】ピラティス｜袋文字（ストローク）で抜く',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/pilates_fv13.webp',
                'code_url' => "$page_template_url/fv_only/pilates_fv13.php",
                'designer' => '',
                'message' => '同じ fv-13。文字を塗らずに縁だけ（ストローク3px）にすると、写真を隠さずに大きな見出しが置ける。　※このサンプルはプレミアムブロックを使っています。無料プランのままだとフロントに表示されません。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '【プレミアム】日帰り温泉｜フィルタでほぼ塗りつぶす',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/onsen_fv13.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '【プレミアム】日帰り温泉｜フィルタでほぼ塗りつぶす',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/onsen_fv13.webp',
                'code_url' => "$page_template_url/fv_only/onsen_fv13.php",
                'designer' => '',
                'message' => '同じ fv-13。フィルタを0.9まで上げて写真をほぼ塗りつぶすと、色の面に近づく。素材の写真が弱いときの逃げ道。　※このサンプルはプレミアムブロックを使っています。無料プランのままだとフロントに表示されません。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '【プレミアム】賃貸専門店｜ヘッダーを出さない形',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/chintai_fv14.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '【プレミアム】賃貸専門店｜ヘッダーを出さない形',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/chintai_fv14.webp',
                'code_url' => "$page_template_url/fv_only/chintai_fv14.php",
                'designer' => '',
                'message' => '同じ fv-14。showHeader をオフにするとロゴとメニューが消える。サイト共通のヘッダーが別にある場合はこちら。　※このサンプルはプレミアムブロックを使っています。無料プランのままだとフロントに表示されません。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '【プレミアム】プログラミング教室｜グラデーションのフィルタ',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/prog_fv14.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '【プレミアム】プログラミング教室｜グラデーションのフィルタ',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/prog_fv14.webp',
                'code_url' => "$page_template_url/fv_only/prog_fv14.php",
                'designer' => '',
                'message' => '同じ fv-14。グラデーションのフィルタにすると上半分の写真が残る。ヘッダーの文字も読めるちょうどよい濃さになる。　※このサンプルはプレミアムブロックを使っています。無料プランのままだとフロントに表示されません。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '【プレミアム】会計事務所｜CTAを1つに絞る',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/kaikei_fv14.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '【プレミアム】会計事務所｜CTAを1つに絞る',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/kaikei_fv14.webp',
                'code_url' => "$page_template_url/fv_only/kaikei_fv14.php",
                'designer' => '',
                'message' => '同じ fv-14。CTAを2つから1つに減らすと迷いが減る。連絡手段が1つしかない事務所向け。　※このサンプルはプレミアムブロックを使っています。無料プランのままだとフロントに表示されません。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '【プレミアム】矯正歯科｜明朝体・細字',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/kyosei_fv15.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '【プレミアム】矯正歯科｜明朝体・細字',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/kyosei_fv15.webp',
                'code_url' => "$page_template_url/fv_only/kyosei_fv15.php",
                'designer' => '',
                'message' => '同じ fv-15。明朝＋太さ300にすると、同じ骨組みでも医療系らしい静けさが出る。　※このサンプルはプレミアムブロックを使っています。無料プランのままだとフロントに表示されません。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '【プレミアム】コーヒー焙煎所｜ボタンを出さない',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/roast_fv15.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '【プレミアム】コーヒー焙煎所｜ボタンを出さない',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/roast_fv15.webp',
                'code_url' => "$page_template_url/fv_only/roast_fv15.php",
                'designer' => '',
                'message' => '同じ fv-15。showButton をオフにすると見出しと一文だけになる。通販ページへ誘導しない実店舗向け。　※このサンプルはプレミアムブロックを使っています。無料プランのままだとフロントに表示されません。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '【プレミアム】引越し｜袋文字＋角のないボタン',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/hikkoshi_fv15.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '【プレミアム】引越し｜袋文字＋角のないボタン',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/hikkoshi_fv15.webp',
                'code_url' => "$page_template_url/fv_only/hikkoshi_fv15.php",
                'designer' => '',
                'message' => '同じ fv-15。袋文字にしてボタンの角丸をゼロにすると、価格訴求向けの強い面になる。　※このサンプルはプレミアムブロックを使っています。無料プランのままだとフロントに表示されません。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '【プレミアム】板金塗装｜内側の帯を白にして黒文字',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/bankin_fv16.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '【プレミアム】板金塗装｜内側の帯を白にして黒文字',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/bankin_fv16.webp',
                'code_url' => "$page_template_url/fv_only/bankin_fv16.php",
                'designer' => '',
                'message' => '同じ fv-16。内側の帯を白（0.82）にして黒文字を乗せると、写真の上でも一番読みやすい形になる。　※このサンプルはプレミアムブロックを使っています。無料プランのままだとフロントに表示されません。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '【プレミアム】ヘッドスパ｜内側の帯を消して袋文字',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/headspa_fv16.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '【プレミアム】ヘッドスパ｜内側の帯を消して袋文字',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/headspa_fv16.webp',
                'code_url' => "$page_template_url/fv_only/headspa_fv16.php",
                'designer' => '',
                'message' => '同じ fv-16。帯の不透明度をゼロにすると枠が消え、写真がそのまま見える。文字は袋文字で抜いた。　※このサンプルはプレミアムブロックを使っています。無料プランのままだとフロントに表示されません。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '【プレミアム】ゴルフレッスン｜濃い帯＋明朝',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/golf_fv16.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '【プレミアム】ゴルフレッスン｜濃い帯＋明朝',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/golf_fv16.webp',
                'code_url' => "$page_template_url/fv_only/golf_fv16.php",
                'designer' => '',
                'message' => '同じ fv-16。帯を深緑（0.72）まで濃くして明朝を合わせると、写真が背景に退いて文字だけが立つ。　※このサンプルはプレミアムブロックを使っています。無料プランのままだとフロントに表示されません。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '【プレミアム】行政書士（下層）｜写真を敷いて濃くする',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/gyosei_fv17.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '【プレミアム】行政書士（下層）｜写真を敷いて濃くする',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/gyosei_fv17.webp',
                'code_url' => "$page_template_url/fv_only/gyosei_fv17.php",
                'designer' => '',
                'message' => '同じ fv-17。飾りを使わず、**帯の形の写真**を薄く敷いて濃い色をのぞかせる形。写真で雰囲気を出したいときはこちら。　※このサンプルはプレミアムブロックを使っています。無料プランのままだとフロントに表示されません。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '【プレミアム】社会保険労務士（下層）｜飾りを片側だけに',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/sharoushi_fv17.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '【プレミアム】社会保険労務士（下層）｜飾りを片側だけに',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/sharoushi_fv17.webp',
                'code_url' => "$page_template_url/fv_only/sharoushi_fv17.php",
                'designer' => '',
                'message' => '同じ fv-17。紙の質感の上に、飾りを**右だけ**に置いた形。左右そろえなくても成立するので、飾りが1枚しかないときに。　※このサンプルはプレミアムブロックを使っています。無料プランのままだとフロントに表示されません。',
            ],
        ],
        [
            'type' => 'item',
            'title' => '【プレミアム】内科クリニック（下層）｜落ち着いた色の飾りを両側に',
            'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/clinic_fv17.webp',
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => '【プレミアム】内科クリニック（下層）｜落ち着いた色の飾りを両側に',
                'paid' => false,
                'img' => 'https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/pv/clinic_fv17.webp',
                'code_url' => "$page_template_url/fv_only/clinic_fv17.php",
                'designer' => '',
                'message' => '同じ fv-17。飾りの絵柄を変えるだけで印象が変わる。seitai_fv17 が水彩の植物、こちらは落ち着いた幾何の飾り。　※このサンプルはプレミアムブロックを使っています。無料プランのままだとフロントに表示されません。',
            ],
        ],
        [   
            'type' => 'h2',
            'id' => 'page_template',
            'title' => 'ページテンプレート',
        ],
        [   
            'type' => 'item',
            'title' => 'トップページ用（製品紹介系）<br>パターン 01',
            'img' => "$page_template_url/top/ptn_1.webp",
            'img_size' => '',
            'class' => '',
            'item_detail' => [
                'title' => 'トップページ用<br>パターン 01',
                'paid' => false,
                'img' => "$page_template_url/top/ptn_1.webp",
                'code_url' => "$page_template_url/top/ptn_1.php",
                'designer' => '',
                'message' => '',
            ],
        ],
        [   
            'type' => 'item',
            'title' => 'トップページ用（カメラマン系）<br>パターン 02',
            'img' => "$page_template_url/top/ptn_2.webp",
            'img_size' => '',
            'class' => '',
            'item_detail' => [
                'title' => 'トップページ用<br>パターン 02',
                'paid' => false,
                'img' => "$page_template_url/top/ptn_2.webp",
                'code_url' => "$page_template_url/top/ptn_2.php",
                'designer' => '',
                'message' => '',
            ],
        ],
        [   
            'type' => 'item',
            'title' => 'トップページ用（エステ系）<br>パターン 04',
            'img' => "$page_template_url/top/ptn_4.webp",
            'img_size' => '',
            'class' => '',
            'item_detail' => [
                'title' => 'トップページ用<br>パターン 04',
                'paid' => false,
                'img' => "$page_template_url/top/ptn_4.webp",
                'code_url' => "$page_template_url/top/ptn_4.php",
                'designer' => '',
                'message' => '',
            ],
        ],

        [   
            'type' => 'item',
            'title' => '会社概要ページ用<br>パターン 01',
            'img' => "$page_template_url/company/ptn_1.webp",
            'img_size' => '',
            'class' => '',
            'item_detail' => [
                'title' => '会社概要ページ用<br>パターン 01',
                'paid' => false,
                'img' => "$page_template_url/company/ptn_1.webp",
                'code_url' => "$page_template_url/company/ptn_1.php",
                'designer' => '',
                'message' => '',
            ],
        ],
        [   
            'type' => 'item',
            'title' => 'プロフィールページ用<br>パターン 01',
            'img' => "$page_template_url/profile/ptn_1.webp",
            'img_size' => '',
            'class' => '',
            'item_detail' => [
                'title' => 'プロフィールページ用<br>パターン 01',
                'paid' => false,
                'img' => "$page_template_url/profile/ptn_1.webp",
                'code_url' => "$page_template_url/profile/ptn_1.php",
                'designer' => '',
                'message' => '',
            ],
        ],
        [   
            'type' => 'item',
            'title' => 'アクセスページ用<br>パターン 01',
            'img' => "$page_template_url/access/ptn_1.webp",
            'img_size' => '',
            'class' => '',
            'item_detail' => [
                'title' => 'アクセスページ用<br>パターン 01',
                'paid' => false,
                'img' => "$page_template_url/access/ptn_1.webp",
                'code_url' => "$page_template_url/access/ptn_1.php",
                'designer' => '',
                'message' => '',
            ],
        ],
        [   
            'type' => 'item',
            'title' => 'LPページ用<br>パターン 01',
            'img' => "$page_template_url/lp/ptn_1.webp",
            'img_size' => '',
            'class' => '',
            'item_detail' => [
                'title' => 'LPページ用<br>パターン 01',
                'paid' => false,
                'img' => "$page_template_url/lp/ptn_1.webp",
                'code_url' => "$page_template_url/lp/ptn_1.php",
                'designer' => '',
                'message' => '',
            ],
        ],
        // [   
        //     'type' => 'h2',
        //     'id' => 'page_template',
        //     'title' => 'フィットネスジム（有料ページテンプレート）',
        // ],
        // [   
        //     'type' => 'item',
        //     'title' => 'フィットネスジム用 01<br>トップページパターン',
        //     'img' => "$page_template_url/shin/fitness_01/top_pc.webp",
        //     'img_size' => 'large',
        //     'class' => '',
        //     'item_detail' => [
        //         'title' => 'フィットネスジム用 01<br>トップページパターン',
        //         'template_id' => 'shin_fitness_01_top',
        //         'paid' => true,
        //         'price' => '5,000',
        //         'shop_url' => $shop_url.'&template_url=shin_fitness_01_top',
        //         'img' => "$page_template_url/shin/fitness_01/top_pc.webp",
        //         'code_url' => "$page_template_url/profile/ptn_1.php",
        //         'designer' => 'shin',
        //         'message' => '',
        //         "block_used" => [
        //             "shin_fitness_01_fv",
        //             "shin_fitness_01_about",
        //             "shin_fitness_01_service",
        //             "shin_fitness_01_contact",
        //         ],
        //     ],
        // ],
    ];
    
    if (templateSettingCheck("shin_gas_station_01")) {
        $items[] = [   
            'type' => 'h2',
            'id' => 'page_template',
            'title' => 'ガスステーション 01',
        ];  
        $items[] = [   
            'type' => 'item',
            'title' => 'ガスステーション 01<br>トップページパターン',
            'img' => "$page_template_url/shin/gas_station_01/top_pc.webp",
            'img_size' => 'large',
            'class' => '',
            'item_detail' => [
                'title' => 'ガスステーション 01<br>トップページパターン',
                'template_id' => 'shin_gas_station_01',
                'paid' => true,
                'price' => '',
                'shop_url' => $shop_url.'&template_url=shin_gas_station_01',
                'img' => "$page_template_url/shin/gas_station_01/top_pc.webp",
                'code_url' => "$page_template_url/shin/gas_station_01/top.php",
                'designer' => '',
                'message' => '',
                "block_used" => [
                    "shin-gas-station-01-fv-top",
                    "shin-gas-station-01-fv-lower-01",
                    "shin-gas-station-01-custom-title-1",
                    "shin-gas-station-01-custom-title-2",
                    "shin-gas-station-01-news",
                    "shin-gas-station-01-list-1",
                    "shin-gas-station-01-list-2",
                    "shin-gas-station-01-list-3",
                    "shin-gas-station-01-list-4",
                    "shin-gas-station-01-step-1",
                    "shin-gas-station-01-post-list",
                    "shin-gas-station-01-cta",
                    "shin-gas-station-01-cta2",
                    "shin-gas-station-01-message-01",
                    "shin-gas-station-01-company-01",
                    "shin-gas-station-01-shop-list-1",
                    "shin-gas-station-01-contact",
                    "shin-gas-station-01-button-01",
                ],
            ],
        ];
        $items[] = [   
            'type' => 'item',
            'title' => 'ガスステーション 01<br>事業内容パターン',
            'img' => "$page_template_url/shin/gas_station_01/business_pc.webp",
            'img_size' => 'large',
            'class' => '',
            'item_detail' => [
                'title' => 'ガスステーション 01<br>事業内容パターン',
                'template_id' => 'shin_gas_station_01',
                'paid' => true,
                'price' => '',
                'shop_url' => $shop_url.'&template_url=shin_gas_station_01',
                'img' => "$page_template_url/shin/gas_station_01/business_pc.webp",
                'code_url' => "$page_template_url/shin/gas_station_01/business.php",
                'designer' => '',
                'message' => '',
                "block_used" => [],
            ],
        ];
        $items[] = [   
            'type' => 'item',
            'title' => 'ガスステーション 01<br>会社概要ページパターン',
            'img' => "$page_template_url/shin/gas_station_01/company_pc.webp",
            'img_size' => 'large',
            'class' => '',
            'item_detail' => [
                'title' => 'ガスステーション 01<br>会社概要ページパターン',
                'template_id' => 'shin_gas_station_01',
                'paid' => true,
                'price' => '',
                'shop_url' => $shop_url.'&template_url=shin_gas_station_01',
                'img' => "$page_template_url/shin/gas_station_01/company_pc.webp",
                'code_url' => "$page_template_url/shin/gas_station_01/company.php",
                'message' => '',
                "block_used" => [],
            ],
        ];
        $items[] = [   
            'type' => 'item',
            'title' => 'ガスステーション 01<br>店舗一覧ページパターン',
            'img' => "$page_template_url/shin/gas_station_01/shop_pc.webp",
            'img_size' => 'large',
            'class' => '',
            'item_detail' => [
                'title' => 'ガスステーション 01<br>店舗一覧ページパターン',
                'template_id' => 'shin_gas_station_01',
                'paid' => true,
                'price' => '',
                'shop_url' => $shop_url.'&template_url=shin_gas_station_01',
                'img' => "$page_template_url/shin/gas_station_01/shop_pc.webp",
                'code_url' => "$page_template_url/shin/gas_station_01/shop.php",
                'designer' => '',
                'message' => '',
                "block_used" => [],
            ],
        ];
        $items[] = [   
            'type' => 'item',
            'title' => 'ガスステーション 01<br>お問い合わせページパターン',
            'img' => "$page_template_url/shin/gas_station_01/contact_pc.webp",
            'img_size' => 'large',
            'class' => '',
            'item_detail' => [
                'title' => 'ガスステーション 01<br>お問い合わせページパターン',
                'template_id' => 'shin_gas_station_01',
                'paid' => true,
                'price' => '',
                'shop_url' => $shop_url.'&template_url=shin_gas_station_01',
                'img' => "$page_template_url/shin/gas_station_01/contact_pc.webp",
                'code_url' => "$page_template_url/shin/gas_station_01/contact.php",
                'designer' => '',
                'message' => '',
                "block_used" => [],
            ],
        ];
        $items[] = [   
            'type' => 'item',
            'title' => 'ガスステーション 01<br>サンクスページパターン',
            'img' => "$page_template_url/shin/gas_station_01/thanks_pc.webp",
            'img_size' => 'large',
            'class' => '',
            'item_detail' => [
                'title' => 'ガスステーション 01<br>サンクスページパターン',
                'template_id' => 'shin_gas_station_01',
                'paid' => true,
                'price' => '',
                'shop_url' => $shop_url.'&template_url=shin_gas_station_01',
                'img' => "$page_template_url/shin/gas_station_01/thanks_pc.webp",
                'code_url' => "$page_template_url/shin/gas_station_01/thanks.php",
                'designer' => '',
                'message' => '',
                "block_used" => [],
            ],
        ];
    }
   if (!templateSettingCheck("shin_gas_station_01")) {
    $items[] = [   
        'type' => 'h2',
        'id' => 'page_template',
        'title' => '行政書士用テンプレート （有料 6ページセット）',
    ];  
    $items[] = [   
        'type' => 'item',
        'title' => '行政書士用テンプレート 01<br>トップページパターン',
        'img' => "$page_template_url/shin/template_001/top.webp",
        'img_size' => 'large',
        'class' => '',
        'item_detail' => [
            'title' => '行政書士用テンプレート 01<br>トップページパターン',
            'template_id' => 'template_001',
            'paid' => true,
            'price' => '',
            'sample_site' => 'https://demo.lite-word.com/theme-001/',
            'shop_url' => $shop_url.'&template_url=template_001',
            'img' => "$page_template_url/shin/template_001/top.webp",
            'code_url' => "$page_template_url/shin/template_001/top.php",
            'designer' => '',
            'message' => '',
            "block_used" => [
                "shin-gas-station-01-fv-top",
                "shin-gas-station-01-fv-lower-01",
                "shin-gas-station-01-custom-title-1",
                "shin-gas-station-01-custom-title-2",
                "shin-gas-station-01-news",
                "shin-gas-station-01-list-1",
                "shin-gas-station-01-list-2",
                "shin-gas-station-01-list-3",
                "shin-gas-station-01-list-4",
                "shin-gas-station-01-step-1",
                "shin-gas-station-01-post-list",
                "shin-gas-station-01-cta",
                "shin-gas-station-01-cta2",
                "shin-gas-station-01-message-01",
                "shin-gas-station-01-company-01",
                "shin-gas-station-01-shop-list-1",
                "shin-gas-station-01-contact",
                "shin-gas-station-01-button-01",
            ],
        ],
    ];
    $items[] = [   
        'type' => 'item',
        'title' => '行政書士用テンプレート 01<br>事業内容パターン',
        'img' => "$page_template_url/shin/template_001/service.webp",
        'img_size' => 'large',
        'class' => '',
        'item_detail' => [
            'title' => '行政書士用テンプレート 01<br>事業内容パターン',
            'template_id' => 'template_001',
            'paid' => true,
            'price' => '',
            'sample_site' => 'https://demo.lite-word.com/theme-001/service/',
            'shop_url' => $shop_url.'&template_url=template_001',
            'img' => "$page_template_url/shin/template_001/service.webp",
            'code_url' => "$page_template_url/shin/template_001/service.php",
            'designer' => '',
            'message' => '',
            "block_used" => [],
        ],
    ];
    $items[] = [   
        'type' => 'item',
        'title' => '行政書士用テンプレート 01<br>会社概要ページパターン',
        'img' => "$page_template_url/shin/template_001/company.webp",
        'img_size' => 'large',
        'class' => '',
        'item_detail' => [
            'title' => '行政書士用テンプレート 01<br>会社概要ページパターン',
            'template_id' => 'template_001',
            'paid' => true,
            'price' => '',
            'sample_site' => 'https://demo.lite-word.com/theme-001/comany/',
            'shop_url' => $shop_url.'&template_url=template_001',
            'img' => "$page_template_url/shin/template_001/company.webp",
            'code_url' => "$page_template_url/shin/template_001/company.php",
            'message' => '',
            "block_used" => [],
        ],
    ];
        $items[] = [   
        'type' => 'item',
        'title' => '行政書士用テンプレート 01<br>採用情報ページパターン',
        'img' => "$page_template_url/shin/template_001/recruit.webp",
        'img_size' => 'large',
        'class' => '',
        'item_detail' => [
            'title' => '行政書士用テンプレート 01<br>採用情報ページパターン',
            'template_id' => 'template_001',
            'paid' => true,
            'price' => '',
            'sample_site' => 'https://demo.lite-word.com/theme-001/recruit/',
            'shop_url' => $shop_url.'&template_url=template_001',
            'img' => "$page_template_url/shin/template_001/recruit.webp",
            'code_url' => "$page_template_url/shin/template_001/recruit.php",
            'message' => '',
            "block_used" => [],
        ],
    ];
    $items[] = [   
        'type' => 'item',
        'title' => '行政書士用テンプレート 01<br>お問い合わせページパターン',
        'img' => "$page_template_url/shin/template_001/contact.webp",
        'img_size' => 'large',
        'class' => '',
        'item_detail' => [
            'title' => '行政書士用テンプレート 01<br>お問い合わせページパターン',
            'template_id' => 'template_001',
            'paid' => true,
            'price' => '',
            'sample_site' => 'https://demo.lite-word.com/theme-001/contact/',
            'shop_url' => $shop_url.'&template_url=template_001',
            'img' => "$page_template_url/shin/template_001/contact.webp",
            'code_url' => "$page_template_url/shin/template_001/contact.php",
            'designer' => '',
            'message' => '',
            "block_used" => [],
        ],
    ];
    $items[] = [   
        'type' => 'item',
        'title' => '行政書士用テンプレート 01<br>サンクスページパターン',
        'img' => "$page_template_url/shin/template_001/thanks.webp",
        'img_size' => 'large',
        'class' => '',
        'item_detail' => [
            'title' => '行政書士用テンプレート 01<br>サンクスページパターン',
            'template_id' => 'template_001',
            'paid' => true,
            'price' => '',
            'sample_site' => 'https://demo.lite-word.com/theme-001/thanks/',
            'shop_url' => $shop_url.'&template_url=template_001',
            'img' => "$page_template_url/shin/template_001/thanks.webp",
            'code_url' => "$page_template_url/shin/template_001/thanks.php",
            'designer' => '',
            'message' => '',
            "block_used" => [],
        ],
    ];
}
    if (templateSettingCheck("kaoru_lp_01")) {
        $items[] = [   
            'type' => 'h2',
            'id' => 'page_template',
            'title' => 'カオルさん限定 LP',
        ];  
        $items[] = [   
            'type' => 'item',
            'title' => 'タカラリサイクルLP',
            'img' => "$page_template_url/kaoru/lp_1/img.webp",
            'img_size' => 'large',
            'class' => '',
            'item_detail' => [
                'title' => 'タカラリサイクルLP',
                'template_id' => 'kaoru_lp_01',
                'paid' => true,
                'price' => '',
                'shop_url' => $shop_url.'&template_url=kaoru_lp_01',
                'img' => "$page_template_url/kaoru/lp_1/img.webp",
                'code_url' => "$page_template_url/kaoru/lp_1/index.php",
                'designer' => '',
                'message' => '',
                "block_used" => [
                    "paid-block-fv-8",
                    "paid-block-solution-2",
                    "paid-block-cta-3",
                ],
            ],
        ];
        $items[] = [   
            'type' => 'item',
            'title' => 'タカラリサイクルLP<br>(CTAをブロック形式にしたもの)',
            'img' => "$page_template_url/kaoru/lp_1/img.webp",
            'img_size' => 'large',
            'class' => '',
            'item_detail' => [
                'title' => 'タカラリサイクルLP<br>(CTAをブロック形式にしたもの)',
                'template_id' => 'kaoru_lp_01',
                'paid' => true,
                'price' => '',
                'shop_url' => $shop_url.'&template_url=kaoru_lp_01',
                'img' => "$page_template_url/kaoru/lp_1/img.webp",
                'code_url' => "$page_template_url/kaoru/lp_1/ptn_2.php",
                'designer' => '',
                'message' => '',
                "block_used" => [
                ],
            ],
        ];
    }
    return $items;
}


