<?php
if ( !defined( 'ABSPATH' ) ) exit;
function LwTemplateItems($page_template_url="",$shop_url=""){
    $items = [
        [
            'type' => 'item',
            'title' => '白紙',
            'img' => "$page_template_url/blank.webp",
            'img_size' => '',
            'class' => 'CloseLwTemplatePopup',
        ],
        [   
            'type' => 'h2',
            'id' => 'title_only',
            'title' => 'ページタイトルのみ',
        ],
        [   
            'type' => 'item',
            'title' => 'ページタイトル 01<br>トップページ用',
            'img' => "$page_template_url/fv_only/ptn_1.webp",
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => 'ページタイトル 01<br>トップページ用',
                'paid' => false,
                'img' => "$page_template_url/fv_only/ptn_1.webp",
                'code_url' => "$page_template_url/fv_only/ptn_1.php",
                'designer' => '',
                'message' => '',
            ],
        ],
        [   
            'type' => 'item',
            'title' => 'ページタイトル 02<br>下層ページ用',
            'img' => "$page_template_url/fv_only/ptn_2.webp",
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => 'ページタイトル 02<br>下層ページ用',
                'paid' => false,
                'img' => "$page_template_url/fv_only/ptn_2.webp",
                'code_url' => "$page_template_url/fv_only/ptn_2.php",
                'designer' => '',
                'message' => '',
            ],
        ],
        [   
            'type' => 'item',
            'title' => 'ページタイトル 03<br>画像を設置する場合',
            'img' => "$page_template_url/fv_only/ptn_3.webp",
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => 'ページタイトル 03<br>画像を設置する場合',
                'paid' => false,
                'img' => "$page_template_url/fv_only/ptn_3.webp",
                'code_url' => "$page_template_url/fv_only/ptn_3.php",
                'designer' => '',
                'message' => '',
            ],
        ],
        [   
            'type' => 'item',
            'title' => 'ページタイトル 04<br>トップページ用',
            'img' => "$page_template_url/fv_only/ptn_4.webp",
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => 'ページタイトル 04<br>トップページ用',
                'paid' => false,
                'img' => "$page_template_url/fv_only/ptn_4.webp",
                'code_url' => "$page_template_url/fv_only/ptn_4.php",
                'designer' => '',
                'message' => '',
            ],
        ],
        [   
            'type' => 'item',
            'title' => 'ページタイトル 05<br>下層ページ用',
            'img' => "$page_template_url/fv_only/ptn_5.webp",
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => 'ページタイトル 05<br>下層ページ用',
                'paid' => false,
                'img' => "$page_template_url/fv_only/ptn_5.webp",
                'code_url' => "$page_template_url/fv_only/ptn_5.php",
                'designer' => '',
                'message' => '',
            ],
        ],
        [   
            'type' => 'item',
            'title' => 'ページタイトル 06<br>下層ページ用',
            'img' => "$page_template_url/fv_only/ptn_6.webp",
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => 'ページタイトル 06<br>下層ページ用',
                'paid' => false,
                'img' => "$page_template_url/fv_only/ptn_6.webp",
                'code_url' => "$page_template_url/fv_only/ptn_6.php",
                'designer' => '',
                'message' => '',
            ],
        ],
        [   
            'type' => 'item',
            'title' => 'ページタイトル 07<br>トップページ用（動画背景）',
            'img' => "$page_template_url/fv_only/ptn_7.webp",
            'img_size' => 'small',
            'class' => '',
            'item_detail' => [
                'title' => 'ページタイトル 07<br>トップページ用（動画背景）',
                'paid' => false,
                'img' => "$page_template_url/fv_only/ptn_7.webp",
                'code_url' => "$page_template_url/fv_only/ptn_7.php",
                'designer' => '',
                'message' => '',
            ],
        ],
        [   
            'type' => 'h2',
            'id' => 'page_template',
            'title' => 'ページテンプレート',
        ],
        [   
            'type' => 'item',
            'title' => 'トップページ用（製品紹介系）<br>パターン 01',
            'img' => "$page_template_url/top/ptn_1.webp",
            'img_size' => '',
            'class' => '',
            'item_detail' => [
                'title' => 'トップページ用<br>パターン 01',
                'paid' => false,
                'img' => "$page_template_url/top/ptn_1.webp",
                'code_url' => "$page_template_url/top/ptn_1.php",
                'designer' => '',
                'message' => '',
            ],
        ],
        [   
            'type' => 'item',
            'title' => 'トップページ用（カメラマン系）<br>パターン 02',
            'img' => "$page_template_url/top/ptn_2.webp",
            'img_size' => '',
            'class' => '',
            'item_detail' => [
                'title' => 'トップページ用<br>パターン 02',
                'paid' => false,
                'img' => "$page_template_url/top/ptn_2.webp",
                'code_url' => "$page_template_url/top/ptn_2.php",
                'designer' => '',
                'message' => '',
            ],
        ],
        [   
            'type' => 'item',
            'title' => 'トップページ用（エステ系）<br>パターン 04',
            'img' => "$page_template_url/top/ptn_4.webp",
            'img_size' => '',
            'class' => '',
            'item_detail' => [
                'title' => 'トップページ用<br>パターン 04',
                'paid' => false,
                'img' => "$page_template_url/top/ptn_4.webp",
                'code_url' => "$page_template_url/top/ptn_4.php",
                'designer' => '',
                'message' => '',
            ],
        ],

        [   
            'type' => 'item',
            'title' => '会社概要ページ用<br>パターン 01',
            'img' => "$page_template_url/company/ptn_1.webp",
            'img_size' => '',
            'class' => '',
            'item_detail' => [
                'title' => '会社概要ページ用<br>パターン 01',
                'paid' => false,
                'img' => "$page_template_url/company/ptn_1.webp",
                'code_url' => "$page_template_url/company/ptn_1.php",
                'designer' => '',
                'message' => '',
            ],
        ],
        [   
            'type' => 'item',
            'title' => 'プロフィールページ用<br>パターン 01',
            'img' => "$page_template_url/profile/ptn_1.webp",
            'img_size' => '',
            'class' => '',
            'item_detail' => [
                'title' => 'プロフィールページ用<br>パターン 01',
                'paid' => false,
                'img' => "$page_template_url/profile/ptn_1.webp",
                'code_url' => "$page_template_url/profile/ptn_1.php",
                'designer' => '',
                'message' => '',
            ],
        ],
        [   
            'type' => 'item',
            'title' => 'アクセスページ用<br>パターン 01',
            'img' => "$page_template_url/access/ptn_1.webp",
            'img_size' => '',
            'class' => '',
            'item_detail' => [
                'title' => 'アクセスページ用<br>パターン 01',
                'paid' => false,
                'img' => "$page_template_url/access/ptn_1.webp",
                'code_url' => "$page_template_url/access/ptn_1.php",
                'designer' => '',
                'message' => '',
            ],
        ],
        [   
            'type' => 'item',
            'title' => 'LPページ用<br>パターン 01',
            'img' => "$page_template_url/lp/ptn_1.webp",
            'img_size' => '',
            'class' => '',
            'item_detail' => [
                'title' => 'LPページ用<br>パターン 01',
                'paid' => false,
                'img' => "$page_template_url/lp/ptn_1.webp",
                'code_url' => "$page_template_url/lp/ptn_1.php",
                'designer' => '',
                'message' => '',
            ],
        ],
        // [   
        //     'type' => 'h2',
        //     'id' => 'page_template',
        //     'title' => 'フィットネスジム（有料ページテンプレート）',
        // ],
        // [   
        //     'type' => 'item',
        //     'title' => 'フィットネスジム用 01<br>トップページパターン',
        //     'img' => "$page_template_url/shin/fitness_01/top_pc.webp",
        //     'img_size' => 'large',
        //     'class' => '',
        //     'item_detail' => [
        //         'title' => 'フィットネスジム用 01<br>トップページパターン',
        //         'template_id' => 'shin_fitness_01_top',
        //         'paid' => true,
        //         'price' => '5,000',
        //         'shop_url' => $shop_url.'&template_url=shin_fitness_01_top',
        //         'img' => "$page_template_url/shin/fitness_01/top_pc.webp",
        //         'code_url' => "$page_template_url/profile/ptn_1.php",
        //         'designer' => 'shin',
        //         'message' => '',
        //         "block_used" => [
        //             "shin_fitness_01_fv",
        //             "shin_fitness_01_about",
        //             "shin_fitness_01_service",
        //             "shin_fitness_01_contact",
        //         ],
        //     ],
        // ],
    ];
    
    if (templateSettingCheck("shin_gas_station_01")) {
        $items[] = [   
            'type' => 'h2',
            'id' => 'page_template',
            'title' => 'ガスステーション 01',
        ];  
        $items[] = [   
            'type' => 'item',
            'title' => 'ガスステーション 01<br>トップページパターン',
            'img' => "$page_template_url/shin/gas_station_01/top_pc.webp",
            'img_size' => 'large',
            'class' => '',
            'item_detail' => [
                'title' => 'ガスステーション 01<br>トップページパターン',
                'template_id' => 'shin_gas_station_01',
                'paid' => true,
                'price' => '',
                'shop_url' => $shop_url.'&template_url=shin_gas_station_01',
                'img' => "$page_template_url/shin/gas_station_01/top_pc.webp",
                'code_url' => "$page_template_url/shin/gas_station_01/top.php",
                'designer' => '',
                'message' => '',
                "block_used" => [
                    "shin-gas-station-01-fv-top",
                    "shin-gas-station-01-fv-lower-01",
                    "shin-gas-station-01-custom-title-1",
                    "shin-gas-station-01-custom-title-2",
                    "shin-gas-station-01-news",
                    "shin-gas-station-01-list-1",
                    "shin-gas-station-01-list-2",
                    "shin-gas-station-01-list-3",
                    "shin-gas-station-01-list-4",
                    "shin-gas-station-01-step-1",
                    "shin-gas-station-01-post-list",
                    "shin-gas-station-01-cta",
                    "shin-gas-station-01-cta2",
                    "shin-gas-station-01-message-01",
                    "shin-gas-station-01-company-01",
                    "shin-gas-station-01-shop-list-1",
                    "shin-gas-station-01-contact",
                    "shin-gas-station-01-button-01",
                ],
            ],
        ];
        $items[] = [   
            'type' => 'item',
            'title' => 'ガスステーション 01<br>事業内容パターン',
            'img' => "$page_template_url/shin/gas_station_01/business_pc.webp",
            'img_size' => 'large',
            'class' => '',
            'item_detail' => [
                'title' => 'ガスステーション 01<br>事業内容パターン',
                'template_id' => 'shin_gas_station_01',
                'paid' => true,
                'price' => '',
                'shop_url' => $shop_url.'&template_url=shin_gas_station_01',
                'img' => "$page_template_url/shin/gas_station_01/business_pc.webp",
                'code_url' => "$page_template_url/shin/gas_station_01/business.php",
                'designer' => '',
                'message' => '',
                "block_used" => [],
            ],
        ];
        $items[] = [   
            'type' => 'item',
            'title' => 'ガスステーション 01<br>会社概要ページパターン',
            'img' => "$page_template_url/shin/gas_station_01/company_pc.webp",
            'img_size' => 'large',
            'class' => '',
            'item_detail' => [
                'title' => 'ガスステーション 01<br>会社概要ページパターン',
                'template_id' => 'shin_gas_station_01',
                'paid' => true,
                'price' => '',
                'shop_url' => $shop_url.'&template_url=shin_gas_station_01',
                'img' => "$page_template_url/shin/gas_station_01/company_pc.webp",
                'code_url' => "$page_template_url/shin/gas_station_01/company.php",
                'message' => '',
                "block_used" => [],
            ],
        ];
        $items[] = [   
            'type' => 'item',
            'title' => 'ガスステーション 01<br>店舗一覧ページパターン',
            'img' => "$page_template_url/shin/gas_station_01/shop_pc.webp",
            'img_size' => 'large',
            'class' => '',
            'item_detail' => [
                'title' => 'ガスステーション 01<br>店舗一覧ページパターン',
                'template_id' => 'shin_gas_station_01',
                'paid' => true,
                'price' => '',
                'shop_url' => $shop_url.'&template_url=shin_gas_station_01',
                'img' => "$page_template_url/shin/gas_station_01/shop_pc.webp",
                'code_url' => "$page_template_url/shin/gas_station_01/shop.php",
                'designer' => '',
                'message' => '',
                "block_used" => [],
            ],
        ];
        $items[] = [   
            'type' => 'item',
            'title' => 'ガスステーション 01<br>お問い合わせページパターン',
            'img' => "$page_template_url/shin/gas_station_01/contact_pc.webp",
            'img_size' => 'large',
            'class' => '',
            'item_detail' => [
                'title' => 'ガスステーション 01<br>お問い合わせページパターン',
                'template_id' => 'shin_gas_station_01',
                'paid' => true,
                'price' => '',
                'shop_url' => $shop_url.'&template_url=shin_gas_station_01',
                'img' => "$page_template_url/shin/gas_station_01/contact_pc.webp",
                'code_url' => "$page_template_url/shin/gas_station_01/contact.php",
                'designer' => '',
                'message' => '',
                "block_used" => [],
            ],
        ];
        $items[] = [   
            'type' => 'item',
            'title' => 'ガスステーション 01<br>サンクスページパターン',
            'img' => "$page_template_url/shin/gas_station_01/thanks_pc.webp",
            'img_size' => 'large',
            'class' => '',
            'item_detail' => [
                'title' => 'ガスステーション 01<br>サンクスページパターン',
                'template_id' => 'shin_gas_station_01',
                'paid' => true,
                'price' => '',
                'shop_url' => $shop_url.'&template_url=shin_gas_station_01',
                'img' => "$page_template_url/shin/gas_station_01/thanks_pc.webp",
                'code_url' => "$page_template_url/shin/gas_station_01/thanks.php",
                'designer' => '',
                'message' => '',
                "block_used" => [],
            ],
        ];
    }
   if (!templateSettingCheck("shin_gas_station_01")) {
    $items[] = [   
        'type' => 'h2',
        'id' => 'page_template',
        'title' => '行政書士用テンプレート （有料 6ページセット）',
    ];  
    $items[] = [   
        'type' => 'item',
        'title' => '行政書士用テンプレート 01<br>トップページパターン',
        'img' => "$page_template_url/shin/template_001/top.webp",
        'img_size' => 'large',
        'class' => '',
        'item_detail' => [
            'title' => '行政書士用テンプレート 01<br>トップページパターン',
            'template_id' => 'template_001',
            'paid' => true,
            'price' => '',
            'sample_site' => 'https://demo.lite-word.com/theme-001/',
            'shop_url' => $shop_url.'&template_url=template_001',
            'img' => "$page_template_url/shin/template_001/top.webp",
            'code_url' => "$page_template_url/shin/template_001/top.php",
            'designer' => '',
            'message' => '',
            "block_used" => [
                "shin-gas-station-01-fv-top",
                "shin-gas-station-01-fv-lower-01",
                "shin-gas-station-01-custom-title-1",
                "shin-gas-station-01-custom-title-2",
                "shin-gas-station-01-news",
                "shin-gas-station-01-list-1",
                "shin-gas-station-01-list-2",
                "shin-gas-station-01-list-3",
                "shin-gas-station-01-list-4",
                "shin-gas-station-01-step-1",
                "shin-gas-station-01-post-list",
                "shin-gas-station-01-cta",
                "shin-gas-station-01-cta2",
                "shin-gas-station-01-message-01",
                "shin-gas-station-01-company-01",
                "shin-gas-station-01-shop-list-1",
                "shin-gas-station-01-contact",
                "shin-gas-station-01-button-01",
            ],
        ],
    ];
    $items[] = [   
        'type' => 'item',
        'title' => '行政書士用テンプレート 01<br>事業内容パターン',
        'img' => "$page_template_url/shin/template_001/service.webp",
        'img_size' => 'large',
        'class' => '',
        'item_detail' => [
            'title' => '行政書士用テンプレート 01<br>事業内容パターン',
            'template_id' => 'template_001',
            'paid' => true,
            'price' => '',
            'sample_site' => 'https://demo.lite-word.com/theme-001/service/',
            'shop_url' => $shop_url.'&template_url=template_001',
            'img' => "$page_template_url/shin/template_001/service.webp",
            'code_url' => "$page_template_url/shin/template_001/service.php",
            'designer' => '',
            'message' => '',
            "block_used" => [],
        ],
    ];
    $items[] = [   
        'type' => 'item',
        'title' => '行政書士用テンプレート 01<br>会社概要ページパターン',
        'img' => "$page_template_url/shin/template_001/company.webp",
        'img_size' => 'large',
        'class' => '',
        'item_detail' => [
            'title' => '行政書士用テンプレート 01<br>会社概要ページパターン',
            'template_id' => 'template_001',
            'paid' => true,
            'price' => '',
            'sample_site' => 'https://demo.lite-word.com/theme-001/comany/',
            'shop_url' => $shop_url.'&template_url=template_001',
            'img' => "$page_template_url/shin/template_001/company.webp",
            'code_url' => "$page_template_url/shin/template_001/company.php",
            'message' => '',
            "block_used" => [],
        ],
    ];
        $items[] = [   
        'type' => 'item',
        'title' => '行政書士用テンプレート 01<br>採用情報ページパターン',
        'img' => "$page_template_url/shin/template_001/recruit.webp",
        'img_size' => 'large',
        'class' => '',
        'item_detail' => [
            'title' => '行政書士用テンプレート 01<br>採用情報ページパターン',
            'template_id' => 'template_001',
            'paid' => true,
            'price' => '',
            'sample_site' => 'https://demo.lite-word.com/theme-001/recruit/',
            'shop_url' => $shop_url.'&template_url=template_001',
            'img' => "$page_template_url/shin/template_001/recruit.webp",
            'code_url' => "$page_template_url/shin/template_001/recruit.php",
            'message' => '',
            "block_used" => [],
        ],
    ];
    $items[] = [   
        'type' => 'item',
        'title' => '行政書士用テンプレート 01<br>お問い合わせページパターン',
        'img' => "$page_template_url/shin/template_001/contact.webp",
        'img_size' => 'large',
        'class' => '',
        'item_detail' => [
            'title' => '行政書士用テンプレート 01<br>お問い合わせページパターン',
            'template_id' => 'template_001',
            'paid' => true,
            'price' => '',
            'sample_site' => 'https://demo.lite-word.com/theme-001/contact/',
            'shop_url' => $shop_url.'&template_url=template_001',
            'img' => "$page_template_url/shin/template_001/contact.webp",
            'code_url' => "$page_template_url/shin/template_001/contact.php",
            'designer' => '',
            'message' => '',
            "block_used" => [],
        ],
    ];
    $items[] = [   
        'type' => 'item',
        'title' => '行政書士用テンプレート 01<br>サンクスページパターン',
        'img' => "$page_template_url/shin/template_001/thanks.webp",
        'img_size' => 'large',
        'class' => '',
        'item_detail' => [
            'title' => '行政書士用テンプレート 01<br>サンクスページパターン',
            'template_id' => 'template_001',
            'paid' => true,
            'price' => '',
            'sample_site' => 'https://demo.lite-word.com/theme-001/thanks/',
            'shop_url' => $shop_url.'&template_url=template_001',
            'img' => "$page_template_url/shin/template_001/thanks.webp",
            'code_url' => "$page_template_url/shin/template_001/thanks.php",
            'designer' => '',
            'message' => '',
            "block_used" => [],
        ],
    ];
}
    if (templateSettingCheck("kaoru_lp_01")) {
        $items[] = [   
            'type' => 'h2',
            'id' => 'page_template',
            'title' => 'カオルさん限定 LP',
        ];  
        $items[] = [   
            'type' => 'item',
            'title' => 'タカラリサイクルLP',
            'img' => "$page_template_url/kaoru/lp_1/img.webp",
            'img_size' => 'large',
            'class' => '',
            'item_detail' => [
                'title' => 'タカラリサイクルLP',
                'template_id' => 'kaoru_lp_01',
                'paid' => true,
                'price' => '',
                'shop_url' => $shop_url.'&template_url=kaoru_lp_01',
                'img' => "$page_template_url/kaoru/lp_1/img.webp",
                'code_url' => "$page_template_url/kaoru/lp_1/index.php",
                'designer' => '',
                'message' => '',
                "block_used" => [
                    "paid-block-fv-8",
                    "paid-block-solution-2",
                    "paid-block-cta-3",
                ],
            ],
        ];
        $items[] = [   
            'type' => 'item',
            'title' => 'タカラリサイクルLP<br>(CTAをブロック形式にしたもの)',
            'img' => "$page_template_url/kaoru/lp_1/img.webp",
            'img_size' => 'large',
            'class' => '',
            'item_detail' => [
                'title' => 'タカラリサイクルLP<br>(CTAをブロック形式にしたもの)',
                'template_id' => 'kaoru_lp_01',
                'paid' => true,
                'price' => '',
                'shop_url' => $shop_url.'&template_url=kaoru_lp_01',
                'img' => "$page_template_url/kaoru/lp_1/img.webp",
                'code_url' => "$page_template_url/kaoru/lp_1/ptn_2.php",
                'designer' => '',
                'message' => '',
                "block_used" => [
                ],
            ],
        ];
    }
    return $items;
}


