<!-- wp:wdl/fv-2 {"title":"A社を3か月使ってみた","headingLevel":1,"backgroundImage":"","backgroundImageSp":"","filterBackgroundColor":"#16305c","filterOpacity":1,"textColor":"#ffffff","h1AfterColor":"#c1440e","minHeightPc":"min-h-pc-320px","minHeightTb":"min-h-tb-280px","minHeightSp":"min-h-sp-220px"} -->
<div class="wp-block-wdl-fv-2 fv-2 min-h-pc-320px min-h-tb-280px min-h-sp-220px"><h1 class="ttl" style="color:#ffffff">A社を3か月使ってみた</h1><div class="filter" style="background-color:#16305c;opacity:1"></div><style>
                        .fv-2 h1:after {
                            background: #c1440e;
                        }
                    </style></div>
<!-- /wp:wdl/fv-2 -->
<!-- wp:paragraph {"align":"center","style":{"color":{"background":"#eef2f7","text":"#1f2733"},"typography":{"fontSize":"14px"},"spacing":{"padding":{"top":"10px","bottom":"10px","left":"16px","right":"16px"}}}} -->
<p class="has-text-align-center has-text-color has-background" style="color:#1f2733;font-size:14px"><strong>PR</strong>　このサイトには広告（アフィリエイトリンク）が含まれます。</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"align":"center","style":{"color":{"text":"#1f2733"},"typography":{"fontSize":"15px","lineHeight":"2"},"spacing":{"margin":{"top":"24px","bottom":"8px"}}}} -->
<p class="has-text-align-center has-text-color" style="color:#1f2733;font-size:15px;line-height:2;margin-top:24px;margin-bottom:8px">自分の回線を1本まるごと A社に移して、3か月ぶん記録したページです。<br><strong>借りたものではなく、自分で契約して自分で払っています。</strong><br>速度は毎日の同じ時刻・同じ場所で測りました（東京23区・屋内）。<br>場所と時間帯で結果は変わるので、そのまま当てはまるとは限りません。<br>良かった点だけでなく、やめようかと思った点も書いています。</p>
<!-- /wp:paragraph -->
<!-- wp:wdl/lw-space-1 {"pcHeight":24,"tbHeight":20,"spHeight":16} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:24px"></div><div class="tb" style="height:20px"></div><div class="sp" style="height:16px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-pr-column-1 {"columnsPc":1,"columnWidthsPc":[1],"columnsSp":1,"wrapPaddingTopPc":0,"wrapPaddingBottomPc":0,"itemBgNone":false,"itemBgTypePc":"solid","itemBgColorPc":"#eef2f7","itemBgTypeSp":"solid","itemBgColorSp":"#eef2f7","itemBorderColorPc":"#c1440e","itemBorderWidthPc":1,"itemBorderStylePc":"solid","itemBorderColorSp":"#c1440e","itemBorderWidthSp":1,"itemBorderStyleSp":"solid","itemPaddingTopPc":24,"itemPaddingBottomPc":24,"itemPaddingLeftPc":28,"itemPaddingRightPc":28,"itemPaddingTopSp":18,"itemPaddingBottomSp":18,"itemPaddingLeftSp":16,"itemPaddingRightSp":16,"itemBorderRadiusTopLeftPc":6,"itemBorderRadiusTopRightPc":6,"itemBorderRadiusBottomRightPc":6,"itemBorderRadiusBottomLeftPc":6,"itemBorderRadiusTopLeftSp":6,"itemBorderRadiusTopRightSp":6,"itemBorderRadiusBottomRightSp":6,"itemBorderRadiusBottomLeftSp":6} -->
<div class="wp-block-wdl-lw-pr-column-1 lw-pr-column-1" style="--column-1-wrap-padding-pc:0px 0px 0px 0px;--column-1-wrap-padding-sp:0px 0px 0px 0px;--column-1-border-color-pc:rgb(131, 131, 131);--column-1-border-width-pc:0px;--column-1-border-style-pc:solid;--column-1-border-color-sp:rgb(131, 131, 131);--column-1-border-width-sp:0px;--column-1-border-style-sp:solid;--column-1-bdr-pc:0px 0px 0px 0px;--column-1-bdr-sp:0px 0px 0px 0px;--column-1-gtc-pc:1fr;--column-1-gtc-sp:1fr;--column-1-row-gap-pc:8px;--column-1-row-gap-sp:8px;--column-1-column-gap-pc:8px;--column-1-column-gap-sp:8px;--column-1-item-bg-pc:#eef2f7;--column-1-item-bg-sp:#eef2f7;--column-1-item-min-h-pc:0px;--column-1-item-min-h-sp:0px;--column-1-item-padding-pc:24px 28px 24px 28px;--column-1-item-padding-sp:18px 16px 18px 16px;--column-1-item-bdr-pc:6px 6px 6px 6px;--column-1-item-bdr-sp:6px 6px 6px 6px;--column-1-item-border-color-pc:#c1440e;--column-1-item-border-width-pc:1px;--column-1-item-border-style-pc:solid;--column-1-item-border-color-sp:#c1440e;--column-1-item-border-width-sp:1px;--column-1-item-border-style-sp:solid"><div class="custom_wrap"><!-- wp:paragraph {"style":{"color":{"text":"#1f2733"},"typography":{"fontSize":"16px","lineHeight":"1.9"},"spacing":{"margin":{"top":"0px","bottom":"0px"}}}} -->
<p class="has-text-color" style="color:#1f2733;font-size:16px;line-height:1.9;margin-top:0px;margin-bottom:0px"><strong>このページの数字は、1人が1か所で測った結果です。</strong><br>測った場所は東京23区の屋内1か所、期間は2026年6月〜8月の3か月、1日3回（8時・12時・19時）で計273回の平均です。<br>住んでいる場所・建物・時間帯が変われば結果は変わります。<strong>「この会社は速い」と言い切れるだけの数ではありません。</strong></p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:wdl/lw-pr-column-1 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":80,"tbHeight":64,"spHeight":40} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:80px"></div><div class="tb" style="height:64px"></div><div class="sp" style="height:40px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-pr-custom-title-13 {"mainTitle":"先に結論","subTitle":"CONCLUSION","headingLevel":2,"colorMain":"#16305c"} -->
<div class="wp-block-wdl-lw-pr-custom-title-13 lw-pr-custom-title-13" style="--color-main:#16305c" id="review"><h2 class="ttl"><span class="sub">CONCLUSION</span><span class="main">先に結論</span><div class="left"></div><div class="right"></div></h2></div>
<!-- /wp:wdl/lw-pr-custom-title-13 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":16,"tbHeight":16,"spHeight":12} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:16px"></div><div class="tb" style="height:16px"></div><div class="sp" style="height:12px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-pr-comment-2 {"comment2ImageUrl":"https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/sm_comment_1.webp","comment2ImageAlt":"スマートフォンを持つ手","comment2ImagePosition":"left","comment2ImageWidthPc":150,"comment2ImageWidthSp":64,"comment2ImageBdColorPc":"#16305c","comment2ImageBg":"#ffffff","comment2Text":"月7,800円が2,200円になりました。\u003cbr\u003eただし昼の12時台だけは、はっきり遅いです。","comment2TextColor":"#16305c","comment2TextBg":"#eef2f7","comment2TextFontsizePc":18,"comment2TextFontsizeSp":15,"comment2MaxWidth":880} -->
<div class="wp-block-wdl-lw-pr-comment-2 lw-pr-comment-2"><div class="lw-pr-comment-2__wrap" style="--comment-2-max-width:880px;--comment-2-image-width-pc:150px;--comment-2-image-width-sp:64px;--comment-2-image-bd-width-pc:2px;--comment-2-image-bd-width-sp:2px;--comment-2-image-bd-color-pc:#16305c;--comment-2-image-bd-color-sp:#16305c;--comment-2-image-bg:#ffffff;--comment-2-text-color:#16305c;--comment-2-text-bg:#eef2f7;--comment-2-text-mt-pc:24px;--comment-2-text-mt-sp:8px;--comment-2-text-fontsize-pc:18px;--comment-2-text-fontsize-sp:15px;--comment-2-text-bdr-pc:12px;--comment-2-text-bdr-sp:8px;--comment-2-triangle-top:20%"><div class="lw-pr-comment-2__image"><img src="https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/sm_comment_1.webp" alt="スマートフォンを持つ手"/></div><div class="lw-pr-comment-2__text"><p data-lw_font_set="">月7,800円が2,200円になりました。<br>ただし昼の12時台だけは、はっきり遅いです。</p></div></div></div>
<!-- /wp:wdl/lw-pr-comment-2 -->
<!-- wp:paragraph {"style":{"color":{"text":"#1f2733"},"typography":{"fontSize":"16px","lineHeight":"1.9"}}} -->
<p class="has-text-color" style="color:#1f2733;font-size:16px;line-height:1.9">3か月で下がった額は 5,600円 × 3 = <strong>16,800円</strong>でした。手続きにかかった時間は、明細の確認からSIMの差し替えまで合わせて1時間ほど。面倒だったのは <strong>MNP予約番号の期限（15日）を1度切らして取り直したこと</strong>だけです。昼に動画を見る習慣がある人には勧めません。それ以外の人には、戻す理由が見つかりませんでした。</p>
<!-- /wp:paragraph -->
<!-- wp:wdl/lw-space-1 {"pcHeight":80,"tbHeight":64,"spHeight":40} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:80px"></div><div class="tb" style="height:64px"></div><div class="sp" style="height:40px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-pr-custom-title-13 {"mainTitle":"良い点と気になる点","subTitle":"GOOD & BAD","headingLevel":2,"colorMain":"#16305c"} -->
<div class="wp-block-wdl-lw-pr-custom-title-13 lw-pr-custom-title-13" style="--color-main:#16305c"><h2 class="ttl"><span class="sub">GOOD & BAD</span><span class="main">良い点と気になる点</span><div class="left"></div><div class="right"></div></h2></div>
<!-- /wp:wdl/lw-pr-custom-title-13 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":16,"tbHeight":16,"spHeight":12} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:16px"></div><div class="tb" style="height:16px"></div><div class="sp" style="height:12px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:paragraph {"align":"center","style":{"spacing":{"margin":{"top":"28px","bottom":"24px"}}}} -->
<p class="has-text-align-center" style="margin-top:28px;margin-bottom:24px">3か月のあいだにメモしたものを、そのまま並べています。</p>
<!-- /wp:paragraph -->
<!-- wp:wdl/lw-pr-goodbad-1 {"goodTitle":"ここが良い","badTitle":"気になる点","goodItems":["月額が7,800円から2,200円になった（20GB・かけ放題なし）","朝と夜は前の会社と体感で差がなかった","解約金も最低利用期間も無く、いつでも抜けられる","申し込みから開通まで、店舗に行かずに3日で終わった","データの繰り越しがあり、使わなかった月のぶんが翌月に残る"],"badItems":["平日12時〜13時は、動画の画質が落ちるか止まる","問い合わせがチャットのみで、電話がつながらない","支払いがクレジットカードのみ（口座振替が選べない）","通話アプリを経由しないと、通話料が30秒22円かかる"],"goodMark":"○","badMark":"△","maxWidth":900,"fontSize":16,"fontSizeSp":15,"textColor":"#1f2733","borderRadius":8} -->
<div class="wp-block-wdl-lw-pr-goodbad-1 lw-pr-goodbad-1 is-side" style="margin-top:0px;margin-bottom:0px;--gb1-max-width:900px;--gb1-radius:8px;--gb1-border-w:1px;--gb1-size:16px;--gb1-size-sp:15px;--gb1-title-size:17px"><div class="lw-pr-goodbad-1__cols"><div class="lw-pr-goodbad-1__col is-good" style="background-color:#f2f8f4;border-color:#cfe4d6"><p class="lw-pr-goodbad-1__title" style="color:#1f7a4d" data-lw_font_set="">ここが良い</p><ul class="lw-pr-goodbad-1__list"><li><span class="lw-pr-goodbad-1__mark" style="color:#1f7a4d">○</span><span class="lw-pr-goodbad-1__text" style="color:#1f2733">月額が7,800円から2,200円になった（20GB・かけ放題なし）</span></li><li><span class="lw-pr-goodbad-1__mark" style="color:#1f7a4d">○</span><span class="lw-pr-goodbad-1__text" style="color:#1f2733">朝と夜は前の会社と体感で差がなかった</span></li><li><span class="lw-pr-goodbad-1__mark" style="color:#1f7a4d">○</span><span class="lw-pr-goodbad-1__text" style="color:#1f2733">解約金も最低利用期間も無く、いつでも抜けられる</span></li><li><span class="lw-pr-goodbad-1__mark" style="color:#1f7a4d">○</span><span class="lw-pr-goodbad-1__text" style="color:#1f2733">申し込みから開通まで、店舗に行かずに3日で終わった</span></li><li><span class="lw-pr-goodbad-1__mark" style="color:#1f7a4d">○</span><span class="lw-pr-goodbad-1__text" style="color:#1f2733">データの繰り越しがあり、使わなかった月のぶんが翌月に残る</span></li></ul></div><div class="lw-pr-goodbad-1__col is-bad" style="background-color:#fbf5f4;border-color:#e8d5d2"><p class="lw-pr-goodbad-1__title" style="color:#9c5a5a" data-lw_font_set="">気になる点</p><ul class="lw-pr-goodbad-1__list"><li><span class="lw-pr-goodbad-1__mark" style="color:#9c5a5a">△</span><span class="lw-pr-goodbad-1__text" style="color:#1f2733">平日12時〜13時は、動画の画質が落ちるか止まる</span></li><li><span class="lw-pr-goodbad-1__mark" style="color:#9c5a5a">△</span><span class="lw-pr-goodbad-1__text" style="color:#1f2733">問い合わせがチャットのみで、電話がつながらない</span></li><li><span class="lw-pr-goodbad-1__mark" style="color:#9c5a5a">△</span><span class="lw-pr-goodbad-1__text" style="color:#1f2733">支払いがクレジットカードのみ（口座振替が選べない）</span></li><li><span class="lw-pr-goodbad-1__mark" style="color:#9c5a5a">△</span><span class="lw-pr-goodbad-1__text" style="color:#1f2733">通話アプリを経由しないと、通話料が30秒22円かかる</span></li></ul></div></div></div>
<!-- /wp:wdl/lw-pr-goodbad-1 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":80,"tbHeight":64,"spHeight":40} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:80px"></div><div class="tb" style="height:64px"></div><div class="sp" style="height:40px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-pr-custom-title-13 {"mainTitle":"3か月の記録","subTitle":"LOG","headingLevel":2,"colorMain":"#16305c"} -->
<div class="wp-block-wdl-lw-pr-custom-title-13 lw-pr-custom-title-13" style="--color-main:#16305c"><h2 class="ttl"><span class="sub">LOG</span><span class="main">3か月の記録</span><div class="left"></div><div class="right"></div></h2></div>
<!-- /wp:wdl/lw-pr-custom-title-13 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":16,"tbHeight":16,"spHeight":12} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:16px"></div><div class="tb" style="height:16px"></div><div class="sp" style="height:12px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/paid-block-history-1 {"yearText":"2026年","yearTag":"h3","pointBorderColor":"#1668b0","colorDt":"#1668b0","colorDd":"#1f2733"} -->
<div class="wp-block-wdl-paid-block-history-1 paid-block-history-1"><div class="history__year" aria-labelledby="y2026"><div class="history__point" style="background:#ffffff;border-color:#1668b0"></div><h3 class="history__year-heading" data-lw_font_set="">2026年</h3><dl class="history__events"><div class="history__events_row"><dt class="history__dt"><time datetime="6" data-lw_font_set="" style="color:#1668b0">6月</time></dt><dd class="history__dd" data-lw_font_set="" style="color:#1f2733">乗り換え1か月目。請求は2,200円＋事務手数料3,300円で合計5,500円。開通した日の夜に速度を測ったら前の会社と変わらず、拍子抜けした。</dd></div><div class="history__events_row"><dt class="history__dt"><time datetime="7" data-lw_font_set="" style="color:#1668b0">7月</time></dt><dd class="history__dd" data-lw_font_set="" style="color:#1f2733">2か月目。請求は2,200円のみ。昼休みに動画を見ようとして止まり、初めて「これか」と分かった。テザリングでノートPCをつないでも追加料金はなかった。</dd></div><div class="history__events_row"><dt class="history__dt"><time datetime="8" data-lw_font_set="" style="color:#1668b0">8月</time></dt><dd class="history__dd" data-lw_font_set="" style="color:#1f2733">3か月目。請求は2,200円。前月に使い切らなかった4GBが繰り越されて24GB使えた。問い合わせをチャットで1回。返事は40分後だった。</dd></div></dl></div></div>
<!-- /wp:wdl/paid-block-history-1 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":80,"tbHeight":64,"spHeight":40} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:80px"></div><div class="tb" style="height:64px"></div><div class="sp" style="height:40px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-pr-custom-title-13 {"mainTitle":"測った数字","subTitle":"MEASURED","headingLevel":2,"colorMain":"#16305c"} -->
<div class="wp-block-wdl-lw-pr-custom-title-13 lw-pr-custom-title-13" style="--color-main:#16305c"><h2 class="ttl"><span class="sub">MEASURED</span><span class="main">測った数字</span><div class="left"></div><div class="right"></div></h2></div>
<!-- /wp:wdl/lw-pr-custom-title-13 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":16,"tbHeight":16,"spHeight":12} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:16px"></div><div class="tb" style="height:16px"></div><div class="sp" style="height:12px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:paragraph {"align":"center","style":{"spacing":{"margin":{"top":"28px","bottom":"24px"}}}} -->
<p class="has-text-align-center" style="margin-top:28px;margin-bottom:24px">2026年6月〜8月・東京23区の屋内1か所・1日3回・計273回の平均です。</p>
<!-- /wp:paragraph -->
<!-- wp:wdl/lw-pr-table-2 {"rows":[{"dtText":"朝8時台","ddText":"下り 42.1Mbps（動画も地図も普通に使えました）"},{"dtText":"昼12時台","ddText":"下り 1.8Mbps（動画は画質が落ちるか止まります）"},{"dtText":"夜19時台","ddText":"下り 28.6Mbps（動画は問題ありませんでした）"},{"dtText":"月額","ddText":"2,200円（20GB・かけ放題なし・税込）"},{"dtText":"初期費用","ddText":"3,300円（事務手数料・初月のみ）"},{"dtText":"3か月の合計","ddText":"9,900円（前の会社なら23,400円でした）"}],"dtFixedPc":true,"dtWidthPc":200,"defaultSpClm1":true,"dtBgColor":"#eef2f7","dtTextColor":"#16305c","ddTextColor":"#1f2733","dtFontWeight":"600","dlBorderColor":"#d8dfe8","rowBorderColor":"#d8dfe8","dtBorderColor":"#d8dfe8","fontSizePc":17,"fontSizeSp":16,"cellPaddingPc":18} -->
<div class="wp-block-wdl-lw-pr-table-2 lw-pr-table-2" style="--table-2-dl-width-pc:100%;--table-2-dl-width-sp:100%;--table-2-grid-columns-pc:200px calc(100% - 200px);--table-2-grid-columns-sp:1fr 1fr;--table-2-dl-border-color:#d8dfe8;--table-2-dl-border-style:solid;--table-2-dl-border-width:1px;--table-2-dl-border-individual:0;--table-2-dl-border-top-color:#d8dfe8;--table-2-dl-border-top-style:solid;--table-2-dl-border-top-width:1px;--table-2-dl-border-bottom-color:#d8dfe8;--table-2-dl-border-bottom-style:solid;--table-2-dl-border-bottom-width:1px;--table-2-dl-border-left-color:#d8dfe8;--table-2-dl-border-left-style:solid;--table-2-dl-border-left-width:1px;--table-2-dl-border-right-color:#d8dfe8;--table-2-dl-border-right-style:solid;--table-2-dl-border-right-width:1px;--table-2-row-border-color:#d8dfe8;--table-2-row-border-style:solid;--table-2-row-border-width:1px;--table-2-dt-border-color:#d8dfe8;--table-2-dt-border-style:solid;--table-2-dt-border-width:1px;--table-2-dt-bg-color:#eef2f7;--table-2-cell-padding-pc:18px;--table-2-cell-padding-sp:18px;--table-2-font-size-pc:17px;--table-2-font-size-sp:16px;--table-2-dt-align-pc:left;--table-2-dt-align-sp:left;--table-2-dd-align-pc:left;--table-2-dd-align-sp:left;--table-2-dt-text-color:#16305c;--table-2-dd-text-color:#1f2733"><dl class="table-2__dl"><div class="table-2__row"><dt class="table-2__dt"><p data-lw_font_set="" style="font-weight:600">朝8時台</p></dt><dd class="table-2__dd"><p data-lw_font_set="">下り 42.1Mbps（動画も地図も普通に使えました）</p></dd></div><div class="table-2__row"><dt class="table-2__dt"><p data-lw_font_set="" style="font-weight:600">昼12時台</p></dt><dd class="table-2__dd"><p data-lw_font_set="">下り 1.8Mbps（動画は画質が落ちるか止まります）</p></dd></div><div class="table-2__row"><dt class="table-2__dt"><p data-lw_font_set="" style="font-weight:600">夜19時台</p></dt><dd class="table-2__dd"><p data-lw_font_set="">下り 28.6Mbps（動画は問題ありませんでした）</p></dd></div><div class="table-2__row"><dt class="table-2__dt"><p data-lw_font_set="" style="font-weight:600">月額</p></dt><dd class="table-2__dd"><p data-lw_font_set="">2,200円（20GB・かけ放題なし・税込）</p></dd></div><div class="table-2__row"><dt class="table-2__dt"><p data-lw_font_set="" style="font-weight:600">初期費用</p></dt><dd class="table-2__dd"><p data-lw_font_set="">3,300円（事務手数料・初月のみ）</p></dd></div><div class="table-2__row"><dt class="table-2__dt"><p data-lw_font_set="" style="font-weight:600">3か月の合計</p></dt><dd class="table-2__dd"><p data-lw_font_set="">9,900円（前の会社なら23,400円でした）</p></dd></div></dl></div>
<!-- /wp:wdl/lw-pr-table-2 -->
<!-- wp:paragraph {"align":"center","style":{"spacing":{"margin":{"top":"24px"}}}} -->
<p class="has-text-align-center" style="margin-top:24px">速度は測る場所・時間・端末で変わります。この数字は「うちの場合はこうだった」というだけの記録です。</p>
<!-- /wp:paragraph -->
<!-- wp:wdl/lw-space-1 {"pcHeight":80,"tbHeight":64,"spHeight":40} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:80px"></div><div class="tb" style="height:64px"></div><div class="sp" style="height:40px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-pr-custom-title-13 {"mainTitle":"向いていない人・向いている人","subTitle":"FOR WHOM","headingLevel":2,"colorMain":"#16305c"} -->
<div class="wp-block-wdl-lw-pr-custom-title-13 lw-pr-custom-title-13" style="--color-main:#16305c"><h2 class="ttl"><span class="sub">FOR WHOM</span><span class="main">向いていない人・向いている人</span><div class="left"></div><div class="right"></div></h2></div>
<!-- /wp:wdl/lw-pr-custom-title-13 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":16,"tbHeight":16,"spHeight":12} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:16px"></div><div class="tb" style="height:16px"></div><div class="sp" style="height:12px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:paragraph {"align":"center","style":{"spacing":{"margin":{"top":"28px","bottom":"24px"}}}} -->
<p class="has-text-align-center" style="margin-top:28px;margin-bottom:24px">先に「向いていない人」から書きます。当てはまる人は、たぶん戻したくなります。</p>
<!-- /wp:paragraph -->
<!-- wp:wdl/lw-pr-column-1 {"columnsPc":2,"columnWidthsPc":[1,1],"columnsSp":1,"rowGapPc":20,"columnGapPc":20,"rowGapSp":16,"itemBgNone":false,"itemBgTypePc":"solid","itemBgColorPc":"#eef2f7","itemBgTypeSp":"solid","itemBgColorSp":"#eef2f7","itemPaddingTopPc":26,"itemPaddingBottomPc":26,"itemPaddingLeftPc":26,"itemPaddingRightPc":26,"itemPaddingTopSp":20,"itemPaddingBottomSp":20,"itemPaddingLeftSp":18,"itemPaddingRightSp":18,"itemBorderRadiusTopLeftPc":8,"itemBorderRadiusTopRightPc":8,"itemBorderRadiusBottomRightPc":8,"itemBorderRadiusBottomLeftPc":8,"itemBorderRadiusTopLeftSp":8,"itemBorderRadiusTopRightSp":8,"itemBorderRadiusBottomRightSp":8,"itemBorderRadiusBottomLeftSp":8} -->
<div class="wp-block-wdl-lw-pr-column-1 lw-pr-column-1" style="--column-1-wrap-padding-pc:0px 0px 0px 0px;--column-1-wrap-padding-sp:0px 0px 0px 0px;--column-1-border-color-pc:rgb(131, 131, 131);--column-1-border-width-pc:0px;--column-1-border-style-pc:solid;--column-1-border-color-sp:rgb(131, 131, 131);--column-1-border-width-sp:0px;--column-1-border-style-sp:solid;--column-1-bdr-pc:0px 0px 0px 0px;--column-1-bdr-sp:0px 0px 0px 0px;--column-1-gtc-pc:1fr 1fr;--column-1-gtc-sp:1fr;--column-1-row-gap-pc:20px;--column-1-row-gap-sp:16px;--column-1-column-gap-pc:20px;--column-1-column-gap-sp:20px;--column-1-item-bg-pc:#eef2f7;--column-1-item-bg-sp:#eef2f7;--column-1-item-min-h-pc:0px;--column-1-item-min-h-sp:0px;--column-1-item-padding-pc:26px 26px 26px 26px;--column-1-item-padding-sp:20px 18px 20px 18px;--column-1-item-bdr-pc:8px 8px 8px 8px;--column-1-item-bdr-sp:8px 8px 8px 8px;--column-1-item-border-color-pc:rgb(131, 131, 131);--column-1-item-border-width-pc:0px;--column-1-item-border-style-pc:solid;--column-1-item-border-color-sp:rgb(131, 131, 131);--column-1-item-border-width-sp:0px;--column-1-item-border-style-sp:solid"><div class="custom_wrap"><!-- wp:heading {"level":3,"style":{"color":{"text":"#c1440e"},"typography":{"fontSize":"18px","lineHeight":"1.5"},"spacing":{"margin":{"top":"0px","bottom":"12px"}}}} -->
<h3 class="has-text-color" style="color:#c1440e;font-size:18px;line-height:1.5;margin-top:0px;margin-bottom:12px">向いていない人</h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"style":{"color":{"text":"#1f2733"},"typography":{"fontSize":"15px","lineHeight":"2"},"spacing":{"margin":{"top":"0px","bottom":"0px"}}}} -->
<p class="has-text-color" style="color:#1f2733;font-size:15px;line-height:2;margin-top:0px;margin-bottom:0px">・昼休みに動画を見る習慣がある<br>・困ったときに電話で聞きたい<br>・支払いを口座振替にしたい<br>・通話アプリを入れるのが面倒</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":3,"style":{"color":{"text":"#1668b0"},"typography":{"fontSize":"18px","lineHeight":"1.5"},"spacing":{"margin":{"top":"0px","bottom":"12px"}}}} -->
<h3 class="has-text-color" style="color:#1668b0;font-size:18px;line-height:1.5;margin-top:0px;margin-bottom:12px">向いている人</h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"style":{"color":{"text":"#1f2733"},"typography":{"fontSize":"15px","lineHeight":"2"},"spacing":{"margin":{"top":"0px","bottom":"0px"}}}} -->
<p class="has-text-color" style="color:#1f2733;font-size:15px;line-height:2;margin-top:0px;margin-bottom:0px">・家と職場にWi-Fiがある<br>・問い合わせがチャットでも気にならない<br>・クレジットカードで払っている<br>・合わなければ翌月に戻せばいい、と思える</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:wdl/lw-pr-column-1 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":80,"tbHeight":64,"spHeight":40} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:80px"></div><div class="tb" style="height:64px"></div><div class="sp" style="height:40px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-pr-custom-title-13 {"mainTitle":"いっしょに買った端末","subTitle":"DEVICE","headingLevel":2,"colorMain":"#16305c"} -->
<div class="wp-block-wdl-lw-pr-custom-title-13 lw-pr-custom-title-13" style="--color-main:#16305c"><h2 class="ttl"><span class="sub">DEVICE</span><span class="main">いっしょに買った端末</span><div class="left"></div><div class="right"></div></h2></div>
<!-- /wp:wdl/lw-pr-custom-title-13 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":16,"tbHeight":16,"spHeight":12} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:16px"></div><div class="tb" style="height:16px"></div><div class="sp" style="height:12px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:paragraph {"align":"center","style":{"spacing":{"margin":{"top":"28px","bottom":"24px"}}}} -->
<p class="has-text-align-center" style="margin-top:28px;margin-bottom:24px">4年使った端末が電池切れになったので、乗り換えと同時に買い替えました。<span class="lw-br on_500px"></span>会社から買わず、自分で選んで持ち込んでいます。</p>
<!-- /wp:paragraph -->
<!-- wp:wdl/lw-pr-product-1 {"showPr":true,"prText":"PR","isAffiliate":true,"prBgColor":"#16305c","prTextColor":"#ffffff","imageUrl":"https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/sm_device_1.webp","imageAlt":"黒いスマートフォン","productName":"SIMフリーの5万円クラスの端末","productDesc":"3年使うつもりで、電池の持ちと本体の重さだけで選びました。カメラは値段なりです。「動作確認済み端末」の一覧に載っていることを申し込む前に確かめてください。","productPrice":"49,800円（税込）","priceNote":"※価格は掲載時点のものです。最新の価格は各サイトでご確認ください。","shops":[{"label":"Amazonで見る","url":"https://example.com/shop-a/","bgColor":"#ff9900","textColor":"#ffffff"},{"label":"楽天市場で見る","url":"https://example.com/shop-r/","bgColor":"#bf0000","textColor":"#ffffff"},{"label":"Yahoo!で見る","url":"","bgColor":"#ff0033","textColor":"#ffffff"}],"maxWidth":900,"boxBorderColor":"#d8dfe8","nameColor":"#16305c","descColor":"#5c6673","priceColor":"#1f2733","borderRadius":8} -->
<div class="wp-block-wdl-lw-pr-product-1 lw-pr-product-1" style="margin-top:0px;margin-bottom:0px;--pd1-max-width:900px;--pd1-img-w:200px;--pd1-img-w-sp:110px;--pd1-name-size:19px;--pd1-name-size-sp:17px;--pd1-btn-col:2;--pd1-btn-col-sp:1;--pd1-btn-size:15px"><div class="lw-pr-product-1__box" style="background-color:#ffffff;border-color:#d8dfe8;border-width:1px;border-radius:8px"><span class="lw-pr-product-1__pr" style="background-color:#16305c;color:#ffffff">PR</span><div class="lw-pr-product-1__main"><div class="lw-pr-product-1__img"><img src="https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/sm_device_1.webp" alt="黒いスマートフォン"/></div><div class="lw-pr-product-1__body"><p class="lw-pr-product-1__name" style="color:#16305c" data-lw_font_set="">SIMフリーの5万円クラスの端末</p><p class="lw-pr-product-1__desc" style="color:#5c6673">3年使うつもりで、電池の持ちと本体の重さだけで選びました。カメラは値段なりです。「動作確認済み端末」の一覧に載っていることを申し込む前に確かめてください。</p><p class="lw-pr-product-1__price" style="color:#1f2733">49,800円（税込）</p></div></div><div class="lw-pr-product-1__shops"><a class="lw-pr-product-1__shop" href="https://example.com/shop-a/" target="_blank" rel="noopener noreferrer sponsored nofollow" style="background-color:#ff9900;color:#ffffff;border-radius:6px" data-lw_font_set="">Amazonで見る</a><a class="lw-pr-product-1__shop" href="https://example.com/shop-r/" target="_blank" rel="noopener noreferrer sponsored nofollow" style="background-color:#bf0000;color:#ffffff;border-radius:6px" data-lw_font_set="">楽天市場で見る</a></div><p class="lw-pr-product-1__note">※価格は掲載時点のものです。最新の価格は各サイトでご確認ください。</p></div></div>
<!-- /wp:wdl/lw-pr-product-1 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":80,"tbHeight":64,"spHeight":40} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:80px"></div><div class="tb" style="height:64px"></div><div class="sp" style="height:40px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-button-03 {"btnTextSub":"3か月使って、戻す理由は見つかりませんでした","btnTextMain":"A社の公式サイトを見る","btnUrl":"https://example.com/a-mobile/","isAffiliate":true,"openNewTab":true,"bgGradient":"#c1440e","textMainColor":"#ffffff","textSubColor":"#16305c","iconColor":"#ffffff","fontWeight":"600","selectedIcon":"\u003csvg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 512 512\"\u003e\u003c!--!Font Awesome Free 6.6.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--\u003e\u003cpath d=\"M320 0c-17.7 0-32 14.3-32 32s14.3 32 32 32l82.7 0L201.4 265.4c-12.5 12.5-12.5 32.8 0 45.3s32.8 12.5 45.3 0L448 109.3l0 82.7c0 17.7 14.3 32 32 32s32-14.3 32-32l0-160c0-17.7-14.3-32-32-32L320 0zM80 32C35.8 32 0 67.8 0 112L0 432c0 44.2 35.8 80 80 80l320 0c44.2 0 80-35.8 80-80l0-112c0-17.7-14.3-32-32-32s-32 14.3-32 32l0 112c0 8.8-7.2 16-16 16L80 448c-8.8 0-16-7.2-16-16l0-320c0-8.8 7.2-16 16-16l112 0c17.7 0 32-14.3 32-32s-14.3-32-32-32L80 32z\"/\u003e\u003c/svg\u003e"} -->
<div class="wp-block-wdl-lw-button-03 lw-button-03"><div class="a_inner"><a href="https://example.com/a-mobile/" target="_blank" rel="sponsored nofollow"><span class="text_sub" style="color:#16305c;font-weight:600" data-lw_font_set="">3か月使って、戻す理由は見つかりませんでした</span><div class="text_main_wrap"><div class="icon-svg" style="fill:#ffffff"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><!--!Font Awesome Free 6.6.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M320 0c-17.7 0-32 14.3-32 32s14.3 32 32 32l82.7 0L201.4 265.4c-12.5 12.5-12.5 32.8 0 45.3s32.8 12.5 45.3 0L448 109.3l0 82.7c0 17.7 14.3 32 32 32s32-14.3 32-32l0-160c0-17.7-14.3-32-32-32L320 0zM80 32C35.8 32 0 67.8 0 112L0 432c0 44.2 35.8 80 80 80l320 0c44.2 0 80-35.8 80-80l0-112c0-17.7-14.3-32-32-32s-32 14.3-32 32l0 112c0 8.8-7.2 16-16 16L80 448c-8.8 0-16-7.2-16-16l0-320c0-8.8 7.2-16 16-16l112 0c17.7 0 32-14.3 32-32s-14.3-32-32-32L80 32z"/></svg></div><span class="text_main" style="color:#ffffff;font-weight:600" data-lw_font_set="">A社の公式サイトを見る</span></div></a><div class="a_background" style="background:#c1440e"></div></div></div>
<!-- /wp:wdl/lw-button-03 -->
<!-- wp:wdl/cta-1 {"buttonUrl":"/sim-plan/","openInNewTab":false,"filterColor":"rgba(22,48,92,0.82)","buttonBackgroundColor":"#c1440e","buttonBorderColor":"#ffffff","buttonBorderSize":1,"buttonMaxWidth":320,"headingLevel":2} -->
<div class="wp-block-wdl-cta-1 wp-block-wdl-cta-1 "><div class="cta-1__inner"><h2 class="cta-1__title heading_style_reset">自分の使い方だと、いくらになるか</h2><p class="cta-1__text  ">同じ条件で5社を並べた表を用意しています。昼に動画を見るかどうかで選ぶ会社が変わるので、まずそこから決めてください。</p><a class="cta-1__button" href="/sim-plan/" style="background-color:#c1440e;border-color:#ffffff;border-width:1px;border-style:solid;max-width:320px">料金をくらべる</a></div><div class="cta-1__image"><img src="https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/sm_cta_bg.webp" alt="" loading="lazy"/><div style="background-color:rgba(22,48,92,0.82);position:absolute;top:0;left:0;right:0;bottom:0;z-index:1"></div></div></div>
<!-- /wp:wdl/cta-1 -->