<!-- wp:wdl/lw-pr-fv-18 {"backgroundType":"image","imageUrlPc":"https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/br_fv.webp","imageUrlSp":"","imageAlt":"打ち合わせのテーブル","bgColor":"#4a3c17","filterColor":"#4a3c17","filterOpacity":0.86,"maxWidth":1180,"formSide":"right","formWidth":396,"showBadge":true,"badgeLabel":"無料","badgeText":"ご相談だけで終わって結構です","badgeBgColor":"#8a6f2e","badgeTextColor":"#ffffff","headingLevel":1,"mainTitle":"相談だけの日を\u003cbr\u003eつくりました","titleColor":"#ffffff","titleFontWeight":"700","titleFontSizePc":44,"titleFontSizeSp":29,"description":"式の日取りが決まっていなくても構いません。決めることの多さに困ったら、まず一度お話しください。","descriptionColor":"#eae5d9","showTicks":true,"tickItems":[{"text":"所要60分"},{"text":"その場で契約は求めません"},{"text":"ご家族とご一緒でも"}],"tickTextColor":"#ffffff","tickMarkBgColor":"#ffffff","tickMarkColor":"#4a3c17","cardBgColor":"#ffffff","cardTitle":"相談日をおさえる","cardTitleColor":"#8a6f2e","cardSubText":"ご希望の日を1つ書くだけ・30秒","cardSubColor":"#5c5443","formId":"1","submitBgColor":"#635021","submitTextColor":"#ffffff","requiredBgColor":"#635021","cardNote":"いただいたご連絡先は、ご相談の日程調整だけに使います。","cardNoteColor":"#5c5443","buttonText":"","buttonSub":"","buttonUrl":"","buttonLinkType":"url","ctaBgColor":"#635021","ctaTextColor":"#ffffff","ctaBorderRadius":6,"minHeightPc":"min-h-pc-560px","minHeightTb":"min-h-tb-480px","minHeightSp":""} -->
<div class="wp-block-wdl-lw-pr-fv-18 lw-pr-fv-18 min-h-pc-560px min-h-tb-480px form_right" style="--fv18-max-width:1180px;--fv18-form-width:396px;--fv18-bg:#4a3c17;--fv18-filter-color:#4a3c17;--fv18-filter-opacity:0.86;--fv18-badge-bg:#8a6f2e;--fv18-badge-text:#ffffff;--fv18-title-color:#ffffff;--fv18-title-weight:700;--fv18-title-size-pc:44px;--fv18-title-size-sp:29px;--fv18-description-color:#eae5d9;--fv18-tick-color:#ffffff;--fv18-tick-mark-bg:#ffffff;--fv18-tick-mark-color:#4a3c17;--fv18-card-bg:#ffffff;--fv18-card-title-color:#8a6f2e;--fv18-card-sub-color:#5c5443;--fv18-card-note-color:#5c5443;--fv18-submit-bg:#635021;--fv18-submit-text:#ffffff;--fv18-required-bg:#635021;--fv18-cta-bg:#635021;--fv18-cta-text:#ffffff;--fv18-cta-radius:6px" id="form"><div class="bg_filter"><div class="bg_filter_inner"></div><picture><source srcSet="https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/br_fv.webp" media="(max-width: 800px)"/><source srcSet="https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/br_fv.webp" media="(min-width: 801px)"/><img src="https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/br_fv.webp" alt="打ち合わせのテーブル"/></picture></div><div class="this_wrap"><div class="lead_side"><span class="offer_badge"><b>無料</b><span>ご相談だけで終わって結構です</span></span><h1 class="main_ttl" data-lw_font_set="">相談だけの日を<br>つくりました</h1><p class="description">式の日取りが決まっていなくても構いません。決めることの多さに困ったら、まず一度お話しください。</p><ul class="tick_list"><li><i>✓</i><span>所要60分</span></li><li><i>✓</i><span>その場で契約は求めません</span></li><li><i>✓</i><span>ご家族とご一緒でも</span></li></ul></div><div class="form_side"><div class="form_card"><p class="card_ttl">相談日をおさえる</p><p class="card_sub">ご希望の日を1つ書くだけ・30秒</p>[lw_mail_form_select id='1']<p class="card_note">いただいたご連絡先は、ご相談の日程調整だけに使います。</p></div></div></div></div>
<!-- /wp:wdl/lw-pr-fv-18 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":80,"tbHeight":64,"spHeight":40} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:80px"></div><div class="tb" style="height:64px"></div><div class="sp" style="height:40px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-pr-custom-title-11 {"mainTitle":"その日にすること","subTitle":"WHAT WE DO","headingLevel":2,"colorMain":"#8a6f2e","colorMainText":"#ffffff","colorSubText":"#ffffff","borderRadius":4} -->
<div class="wp-block-wdl-lw-pr-custom-title-11 lw-pr-custom-title-11" style="--color-main:#8a6f2e;--color-main-text:#ffffff;--color-sub-text:#ffffff;width:100%;margin:1em auto"><h2 class="ttl" style="border-radius:4px"><span class="sub">WHAT WE DO</span><span class="main">その日にすること</span></h2></div>
<!-- /wp:wdl/lw-pr-custom-title-11 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":16,"tbHeight":16,"spHeight":12} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:16px"></div><div class="tb" style="height:16px"></div><div class="sp" style="height:12px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:paragraph {"align":"center","style":{"color":{"text":"#38342c"},"typography":{"fontSize":"16px","lineHeight":"2"},"spacing":{"margin":{"top":"28px","bottom":"24px"}}}} -->
<p class="has-text-align-center has-text-color" style="color:#38342c;font-size:16px;line-height:2;margin-top:28px;margin-bottom:24px">お化粧はしたままでお越しください。<span class="lw-br on_500px"></span>着替えも必要ありません。</p>
<!-- /wp:paragraph -->
<!-- wp:wdl/paid-block-lw-step-6 {"numberBgColor":"#635021","borderColor":"#635021","titleBorderColor":"#635021","fontColorLi":"#4a3c17","fontColorLiP":"#38342c","liBorderColor":"#ece2cd","showNumber":true} -->
<div class="wp-block-wdl-paid-block-lw-step-6 paid-block-lw-step-6"><ul class="paid-block-lw-step-6__inner"><li class="paid-block-lw-step-6__li" style="border-color:#ece2cd;border-width:1px;border-style:solid;border-radius:0px"><div class="number" style="background-color:#635021;color:#fff;font-weight:700"><span>20分</span></div><div class="link"><div class="image" style="border-radius:0px;border-color:#635021;border-width:0;border-style:none;aspect-ratio:400 / 300"><img src="https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/br_care.webp" alt="" style="object-fit:cover"/></div><h3 class="ttl font_size_m" data-lw_font_set="" style="font-weight:600;color:#4a3c17;border-bottom-color:#635021;border-bottom-width:2px;border-bottom-style:solid">見る</h3><p class="paid-block-lw-step-6__text font_size_m" data-lw_font_set="" style="font-weight:400;color:#38342c">顔と、ドレスで出るところ（背中・腕・デコルテ）を見ます。触れるのはこの時間だけです。</p></div></li><li class="paid-block-lw-step-6__li" style="border-color:#ece2cd;border-width:1px;border-style:solid;border-radius:0px"><div class="number" style="background-color:#635021;color:#fff;font-weight:700"><span>30分</span></div><div class="link"><div class="image" style="border-radius:0px;border-color:#635021;border-width:0;border-style:none;aspect-ratio:400 / 300"><img src="https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/br_counsel.webp" alt="" style="object-fit:cover"/></div><h3 class="ttl font_size_m" data-lw_font_set="" style="font-weight:600;color:#4a3c17;border-bottom-color:#635021;border-bottom-width:2px;border-bottom-style:solid">引く</h3><p class="paid-block-lw-step-6__text font_size_m" data-lw_font_set="" style="font-weight:400;color:#38342c">式の日から逆算して、何をいつまでにするかを紙に引きます。当店に通わない前提の案も一緒に書きます。</p></div></li><li class="paid-block-lw-step-6__li" style="border-color:#ece2cd;border-width:1px;border-style:solid;border-radius:0px"><div class="number" style="background-color:#635021;color:#fff;font-weight:700"><span>10分</span></div><div class="link"><div class="image" style="border-radius:0px;border-color:#635021;border-width:0;border-style:none;aspect-ratio:400 / 300"><img src="https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/br_dress.webp" alt="" style="object-fit:cover"/></div><h3 class="ttl font_size_m" data-lw_font_set="" style="font-weight:600;color:#4a3c17;border-bottom-color:#635021;border-bottom-width:2px;border-bottom-style:solid">渡す</h3><p class="paid-block-lw-step-6__text font_size_m" data-lw_font_set="" style="font-weight:400;color:#38342c">その紙をお渡しして終わりです。お持ち帰りいただいて、彼やご家族と相談してからで結構です。</p></div></li></ul></div>
<!-- /wp:wdl/paid-block-lw-step-6 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":80,"tbHeight":64,"spHeight":40} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:80px"></div><div class="tb" style="height:64px"></div><div class="sp" style="height:40px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-pr-custom-title-11 {"mainTitle":"予約から当日まで","subTitle":"FLOW","headingLevel":2,"colorMain":"#8a6f2e","colorMainText":"#ffffff","colorSubText":"#ffffff","borderRadius":4} -->
<div class="wp-block-wdl-lw-pr-custom-title-11 lw-pr-custom-title-11" style="--color-main:#8a6f2e;--color-main-text:#ffffff;--color-sub-text:#ffffff;width:100%;margin:1em auto" id="flow"><h2 class="ttl" style="border-radius:4px"><span class="sub">FLOW</span><span class="main">予約から当日まで</span></h2></div>
<!-- /wp:wdl/lw-pr-custom-title-11 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":16,"tbHeight":16,"spHeight":12} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:16px"></div><div class="tb" style="height:16px"></div><div class="sp" style="height:12px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/paid-block-lw-step-3 {"ulMaxWidth":1040,"fontSizeClass":"font_size_m","bgGradient":"#635021","colorH3":"#4a3c17","colorP":"#38342c","noWidthEm":0,"noFontSizeEm":0} -->
<div class="wp-block-wdl-paid-block-lw-step-3 paid-block-lw-step-3 font_size_m"><ul class="lw-step-2__inner" style="max-width:1040px"><li class="lw-step-2__li" style="border-color:#635021"><div class="lw-step-2__li_no" data-lw_font_set="Murecho" style="font-weight:600;background:#635021">01</div><div class="lw-step-2__li_in"><h3 class="lw-step-2__li_title ttl" data-lw_font_set="" style="color:#4a3c17">空いている日を選ぶ</h3><p class="lw-step-2__li_text" data-lw_font_set="" style="color:#38342c">ご予約ページか、お電話でお申し込みください。式の3か月前までにお越しになる方が多いですが、1か月前でもできることはあります。</p></div></li><li class="lw-step-2__li" style="border-color:#635021"><div class="lw-step-2__li_no" data-lw_font_set="Murecho" style="font-weight:600;background:#635021">02</div><div class="lw-step-2__li_in"><h3 class="lw-step-2__li_title ttl" data-lw_font_set="" style="color:#4a3c17">前日にお知らせが届く</h3><p class="lw-step-2__li_text" data-lw_font_set="" style="color:#38342c">前日の夕方に、場所と持ち物のご案内をお送りします。持ち物はありません。ドレスの写真があれば、お手元にご用意ください。</p></div></li><li class="lw-step-2__li" style="border-color:#635021"><div class="lw-step-2__li_no" data-lw_font_set="Murecho" style="font-weight:600;background:#635021">03</div><div class="lw-step-2__li_in"><h3 class="lw-step-2__li_title ttl" data-lw_font_set="" style="color:#4a3c17">当日・受付</h3><p class="lw-step-2__li_text" data-lw_font_set="" style="color:#38342c">ご予約の5分前にお越しください。上着をお預かりして、そのままお部屋へご案内します。お連れさまの同席もできます。</p></div></li><li class="lw-step-2__li" style="border-color:#635021"><div class="lw-step-2__li_no" data-lw_font_set="Murecho" style="font-weight:600;background:#635021">04</div><div class="lw-step-2__li_in"><h3 class="lw-step-2__li_title ttl" data-lw_font_set="" style="color:#4a3c17">60分の相談</h3><p class="lw-step-2__li_text" data-lw_font_set="" style="color:#38342c">見る・引く・渡すの3つだけです。途中で「やっぱり今日はやめておきます」とおっしゃっていただいても構いません。</p></div></li><li class="lw-step-2__li" style="border-color:#635021"><div class="lw-step-2__li_no" data-lw_font_set="Murecho" style="font-weight:600;background:#635021">05</div><div class="lw-step-2__li_in"><h3 class="lw-step-2__li_title ttl" data-lw_font_set="" style="color:#4a3c17">お帰り</h3><p class="lw-step-2__li_text" data-lw_font_set="" style="color:#38342c">その日にお決めいただくことは何もありません。ご連絡をこちらから差し上げることもありません。</p></div></li></ul></div>
<!-- /wp:wdl/paid-block-lw-step-3 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":80,"tbHeight":64,"spHeight":40} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:80px"></div><div class="tb" style="height:64px"></div><div class="sp" style="height:40px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-bg-1 {"backgroundType":"image","imagePc":"","imageSp":"","isFullWidth":true,"maxWidth":1040,"minHeightPc":"min-h-pc-150px","minHeightTb":"min-h-tb-160px","minHeightSp":"min-h-sp-160px","innerPaddingTopPc":80,"innerPaddingBottomPc":80,"innerPaddingLeftPc":40,"innerPaddingRightPc":40,"innerPaddingTopTb":64,"innerPaddingBottomTb":64,"innerPaddingLeftTb":32,"innerPaddingRightTb":32,"innerPaddingTopSp":48,"innerPaddingBottomSp":48,"innerPaddingLeftSp":20,"innerPaddingRightSp":20,"filterTypePc":"solid","filterColorPc":"#faf6ec","opacityPc":1,"filterTypeTb":"solid","filterColorTb":"#faf6ec","opacityTb":1,"filterTypeSp":"solid","filterColorSp":"#faf6ec","opacitySp":1} -->
<div class="wp-block-wdl-lw-bg-1 lw-bg-1 min-h-pc-150px min-h-tb-160px min-h-sp-160px bg_all" style="--lw-bg-color-filter-pc:#faf6ec;--lw-bg-opacity-pc:1;--lw-bg-color-filter-tb:#faf6ec;--lw-bg-opacity-tb:1;--lw-bg-color-filter-sp:#faf6ec;--lw-bg-opacity-sp:1;--lw-bg-position-pc:50% 50%;--lw-bg-position-sp:50% 50%;--lw-bg-wrap-centering-pc:center;--lw-bg-wrap-align-pc:center;--lw-bg-wrap-centering-tb:center;--lw-bg-wrap-align-tb:center;--lw-bg-wrap-centering-sp:center;--lw-bg-wrap-align-sp:center"><div class="lw-bg-1-wrap" style="--lw-bg-padding-top-pc:80px;--lw-bg-padding-bottom-pc:80px;--lw-bg-padding-left-pc:40px;--lw-bg-padding-right-pc:40px;--lw-bg-padding-top-tb:64px;--lw-bg-padding-bottom-tb:64px;--lw-bg-padding-left-tb:32px;--lw-bg-padding-right-tb:32px;--lw-bg-padding-top-sp:48px;--lw-bg-padding-bottom-sp:48px;--lw-bg-padding-left-sp:20px;--lw-bg-padding-right-sp:20px;--lw-bg-max-width:1040px"><!-- wp:heading {"level":3,"style":{"color":{"text":"#4a3c17"},"typography":{"fontSize":"24px","lineHeight":"1.6"},"spacing":{"margin":{"top":"0px","bottom":"16px"}}},"textAlign":"center"} -->
<h3 class="has-text-align-center has-text-color" style="color:#4a3c17;font-size:24px;line-height:1.6;margin-top:0px;margin-bottom:16px">どこまでが無料か</h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"style":{"color":{"text":"#38342c"},"typography":{"fontSize":"16px","lineHeight":"1.9"}},"align":"center"} -->
<p class="has-text-align-center has-text-color" style="color:#38342c;font-size:16px;line-height:1.9">上の60分に費用はかかりません。当日その場で施術をご希望された場合のみ、通常の料金（1回 11,000円〜）がかかります。化粧品・回数券の販売はしておりません。キャンセル料も、当日のご連絡までいただきません。</p>
<!-- /wp:paragraph -->
<!-- wp:wdl/lw-space-1 {"pcHeight":24,"tbHeight":20,"spHeight":16} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:24px"></div><div class="tb" style="height:20px"></div><div class="sp" style="height:16px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-list-4 {"colorLiSvg":"#635021","borderColor":"#ece2cd","borderWidth":1,"textColor":"#38342c","bgColor":"#ffffff","maxWidth":720,"colClass":"clm_1"} -->
<div class="wp-block-wdl-lw-list-4 lw-list-4"><ul class="lw-list-4__inner clm_1 " style="border-color:#ece2cd;border-width:1px;border-style:solid;border-radius:0.5em;max-width:720px;background-color:#ffffff"><li class="lw-list-4__li size_m"><span class="icon" style="width:1.2em"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" style="fill:#635021"><path d="M64 80c-8.8 0-16 7.2-16 16l0 320c0 8.8 7.2 16 16 16l320 0c8.8 0 16-7.2 16-16l0-320c0-8.8-7.2-16-16-16L64 80zM0 96C0 60.7 28.7 32 64 32l320 0c35.3 0 64 28.7 64 64l0 320c0 35.3-28.7 64-64 64L64 480c-35.3 0-64-28.7-64-64L0 96zM337 209L209 337c-9.4 9.4-24.6 9.4-33.9 0l-64-64c-9.4-9.4-9.4-24.6 0-33.9s24.6-9.4 33.9 0l47 47L303 175c9.4-9.4 24.6-9.4 33.9 0s9.4 24.6 0 33.9z"></path></svg></span><span class="lw-list-4__text"><p data-lw_font_set="" style="color:#38342c;width:calc(100% - 1.2em)">相談だけで帰られる方がいちばん多いです</p></span></li><li class="lw-list-4__li size_m"><span class="icon" style="width:1.2em"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" style="fill:#635021"><path d="M64 80c-8.8 0-16 7.2-16 16l0 320c0 8.8 7.2 16 16 16l320 0c8.8 0 16-7.2 16-16l0-320c0-8.8-7.2-16-16-16L64 80zM0 96C0 60.7 28.7 32 64 32l320 0c35.3 0 64 28.7 64 64l0 320c0 35.3-28.7 64-64 64L64 480c-35.3 0-64-28.7-64-64L0 96zM337 209L209 337c-9.4 9.4-24.6 9.4-33.9 0l-64-64c-9.4-9.4-9.4-24.6 0-33.9s24.6-9.4 33.9 0l47 47L303 175c9.4-9.4 24.6-9.4 33.9 0s9.4 24.6 0 33.9z"></path></svg></span><span class="lw-list-4__text"><p data-lw_font_set="" style="color:#38342c;width:calc(100% - 1.2em)">お連れさまが一緒でも費用は変わりません</p></span></li><li class="lw-list-4__li size_m"><span class="icon" style="width:1.2em"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" style="fill:#635021"><path d="M64 80c-8.8 0-16 7.2-16 16l0 320c0 8.8 7.2 16 16 16l320 0c8.8 0 16-7.2 16-16l0-320c0-8.8-7.2-16-16-16L64 80zM0 96C0 60.7 28.7 32 64 32l320 0c35.3 0 64 28.7 64 64l0 320c0 35.3-28.7 64-64 64L64 480c-35.3 0-64-28.7-64-64L0 96zM337 209L209 337c-9.4 9.4-24.6 9.4-33.9 0l-64-64c-9.4-9.4-9.4-24.6 0-33.9s24.6-9.4 33.9 0l47 47L303 175c9.4-9.4 24.6-9.4 33.9 0s9.4 24.6 0 33.9z"></path></svg></span><span class="lw-list-4__text"><p data-lw_font_set="" style="color:#38342c;width:calc(100% - 1.2em)">ご予約の変更は前日までにご連絡ください</p></span></li></ul></div>
<!-- /wp:wdl/lw-list-4 -->
<!-- wp:paragraph {"align":"center","style":{"color":{"text":"#5c5443"},"typography":{"fontSize":"14px","lineHeight":"1.9"},"spacing":{"margin":{"top":"16px","bottom":"0px"}}}} -->
<p class="has-text-align-center has-text-color" style="color:#5c5443;font-size:14px;line-height:1.9;margin-top:16px;margin-bottom:0px">※ 当店は医療機関ではありません。診断・治療・お薬の処方はいたしません。</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:wdl/lw-bg-1 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":80,"tbHeight":64,"spHeight":40} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:80px"></div><div class="tb" style="height:64px"></div><div class="sp" style="height:40px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-pr-custom-title-11 {"mainTitle":"よくうかがうこと","subTitle":"QUESTIONS","headingLevel":2,"colorMain":"#8a6f2e","colorMainText":"#ffffff","colorSubText":"#ffffff","borderRadius":4} -->
<div class="wp-block-wdl-lw-pr-custom-title-11 lw-pr-custom-title-11" style="--color-main:#8a6f2e;--color-main-text:#ffffff;--color-sub-text:#ffffff;width:100%;margin:1em auto"><h2 class="ttl" style="border-radius:4px"><span class="sub">QUESTIONS</span><span class="main">よくうかがうこと</span></h2></div>
<!-- /wp:wdl/lw-pr-custom-title-11 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":16,"tbHeight":16,"spHeight":12} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:16px"></div><div class="tb" style="height:16px"></div><div class="sp" style="height:12px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-pr-qa-3 {"maxWidth":880,"qLabelColor":"#635021","aLabelColor":"#5c5443","lineColor":"#ece2cd"} -->
<div class="wp-block-wdl-lw-pr-qa-3 lw-pr-qa-3" style="--qa3-max-w:880px;--qa3-gap:24px;--qa3-label-w:32px;--qa3-q-color:#635021;--qa3-a-color:#5c5443;--qa3-line:#ece2cd;--qa3-label-size-pc:18px;--qa3-label-size-sp:16px;--qa3-q-size-pc:17px;--qa3-q-size-sp:15px;--qa3-a-size-pc:15px;--qa3-a-size-sp:14px"><dl class="qa-3__item"><dt><span class="label" data-lw_font_set="Roboto">Q</span><p class="qa-3__q_text">式まで1か月しかありません。</p></dt><dd><span class="label" data-lw_font_set="Roboto">A</span><p class="qa-3__a_text">間に合うことと、間に合わないことをその日にはっきりお伝えします。無理に回数を詰めるご提案はしません。1か月でできることだけを紙に書きます。</p></dd></dl><dl class="qa-3__item"><dt><span class="label" data-lw_font_set="Roboto">Q</span><p class="qa-3__q_text">彼と一緒に行ってもいいですか。</p></dt><dd><span class="label" data-lw_font_set="Roboto">A</span><p class="qa-3__a_text">もちろん構いません。お二人で来られる方も多くいらっしゃいます。ご新郎の背中のご相談もあわせてお受けします。費用は変わりません。</p></dd></dl><dl class="qa-3__item"><dt><span class="label" data-lw_font_set="Roboto">Q</span><p class="qa-3__q_text">肌が弱いのですが受けられますか。</p></dt><dd><span class="label" data-lw_font_set="Roboto">A</span><p class="qa-3__a_text">お使いのお薬と、荒れたときの様子をうかがいます。合わないと判断したら、その場でお断りすることもあります。</p></dd></dl></div>
<!-- /wp:wdl/lw-pr-qa-3 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":80,"tbHeight":64,"spHeight":40} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:80px"></div><div class="tb" style="height:64px"></div><div class="sp" style="height:40px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-bg-1 {"backgroundType":"image","imagePc":"","imageSp":"","isFullWidth":true,"maxWidth":1040,"minHeightPc":"min-h-pc-150px","minHeightTb":"min-h-tb-160px","minHeightSp":"min-h-sp-160px","innerPaddingTopPc":80,"innerPaddingBottomPc":80,"innerPaddingLeftPc":40,"innerPaddingRightPc":40,"innerPaddingTopTb":64,"innerPaddingBottomTb":64,"innerPaddingLeftTb":32,"innerPaddingRightTb":32,"innerPaddingTopSp":48,"innerPaddingBottomSp":48,"innerPaddingLeftSp":20,"innerPaddingRightSp":20,"filterTypePc":"solid","filterColorPc":"#4a3c17","opacityPc":1,"filterTypeTb":"solid","filterColorTb":"#4a3c17","opacityTb":1,"filterTypeSp":"solid","filterColorSp":"#4a3c17","opacitySp":1} -->
<div class="wp-block-wdl-lw-bg-1 lw-bg-1 min-h-pc-150px min-h-tb-160px min-h-sp-160px bg_all" style="--lw-bg-color-filter-pc:#4a3c17;--lw-bg-opacity-pc:1;--lw-bg-color-filter-tb:#4a3c17;--lw-bg-opacity-tb:1;--lw-bg-color-filter-sp:#4a3c17;--lw-bg-opacity-sp:1;--lw-bg-position-pc:50% 50%;--lw-bg-position-sp:50% 50%;--lw-bg-wrap-centering-pc:center;--lw-bg-wrap-align-pc:center;--lw-bg-wrap-centering-tb:center;--lw-bg-wrap-align-tb:center;--lw-bg-wrap-centering-sp:center;--lw-bg-wrap-align-sp:center"><div class="lw-bg-1-wrap" style="--lw-bg-padding-top-pc:80px;--lw-bg-padding-bottom-pc:80px;--lw-bg-padding-left-pc:40px;--lw-bg-padding-right-pc:40px;--lw-bg-padding-top-tb:64px;--lw-bg-padding-bottom-tb:64px;--lw-bg-padding-left-tb:32px;--lw-bg-padding-right-tb:32px;--lw-bg-padding-top-sp:48px;--lw-bg-padding-bottom-sp:48px;--lw-bg-padding-left-sp:20px;--lw-bg-padding-right-sp:20px;--lw-bg-max-width:1040px"><!-- wp:heading {"level":3,"style":{"color":{"text":"#ffffff"},"typography":{"fontSize":"26px","lineHeight":"1.6"},"spacing":{"margin":{"top":"0px","bottom":"16px"}}},"textAlign":"center"} -->
<h3 class="has-text-align-center has-text-color" style="color:#ffffff;font-size:26px;line-height:1.6;margin-top:0px;margin-bottom:16px">日取りが決まったら</h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"style":{"color":{"text":"#f2e6c8"},"typography":{"fontSize":"16px","lineHeight":"2"}},"align":"center"} -->
<p class="has-text-align-center has-text-color" style="color:#f2e6c8;font-size:16px;line-height:2">早いほうができることは増えますが、遅いから間に合わないということもありません。まずは今の状態を見せにいらしてください。</p>
<!-- /wp:paragraph -->
<!-- wp:wdl/lw-space-1 {"pcHeight":24,"tbHeight":20,"spHeight":16} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:24px"></div><div class="tb" style="height:20px"></div><div class="sp" style="height:16px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-pr-button-4 {"textMain":"000-000-0000","textSub":"受付時間 10:00〜19:00（火曜定休）","btnUrl":"tel:0000000000","btnAlign":"center","bgColor":"#ffffff","bgColorHover":"#f5eeda","textColorMain":"#4a3c17","textColorSub":"#4a3c17","borderWidth":0,"borderRadius":4} -->
<div class="wp-block-wdl-lw-pr-button-4 lw-pr-button-4"><div class="wrap_btn center"><a href="tel:0000000000" class="lw_btn_a " style="--hover-bg:#f5eeda;--transition-duration:0.3s;--max-width-sp:480px;--shake-interval:3s;--font-size-main:28px;--font-size-main-sp:18px;--font-size-sub:14px;--letter-spacing:0.05em;max-width:580px;padding:1.2em 1.5em;background:#ffffff;border:0px solid #000000;border-radius:4px;box-shadow:0px 0px 6px rgba(0, 0, 0, 0.2)"><span class="text_main" style="color:#4a3c17;font-weight:500;font-size:28px;letter-spacing:0.05em" data-lw_font_set=""><span class="icon" style="fill:#ffffff;width:32px;margin-right:8px;margin-left:-8px"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M164.9 24.6c-7.7-18.6-28-28.5-47.4-23.2l-88 24C12.1 30.2 0 46 0 64C0 311.4 200.6 512 448 512c18 0 33.8-12.1 38.6-29.5l24-88c5.3-19.4-4.6-39.7-23.2-47.4l-96-40c-16.3-6.8-35.2-2.1-46.3 11.6L304.7 368C234.3 334.7 177.3 277.7 144 207.3L193.3 167c13.7-11.2 18.4-30 11.6-46.3l-40-96z"/></svg></span>000-000-0000</span><span class="text_sub" style="color:#4a3c17;font-weight:500;font-size:14px" data-lw_font_set="">受付時間 10:00〜19:00（火曜定休）</span></a></div></div>
<!-- /wp:wdl/lw-pr-button-4 --></div></div>
<!-- /wp:wdl/lw-bg-1 -->
<!-- wp:wdl/lw-bg-1 {"backgroundType":"image","imagePc":"","imageSp":"","isFullWidth":true,"maxWidth":1040,"minHeightPc":"min-h-pc-150px","minHeightTb":"min-h-tb-160px","minHeightSp":"min-h-sp-160px","innerPaddingTopPc":80,"innerPaddingBottomPc":80,"innerPaddingLeftPc":40,"innerPaddingRightPc":40,"innerPaddingTopTb":64,"innerPaddingBottomTb":64,"innerPaddingLeftTb":32,"innerPaddingRightTb":32,"innerPaddingTopSp":48,"innerPaddingBottomSp":48,"innerPaddingLeftSp":20,"innerPaddingRightSp":20,"filterTypePc":"solid","filterColorPc":"#4a3c17","opacityPc":1,"filterTypeTb":"solid","filterColorTb":"#4a3c17","opacityTb":1,"filterTypeSp":"solid","filterColorSp":"#4a3c17","opacitySp":1} -->
<div class="wp-block-wdl-lw-bg-1 lw-bg-1 min-h-pc-150px min-h-tb-160px min-h-sp-160px bg_all" style="--lw-bg-color-filter-pc:#4a3c17;--lw-bg-opacity-pc:1;--lw-bg-color-filter-tb:#4a3c17;--lw-bg-opacity-tb:1;--lw-bg-color-filter-sp:#4a3c17;--lw-bg-opacity-sp:1;--lw-bg-position-pc:50% 50%;--lw-bg-position-sp:50% 50%;--lw-bg-wrap-centering-pc:center;--lw-bg-wrap-align-pc:center;--lw-bg-wrap-centering-tb:center;--lw-bg-wrap-align-tb:center;--lw-bg-wrap-centering-sp:center;--lw-bg-wrap-align-sp:center"><div class="lw-bg-1-wrap" style="--lw-bg-padding-top-pc:80px;--lw-bg-padding-bottom-pc:80px;--lw-bg-padding-left-pc:40px;--lw-bg-padding-right-pc:40px;--lw-bg-padding-top-tb:64px;--lw-bg-padding-bottom-tb:64px;--lw-bg-padding-left-tb:32px;--lw-bg-padding-right-tb:32px;--lw-bg-padding-top-sp:48px;--lw-bg-padding-bottom-sp:48px;--lw-bg-padding-left-sp:20px;--lw-bg-padding-right-sp:20px;--lw-bg-max-width:1040px"><!-- wp:heading {"level":3,"style":{"color":{"text":"#ffffff"},"typography":{"fontSize":"26px","lineHeight":"1.6"},"spacing":{"margin":{"top":"0px","bottom":"16px"}}},"textAlign":"center"} -->
<h3 class="has-text-align-center has-text-color" style="color:#ffffff;font-size:26px;line-height:1.6;margin-top:0px;margin-bottom:16px">ご希望の日を1つ書くだけ</h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"style":{"color":{"text":"#faf6ec"},"typography":{"fontSize":"16px","lineHeight":"2"}},"align":"center"} -->
<p class="has-text-align-center has-text-color" style="color:#faf6ec;font-size:16px;line-height:2">お決まりでなければ空欄で結構です。<span class="lw-br on_500px"></span>こちらから2〜3の候補をお出しします。</p>
<!-- /wp:paragraph -->
<!-- wp:wdl/lw-space-1 {"pcHeight":24,"tbHeight":20,"spHeight":16} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:24px"></div><div class="tb" style="height:20px"></div><div class="sp" style="height:16px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-pr-button-2 {"textSub":"＼ ご相談だけで終わって結構です ／","textMain":"上のフォームから予約する","btnUrl":"#form","btnAlign":"center","bgGradient":"#ffffff","bgGradientHover":"#faf6ec","textColorMain":"#4a3c17","textColorSub":"#faf6ec","fontSizeMain":18,"fontSizeMainSp":16,"fontSizeSub":13,"maxWidth":420,"borderRadius":6} -->
<div class="wp-block-wdl-lw-pr-button-2 lw-pr-button-2 center"><div class="wrap_btn"><span class="text_sub" style="margin-bottom:6px;color:#faf6ec;font-size:13px;font-weight:500" data-lw_font_set="">＼ ご相談だけで終わって結構です ／</span><a href="#form" class="lw_btn_a " style="padding:1.2em 1em;max-width:420px;background:#ffffff;border-radius:6px;box-shadow:0px 0px 6px rgba(0, 0, 0, 0.2);--hover-bg:#faf6ec;--transition-duration:0.3s;--shake-interval:3s;--max-width-sp:300px;--font-size-main-sp:16px"><span class="text_main" style="font-size:18px;font-weight:500;color:#4a3c17" data-lw_font_set="">上のフォームから予約する</span></a></div></div>
<!-- /wp:wdl/lw-pr-button-2 --></div></div>
<!-- /wp:wdl/lw-bg-1 -->
<!-- wp:paragraph {"align":24,"style":{"color":{"text":"#5c5443"},"typography":{"fontSize":"14px","lineHeight":"1.9"},"spacing":{"margin":{"top":"16px","bottom":"0px"}}}} -->
<p class="has-text-align-24 has-text-color" style="color:#5c5443;font-size:14px;line-height:1.9;margin-top:16px;margin-bottom:0px">※ このページは見本です。実際に送信いただいてもお返事はできません。</p>
<!-- /wp:paragraph -->