<!-- wp:wdl/lw-pr-fv-20 {"panelBgColor":"#824d5f","imageUrlPc":"https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/cs_fv_01.webp","imageUrlSp":"","imageAlt":"朝の窓辺","imageSide":"right","maxWidth":600,"showEyebrow":true,"eyebrow":"1日と15日の朝に","eyebrowColor":"#ead6dd","headingLevel":1,"mainTitle":"月に2回だけ、\u003cbr\u003e送ります","titleColor":"#ffffff","titleFontWeight":"700","titleFontSizePc":42,"titleFontSizeSp":28,"description":"読み終わるまで1分。やめるときは、メールの中のリンクを1回押すだけです。","descriptionColor":"#f3e7eb","buttonText":"メールで受け取る","buttonSub":"アドレスだけ・30秒","buttonUrl":"#form","buttonLinkType":"url","ctaBgColor":"#ffffff","ctaTextColor":"#6b3446","ctaSubColor":"#764656","ctaBorderRadius":6,"showStats":true,"statsItems":[{"num":"2","unit":"回","label":"ひと月に届く数"},{"num":"1","unit":"分","label":"読み終わるまで"},{"num":"1","unit":"タップ","label":"やめるときの手数"},{"num":"0","unit":"円","label":"ずっと無料"}],"statsBgColor":"#51303b","statsNumColor":"#ffffff","statsUnitColor":"#debcc8","statsLabelColor":"#e7d0d8","statsTopLineColor":"#d4a9b8","statsColumnsSp":2,"minHeightPc":"min-h-pc-440px","minHeightTb":"min-h-tb-360px","minHeightSp":""} -->
<div class="wp-block-wdl-lw-pr-fv-20 lw-pr-fv-20 image_right" style="--fv20-panel-bg:#824d5f;--fv20-max-width:600px;--fv20-eyebrow-color:#ead6dd;--fv20-title-color:#ffffff;--fv20-title-weight:700;--fv20-title-size-pc:42px;--fv20-title-size-sp:28px;--fv20-description-color:#f3e7eb;--fv20-cta-bg:#ffffff;--fv20-cta-text:#6b3446;--fv20-cta-sub:#764656;--fv20-cta-radius:6px;--fv20-stats-bg:#51303b;--fv20-stats-num:#ffffff;--fv20-stats-unit:#debcc8;--fv20-stats-label:#e7d0d8;--fv20-stats-line:#d4a9b8;--fv20-stats-cols:4;--fv20-stats-cols-sp:2"><div class="fv20_top min-h-pc-440px min-h-tb-360px"><div class="txt_side"><div class="txt_inner"><p class="eyebrow">1日と15日の朝に</p><h1 class="main_ttl" data-lw_font_set="">月に2回だけ、<br>送ります</h1><p class="description">読み終わるまで1分。やめるときは、メールの中のリンクを1回押すだけです。</p><a class="cta_btn" href="#form">メールで受け取る<small>アドレスだけ・30秒</small></a></div></div><div class="pic_side"><picture><source srcSet="https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/cs_fv_01.webp" media="(max-width: 800px)"/><source srcSet="https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/cs_fv_01.webp" media="(min-width: 801px)"/><img src="https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/cs_fv_01.webp" alt="朝の窓辺"/></picture></div></div><div class="stats_bar"><div class="stat"><p class="n">2<span class="u">回</span></p><p class="l">ひと月に届く数</p></div><div class="stat"><p class="n">1<span class="u">分</span></p><p class="l">読み終わるまで</p></div><div class="stat"><p class="n">1<span class="u">タップ</span></p><p class="l">やめるときの手数</p></div><div class="stat"><p class="n">0<span class="u">円</span></p><p class="l">ずっと無料</p></div></div></div>
<!-- /wp:wdl/lw-pr-fv-20 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":80,"tbHeight":64,"spHeight":40} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:80px"></div><div class="tb" style="height:64px"></div><div class="sp" style="height:40px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-pr-custom-title-15 {"mainTitle":"月に2回だけ送ります","subTitle":"NEWSLETTER","headingLevel":2,"showSubTitle":true,"afterColor":"#b56b84","afterHeightPc":4,"afterWidthPc":56,"fontSizePc":15,"fontSizeSp":14,"mainFontWeight":"700","positionPc":"center","positionSp":"center"} -->
<h2 class="wp-block-wdl-lw-pr-custom-title-15 lw-pr-custom-title-15 center center" style="--custom-title-sub-margin-top-pc:0.2em;--custom-title-sub-margin-top-sp:0.2em;--title-15-after-color:#b56b84;--title-15-after-mt-pc:1em;--title-15-after-mt-sp:0.8em;--title-15-after-h-pc:4px;--title-15-after-h-sp:4px;--title-15-after-w-pc:56px;--title-15-after-w-sp:50px;--title-15-font-size_pc:15px;--title-15-font-size_sp:14px"><span class="main" style="font-weight:700">月に2回だけ送ります</span><span class="sub">NEWSLETTER</span></h2>
<!-- /wp:wdl/lw-pr-custom-title-15 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":16,"tbHeight":16,"spHeight":12} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:16px"></div><div class="tb" style="height:16px"></div><div class="sp" style="height:12px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:paragraph {"align":"center","style":{"color":{"text":"#3b3338"},"typography":{"fontSize":"16px","lineHeight":"2"},"spacing":{"margin":{"top":"28px","bottom":"24px"}}}} -->
<p class="has-text-align-center has-text-color" style="color:#3b3338;font-size:16px;line-height:2;margin-top:28px;margin-bottom:24px">毎日は届きません。<span class="lw-br on_500px"></span>1日と15日の朝、それだけです。</p>
<!-- /wp:paragraph -->
<!-- wp:wdl/paid-block-lw-company-3 {"dtBackgroundColor":"#824d5f","borderColor":"#f0dfe5","ddTextColor":"#3b3338","spFullDt":true,"maxWidth":1040} -->
<div class="wp-block-wdl-paid-block-lw-company-3 paid-block-lw-company-3 font_size_m"><dl class="lw-company-3__inner" style="max-width:1040px;line-height:1.6"><div class="lw-company-3__row dt_width_m sp_clm_1"><dt class="lw-company-3__dt" style="background:#824d5f"><div class="lw-company-3__dt_text" data-lw_font_set="Murecho" style="font-weight:600;line-height:1.6">月2回</div><div class="lw-company-3__dt_arrow" style="background:#824d5f"></div></dt><dd class="lw-company-3__dd" data-lw_font_set="" style="color:#3b3338;border-color:#f0dfe5;line-height:1.6">1日と15日の朝8時に届きます。セールの前でも回数は増やしません。</dd></div><div class="lw-company-3__row dt_width_m sp_clm_1"><dt class="lw-company-3__dt" style="background:#824d5f"><div class="lw-company-3__dt_text" data-lw_font_set="Murecho" style="font-weight:600;line-height:1.6">1分</div><div class="lw-company-3__dt_arrow" style="background:#824d5f"></div></dt><dd class="lw-company-3__dd" data-lw_font_set="" style="color:#3b3338;border-color:#f0dfe5;line-height:1.6">読み終わるまでの目安です。長くなりそうな回は、続きをサイトに置いています。</dd></div><div class="lw-company-3__row dt_width_m sp_clm_1"><dt class="lw-company-3__dt" style="background:#824d5f"><div class="lw-company-3__dt_text" data-lw_font_set="Murecho" style="font-weight:600;line-height:1.6">1押し</div><div class="lw-company-3__dt_arrow" style="background:#824d5f"></div></dt><dd class="lw-company-3__dd" data-lw_font_set="" style="color:#3b3338;border-color:#f0dfe5;line-height:1.6">やめるときは、メールのいちばん下のリンクを1回押すだけです。理由もうかがいません。</dd></div></dl></div>
<!-- /wp:wdl/paid-block-lw-company-3 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":80,"tbHeight":64,"spHeight":40} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:80px"></div><div class="tb" style="height:64px"></div><div class="sp" style="height:40px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-pr-custom-title-15 {"mainTitle":"中身は3つ","subTitle":"CONTENTS","headingLevel":2,"showSubTitle":true,"afterColor":"#b56b84","afterHeightPc":4,"afterWidthPc":56,"fontSizePc":15,"fontSizeSp":14,"mainFontWeight":"700","positionPc":"center","positionSp":"center"} -->
<h2 class="wp-block-wdl-lw-pr-custom-title-15 lw-pr-custom-title-15 center center" style="--custom-title-sub-margin-top-pc:0.2em;--custom-title-sub-margin-top-sp:0.2em;--title-15-after-color:#b56b84;--title-15-after-mt-pc:1em;--title-15-after-mt-sp:0.8em;--title-15-after-h-pc:4px;--title-15-after-h-sp:4px;--title-15-after-w-pc:56px;--title-15-after-w-sp:50px;--title-15-font-size_pc:15px;--title-15-font-size_sp:14px"><span class="main" style="font-weight:700">中身は3つ</span><span class="sub">CONTENTS</span></h2>
<!-- /wp:wdl/lw-pr-custom-title-15 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":16,"tbHeight":16,"spHeight":12} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:16px"></div><div class="tb" style="height:16px"></div><div class="sp" style="height:12px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:paragraph {"align":"center","style":{"color":{"text":"#3b3338"},"typography":{"fontSize":"16px","lineHeight":"2"},"spacing":{"margin":{"top":"28px","bottom":"24px"}}}} -->
<p class="has-text-align-center has-text-color" style="color:#3b3338;font-size:16px;line-height:2;margin-top:28px;margin-bottom:24px">売り込みの回はありません。買っていただかなくても読めるものだけを入れています。</p>
<!-- /wp:paragraph -->
<!-- wp:wdl/lw-pr-list-5 {"listColumns":1,"imageUrl":"https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/cs_item_01.webp","imageAlt":"並べられた化粧品の容器","bgColor":"#ffffff","textColor":"#6b3446","leftItems":["入荷のお知らせ　少量しか入らないものは、店頭に出す前に。とっておけます","使い方の話　量・順番・季節での変え方を1回に1つだけ","返品の実例　合わなくて返された品と、その理由をそのまま"],"rightItems":[]} -->
<div class="wp-block-wdl-lw-pr-list-5 lw-pr-list-5 columns-1" style="--list_items_bg_color:#ffffff;--list_items_color:#6b3446"><div class="lw-pr-list-5_wrap"><div class="list_items"><div class="list_items_inner"><ul class="list_left" data-lw_font_set=""><li><span>入荷のお知らせ　少量しか入らないものは、店頭に出す前に。とっておけます</span></li><li><span>使い方の話　量・順番・季節での変え方を1回に1つだけ</span></li><li><span>返品の実例　合わなくて返された品と、その理由をそのまま</span></li></ul></div></div><div class="image"><img loading="lazy" src="https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/cs_item_01.webp" alt="並べられた化粧品の容器"/></div></div></div>
<!-- /wp:wdl/lw-pr-list-5 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":80,"tbHeight":64,"spHeight":40} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:80px"></div><div class="tb" style="height:64px"></div><div class="sp" style="height:40px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-pr-custom-title-15 {"mainTitle":"読んでくださっている方から","subTitle":"FROM READERS","headingLevel":2,"showSubTitle":true,"afterColor":"#b56b84","afterHeightPc":4,"afterWidthPc":56,"fontSizePc":15,"fontSizeSp":14,"mainFontWeight":"700","positionPc":"center","positionSp":"center"} -->
<h2 class="wp-block-wdl-lw-pr-custom-title-15 lw-pr-custom-title-15 center center" style="--custom-title-sub-margin-top-pc:0.2em;--custom-title-sub-margin-top-sp:0.2em;--title-15-after-color:#b56b84;--title-15-after-mt-pc:1em;--title-15-after-mt-sp:0.8em;--title-15-after-h-pc:4px;--title-15-after-h-sp:4px;--title-15-after-w-pc:56px;--title-15-after-w-sp:50px;--title-15-font-size_pc:15px;--title-15-font-size_sp:14px"><span class="main" style="font-weight:700">読んでくださっている方から</span><span class="sub">FROM READERS</span></h2>
<!-- /wp:wdl/lw-pr-custom-title-15 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":16,"tbHeight":16,"spHeight":12} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:16px"></div><div class="tb" style="height:16px"></div><div class="sp" style="height:12px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-comment-1 {"name":"みずき","title":"\u003cstrong\u003e3年目の読者です\u003c/strong\u003e\n返品の実例がいちばん好きです。「これは合わない人が多い」と書いてあるお店を、ほかに知りません。","imageUrl":"https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/sk_av_01.webp","imageColor":"#b56b84","altText":"みずきさん","commentAlignment":"left","commentBgColor":"#fcf3f6","nameTextColor":"#6b3446","titleTextColor":"#3b3338","maxWidth":1040} -->
<div class="wp-block-wdl-lw-comment-1 lw-comment-1 left"><div class="lw-comment-1__wrap" style="max-width:1040px"><div class="lw-comment-1__image"><img src="https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/sk_av_01.webp" alt="みずきさん" style="border-color:#b56b84"/><div class="lw-comment-1__name"><p class="lw-p" style="color:#6b3446">みずき</p></div></div><div class="lw-comment-1__text_wrap"><div class="lw-comment-1__text"><p class="lw-p" style="color:#3b3338"><strong>3年目の読者です</strong>
返品の実例がいちばん好きです。「これは合わない人が多い」と書いてあるお店を、ほかに知りません。</p><div class="lw-arrow" style="background-color:#fcf3f6"></div><div class="lw-bg_color" style="background-color:#fcf3f6"></div></div></div></div></div>
<!-- /wp:wdl/lw-comment-1 -->
<!-- wp:wdl/lw-comment-1 {"name":"たかし","title":"\u003cstrong\u003e妻に勧められて\u003c/strong\u003e\n男でも読めます。成分の名前がほとんど出てこないので、そこが助かっています。","imageUrl":"https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/sk_av_02.webp","imageColor":"#b56b84","altText":"たかしさん","commentAlignment":"right","commentBgColor":"#fcf3f6","nameTextColor":"#6b3446","titleTextColor":"#3b3338","maxWidth":1040} -->
<div class="wp-block-wdl-lw-comment-1 lw-comment-1 right"><div class="lw-comment-1__wrap" style="max-width:1040px"><div class="lw-comment-1__image"><img src="https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/sk_av_02.webp" alt="たかしさん" style="border-color:#b56b84"/><div class="lw-comment-1__name"><p class="lw-p" style="color:#6b3446">たかし</p></div></div><div class="lw-comment-1__text_wrap"><div class="lw-comment-1__text"><p class="lw-p" style="color:#3b3338"><strong>妻に勧められて</strong>
男でも読めます。成分の名前がほとんど出てこないので、そこが助かっています。</p><div class="lw-arrow" style="background-color:#fcf3f6"></div><div class="lw-bg_color" style="background-color:#fcf3f6"></div></div></div></div></div>
<!-- /wp:wdl/lw-comment-1 -->
<!-- wp:wdl/lw-comment-1 {"name":"ふみ","title":"\u003cstrong\u003e一度やめました\u003c/strong\u003e\n忙しい時期に解除したのですが、本当に1回押すだけで止まりました。それが気持ちよくて、半年後にまた登録しました。","imageUrl":"https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/sk_av_03.webp","imageColor":"#b56b84","altText":"ふみさん","commentAlignment":"left","commentBgColor":"#fcf3f6","nameTextColor":"#6b3446","titleTextColor":"#3b3338","maxWidth":1040} -->
<div class="wp-block-wdl-lw-comment-1 lw-comment-1 left"><div class="lw-comment-1__wrap" style="max-width:1040px"><div class="lw-comment-1__image"><img src="https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/sk_av_03.webp" alt="ふみさん" style="border-color:#b56b84"/><div class="lw-comment-1__name"><p class="lw-p" style="color:#6b3446">ふみ</p></div></div><div class="lw-comment-1__text_wrap"><div class="lw-comment-1__text"><p class="lw-p" style="color:#3b3338"><strong>一度やめました</strong>
忙しい時期に解除したのですが、本当に1回押すだけで止まりました。それが気持ちよくて、半年後にまた登録しました。</p><div class="lw-arrow" style="background-color:#fcf3f6"></div><div class="lw-bg_color" style="background-color:#fcf3f6"></div></div></div></div></div>
<!-- /wp:wdl/lw-comment-1 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":80,"tbHeight":64,"spHeight":40} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:80px"></div><div class="tb" style="height:64px"></div><div class="sp" style="height:40px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-bg-1 {"backgroundType":"image","imagePc":"","imageSp":"","isFullWidth":true,"maxWidth":1040,"minHeightPc":"min-h-pc-150px","minHeightTb":"min-h-tb-160px","minHeightSp":"min-h-sp-160px","innerPaddingTopPc":80,"innerPaddingBottomPc":80,"innerPaddingLeftPc":40,"innerPaddingRightPc":40,"innerPaddingTopTb":64,"innerPaddingBottomTb":64,"innerPaddingLeftTb":32,"innerPaddingRightTb":32,"innerPaddingTopSp":48,"innerPaddingBottomSp":48,"innerPaddingLeftSp":20,"innerPaddingRightSp":20,"filterTypePc":"solid","filterColorPc":"#fcf3f6","opacityPc":1,"filterTypeTb":"solid","filterColorTb":"#fcf3f6","opacityTb":1,"filterTypeSp":"solid","filterColorSp":"#fcf3f6","opacitySp":1} -->
<div class="wp-block-wdl-lw-bg-1 lw-bg-1 min-h-pc-150px min-h-tb-160px min-h-sp-160px bg_all" style="--lw-bg-color-filter-pc:#fcf3f6;--lw-bg-opacity-pc:1;--lw-bg-color-filter-tb:#fcf3f6;--lw-bg-opacity-tb:1;--lw-bg-color-filter-sp:#fcf3f6;--lw-bg-opacity-sp:1;--lw-bg-position-pc:50% 50%;--lw-bg-position-sp:50% 50%;--lw-bg-wrap-centering-pc:center;--lw-bg-wrap-align-pc:center;--lw-bg-wrap-centering-tb:center;--lw-bg-wrap-align-tb:center;--lw-bg-wrap-centering-sp:center;--lw-bg-wrap-align-sp:center"><div class="lw-bg-1-wrap" style="--lw-bg-padding-top-pc:80px;--lw-bg-padding-bottom-pc:80px;--lw-bg-padding-left-pc:40px;--lw-bg-padding-right-pc:40px;--lw-bg-padding-top-tb:64px;--lw-bg-padding-bottom-tb:64px;--lw-bg-padding-left-tb:32px;--lw-bg-padding-right-tb:32px;--lw-bg-padding-top-sp:48px;--lw-bg-padding-bottom-sp:48px;--lw-bg-padding-left-sp:20px;--lw-bg-padding-right-sp:20px;--lw-bg-max-width:1040px"><!-- wp:heading {"level":3,"style":{"color":{"text":"#6b3446"},"typography":{"fontSize":"24px","lineHeight":"1.6"},"spacing":{"margin":{"top":"0px","bottom":"16px"}}},"textAlign":"center"} -->
<h3 class="has-text-align-center has-text-color" style="color:#6b3446;font-size:24px;line-height:1.6;margin-top:0px;margin-bottom:16px">お預かりするもの</h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"style":{"color":{"text":"#3b3338"},"typography":{"fontSize":"16px","lineHeight":"1.9"}},"align":"center"} -->
<p class="has-text-align-center has-text-color" style="color:#3b3338;font-size:16px;line-height:1.9">メールアドレスだけです。お名前も、生年月日も、お住まいもうかがいません。いただいたアドレスは、このお知らせを送るためだけに使います。他社にお渡しすることも、広告に使うこともありません。</p>
<!-- /wp:paragraph -->
<!-- wp:wdl/lw-space-1 {"pcHeight":24,"tbHeight":20,"spHeight":16} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:24px"></div><div class="tb" style="height:20px"></div><div class="sp" style="height:16px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-pr-list-7 {"colorLiSvg":"#824d5f","textColor":"#3b3338","colClass":"clm_1","columnWidths":[1],"columnWidthsSp":[1],"fontSizePc":16,"bgColor":"#ffffff","listGroups":[{"contents":[{"text":"解除はメール下部のリンクを1回押すだけです（理由はうかがいません）"},{"text":"解除されたアドレスは、その場で消します"},{"text":"お預かりしていること自体を知らせるメールも送りません"}]}]} -->
<div class="wp-block-wdl-lw-pr-list-7 lw-pr-list-7" style="--list-7-gtc-pc:1fr;--list-7-gtc-sp:1fr;--list-7-inner-row-gap-pc:20px;--list-7-inner-column-gap-pc:20px;--list-7-inner-row-gap-sp:20px;--list-7-inner-column-gap-sp:20px;--list-7-row-gap-pc:20px;--list-7-column-gap-pc:20px;--list-7-row-gap-sp:20px;--list-7-column-gap-sp:20px;--list-7-font-size-pc:16px;--list-7-font-size-sp:16px"><div class="custom_inner"><ul class="lw-pr-list-7__inner clm_1" style="background-color:#ffffff"><li class="lw-pr-list-7__li"><span class="icon" style="width:1.2em"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" style="fill:#824d5f"><path d="M64 80c-8.8 0-16 7.2-16 16l0 320c0 8.8 7.2 16 16 16l320 0c8.8 0 16-7.2 16-16l0-320c0-8.8-7.2-16-16-16L64 80zM0 96C0 60.7 28.7 32 64 32l320 0c35.3 0 64 28.7 64 64l0 320c0 35.3-28.7 64-64 64L64 480c-35.3 0-64-28.7-64-64L0 96zM337 209L209 337c-9.4 9.4-24.6 9.4-33.9 0l-64-64c-9.4-9.4-9.4-24.6 0-33.9s24.6-9.4 33.9 0l47 47L303 175c9.4-9.4 24.6-9.4 33.9 0s9.4 24.6 0 33.9z"></path></svg></span><span class="lw-pr-list-7__text"><p data-lw_font_set="" style="color:#3b3338;width:calc(100% - 1.2em)">解除はメール下部のリンクを1回押すだけです（理由はうかがいません）</p></span></li><li class="lw-pr-list-7__li"><span class="icon" style="width:1.2em"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" style="fill:#824d5f"><path d="M64 80c-8.8 0-16 7.2-16 16l0 320c0 8.8 7.2 16 16 16l320 0c8.8 0 16-7.2 16-16l0-320c0-8.8-7.2-16-16-16L64 80zM0 96C0 60.7 28.7 32 64 32l320 0c35.3 0 64 28.7 64 64l0 320c0 35.3-28.7 64-64 64L64 480c-35.3 0-64-28.7-64-64L0 96zM337 209L209 337c-9.4 9.4-24.6 9.4-33.9 0l-64-64c-9.4-9.4-9.4-24.6 0-33.9s24.6-9.4 33.9 0l47 47L303 175c9.4-9.4 24.6-9.4 33.9 0s9.4 24.6 0 33.9z"></path></svg></span><span class="lw-pr-list-7__text"><p data-lw_font_set="" style="color:#3b3338;width:calc(100% - 1.2em)">解除されたアドレスは、その場で消します</p></span></li><li class="lw-pr-list-7__li"><span class="icon" style="width:1.2em"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" style="fill:#824d5f"><path d="M64 80c-8.8 0-16 7.2-16 16l0 320c0 8.8 7.2 16 16 16l320 0c8.8 0 16-7.2 16-16l0-320c0-8.8-7.2-16-16-16L64 80zM0 96C0 60.7 28.7 32 64 32l320 0c35.3 0 64 28.7 64 64l0 320c0 35.3-28.7 64-64 64L64 480c-35.3 0-64-28.7-64-64L0 96zM337 209L209 337c-9.4 9.4-24.6 9.4-33.9 0l-64-64c-9.4-9.4-9.4-24.6 0-33.9s24.6-9.4 33.9 0l47 47L303 175c9.4-9.4 24.6-9.4 33.9 0s9.4 24.6 0 33.9z"></path></svg></span><span class="lw-pr-list-7__text"><p data-lw_font_set="" style="color:#3b3338;width:calc(100% - 1.2em)">お預かりしていること自体を知らせるメールも送りません</p></span></li></ul></div></div>
<!-- /wp:wdl/lw-pr-list-7 -->
<!-- wp:paragraph {"align":"center","style":{"color":{"text":"#5d525a"},"typography":{"fontSize":"14px","lineHeight":"1.9"},"spacing":{"margin":{"top":"16px","bottom":"0px"}}}} -->
<p class="has-text-align-center has-text-color" style="color:#5d525a;font-size:14px;line-height:1.9;margin-top:16px;margin-bottom:0px">※ 携帯電話のメールアドレスをお使いの方は、受信の設定によって届かないことがあります。</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:wdl/lw-bg-1 -->
<!-- wp:wdl/lw-bg-1 {"backgroundType":"image","imagePc":"","imageSp":"","isFullWidth":true,"maxWidth":1040,"minHeightPc":"min-h-pc-150px","minHeightTb":"min-h-tb-160px","minHeightSp":"min-h-sp-160px","innerPaddingTopPc":80,"innerPaddingBottomPc":80,"innerPaddingLeftPc":40,"innerPaddingRightPc":40,"innerPaddingTopTb":64,"innerPaddingBottomTb":64,"innerPaddingLeftTb":32,"innerPaddingRightTb":32,"innerPaddingTopSp":48,"innerPaddingBottomSp":48,"innerPaddingLeftSp":20,"innerPaddingRightSp":20,"filterTypePc":"solid","filterColorPc":"#6b3446","opacityPc":1,"filterTypeTb":"solid","filterColorTb":"#6b3446","opacityTb":1,"filterTypeSp":"solid","filterColorSp":"#6b3446","opacitySp":1} -->
<div class="wp-block-wdl-lw-bg-1 lw-bg-1 min-h-pc-150px min-h-tb-160px min-h-sp-160px bg_all" style="--lw-bg-color-filter-pc:#6b3446;--lw-bg-opacity-pc:1;--lw-bg-color-filter-tb:#6b3446;--lw-bg-opacity-tb:1;--lw-bg-color-filter-sp:#6b3446;--lw-bg-opacity-sp:1;--lw-bg-position-pc:50% 50%;--lw-bg-position-sp:50% 50%;--lw-bg-wrap-centering-pc:center;--lw-bg-wrap-align-pc:center;--lw-bg-wrap-centering-tb:center;--lw-bg-wrap-align-tb:center;--lw-bg-wrap-centering-sp:center;--lw-bg-wrap-align-sp:center"><div class="lw-bg-1-wrap" style="--lw-bg-padding-top-pc:80px;--lw-bg-padding-bottom-pc:80px;--lw-bg-padding-left-pc:40px;--lw-bg-padding-right-pc:40px;--lw-bg-padding-top-tb:64px;--lw-bg-padding-bottom-tb:64px;--lw-bg-padding-left-tb:32px;--lw-bg-padding-right-tb:32px;--lw-bg-padding-top-sp:48px;--lw-bg-padding-bottom-sp:48px;--lw-bg-padding-left-sp:20px;--lw-bg-padding-right-sp:20px;--lw-bg-max-width:1040px"><!-- wp:heading {"level":3,"style":{"color":{"text":"#ffffff"},"typography":{"fontSize":"26px","lineHeight":"1.6"},"spacing":{"margin":{"top":"0px","bottom":"16px"}}},"textAlign":"center"} -->
<h3 class="has-text-align-center has-text-color" style="color:#ffffff;font-size:26px;line-height:1.6;margin-top:0px;margin-bottom:16px">まず1通、読んでみて</h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"style":{"color":{"text":"#f3dde5"},"typography":{"fontSize":"16px","lineHeight":"2"}},"align":"center"} -->
<p class="has-text-align-center has-text-color" style="color:#f3dde5;font-size:16px;line-height:2">合わなければ、その1通の下のリンクを押すだけで終わりです。登録の前に中身を見たい方は、これまでの号をそのまま置いてあります。</p>
<!-- /wp:paragraph -->
<!-- wp:wdl/lw-space-1 {"pcHeight":24,"tbHeight":20,"spHeight":16} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:24px"></div><div class="tb" style="height:20px"></div><div class="sp" style="height:16px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-pr-button-2 {"textSub":"＼ 月2回・解除は1押し ／","textMain":"お知らせを受け取る","btnUrl":"#form","btnAlign":"center","bgGradient":"linear-gradient(135deg, #c67f95 0%, #a05470 100%)","bgGradientHover":"linear-gradient(135deg, #b36e84 0%, #8d4560 100%)","textColorMain":"#ffffff","textColorSub":"#f3dde5","fontSizeMain":18,"fontSizeMainSp":16,"fontSizeSub":13,"maxWidth":340,"borderRadius":64,"shadowY":2,"shadowBlur":10,"shadowOpacity":0.25} -->
<div class="wp-block-wdl-lw-pr-button-2 lw-pr-button-2 center"><div class="wrap_btn"><span class="text_sub" style="margin-bottom:6px;color:#f3dde5;font-size:13px;font-weight:500" data-lw_font_set="">＼ 月2回・解除は1押し ／</span><a href="#form" class="lw_btn_a " style="padding:1.2em 1em;max-width:340px;background:linear-gradient(135deg, #c67f95 0%, #a05470 100%);border-radius:64px;box-shadow:0px 2px 10px rgba(0, 0, 0, 0.25);--hover-bg:linear-gradient(135deg, #b36e84 0%, #8d4560 100%);--transition-duration:0.3s;--shake-interval:3s;--max-width-sp:300px;--font-size-main-sp:16px"><span class="text_main" style="font-size:18px;font-weight:500;color:#ffffff" data-lw_font_set="">お知らせを受け取る</span></a></div></div>
<!-- /wp:wdl/lw-pr-button-2 --></div></div>
<!-- /wp:wdl/lw-bg-1 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":80,"tbHeight":64,"spHeight":40} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:80px"></div><div class="tb" style="height:64px"></div><div class="sp" style="height:40px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:heading {"level":3,"style":{"color":{"text":"#6b3446"},"typography":{"fontSize":"26px","lineHeight":"1.6"},"spacing":{"margin":{"top":"0px","bottom":"16px"}}},"textAlign":"center"} -->
<h3 class="has-text-align-center has-text-color" style="color:#6b3446;font-size:26px;line-height:1.6;margin-top:0px;margin-bottom:16px">お手紙の登録</h3>
<!-- /wp:heading -->
<!-- wp:wdl/lw-space-1 {"pcHeight":16,"tbHeight":16,"spHeight":12} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:16px"></div><div class="tb" style="height:16px"></div><div class="sp" style="height:12px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:paragraph {"align":"center","style":{"color":{"text":"#3b3338"},"typography":{"fontSize":"16px","lineHeight":"2"},"spacing":{"margin":{"top":"28px","bottom":"24px"}}}} -->
<p class="has-text-align-center has-text-color" style="color:#3b3338;font-size:16px;line-height:2;margin-top:28px;margin-bottom:24px">メールアドレスだけで結構です。<br>お名前も、お住まいの地域もうかがいません。</p>
<!-- /wp:paragraph -->
<!-- wp:wdl/lw-contact-3 {"formId":1,"maxWidth":760,"labelColor":"#6b3446","inputBgColor":"#f6f6f6","inputTextColor":"#3b3338","buttonBgColor":"#824d5f","buttonTextColor":"#ffffff","requiredBgColor":"#824d5f","requiredTextColor":"#ffffff","optionalBgColor":"#dddddd","optionalTextColor":"#3b3338","uniqueClass":""} -->
<div class="wp-block-wdl-lw-contact-3 lw-contact-3 " style="max-width:760px" id="form">[lw_mail_form_select id='1']<style>
                    . .lw_mail_form .label_in label,.supplement_text { color: #6b3446; }
                    . .lw_mail_form input[type="text"],
                    . .lw_mail_form input[type="email"],
                    . .lw_mail_form input[type="tel"],
                    . .lw_mail_form input[type="url"],
                    . .lw_mail_form input[type="password"],
                    . .lw_mail_form textarea,
                    . .lw_mail_form select {
                        background-color: #f6f6f6;
                        color: #3b3338;
                    }
                    . .lw_mail_form select option { color: #3b3338; }
                    . .lw_mail_form .checkbox_in label,
                    . .lw_mail_form .radio_in label {
                        color: #6b3446;
                    }
                    . .lw_mail_form .submit_wrap button {
                        background-color: #824d5f;
                        color: #ffffff;
                    }
                    . .lw_mail_form .required:not(.is-optional) {
                        background-color: #824d5f !important;
                        color: #ffffff !important;
                    }
                    . .lw_mail_form .required.is-optional {
                        background-color: #dddddd !important;
                        color: #3b3338 !important;
                    }
                </style></div>
<!-- /wp:wdl/lw-contact-3 -->
<!-- wp:paragraph {"align":24,"style":{"color":{"text":"#5d525a"},"typography":{"fontSize":"14px","lineHeight":"1.9"},"spacing":{"margin":{"top":"16px","bottom":"0px"}}}} -->
<p class="has-text-align-24 has-text-color" style="color:#5d525a;font-size:14px;line-height:1.9;margin-top:16px;margin-bottom:0px">※ このページは見本です。実際に送信いただいてもお返事はできません。</p>
<!-- /wp:paragraph -->