<!-- wp:wdl/fv-6 {"backgroundImage":"https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/nav_bg_01.webp","backgroundImageSp":"","backgroundImageAlt":"木のカウンターのある明るい店内","mainTitle":"店舗と駐車場","subTitle":"SHOPS & PARKING","filterBackgroundColor":"#0f2f36","filterOpacity":0.28,"textColor":"#123640","minHeightPc":"min-h-pc-480px","minHeightTb":"min-h-tb-400px","minHeightSp":"min-h-sp-300px","mainTitleTag":"h1"} -->
<div class="wp-block-wdl-fv-6 fv-6 min-h-pc-480px min-h-tb-400px min-h-sp-300px"><div class="fv-6_inner"><h1 class="ttl" style="color:#123640"><span class="main" style="color:#123640">店舗と駐車場</span><span class="sub" style="color:#123640">SHOPS & PARKING</span></h1><div class="inner_filter"></div></div><div class="filter" style="background-color:#0f2f36;opacity:0.28"></div><picture class="bg_image"><source srcSet="" media="(max-width: 800px)"/><source srcSet="https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/nav_bg_01.webp" media="(min-width: 801px)"/><img src="https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/nav_bg_01.webp" alt="木のカウンターのある明るい店内" loading="eager" fetchpriority="high"/></picture></div>
<!-- /wp:wdl/fv-6 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":80,"tbHeight":64,"spHeight":40} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:80px"></div><div class="tb" style="height:64px"></div><div class="sp" style="height:40px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-pr-custom-title-14 {"mainTitle":"お店は4つあります","subTitle":"SHOP LIST","headingLevel":2,"colorMain":"#2e6f7d","colorMainText":"#123640","colorSubText":"#eaf4f6","borderRadius":8} -->
<div class="wp-block-wdl-lw-pr-custom-title-14 lw-pr-custom-title-14" style="--color-main:#2e6f7d;width:100%;--custom-title-14-border-radius:8px"><h2 class="ttl"><span class="sub"><span class="text" style="color:#eaf4f6">SHOP LIST</span></span><span class="main" style="color:#123640">お店は4つあります</span></h2></div>
<!-- /wp:wdl/lw-pr-custom-title-14 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":16,"tbHeight":16,"spHeight":12} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:16px"></div><div class="tb" style="height:16px"></div><div class="sp" style="height:12px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:paragraph {"align":"center","style":{"color":{"text":"#33403f"},"typography":{"fontSize":"16px","lineHeight":"2"},"spacing":{"margin":{"top":"28px","bottom":"24px"}}}} -->
<p class="has-text-align-center has-text-color" style="color:#33403f;font-size:16px;line-height:2;margin-top:28px;margin-bottom:24px">どの店でも同じパンを焼いていますが、置いている種類と広さが違います。<span class="lw-br on_500px"></span>イートインができるのは本店とけやき台店の2つだけです。</p>
<!-- /wp:paragraph -->
<!-- wp:wdl/lw-pr-list-6 {"columnsPC":4,"columnsSP":1,"rowGapPc":32,"columnGapPc":16,"imageAspectRatio":"9/6","fontSizeTtlPc":18,"alignTtlPc":"center","colorTitle":"#123640","marginTopTtlPc":12,"fontSizePPc":14,"alignPPc":"left","colorDescription":"#33403f","showLabel":true,"labelBgColor":"#2e6f7d","labelTextColor":"#ffffff","labelFontSizePc":15,"items":[{"imageUrl":"https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/bake_02.webp","label":"イートインあり","title":"本店","description":"朝7時から開けています。窯がいちばん大きいので、種類は本店がいちばん多いです。奥に8席のイートインがあります。"},{"imageUrl":"https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/bake_03.webp","label":"イートインあり","title":"けやき台店","description":"駅の西口を出てすぐ。夕方に焼き上がる食パンが人気です。テラス席が4席あります。"},{"imageUrl":"https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/bake_04.webp","label":"駐車場ひろめ","title":"中央通り店","description":"車で来られる方はこちらが停めやすいです。まとめ買いの箱もこの店だけ置いています。"},{"imageUrl":"https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/bake_05.webp","label":"土日のみ","title":"工房直売所","description":"焼いている工房のとなりで、土日だけ開けています。前日の分をお安くお出ししています。"}]} -->
<div class="wp-block-wdl-lw-pr-list-6 lw-pr-list-6" style="--columns-pc:4;--columns-sp:1;--list-6-row-gap-pc:32px;--list-6-row-gap-sp:32px;--list-6-column-gap-pc:16px;--list-6-column-gap-sp:16px;--list-6-fontsize-ttl-pc:18px;--list-6-fontsize-ttl-tb:18px;--list-6-fontsize-ttl-sp:18px;--list-6-align-ttl-pc:center;--list-6-align-ttl-sp:center;--list-6-margin-top-ttl-pc:12px;--list-6-margin-top-ttl-sp:12px;--list-6-fontsize-p-pc:14px;--list-6-fontsize-p-tb:14px;--list-6-fontsize-p-sp:14px;--list-6-align-p-pc:left;--list-6-align-p-sp:left;--list-6-label-bg:#2e6f7d;--list-6-label-color:#ffffff;--list-6-label-fontsize-pc:15px;--list-6-label-fontsize-sp:15px"><ul class="custom_list_items"><li class="custom_item"><div class="image"><img src="https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/bake_02.webp" alt="" style="aspect-ratio:9/6"/><span class="label">イートインあり</span></div><h3 class="custom_ttl" data-lw_font_set="" style="color:#123640">本店</h3><p class="custom_p" data-lw_font_set="" style="color:#33403f">朝7時から開けています。窯がいちばん大きいので、種類は本店がいちばん多いです。奥に8席のイートインがあります。</p></li><li class="custom_item"><div class="image"><img src="https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/bake_03.webp" alt="" style="aspect-ratio:9/6"/><span class="label">イートインあり</span></div><h3 class="custom_ttl" data-lw_font_set="" style="color:#123640">けやき台店</h3><p class="custom_p" data-lw_font_set="" style="color:#33403f">駅の西口を出てすぐ。夕方に焼き上がる食パンが人気です。テラス席が4席あります。</p></li><li class="custom_item"><div class="image"><img src="https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/bake_04.webp" alt="" style="aspect-ratio:9/6"/><span class="label">駐車場ひろめ</span></div><h3 class="custom_ttl" data-lw_font_set="" style="color:#123640">中央通り店</h3><p class="custom_p" data-lw_font_set="" style="color:#33403f">車で来られる方はこちらが停めやすいです。まとめ買いの箱もこの店だけ置いています。</p></li><li class="custom_item"><div class="image"><img src="https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/bake_05.webp" alt="" style="aspect-ratio:9/6"/><span class="label">土日のみ</span></div><h3 class="custom_ttl" data-lw_font_set="" style="color:#123640">工房直売所</h3><p class="custom_p" data-lw_font_set="" style="color:#33403f">焼いている工房のとなりで、土日だけ開けています。前日の分をお安くお出ししています。</p></li></ul></div>
<!-- /wp:wdl/lw-pr-list-6 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":80,"tbHeight":64,"spHeight":40} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:80px"></div><div class="tb" style="height:64px"></div><div class="sp" style="height:40px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-pr-custom-title-14 {"mainTitle":"駐車場のご案内","subTitle":"PARKING","headingLevel":2,"colorMain":"#2e6f7d","colorMainText":"#123640","colorSubText":"#eaf4f6","borderRadius":8} -->
<div class="wp-block-wdl-lw-pr-custom-title-14 lw-pr-custom-title-14" style="--color-main:#2e6f7d;width:100%;--custom-title-14-border-radius:8px"><h2 class="ttl"><span class="sub"><span class="text" style="color:#eaf4f6">PARKING</span></span><span class="main" style="color:#123640">駐車場のご案内</span></h2></div>
<!-- /wp:wdl/lw-pr-custom-title-14 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":16,"tbHeight":16,"spHeight":12} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:16px"></div><div class="tb" style="height:16px"></div><div class="sp" style="height:12px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:paragraph {"align":"center","style":{"color":{"text":"#33403f"},"typography":{"fontSize":"16px","lineHeight":"2"},"spacing":{"margin":{"top":"28px","bottom":"24px"}}}} -->
<p class="has-text-align-center has-text-color" style="color:#33403f;font-size:16px;line-height:2;margin-top:28px;margin-bottom:24px">4店とも駐車場がありますが、停められる台数がちがいます。</p>
<!-- /wp:paragraph -->
<!-- wp:wdl/paid-block-lw-company-3 {"dtBackgroundColor":"#21505a","borderColor":"#d5e4e6","ddTextColor":"#33403f","spFullDt":true,"maxWidth":1040} -->
<div class="wp-block-wdl-paid-block-lw-company-3 paid-block-lw-company-3 font_size_m"><dl class="lw-company-3__inner" style="max-width:1040px;line-height:1.6"><div class="lw-company-3__row dt_width_m sp_clm_1"><dt class="lw-company-3__dt" style="background:#21505a"><div class="lw-company-3__dt_text" data-lw_font_set="Murecho" style="font-weight:600;line-height:1.6">本店</div><div class="lw-company-3__dt_arrow" style="background:#21505a"></div></dt><dd class="lw-company-3__dd" data-lw_font_set="" style="color:#33403f;border-color:#d5e4e6;line-height:1.6">3台（店の裏手）。土曜の午前中は埋まっていることが多いです。</dd></div><div class="lw-company-3__row dt_width_m sp_clm_1"><dt class="lw-company-3__dt" style="background:#21505a"><div class="lw-company-3__dt_text" data-lw_font_set="Murecho" style="font-weight:600;line-height:1.6">けやき台店</div><div class="lw-company-3__dt_arrow" style="background:#21505a"></div></dt><dd class="lw-company-3__dd" data-lw_font_set="" style="color:#33403f;border-color:#d5e4e6;line-height:1.6">ありません。近くのコインパーキングをご利用ください（徒歩1分・30分100円）。</dd></div><div class="lw-company-3__row dt_width_m sp_clm_1"><dt class="lw-company-3__dt" style="background:#21505a"><div class="lw-company-3__dt_text" data-lw_font_set="Murecho" style="font-weight:600;line-height:1.6">中央通り店</div><div class="lw-company-3__dt_arrow" style="background:#21505a"></div></dt><dd class="lw-company-3__dd" data-lw_font_set="" style="color:#33403f;border-color:#d5e4e6;line-height:1.6">8台。4店のなかでいちばん停めやすく、ほぼお待たせしません。</dd></div><div class="lw-company-3__row dt_width_m sp_clm_1"><dt class="lw-company-3__dt" style="background:#21505a"><div class="lw-company-3__dt_text" data-lw_font_set="Murecho" style="font-weight:600;line-height:1.6">工房直売所</div><div class="lw-company-3__dt_arrow" style="background:#21505a"></div></dt><dd class="lw-company-3__dd" data-lw_font_set="" style="color:#33403f;border-color:#d5e4e6;line-height:1.6">5台。大きなお車でも入れる幅があります。</dd></div></dl></div>
<!-- /wp:wdl/paid-block-lw-company-3 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":24,"tbHeight":20,"spHeight":16} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:24px"></div><div class="tb" style="height:20px"></div><div class="sp" style="height:16px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-pr-waku-1 {"waku1MaxWidthPc":900,"waku1PaddingTopPc":28,"waku1PaddingBottomPc":28,"waku1PaddingLeftPc":32,"waku1PaddingRightPc":32,"waku1PaddingTopSp":20,"waku1PaddingBottomSp":20,"waku1PaddingLeftSp":16,"waku1PaddingRightSp":16,"waku1BorderWidthPc":1,"waku1BorderColorPc":"#d5e4e6","waku1BorderRadiusPc":[8,8,8,8],"waku1BgColorPc":"#eef5f6"} -->
<div class="wp-block-wdl-lw-pr-waku-1 lw-pr-waku-1" style="--waku-1-justify-content-pc:center;--waku-1-justify-content-sp:center"><div class="lw-pr-waku-1__custom_wrap" style="--waku-1-max-width-pc:900px;--waku-1-max-width-sp:900px;--waku-1-padding-pc:28px 32px 28px 32px;--waku-1-padding-sp:20px 16px 20px 16px;--waku-1-bd-width-pc:1px;--waku-1-bd-width-sp:1px;--waku-1-bd-style-pc:solid;--waku-1-bd-style-sp:solid;--waku-1-bd-color-pc:#d5e4e6;--waku-1-bd-color-sp:#d5e4e6;--waku-1-bdr-pc:8px 8px 8px 8px;--waku-1-bdr-sp:8px 8px 8px 8px;--waku-1-bg-pc:#eef5f6;--waku-1-bg-sp:#eef5f6;--waku-1-bg-opacity-pc:1;--waku-1-bg-opacity-sp:1;--waku-1-blend-mode-pc:normal;--waku-1-blend-mode-sp:normal;--waku-1-bg-img-pc:none;--waku-1-bg-img-sp:none;--waku-1-img-filter-pc:none;--waku-1-img-filter-sp:none;--waku-1-min-height-pc:auto;--waku-1-min-height-sp:auto;--waku-1-aspect-ratio-pc:auto;--waku-1-aspect-ratio-sp:auto"><!-- wp:heading {"level":3,"style":{"color":{"text":"#123640"},"typography":{"fontSize":"18px","lineHeight":"1.6"},"spacing":{"margin":{"top":"0px","bottom":"12px"}}},"textAlign":"center"} -->
<h3 class="has-text-align-center has-text-color" style="color:#123640;font-size:18px;line-height:1.6;margin-top:0px;margin-bottom:12px">お願い</h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"style":{"color":{"text":"#33403f"},"typography":{"fontSize":"16px","lineHeight":"1.9"},"spacing":{"margin":{"top":"0px","bottom":"0px"}}}} -->
<p class="has-text-color" style="color:#33403f;font-size:16px;line-height:1.9;margin-top:0px;margin-bottom:0px">すぐ横のスーパーの駐車場は当店の枠ではありませんので、停めないようお願いします。満車のときは、お電話をいただければ空き状況をお調べします。</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:wdl/lw-pr-waku-1 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":24,"tbHeight":20,"spHeight":16} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:24px"></div><div class="tb" style="height:20px"></div><div class="sp" style="height:16px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-pr-image-1 {"columnsPc":4,"columnsSp":1,"gapPc":12,"gapSp":8,"aspectRatioW":16,"aspectRatioH":10,"imgBorderRadius":6,"maxWidth":1040,"images":[{"imgUrl":"https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/gallery_01.webp","altText":"本店の店内。窓に沿って棚が並んでいる","linkUrl":""},{"imgUrl":"https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/gallery_02.webp","altText":"けやき台店の棚。袋詰めのパンが並んでいる","linkUrl":""},{"imgUrl":"https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/concept_01.webp","altText":"中央通り店の作業台。生地を伸ばしているところ","linkUrl":""},{"imgUrl":"https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/bake_06.webp","altText":"工房直売所。ケーキも土日だけ出している","linkUrl":""}]} -->
<div class="wp-block-wdl-lw-pr-image-1 lw-pr-image-1" style="--pr-image-1-gap-pc:12px;--pr-image-1-gap-sp:8px;--pr-image-1-clm-pc:4;--pr-image-1-clm-sp:1;--pr-image-1-aspect-w:16;--pr-image-1-aspect-h:10;--pr-image-1-radius:6px;--pr-image-1-mt-pc:16px;--pr-image-1-mb-pc:16px;--pr-image-1-mt-sp:16px;--pr-image-1-mb-sp:16px;--pr-image-1-max-w:1040px"><div class="lw-pr-image-1__wrap"><div class="lw-pr-image-1__item"><img src="https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/gallery_01.webp" alt="本店の店内。窓に沿って棚が並んでいる"/></div><div class="lw-pr-image-1__item"><img src="https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/gallery_02.webp" alt="けやき台店の棚。袋詰めのパンが並んでいる"/></div><div class="lw-pr-image-1__item"><img src="https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/concept_01.webp" alt="中央通り店の作業台。生地を伸ばしているところ"/></div><div class="lw-pr-image-1__item"><img src="https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/bake_06.webp" alt="工房直売所。ケーキも土日だけ出している"/></div></div></div>
<!-- /wp:wdl/lw-pr-image-1 -->
<!-- wp:paragraph {"align":"center","style":{"color":{"text":"#4f5b5c"},"typography":{"fontSize":"14px","lineHeight":"1.9"},"spacing":{"margin":{"top":"16px","bottom":"0px"}}}} -->
<p class="has-text-align-center has-text-color" style="color:#4f5b5c;font-size:14px;line-height:1.9;margin-top:16px;margin-bottom:0px">※ 4店それぞれの店内です。看板が小さいので、この景色を目印にお越しください。</p>
<!-- /wp:paragraph -->
<!-- wp:wdl/lw-space-1 {"pcHeight":80,"tbHeight":64,"spHeight":40} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:80px"></div><div class="tb" style="height:64px"></div><div class="sp" style="height:40px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-bg-1 {"backgroundType":"image","imagePc":"","imageSp":"","isFullWidth":true,"maxWidth":1040,"minHeightPc":"min-h-pc-150px","minHeightTb":"min-h-tb-160px","minHeightSp":"min-h-sp-160px","innerPaddingTopPc":80,"innerPaddingBottomPc":80,"innerPaddingLeftPc":40,"innerPaddingRightPc":40,"innerPaddingTopTb":64,"innerPaddingBottomTb":64,"innerPaddingLeftTb":32,"innerPaddingRightTb":32,"innerPaddingTopSp":48,"innerPaddingBottomSp":48,"innerPaddingLeftSp":20,"innerPaddingRightSp":20,"filterTypePc":"solid","filterColorPc":"#eef5f6","opacityPc":1,"filterTypeTb":"solid","filterColorTb":"#eef5f6","opacityTb":1,"filterTypeSp":"solid","filterColorSp":"#eef5f6","opacitySp":1} -->
<div class="wp-block-wdl-lw-bg-1 lw-bg-1 min-h-pc-150px min-h-tb-160px min-h-sp-160px bg_all" style="--lw-bg-color-filter-pc:#eef5f6;--lw-bg-opacity-pc:1;--lw-bg-color-filter-tb:#eef5f6;--lw-bg-opacity-tb:1;--lw-bg-color-filter-sp:#eef5f6;--lw-bg-opacity-sp:1;--lw-bg-position-pc:50% 50%;--lw-bg-position-sp:50% 50%;--lw-bg-wrap-centering-pc:center;--lw-bg-wrap-align-pc:center;--lw-bg-wrap-centering-tb:center;--lw-bg-wrap-align-tb:center;--lw-bg-wrap-centering-sp:center;--lw-bg-wrap-align-sp:center"><div class="lw-bg-1-wrap" style="--lw-bg-padding-top-pc:80px;--lw-bg-padding-bottom-pc:80px;--lw-bg-padding-left-pc:40px;--lw-bg-padding-right-pc:40px;--lw-bg-padding-top-tb:64px;--lw-bg-padding-bottom-tb:64px;--lw-bg-padding-left-tb:32px;--lw-bg-padding-right-tb:32px;--lw-bg-padding-top-sp:48px;--lw-bg-padding-bottom-sp:48px;--lw-bg-padding-left-sp:20px;--lw-bg-padding-right-sp:20px;--lw-bg-max-width:1040px"><!-- wp:heading {"level":3,"style":{"color":{"text":"#123640"},"typography":{"fontSize":"24px","lineHeight":"1.6"},"spacing":{"margin":{"top":"0px","bottom":"16px"}}},"textAlign":"center"} -->
<h3 class="has-text-align-center has-text-color" style="color:#123640;font-size:24px;line-height:1.6;margin-top:0px;margin-bottom:16px">営業時間</h3>
<!-- /wp:heading -->
<!-- wp:wdl/lw-company-2 {"maxWidth":760,"dtBackgroundColor":"#e2ebed","dtTextColor":"#123640","ddTextColor":"#33403f","fontWeightDt":"600","borderColor":"#d5e4e6","spFullDt":true} -->
<div class="wp-block-wdl-lw-company-2 font_size_m" style="border-color:#d5e4e6"><dl class="sp_clm_1" style="border-color:#d5e4e6;max-width:760px;line-height:1.6"><div class="company-profile-item font_size_m dt_width_m" style="border-color:#d5e4e6"><dt style="background-color:#e2ebed;color:#123640;font-weight:600;line-height:1.6" data-lw_font_set="">本店</dt><dd style="color:#33403f;line-height:1.6" data-lw_font_set="">7:00〜18:00（水曜定休）</dd></div><div class="company-profile-item font_size_m dt_width_m" style="border-color:#d5e4e6"><dt style="background-color:#e2ebed;color:#123640;font-weight:600;line-height:1.6" data-lw_font_set="">けやき台店</dt><dd style="color:#33403f;line-height:1.6" data-lw_font_set="">8:00〜19:00（水曜定休）</dd></div><div class="company-profile-item font_size_m dt_width_m" style="border-color:#d5e4e6"><dt style="background-color:#e2ebed;color:#123640;font-weight:600;line-height:1.6" data-lw_font_set="">中央通り店</dt><dd style="color:#33403f;line-height:1.6" data-lw_font_set="">8:00〜18:00（水曜・木曜定休）</dd></div><div class="company-profile-item font_size_m dt_width_m" style="border-color:#d5e4e6"><dt style="background-color:#e2ebed;color:#123640;font-weight:600;line-height:1.6" data-lw_font_set="">工房直売所</dt><dd style="color:#33403f;line-height:1.6" data-lw_font_set="">土日のみ 10:00〜15:00</dd></div></dl></div>
<!-- /wp:wdl/lw-company-2 -->
<!-- wp:paragraph {"align":"center","style":{"color":{"text":"#4f5b5c"},"typography":{"fontSize":"14px","lineHeight":"1.9"},"spacing":{"margin":{"top":"16px","bottom":"0px"}}}} -->
<p class="has-text-align-center has-text-color" style="color:#4f5b5c;font-size:14px;line-height:1.9;margin-top:16px;margin-bottom:0px">※ パンが売り切れ次第、閉店より早く閉めることがあります。</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:wdl/lw-bg-1 -->
<!-- wp:wdl/lw-bg-1 {"backgroundType":"image","imagePc":"","imageSp":"","isFullWidth":true,"maxWidth":1040,"minHeightPc":"min-h-pc-150px","minHeightTb":"min-h-tb-160px","minHeightSp":"min-h-sp-160px","innerPaddingTopPc":80,"innerPaddingBottomPc":80,"innerPaddingLeftPc":40,"innerPaddingRightPc":40,"innerPaddingTopTb":64,"innerPaddingBottomTb":64,"innerPaddingLeftTb":32,"innerPaddingRightTb":32,"innerPaddingTopSp":48,"innerPaddingBottomSp":48,"innerPaddingLeftSp":20,"innerPaddingRightSp":20,"filterTypePc":"solid","filterColorPc":"#123640","opacityPc":1,"filterTypeTb":"solid","filterColorTb":"#123640","opacityTb":1,"filterTypeSp":"solid","filterColorSp":"#123640","opacitySp":1} -->
<div class="wp-block-wdl-lw-bg-1 lw-bg-1 min-h-pc-150px min-h-tb-160px min-h-sp-160px bg_all" style="--lw-bg-color-filter-pc:#123640;--lw-bg-opacity-pc:1;--lw-bg-color-filter-tb:#123640;--lw-bg-opacity-tb:1;--lw-bg-color-filter-sp:#123640;--lw-bg-opacity-sp:1;--lw-bg-position-pc:50% 50%;--lw-bg-position-sp:50% 50%;--lw-bg-wrap-centering-pc:center;--lw-bg-wrap-align-pc:center;--lw-bg-wrap-centering-tb:center;--lw-bg-wrap-align-tb:center;--lw-bg-wrap-centering-sp:center;--lw-bg-wrap-align-sp:center"><div class="lw-bg-1-wrap" style="--lw-bg-padding-top-pc:80px;--lw-bg-padding-bottom-pc:80px;--lw-bg-padding-left-pc:40px;--lw-bg-padding-right-pc:40px;--lw-bg-padding-top-tb:64px;--lw-bg-padding-bottom-tb:64px;--lw-bg-padding-left-tb:32px;--lw-bg-padding-right-tb:32px;--lw-bg-padding-top-sp:48px;--lw-bg-padding-bottom-sp:48px;--lw-bg-padding-left-sp:20px;--lw-bg-padding-right-sp:20px;--lw-bg-max-width:1040px"><!-- wp:heading {"level":3,"style":{"color":{"text":"#ffffff"},"typography":{"fontSize":"26px","lineHeight":"1.6"},"spacing":{"margin":{"top":"0px","bottom":"16px"}}},"textAlign":"center"} -->
<h3 class="has-text-align-center has-text-color" style="color:#ffffff;font-size:26px;line-height:1.6;margin-top:0px;margin-bottom:16px">どの店か迷ったら</h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"style":{"color":{"text":"#d9eaed"},"typography":{"fontSize":"16px","lineHeight":"2"}},"align":"center"} -->
<p class="has-text-align-center has-text-color" style="color:#d9eaed;font-size:16px;line-height:2">お探しのパンがどの店にあるか、お電話でお答えします。取り置きもできます。</p>
<!-- /wp:paragraph -->
<!-- wp:wdl/lw-space-1 {"pcHeight":24,"tbHeight":20,"spHeight":16} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:24px"></div><div class="tb" style="height:20px"></div><div class="sp" style="height:16px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-pr-button-4 {"textMain":"000-000-0000","textSub":"本店 受付時間 7:00〜18:00（水曜定休）","btnUrl":"tel:0000000000","btnAlign":"center","bgColor":"#2e6f7d","bgColorHover":"#1f5461","textColorMain":"#ffffff","borderWidth":0,"borderRadius":6} -->
<div class="wp-block-wdl-lw-pr-button-4 lw-pr-button-4"><div class="wrap_btn center"><a href="tel:0000000000" class="lw_btn_a " style="--hover-bg:#1f5461;--transition-duration:0.3s;--max-width-sp:480px;--shake-interval:3s;--font-size-main:28px;--font-size-main-sp:18px;--font-size-sub:14px;--letter-spacing:0.05em;max-width:580px;padding:1.2em 1.5em;background:#2e6f7d;border:0px solid #000000;border-radius:6px;box-shadow:0px 0px 6px rgba(0, 0, 0, 0.2)"><span class="text_main" style="color:#ffffff;font-weight:500;font-size:28px;letter-spacing:0.05em" data-lw_font_set=""><span class="icon" style="fill:#ffffff;width:32px;margin-right:8px;margin-left:-8px"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M164.9 24.6c-7.7-18.6-28-28.5-47.4-23.2l-88 24C12.1 30.2 0 46 0 64C0 311.4 200.6 512 448 512c18 0 33.8-12.1 38.6-29.5l24-88c5.3-19.4-4.6-39.7-23.2-47.4l-96-40c-16.3-6.8-35.2-2.1-46.3 11.6L304.7 368C234.3 334.7 177.3 277.7 144 207.3L193.3 167c13.7-11.2 18.4-30 11.6-46.3l-40-96z"/></svg></span>000-000-0000</span><span class="text_sub" style="color:#ffffff;font-weight:500;font-size:14px" data-lw_font_set="">本店 受付時間 7:00〜18:00（水曜定休）</span></a></div></div>
<!-- /wp:wdl/lw-pr-button-4 --></div></div>
<!-- /wp:wdl/lw-bg-1 -->