<!-- wp:wdl/lw-pr-fv-15 {"mainTitle":"アクセス","description":"西口から歩いて5分です。","backgroundType":"image","imageUrlPc":"https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/salon_01.webp","imageUrlSp":"","imageAlt":"店内の様子","bgColor":"#2b2724","filterColor":"#1a1614","filterOpacity":0.15,"headingLevel":1,"titleColor":"#ffffff","titleFontWeight":"700","descriptionColor":"#f0e8dc","descriptionFontWeight":"400","showButton":false} -->
<div class="wp-block-wdl-lw-pr-fv-15 lw-pr-fv-15" style="--fv-color-bg-all:#2b2724;--color-image-filter:#1a1614;--fv-image-filter-opacity:0.15;--lw-stroke-width:0px;--lw-stroke-width-sp:0px;--lw-stroke-color:rgba(255, 255, 255, 0.6);--color-fv-ttl-main:#ffffff;--fv-ttl-main-font-weight:700;--color-fv-description-main:#f0e8dc;--fv-description-main-font-weight:400;--color-cta-bg:#E95555;--color-cta-text:#ffffff;--cta-border-radius:3px;--cta-bd-width:0px;--cta-bd-color:#ffffff"><div class="fv_inner"><h1 class="ttl" data-lw_font_set="">アクセス</h1><p class="description" data-lw_font_set="">西口から歩いて5分です。</p></div><picture class="bg_image"><source srcSet="" media="(max-width: 800px)"/><source srcSet="https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/salon_01.webp" media="(min-width: 801px)"/><img src="https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/salon_01.webp" alt="店内の様子"/></picture></div>
<!-- /wp:wdl/lw-pr-fv-15 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":80,"tbHeight":64,"spHeight":40} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:80px"></div><div class="tb" style="height:64px"></div><div class="sp" style="height:40px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-pr-custom-title-13 {"mainTitle":"行き方は3つあります","subTitle":"ACCESS","headingLevel":2,"colorMain":"#8a5a2b","colorMainText":"#ffffff","colorSubText":"#f3e2cd"} -->
<div class="wp-block-wdl-lw-pr-custom-title-13 lw-pr-custom-title-13" style="--color-main:#8a5a2b;--color-main-text:#ffffff;--color-sub-text:#f3e2cd"><h2 class="ttl"><span class="sub">ACCESS</span><span class="main">行き方は3つあります</span><div class="left"></div><div class="right"></div></h2></div>
<!-- /wp:wdl/lw-pr-custom-title-13 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":16,"tbHeight":16,"spHeight":12} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:16px"></div><div class="tb" style="height:16px"></div><div class="sp" style="height:12px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:paragraph {"align":"center","style":{"color":{"text":"#3a352f"},"typography":{"fontSize":"16px","lineHeight":"2"},"spacing":{"margin":{"top":"28px","bottom":"24px"}}}} -->
<p class="has-text-align-center has-text-color" style="color:#3a352f;font-size:16px;line-height:2;margin-top:28px;margin-bottom:24px">電車・バス・お車のどれでも来られます。<span class="lw-br on_500px"></span>土日は近くの駐車場が混み合うので、電車が確実です。</p>
<!-- /wp:paragraph -->
<!-- wp:wdl/lw-pr-table-2 {"dtFixedPc":true,"dtWidthPc":160,"dtWidthSp":150,"defaultSpClm1":true,"dlBorderColor":"#e2d9cc","rowBorderColor":"#e2d9cc","dtBorderColor":"#e2d9cc","dtBgColor":"#f7f2ea","dtTextColor":"#2b2724","ddTextColor":"#3a352f","dtFontWeight":"600","fontSizePc":17,"fontSizeSp":15,"cellPaddingPc":16,"rows":[{"dtText":"電車で","ddText":"けやき台駅 \u003cb\u003e西口から徒歩5分\u003c/b\u003e。各駅停車のみ停まります。急行は1つ手前の中央駅で乗り換えてください。","pcClm1":null,"spClm1":null,"bgColor":"","textColor":""},{"dtText":"バスで","ddText":"中央駅から \u003cb\u003e「けやき台三丁目」バス停\u003c/b\u003e 下車すぐ。1時間に3本ほど出ています。所要12分。","pcClm1":null,"spClm1":null,"bgColor":"","textColor":""},{"dtText":"お車で","ddText":"提携駐車場をご用意しています。店の裏手のコインパーキング2台分。満車のときはお電話ください。","pcClm1":null,"spClm1":null,"bgColor":"","textColor":""}]} -->
<div class="wp-block-wdl-lw-pr-table-2 lw-pr-table-2" style="--table-2-dl-width-pc:100%;--table-2-dl-width-sp:100%;--table-2-grid-columns-pc:160px calc(100% - 160px);--table-2-grid-columns-sp:1fr 1fr;--table-2-dl-border-color:#e2d9cc;--table-2-dl-border-style:solid;--table-2-dl-border-width:1px;--table-2-dl-border-individual:0;--table-2-dl-border-top-color:#e2d9cc;--table-2-dl-border-top-style:solid;--table-2-dl-border-top-width:1px;--table-2-dl-border-bottom-color:#e2d9cc;--table-2-dl-border-bottom-style:solid;--table-2-dl-border-bottom-width:1px;--table-2-dl-border-left-color:#e2d9cc;--table-2-dl-border-left-style:solid;--table-2-dl-border-left-width:1px;--table-2-dl-border-right-color:#e2d9cc;--table-2-dl-border-right-style:solid;--table-2-dl-border-right-width:1px;--table-2-row-border-color:#e2d9cc;--table-2-row-border-style:solid;--table-2-row-border-width:1px;--table-2-dt-border-color:#e2d9cc;--table-2-dt-border-style:solid;--table-2-dt-border-width:1px;--table-2-dt-bg-color:#f7f2ea;--table-2-cell-padding-pc:16px;--table-2-cell-padding-sp:16px;--table-2-font-size-pc:17px;--table-2-font-size-sp:15px;--table-2-dt-align-pc:left;--table-2-dt-align-sp:left;--table-2-dd-align-pc:left;--table-2-dd-align-sp:left;--table-2-dt-text-color:#2b2724;--table-2-dd-text-color:#3a352f"><dl class="table-2__dl"><div class="table-2__row sp_clm_1"><dt class="table-2__dt"><p data-lw_font_set="" style="font-weight:600">電車で</p></dt><dd class="table-2__dd"><p data-lw_font_set="">けやき台駅 <b>西口から徒歩5分</b>。各駅停車のみ停まります。急行は1つ手前の中央駅で乗り換えてください。</p></dd></div><div class="table-2__row sp_clm_1"><dt class="table-2__dt"><p data-lw_font_set="" style="font-weight:600">バスで</p></dt><dd class="table-2__dd"><p data-lw_font_set="">中央駅から <b>「けやき台三丁目」バス停</b> 下車すぐ。1時間に3本ほど出ています。所要12分。</p></dd></div><div class="table-2__row sp_clm_1"><dt class="table-2__dt"><p data-lw_font_set="" style="font-weight:600">お車で</p></dt><dd class="table-2__dd"><p data-lw_font_set="">提携駐車場をご用意しています。店の裏手のコインパーキング2台分。満車のときはお電話ください。</p></dd></div></dl></div>
<!-- /wp:wdl/lw-pr-table-2 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":80,"tbHeight":64,"spHeight":40} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:80px"></div><div class="tb" style="height:64px"></div><div class="sp" style="height:40px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-pr-custom-title-13 {"mainTitle":"駅からの道順","subTitle":"ROUTE","headingLevel":2,"colorMain":"#8a5a2b","colorMainText":"#ffffff","colorSubText":"#f3e2cd"} -->
<div class="wp-block-wdl-lw-pr-custom-title-13 lw-pr-custom-title-13" style="--color-main:#8a5a2b;--color-main-text:#ffffff;--color-sub-text:#f3e2cd"><h2 class="ttl"><span class="sub">ROUTE</span><span class="main">駅からの道順</span><div class="left"></div><div class="right"></div></h2></div>
<!-- /wp:wdl/lw-pr-custom-title-13 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":16,"tbHeight":16,"spHeight":12} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:16px"></div><div class="tb" style="height:16px"></div><div class="sp" style="height:12px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:paragraph {"align":"center","style":{"color":{"text":"#3a352f"},"typography":{"fontSize":"16px","lineHeight":"2"},"spacing":{"margin":{"top":"28px","bottom":"24px"}}}} -->
<p class="has-text-align-center has-text-color" style="color:#3a352f;font-size:16px;line-height:2;margin-top:28px;margin-bottom:24px">はじめての方は、この4つの目印だけ覚えてきてください。</p>
<!-- /wp:paragraph -->
<!-- wp:wdl/lw-pr-step-7 {"circleBgColor":"#8a5a2b","cardBgColor":"#ffffff","borderColor":"#e2d9cc","ulMaxWidth":1080,"columnCountPc":4,"columnCountSp":1,"fontSizeClass":"font_size_m","fontWeightNo":"700","colorNo":"#ffffff","titleTag":"h3","fontWeightH3":"600","colorH3":"#2b2724","colorP":"#3a352f"} -->
<div class="wp-block-wdl-lw-pr-step-7 lw-pr-step-7 font_size_m"><ul class="lw-pr-step-7__inner" style="max-width:1080px;--column-pc:4;--column-sp:1"><li class="lw-pr-step-7__li" style="background-color:#ffffff;border-color:#e2d9cc"><div class="lw-pr-step-7__li_no" data-lw_font_set="Murecho" style="font-weight:700;background-color:#8a5a2b;color:#ffffff">1</div><div class="lw-pr-step-7__li_in"><h3 class="lw-pr-step-7__li_title ttl" data-lw_font_set="" style="font-weight:600;color:#2b2724">西口を出る</h3><p class="lw-pr-step-7__li_text" data-lw_font_set="" style="font-weight:400;color:#3a352f">改札はひとつだけです。出たらそのまま正面の階段を降ります。東口に出ると反対側なのでご注意ください。</p></div></li><li class="lw-pr-step-7__li" style="background-color:#ffffff;border-color:#e2d9cc"><div class="lw-pr-step-7__li_no" data-lw_font_set="Murecho" style="font-weight:700;background-color:#8a5a2b;color:#ffffff">2</div><div class="lw-pr-step-7__li_in"><h3 class="lw-pr-step-7__li_title ttl" data-lw_font_set="" style="font-weight:600;color:#2b2724">交差点を左へ</h3><p class="lw-pr-step-7__li_text" data-lw_font_set="" style="font-weight:400;color:#3a352f">階段を降りて30mほど直進すると、コンビニのある交差点に出ます。そこを左に曲がります。</p></div></li><li class="lw-pr-step-7__li" style="background-color:#ffffff;border-color:#e2d9cc"><div class="lw-pr-step-7__li_no" data-lw_font_set="Murecho" style="font-weight:700;background-color:#8a5a2b;color:#ffffff">3</div><div class="lw-pr-step-7__li_in"><h3 class="lw-pr-step-7__li_title ttl" data-lw_font_set="" style="font-weight:600;color:#2b2724">花屋を過ぎる</h3><p class="lw-pr-step-7__li_text" data-lw_font_set="" style="font-weight:400;color:#3a352f">ゆるい上り坂を2分ほど。右手に赤いひさしの花屋さんが見えたら、道は合っています。</p></div></li><li class="lw-pr-step-7__li" style="background-color:#ffffff;border-color:#e2d9cc"><div class="lw-pr-step-7__li_no" data-lw_font_set="Murecho" style="font-weight:700;background-color:#8a5a2b;color:#ffffff">4</div><div class="lw-pr-step-7__li_in"><h3 class="lw-pr-step-7__li_title ttl" data-lw_font_set="" style="font-weight:600;color:#2b2724">白いビルの2階</h3><p class="lw-pr-step-7__li_text" data-lw_font_set="" style="font-weight:400;color:#3a352f">花屋から50m先、白い3階建ての建物です。外階段を上がった2階が当店です。</p></div></li></ul></div>
<!-- /wp:wdl/lw-pr-step-7 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":80,"tbHeight":64,"spHeight":40} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:80px"></div><div class="tb" style="height:64px"></div><div class="sp" style="height:40px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-bg-1 {"backgroundType":"image","imagePc":"","imageSp":"","isFullWidth":true,"maxWidth":1040,"minHeightPc":"min-h-pc-150px","minHeightTb":"min-h-tb-160px","minHeightSp":"min-h-sp-160px","innerPaddingTopPc":80,"innerPaddingBottomPc":80,"innerPaddingLeftPc":40,"innerPaddingRightPc":40,"innerPaddingTopTb":64,"innerPaddingBottomTb":64,"innerPaddingLeftTb":32,"innerPaddingRightTb":32,"innerPaddingTopSp":48,"innerPaddingBottomSp":48,"innerPaddingLeftSp":20,"innerPaddingRightSp":20,"filterTypePc":"solid","filterColorPc":"#f7f2ea","opacityPc":1,"filterTypeTb":"solid","filterColorTb":"#f7f2ea","opacityTb":1,"filterTypeSp":"solid","filterColorSp":"#f7f2ea","opacitySp":1} -->
<div class="wp-block-wdl-lw-bg-1 lw-bg-1 min-h-pc-150px min-h-tb-160px min-h-sp-160px bg_all" style="--lw-bg-color-filter-pc:#f7f2ea;--lw-bg-opacity-pc:1;--lw-bg-color-filter-tb:#f7f2ea;--lw-bg-opacity-tb:1;--lw-bg-color-filter-sp:#f7f2ea;--lw-bg-opacity-sp:1;--lw-bg-position-pc:50% 50%;--lw-bg-position-sp:50% 50%;--lw-bg-wrap-centering-pc:center;--lw-bg-wrap-align-pc:center;--lw-bg-wrap-centering-tb:center;--lw-bg-wrap-align-tb:center;--lw-bg-wrap-centering-sp:center;--lw-bg-wrap-align-sp:center"><div class="lw-bg-1-wrap" style="--lw-bg-padding-top-pc:80px;--lw-bg-padding-bottom-pc:80px;--lw-bg-padding-left-pc:40px;--lw-bg-padding-right-pc:40px;--lw-bg-padding-top-tb:64px;--lw-bg-padding-bottom-tb:64px;--lw-bg-padding-left-tb:32px;--lw-bg-padding-right-tb:32px;--lw-bg-padding-top-sp:48px;--lw-bg-padding-bottom-sp:48px;--lw-bg-padding-left-sp:20px;--lw-bg-padding-right-sp:20px;--lw-bg-max-width:1040px"><!-- wp:heading {"level":3,"style":{"color":{"text":"#2b2724"},"typography":{"fontSize":"24px","lineHeight":"1.6"},"spacing":{"margin":{"top":"0px","bottom":"16px"}}},"textAlign":"center"} -->
<h3 class="has-text-align-center has-text-color" style="color:#2b2724;font-size:24px;line-height:1.6;margin-top:0px;margin-bottom:16px">店舗情報</h3>
<!-- /wp:heading -->
<!-- wp:wdl/lw-company-2 {"maxWidth":820,"dtBackgroundColor":"#efe8e1","dtTextColor":"#2b2724","ddTextColor":"#3a352f","fontWeightDt":"600","borderColor":"#e2d9cc","spFullDt":true} -->
<div class="wp-block-wdl-lw-company-2 font_size_m" style="border-color:#e2d9cc"><dl class="sp_clm_1" style="border-color:#e2d9cc;max-width:820px;line-height:1.6"><div class="company-profile-item font_size_m dt_width_m" style="border-color:#e2d9cc"><dt style="background-color:#efe8e1;color:#2b2724;font-weight:600;line-height:1.6" data-lw_font_set="">所在地</dt><dd style="color:#3a352f;line-height:1.6" data-lw_font_set="">〒000-0000　県名市けやき台3-1-2　けやきビル2階</dd></div><div class="company-profile-item font_size_m dt_width_m" style="border-color:#e2d9cc"><dt style="background-color:#efe8e1;color:#2b2724;font-weight:600;line-height:1.6" data-lw_font_set="">電話</dt><dd style="color:#3a352f;line-height:1.6" data-lw_font_set="">000-000-0000</dd></div><div class="company-profile-item font_size_m dt_width_m" style="border-color:#e2d9cc"><dt style="background-color:#efe8e1;color:#2b2724;font-weight:600;line-height:1.6" data-lw_font_set="">営業時間</dt><dd style="color:#3a352f;line-height:1.6" data-lw_font_set="">10:00〜19:00（最終受付 18:00）</dd></div><div class="company-profile-item font_size_m dt_width_m" style="border-color:#e2d9cc"><dt style="background-color:#efe8e1;color:#2b2724;font-weight:600;line-height:1.6" data-lw_font_set="">定休日</dt><dd style="color:#3a352f;line-height:1.6" data-lw_font_set="">毎週火曜・第3月曜</dd></div></dl></div>
<!-- /wp:wdl/lw-company-2 -->
<!-- wp:paragraph {"align":"center","style":{"color":{"text":"#5f584f"},"typography":{"fontSize":"14px","lineHeight":"1.9"},"spacing":{"margin":{"top":"16px","bottom":"0px"}}}} -->
<p class="has-text-align-center has-text-color" style="color:#5f584f;font-size:14px;line-height:1.9;margin-top:16px;margin-bottom:0px">※ 年末年始は営業時間が変わります。最新の予定はお知らせをご覧ください。</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:wdl/lw-bg-1 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":80,"tbHeight":64,"spHeight":40} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:80px"></div><div class="tb" style="height:64px"></div><div class="sp" style="height:40px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-pr-custom-title-13 {"mainTitle":"よくあるご質問","subTitle":"Q&A","headingLevel":2,"colorMain":"#8a5a2b","colorMainText":"#ffffff","colorSubText":"#f3e2cd"} -->
<div class="wp-block-wdl-lw-pr-custom-title-13 lw-pr-custom-title-13" style="--color-main:#8a5a2b;--color-main-text:#ffffff;--color-sub-text:#f3e2cd"><h2 class="ttl"><span class="sub">Q&A</span><span class="main">よくあるご質問</span><div class="left"></div><div class="right"></div></h2></div>
<!-- /wp:wdl/lw-pr-custom-title-13 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":16,"tbHeight":16,"spHeight":12} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:16px"></div><div class="tb" style="height:16px"></div><div class="sp" style="height:12px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-pr-qa-3 {"maxWidth":900,"qLabelColor":"#2b2724","aLabelColor":"#5f584f","lineColor":"#e2d9cc"} -->
<div class="wp-block-wdl-lw-pr-qa-3 lw-pr-qa-3" style="--qa3-max-w:900px;--qa3-gap:24px;--qa3-label-w:32px;--qa3-q-color:#2b2724;--qa3-a-color:#5f584f;--qa3-line:#e2d9cc;--qa3-label-size-pc:18px;--qa3-label-size-sp:16px;--qa3-q-size-pc:17px;--qa3-q-size-sp:15px;--qa3-a-size-pc:15px;--qa3-a-size-sp:14px"><dl class="qa-3__item"><dt><span class="label" data-lw_font_set="Roboto">Q</span><p class="qa-3__q_text">駅のどちらの出口ですか</p></dt><dd><span class="label" data-lw_font_set="Roboto">A</span><p class="qa-3__a_text">西口です。改札はひとつしかありませんので、出たら正面の階段を降りて左へ進んでください。</p></dd></dl><dl class="qa-3__item"><dt><span class="label" data-lw_font_set="Roboto">Q</span><p class="qa-3__q_text">車で行きたいのですが、駐車場はありますか</p></dt><dd><span class="label" data-lw_font_set="Roboto">A</span><p class="qa-3__a_text">店の裏手のコインパーキングに提携枠が2台分あります。ご利用の方には駐車券をお渡しします。満車のときは近隣の駐車場をご案内しますので、お電話ください。</p></dd></dl><dl class="qa-3__item"><dt><span class="label" data-lw_font_set="Roboto">Q</span><p class="qa-3__q_text">ベビーカーでも入れますか</p></dt><dd><span class="label" data-lw_font_set="Roboto">A</span><p class="qa-3__a_text">外階段を上がった2階のため、ベビーカーは1階の軒下にお停めいただいています。お声がけいただければお運びします。</p></dd></dl><dl class="qa-3__item"><dt><span class="label" data-lw_font_set="Roboto">Q</span><p class="qa-3__q_text">雨の日でも同じ道順ですか</p></dt><dd><span class="label" data-lw_font_set="Roboto">A</span><p class="qa-3__a_text">同じです。西口から花屋までは屋根がありませんので、傘をお持ちください。</p></dd></dl></div>
<!-- /wp:wdl/lw-pr-qa-3 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":80,"tbHeight":64,"spHeight":40} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:80px"></div><div class="tb" style="height:64px"></div><div class="sp" style="height:40px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-bg-1 {"backgroundType":"image","imagePc":"","imageSp":"","isFullWidth":true,"maxWidth":1040,"minHeightPc":"min-h-pc-150px","minHeightTb":"min-h-tb-160px","minHeightSp":"min-h-sp-160px","innerPaddingTopPc":80,"innerPaddingBottomPc":80,"innerPaddingLeftPc":40,"innerPaddingRightPc":40,"innerPaddingTopTb":64,"innerPaddingBottomTb":64,"innerPaddingLeftTb":32,"innerPaddingRightTb":32,"innerPaddingTopSp":48,"innerPaddingBottomSp":48,"innerPaddingLeftSp":20,"innerPaddingRightSp":20,"filterTypePc":"solid","filterColorPc":"#2b2724","opacityPc":1,"filterTypeTb":"solid","filterColorTb":"#2b2724","opacityTb":1,"filterTypeSp":"solid","filterColorSp":"#2b2724","opacitySp":1} -->
<div class="wp-block-wdl-lw-bg-1 lw-bg-1 min-h-pc-150px min-h-tb-160px min-h-sp-160px bg_all" style="--lw-bg-color-filter-pc:#2b2724;--lw-bg-opacity-pc:1;--lw-bg-color-filter-tb:#2b2724;--lw-bg-opacity-tb:1;--lw-bg-color-filter-sp:#2b2724;--lw-bg-opacity-sp:1;--lw-bg-position-pc:50% 50%;--lw-bg-position-sp:50% 50%;--lw-bg-wrap-centering-pc:center;--lw-bg-wrap-align-pc:center;--lw-bg-wrap-centering-tb:center;--lw-bg-wrap-align-tb:center;--lw-bg-wrap-centering-sp:center;--lw-bg-wrap-align-sp:center"><div class="lw-bg-1-wrap" style="--lw-bg-padding-top-pc:80px;--lw-bg-padding-bottom-pc:80px;--lw-bg-padding-left-pc:40px;--lw-bg-padding-right-pc:40px;--lw-bg-padding-top-tb:64px;--lw-bg-padding-bottom-tb:64px;--lw-bg-padding-left-tb:32px;--lw-bg-padding-right-tb:32px;--lw-bg-padding-top-sp:48px;--lw-bg-padding-bottom-sp:48px;--lw-bg-padding-left-sp:20px;--lw-bg-padding-right-sp:20px;--lw-bg-max-width:1040px"><!-- wp:heading {"level":3,"style":{"color":{"text":"#ffffff"},"typography":{"fontSize":"26px","lineHeight":"1.6"},"spacing":{"margin":{"top":"0px","bottom":"16px"}}},"textAlign":"center"} -->
<h3 class="has-text-align-center has-text-color" style="color:#ffffff;font-size:26px;line-height:1.6;margin-top:0px;margin-bottom:16px">道に迷われたら、遠慮なくお電話ください</h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"style":{"color":{"text":"#efe6d9"},"typography":{"fontSize":"16px","lineHeight":"2"}},"align":"center"} -->
<p class="has-text-align-center has-text-color" style="color:#efe6d9;font-size:16px;line-height:2">その場所からの行き方をご案内します。10分ほど遅れても、次のご予約に差し支えなければそのままお受けします。</p>
<!-- /wp:paragraph -->
<!-- wp:wdl/lw-space-1 {"pcHeight":24,"tbHeight":20,"spHeight":16} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:24px"></div><div class="tb" style="height:20px"></div><div class="sp" style="height:16px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-pr-button-4 {"textMain":"000-000-0000","textSub":"受付時間 10:00〜18:30（火曜定休）","btnUrl":"tel:0000000000","btnAlign":"center","bgColor":"#8a5a2b","bgColorHover":"#6d4520","textColorMain":"#ffffff","borderWidth":0,"borderRadius":6} -->
<div class="wp-block-wdl-lw-pr-button-4 lw-pr-button-4"><div class="wrap_btn center"><a href="tel:0000000000" class="lw_btn_a " style="--hover-bg:#6d4520;--transition-duration:0.3s;--max-width-sp:480px;--shake-interval:3s;--font-size-main:28px;--font-size-main-sp:18px;--font-size-sub:14px;--letter-spacing:0.05em;max-width:580px;padding:1.2em 1.5em;background:#8a5a2b;border:0px solid #000000;border-radius:6px;box-shadow:0px 0px 6px rgba(0, 0, 0, 0.2)"><span class="text_main" style="color:#ffffff;font-weight:500;font-size:28px;letter-spacing:0.05em" data-lw_font_set=""><span class="icon" style="fill:#ffffff;width:32px;margin-right:8px;margin-left:-8px"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M164.9 24.6c-7.7-18.6-28-28.5-47.4-23.2l-88 24C12.1 30.2 0 46 0 64C0 311.4 200.6 512 448 512c18 0 33.8-12.1 38.6-29.5l24-88c5.3-19.4-4.6-39.7-23.2-47.4l-96-40c-16.3-6.8-35.2-2.1-46.3 11.6L304.7 368C234.3 334.7 177.3 277.7 144 207.3L193.3 167c13.7-11.2 18.4-30 11.6-46.3l-40-96z"/></svg></span>000-000-0000</span><span class="text_sub" style="color:#ffffff;font-weight:500;font-size:14px" data-lw_font_set="">受付時間 10:00〜18:30（火曜定休）</span></a></div></div>
<!-- /wp:wdl/lw-pr-button-4 --></div></div>
<!-- /wp:wdl/lw-bg-1 -->