<!-- wp:wdl/fv-1 {"mainTitle":"会社について","subTitle":"小さな工場が、55年つづいた理由","description":"大きくはなりませんでしたが、取引先はほとんど変わっていません。","buttonText":"沿革を見る","buttonUrl":"#history","buttonLinkType":"url","buttonBackgroundColor":"#ffffff","buttonTextColor":"#3a1c20","buttonBorderColor":"#ffffff","buttonBackgroundColorOpacity":100,"buttonBorderWidth":0,"buttonBorderRadius":4,"backgroundImage":"https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/atelier_01.webp","backgroundImageSp":"","filterBackgroundColor":"#2a1416","filterOpacity":0.55,"minHeightPc":"min-h-pc-480px","minHeightTb":"min-h-tb-400px","minHeightSp":"min-h-sp-360px"} -->
<div class="wp-block-wdl-fv-1 fv-1 min-h-pc-480px min-h-tb-400px min-h-sp-360px"><h1 class="ttl"><span class="main">会社について</span><span class="sub">小さな工場が、55年つづいた理由</span></h1><p>大きくはなりませんでしたが、取引先はほとんど変わっていません。</p><a href="#history" class="button" style="color:#3a1c20;border-color:#ffffff;border-width:0px;border-radius:4px;border-style:solid"><span>沿革を見る</span><div class="btn_bg" style="background-color:#ffffff;opacity:1"></div></a><div class="filter" style="background-color:#2a1416;opacity:0.55"></div><picture class="bg_image"><source srcSet="" media="(max-width: 800px)"/><source srcSet="https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/atelier_01.webp" media="(min-width: 801px)"/><img src="https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/atelier_01.webp" alt="背景画像" loading="eager" fetchpriority="high"/></picture></div>
<!-- /wp:wdl/fv-1 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":80,"tbHeight":64,"spHeight":40} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:80px"></div><div class="tb" style="height:64px"></div><div class="sp" style="height:40px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-pr-custom-title-11 {"mainTitle":"3つの節目","subTitle":"OUR HISTORY","headingLevel":2,"colorMain":"#8c2f39","colorMainText":"#ffffff","colorSubText":"#f0d6d9","borderRadius":4} -->
<div class="wp-block-wdl-lw-pr-custom-title-11 lw-pr-custom-title-11" style="--color-main:#8c2f39;--color-main-text:#ffffff;--color-sub-text:#f0d6d9;width:100%;margin:1em auto" id="history"><h2 class="ttl" style="border-radius:4px"><span class="sub">OUR HISTORY</span><span class="main">3つの節目</span></h2></div>
<!-- /wp:wdl/lw-pr-custom-title-11 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":16,"tbHeight":16,"spHeight":12} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:16px"></div><div class="tb" style="height:16px"></div><div class="sp" style="height:12px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:paragraph {"align":"center","style":{"color":{"text":"#3d3436"},"typography":{"fontSize":"16px","lineHeight":"2"},"spacing":{"margin":{"top":"28px","bottom":"24px"}}}} -->
<p class="has-text-align-center has-text-color" style="color:#3d3436;font-size:16px;line-height:2;margin-top:28px;margin-bottom:24px">55年のあいだに、大きく変わったことが3回ありました。<span class="lw-br on_500px"></span>年表よりも、そのときに何を決めたかを書いておきます。</p>
<!-- /wp:paragraph -->
<!-- wp:wdl/lw-space-1 {"pcHeight":24,"tbHeight":20,"spHeight":16} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:24px"></div><div class="tb" style="height:20px"></div><div class="sp" style="height:16px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-pr-content-8 {"imageUrl":"https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/atelier_02.webp","imageAlt":"創業当時の工房","maxWidth":1040,"bgColor":"#ffffff","borderWidth":2,"borderColor":"#e7d6d8","bdrPc":10,"bdrSp":10,"minHeight":340} -->
<div class="wp-block-wdl-lw-pr-content-8 lw-pr-content-8" style="--content-8-max-w:1040px;--content-8-bdr-pc:10px;--content-8-bdr-sp:10px;--content-8-min-h:340px;background:#ffffff;border:2px solid #e7d6d8"><div class="image"><img loading="lazy" src="https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/atelier_02.webp" alt="創業当時の工房"/></div><div class="content_in"><!-- wp:paragraph {"style":{"typography":{"fontSize":"15px","lineHeight":"1.6"},"spacing":{"margin":{"top":"0px","bottom":"6px"}}}} -->
<p style="font-size:15px;line-height:1.6;margin-top:0px;margin-bottom:6px"><strong style="color:#8c2f39;font-size:15px;letter-spacing:.08em">1971年</strong></p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":3,"style":{"color":{"text":"#3a1c20"},"typography":{"fontSize":"22px","lineHeight":"1.6"},"spacing":{"margin":{"top":"0px","bottom":"16px"}}},"textAlign":"left"} -->
<h3 class="has-text-align-left has-text-color" style="color:#3a1c20;font-size:22px;line-height:1.6;margin-top:0px;margin-bottom:16px">旋盤2台から始めました</h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"style":{"color":{"text":"#3d3436"},"typography":{"fontSize":"16px","lineHeight":"1.9"}}} -->
<p class="has-text-color" style="color:#3d3436;font-size:16px;line-height:1.9">町工場の一角を借りて、創業者ひとりで始めました。「断らない」を通した人で、採算の合わない仕事も引き受けては、夜中まで削っていたそうです。そのときの取引先が、いまも3社残っています。</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:wdl/lw-pr-content-8 -->
<!-- wp:wdl/lw-pr-content-8 {"imageUrl":"https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/atelier_03.webp","imageAlt":"工場の中","maxWidth":1040,"bgColor":"#ffffff","borderWidth":2,"borderColor":"#e7d6d8","bdrPc":10,"bdrSp":10,"minHeight":340} -->
<div class="wp-block-wdl-lw-pr-content-8 lw-pr-content-8" style="--content-8-max-w:1040px;--content-8-bdr-pc:10px;--content-8-bdr-sp:10px;--content-8-min-h:340px;background:#ffffff;border:2px solid #e7d6d8"><div class="image"><img loading="lazy" src="https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/atelier_03.webp" alt="工場の中"/></div><div class="content_in"><!-- wp:paragraph {"style":{"typography":{"fontSize":"15px","lineHeight":"1.6"},"spacing":{"margin":{"top":"0px","bottom":"6px"}}}} -->
<p style="font-size:15px;line-height:1.6;margin-top:0px;margin-bottom:6px"><strong style="color:#8c2f39;font-size:15px;letter-spacing:.08em">1998年</strong></p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":3,"style":{"color":{"text":"#3a1c20"},"typography":{"fontSize":"22px","lineHeight":"1.6"},"spacing":{"margin":{"top":"0px","bottom":"16px"}}},"textAlign":"left"} -->
<h3 class="has-text-align-left has-text-color" style="color:#3a1c20;font-size:22px;line-height:1.6;margin-top:0px;margin-bottom:16px">いちばん苦しかった年</h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"style":{"color":{"text":"#3d3436"},"typography":{"fontSize":"16px","lineHeight":"1.9"}}} -->
<p class="has-text-color" style="color:#3d3436;font-size:16px;line-height:1.9">売上の6割を占めていた1社との取引が終わりました。人を減らさずに済ませるため、それまで受けていなかった「1個ずつの試作」を引き受けることにしました。手間はかかりますが、いまの柱はこのときに生まれたものです。</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:wdl/lw-pr-content-8 -->
<!-- wp:wdl/lw-pr-content-8 {"imageUrl":"https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/concept_01.webp","imageAlt":"若い職人が働く工場","maxWidth":1040,"bgColor":"#ffffff","borderWidth":2,"borderColor":"#e7d6d8","bdrPc":10,"bdrSp":10,"minHeight":340} -->
<div class="wp-block-wdl-lw-pr-content-8 lw-pr-content-8" style="--content-8-max-w:1040px;--content-8-bdr-pc:10px;--content-8-bdr-sp:10px;--content-8-min-h:340px;background:#ffffff;border:2px solid #e7d6d8"><div class="image"><img loading="lazy" src="https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/concept_01.webp" alt="若い職人が働く工場"/></div><div class="content_in"><!-- wp:paragraph {"style":{"typography":{"fontSize":"15px","lineHeight":"1.6"},"spacing":{"margin":{"top":"0px","bottom":"6px"}}}} -->
<p style="font-size:15px;line-height:1.6;margin-top:0px;margin-bottom:6px"><strong style="color:#8c2f39;font-size:15px;letter-spacing:.08em">2019年</strong></p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":3,"style":{"color":{"text":"#3a1c20"},"typography":{"fontSize":"22px","lineHeight":"1.6"},"spacing":{"margin":{"top":"0px","bottom":"16px"}}},"textAlign":"left"} -->
<h3 class="has-text-align-left has-text-color" style="color:#3a1c20;font-size:22px;line-height:1.6;margin-top:0px;margin-bottom:16px">若い人が入るようになった</h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"style":{"color":{"text":"#3d3436"},"typography":{"fontSize":"16px","lineHeight":"1.9"}}} -->
<p class="has-text-color" style="color:#3d3436;font-size:16px;line-height:1.9">図面のやり取りをすべてデータに変え、土曜を休みにしました。以来7年で6人が入り、辞めた人はいません。設備よりも先に、ここを直すべきだったと思っています。</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:wdl/lw-pr-content-8 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":80,"tbHeight":64,"spHeight":40} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:80px"></div><div class="tb" style="height:64px"></div><div class="sp" style="height:40px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-pr-custom-title-11 {"mainTitle":"変えていないこと","subTitle":"OUR RULES","headingLevel":2,"colorMain":"#8c2f39","colorMainText":"#ffffff","colorSubText":"#f0d6d9","borderRadius":4} -->
<div class="wp-block-wdl-lw-pr-custom-title-11 lw-pr-custom-title-11" style="--color-main:#8c2f39;--color-main-text:#ffffff;--color-sub-text:#f0d6d9;width:100%;margin:1em auto"><h2 class="ttl" style="border-radius:4px"><span class="sub">OUR RULES</span><span class="main">変えていないこと</span></h2></div>
<!-- /wp:wdl/lw-pr-custom-title-11 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":16,"tbHeight":16,"spHeight":12} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:16px"></div><div class="tb" style="height:16px"></div><div class="sp" style="height:12px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-pr-list-5 {"listColumns":2,"leftItems":["図面は必ず紙でも残す","1個の試作でも断らない","納期は言った日を動かさない"],"rightItems":["見積の内訳を全部出す","外注に出す分は先に伝える","検品は必ず2人で見る"],"bgColor":"#f8f0f0","textColor":"#3a1c20"} -->
<div class="wp-block-wdl-lw-pr-list-5 lw-pr-list-5 columns-2" style="--list_items_bg_color:#f8f0f0;--list_items_color:#3a1c20"><div class="lw-pr-list-5_wrap"><div class="list_items"><div class="list_items_inner"><ul class="list_left" data-lw_font_set=""><li><span>図面は必ず紙でも残す</span></li><li><span>1個の試作でも断らない</span></li><li><span>納期は言った日を動かさない</span></li></ul><ul class="list_right" data-lw_font_set=""><li><span>見積の内訳を全部出す</span></li><li><span>外注に出す分は先に伝える</span></li><li><span>検品は必ず2人で見る</span></li></ul></div></div><div class="image"><img loading="lazy" src="https://liteword-assets.bigi-ishikawa.workers.dev/t/sample/slide/1.webp" alt=""/></div></div></div>
<!-- /wp:wdl/lw-pr-list-5 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":80,"tbHeight":64,"spHeight":40} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:80px"></div><div class="tb" style="height:64px"></div><div class="sp" style="height:40px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-bg-1 {"backgroundType":"image","imagePc":"","imageSp":"","isFullWidth":true,"maxWidth":1040,"minHeightPc":"min-h-pc-150px","minHeightTb":"min-h-tb-160px","minHeightSp":"min-h-sp-160px","innerPaddingTopPc":80,"innerPaddingBottomPc":80,"innerPaddingLeftPc":40,"innerPaddingRightPc":40,"innerPaddingTopTb":64,"innerPaddingBottomTb":64,"innerPaddingLeftTb":32,"innerPaddingRightTb":32,"innerPaddingTopSp":48,"innerPaddingBottomSp":48,"innerPaddingLeftSp":20,"innerPaddingRightSp":20,"filterTypePc":"solid","filterColorPc":"#f8f0f0","opacityPc":1,"filterTypeTb":"solid","filterColorTb":"#f8f0f0","opacityTb":1,"filterTypeSp":"solid","filterColorSp":"#f8f0f0","opacitySp":1} -->
<div class="wp-block-wdl-lw-bg-1 lw-bg-1 min-h-pc-150px min-h-tb-160px min-h-sp-160px bg_all" style="--lw-bg-color-filter-pc:#f8f0f0;--lw-bg-opacity-pc:1;--lw-bg-color-filter-tb:#f8f0f0;--lw-bg-opacity-tb:1;--lw-bg-color-filter-sp:#f8f0f0;--lw-bg-opacity-sp:1;--lw-bg-position-pc:50% 50%;--lw-bg-position-sp:50% 50%;--lw-bg-wrap-centering-pc:center;--lw-bg-wrap-align-pc:center;--lw-bg-wrap-centering-tb:center;--lw-bg-wrap-align-tb:center;--lw-bg-wrap-centering-sp:center;--lw-bg-wrap-align-sp:center"><div class="lw-bg-1-wrap" style="--lw-bg-padding-top-pc:80px;--lw-bg-padding-bottom-pc:80px;--lw-bg-padding-left-pc:40px;--lw-bg-padding-right-pc:40px;--lw-bg-padding-top-tb:64px;--lw-bg-padding-bottom-tb:64px;--lw-bg-padding-left-tb:32px;--lw-bg-padding-right-tb:32px;--lw-bg-padding-top-sp:48px;--lw-bg-padding-bottom-sp:48px;--lw-bg-padding-left-sp:20px;--lw-bg-padding-right-sp:20px;--lw-bg-max-width:1040px"><!-- wp:heading {"level":3,"style":{"color":{"text":"#3a1c20"},"typography":{"fontSize":"24px","lineHeight":"1.6"},"spacing":{"margin":{"top":"0px","bottom":"16px"}}},"textAlign":"center"} -->
<h3 class="has-text-align-center has-text-color" style="color:#3a1c20;font-size:24px;line-height:1.6;margin-top:0px;margin-bottom:16px">会社概要</h3>
<!-- /wp:heading -->
<!-- wp:wdl/lw-company-2 {"maxWidth":860,"dtBackgroundColor":"#efe2e3","dtTextColor":"#3a1c20","ddTextColor":"#3d3436","fontWeightDt":"600","borderColor":"#e7d6d8","spFullDt":true} -->
<div class="wp-block-wdl-lw-company-2 font_size_m" style="border-color:#e7d6d8"><dl class="sp_clm_1" style="border-color:#e7d6d8;max-width:860px;line-height:1.6"><div class="company-profile-item font_size_m dt_width_m" style="border-color:#e7d6d8"><dt style="background-color:#efe2e3;color:#3a1c20;font-weight:600;line-height:1.6" data-lw_font_set="">商号</dt><dd style="color:#3d3436;line-height:1.6" data-lw_font_set="">株式会社〇〇製作所</dd></div><div class="company-profile-item font_size_m dt_width_m" style="border-color:#e7d6d8"><dt style="background-color:#efe2e3;color:#3a1c20;font-weight:600;line-height:1.6" data-lw_font_set="">所在地</dt><dd style="color:#3d3436;line-height:1.6" data-lw_font_set="">〒000-0000　県名市けやき台1-2-3</dd></div><div class="company-profile-item font_size_m dt_width_m" style="border-color:#e7d6d8"><dt style="background-color:#efe2e3;color:#3a1c20;font-weight:600;line-height:1.6" data-lw_font_set="">創業</dt><dd style="color:#3d3436;line-height:1.6" data-lw_font_set="">1971年4月</dd></div><div class="company-profile-item font_size_m dt_width_m" style="border-color:#e7d6d8"><dt style="background-color:#efe2e3;color:#3a1c20;font-weight:600;line-height:1.6" data-lw_font_set="">資本金</dt><dd style="color:#3d3436;line-height:1.6" data-lw_font_set="">1,000万円</dd></div><div class="company-profile-item font_size_m dt_width_m" style="border-color:#e7d6d8"><dt style="background-color:#efe2e3;color:#3a1c20;font-weight:600;line-height:1.6" data-lw_font_set="">従業員</dt><dd style="color:#3d3436;line-height:1.6" data-lw_font_set="">18名（2026年4月現在）</dd></div><div class="company-profile-item font_size_m dt_width_m" style="border-color:#e7d6d8"><dt style="background-color:#efe2e3;color:#3a1c20;font-weight:600;line-height:1.6" data-lw_font_set="">事業内容</dt><dd style="color:#3d3436;line-height:1.6" data-lw_font_set="">金属部品の切削加工／試作／治具の設計</dd></div></dl></div>
<!-- /wp:wdl/lw-company-2 --></div></div>
<!-- /wp:wdl/lw-bg-1 -->
<!-- wp:wdl/lw-bg-1 {"backgroundType":"image","imagePc":"","imageSp":"","isFullWidth":true,"maxWidth":1040,"minHeightPc":"min-h-pc-150px","minHeightTb":"min-h-tb-160px","minHeightSp":"min-h-sp-160px","innerPaddingTopPc":80,"innerPaddingBottomPc":80,"innerPaddingLeftPc":40,"innerPaddingRightPc":40,"innerPaddingTopTb":64,"innerPaddingBottomTb":64,"innerPaddingLeftTb":32,"innerPaddingRightTb":32,"innerPaddingTopSp":48,"innerPaddingBottomSp":48,"innerPaddingLeftSp":20,"innerPaddingRightSp":20,"filterTypePc":"solid","filterColorPc":"#3a1c20","opacityPc":1,"filterTypeTb":"solid","filterColorTb":"#3a1c20","opacityTb":1,"filterTypeSp":"solid","filterColorSp":"#3a1c20","opacitySp":1} -->
<div class="wp-block-wdl-lw-bg-1 lw-bg-1 min-h-pc-150px min-h-tb-160px min-h-sp-160px bg_all" style="--lw-bg-color-filter-pc:#3a1c20;--lw-bg-opacity-pc:1;--lw-bg-color-filter-tb:#3a1c20;--lw-bg-opacity-tb:1;--lw-bg-color-filter-sp:#3a1c20;--lw-bg-opacity-sp:1;--lw-bg-position-pc:50% 50%;--lw-bg-position-sp:50% 50%;--lw-bg-wrap-centering-pc:center;--lw-bg-wrap-align-pc:center;--lw-bg-wrap-centering-tb:center;--lw-bg-wrap-align-tb:center;--lw-bg-wrap-centering-sp:center;--lw-bg-wrap-align-sp:center"><div class="lw-bg-1-wrap" style="--lw-bg-padding-top-pc:80px;--lw-bg-padding-bottom-pc:80px;--lw-bg-padding-left-pc:40px;--lw-bg-padding-right-pc:40px;--lw-bg-padding-top-tb:64px;--lw-bg-padding-bottom-tb:64px;--lw-bg-padding-left-tb:32px;--lw-bg-padding-right-tb:32px;--lw-bg-padding-top-sp:48px;--lw-bg-padding-bottom-sp:48px;--lw-bg-padding-left-sp:20px;--lw-bg-padding-right-sp:20px;--lw-bg-max-width:1040px"><!-- wp:heading {"level":3,"style":{"color":{"text":"#ffffff"},"typography":{"fontSize":"26px","lineHeight":"1.6"},"spacing":{"margin":{"top":"0px","bottom":"16px"}}},"textAlign":"center"} -->
<h3 class="has-text-align-center has-text-color" style="color:#ffffff;font-size:26px;line-height:1.6;margin-top:0px;margin-bottom:16px">図面がなくても、まずご相談ください</h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"style":{"color":{"text":"#eddadd"},"typography":{"fontSize":"16px","lineHeight":"2"}},"align":"center"} -->
<p class="has-text-align-center has-text-color" style="color:#eddadd;font-size:16px;line-height:2">手書きのスケッチや、現物をお預かりするところから始められます。</p>
<!-- /wp:paragraph -->
<!-- wp:wdl/lw-space-1 {"pcHeight":24,"tbHeight":20,"spHeight":16} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:24px"></div><div class="tb" style="height:20px"></div><div class="sp" style="height:16px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-pr-button-4 {"textMain":"000-000-0000","textSub":"受付時間 8:30〜17:30（土日祝休）","btnUrl":"tel:0000000000","btnAlign":"center","bgColor":"#8c2f39","bgColorHover":"#6d232b","textColorMain":"#ffffff","borderWidth":0,"borderRadius":6} -->
<div class="wp-block-wdl-lw-pr-button-4 lw-pr-button-4"><div class="wrap_btn center"><a href="tel:0000000000" class="lw_btn_a " style="--hover-bg:#6d232b;--transition-duration:0.3s;--max-width-sp:480px;--shake-interval:3s;--font-size-main:28px;--font-size-main-sp:18px;--font-size-sub:14px;--letter-spacing:0.05em;max-width:580px;padding:1.2em 1.5em;background:#8c2f39;border:0px solid #000000;border-radius:6px;box-shadow:0px 0px 6px rgba(0, 0, 0, 0.2)"><span class="text_main" style="color:#ffffff;font-weight:500;font-size:28px;letter-spacing:0.05em" data-lw_font_set=""><span class="icon" style="fill:#ffffff;width:32px;margin-right:8px;margin-left:-8px"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M164.9 24.6c-7.7-18.6-28-28.5-47.4-23.2l-88 24C12.1 30.2 0 46 0 64C0 311.4 200.6 512 448 512c18 0 33.8-12.1 38.6-29.5l24-88c5.3-19.4-4.6-39.7-23.2-47.4l-96-40c-16.3-6.8-35.2-2.1-46.3 11.6L304.7 368C234.3 334.7 177.3 277.7 144 207.3L193.3 167c13.7-11.2 18.4-30 11.6-46.3l-40-96z"/></svg></span>000-000-0000</span><span class="text_sub" style="color:#ffffff;font-weight:500;font-size:14px" data-lw_font_set="">受付時間 8:30〜17:30（土日祝休）</span></a></div></div>
<!-- /wp:wdl/lw-pr-button-4 --></div></div>
<!-- /wp:wdl/lw-bg-1 -->