<!-- wp:wdl/paid-block-fv-10 {"mainTitle":"工事の前と後","backgroundImage":"https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/km_work_01.webp","backgroundImageSp":"","filterBackgroundColor":"#2a2320","filterOpacity":0.3,"innerFilterBg":"#ffffff","innerFilterBorderColor":"#e6dcd6","innerFilterBorderWidth":1,"innerFilterBorderRadius":4,"innerFilterShadowColor":"rgba(59,64,69,0.16)","innerFilterShadowOffsetY":4,"innerFilterShadowBlur":14,"textColor":"#3b4045","minHeightPc":"min-h-pc-480px","minHeightTb":"min-h-tb-400px","minHeightSp":"min-h-sp-300px","titleFontSizeClass":"font_size_m"} -->
<div class="wp-block-wdl-paid-block-fv-10 paid-block-fv-10 min-h-pc-480px min-h-tb-400px min-h-sp-300px"><div class="fv-10_inner"><h1 class="ttl font_size_m" style="color:#3b4045"><span class="main" style="color:#3b4045">工事の前と後</span></h1><div class="inner_filter" style="background-color:#ffffff;border-color:#e6dcd6;border-width:1px;border-style:solid;border-radius:4px;box-shadow:0px 4px 14px 0px rgba(59,64,69,0.16)"></div></div><div class="filter" style="background-color:#2a2320;opacity:0.3"></div><picture class="bg_image"><source srcSet="" media="(max-width: 800px)"/><source srcSet="https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/km_work_01.webp" media="(min-width: 801px)"/><img src="https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/km_work_01.webp" alt="" loading="eager" fetchpriority="high"/></picture></div>
<!-- /wp:wdl/paid-block-fv-10 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":80,"tbHeight":64,"spHeight":40} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:80px"></div><div class="tb" style="height:64px"></div><div class="sp" style="height:40px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/custom-title-1 {"mainTitle":"工事の前と後","subTitle":"WORKS","headingLevel":2} -->
<h2 class="wp-block-wdl-custom-title-1 custom-title-1" style="--custom-title-sub-margin-top-pc:0.2em;--custom-title-sub-margin-top-sp:0.2em"><span class="main">工事の前と後</span><span class="sub">WORKS</span></h2>
<!-- /wp:wdl/custom-title-1 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":16,"tbHeight":16,"spHeight":12} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:16px"></div><div class="tb" style="height:16px"></div><div class="sp" style="height:12px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:paragraph {"align":"center","style":{"color":{"text":"#3a4046"},"typography":{"fontSize":"16px","lineHeight":"2"},"spacing":{"margin":{"top":"28px","bottom":"24px"}}}} -->
<p class="has-text-align-center has-text-color" style="color:#3a4046;font-size:16px;line-height:2;margin-top:28px;margin-bottom:24px">お客様の許可をいただいた3件を、前と後で並べています。<span class="lw-br on_500px"></span>金額と工期も、そのまま書いています。</p>
<!-- /wp:paragraph -->
<!-- wp:wdl/lw-space-1 {"pcHeight":24,"tbHeight":20,"spHeight":16} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:24px"></div><div class="tb" style="height:20px"></div><div class="sp" style="height:16px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:heading {"level":3,"style":{"color":{"text":"#3b4045"},"typography":{"fontSize":"22px","lineHeight":"1.6"},"spacing":{"margin":{"top":"0px","bottom":"16px"}}},"textAlign":"center"} -->
<h3 class="has-text-align-center has-text-color" style="color:#3b4045;font-size:22px;line-height:1.6;margin-top:0px;margin-bottom:16px">築32年・戸建て　浴室まわり</h3>
<!-- /wp:heading -->
<!-- wp:wdl/lw-pr-before-after-3 {"beforeImageUrl":"https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/km_worry.webp","beforeImageAlt":"工事前","beforeText":"BEFORE","beforeDescription":"タイルの目地が割れて、下地まで水が回っていました。","afterImageUrl":"https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/km_svc_01.webp","afterImageAlt":"工事後","afterText":"AFTER","afterDescription":"床下の傷んだ材を入れ替えたうえで、ユニットバスに。","beforeTextBgColor":"#3b4045","afterTextBgColor":"#cf4520","arrowBgColor":"#cf4520","maxWidth":900,"aspectRatioHeight":640,"hasImageShadow":true} -->
<div class="wp-block-wdl-lw-pr-before-after-3 lw-pr-before-after-3"><div class="this_wrap" style="max-width:900px"><div class="image-area"><div class="image has-shadow" style="aspect-ratio:800 / 640"><img src="https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/km_worry.webp" alt="工事前"/><div class="text" style="background-color:#3b4045" data-lw_font_set="Montserrat">BEFORE</div></div><div class="arrow-right" style="border-left:20px solid #cf4520"></div><div class="image has-shadow" style="aspect-ratio:800 / 640"><img src="https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/km_svc_01.webp" alt="工事後"/><div class="text" style="background-color:#cf4520" data-lw_font_set="Montserrat">AFTER</div></div></div><div class="desc-area"><p class="desc">タイルの目地が割れて、下地まで水が回っていました。</p><p class="desc">床下の傷んだ材を入れ替えたうえで、ユニットバスに。</p></div></div></div>
<!-- /wp:wdl/lw-pr-before-after-3 -->
<!-- wp:paragraph {"align":"center","style":{"color":{"text":"#545b62"},"typography":{"fontSize":"14px","lineHeight":"1.9"},"spacing":{"margin":{"top":"16px","bottom":"0px"}}}} -->
<p class="has-text-align-center has-text-color" style="color:#545b62;font-size:14px;line-height:1.9;margin-top:16px;margin-bottom:0px">工期 6日／費用 128万円（税込）　※ 下地の傷みの分で、当初のお見積より12万円上がりました。</p>
<!-- /wp:paragraph -->
<!-- wp:wdl/lw-space-1 {"pcHeight":80,"tbHeight":64,"spHeight":40} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:80px"></div><div class="tb" style="height:64px"></div><div class="sp" style="height:40px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:heading {"level":3,"style":{"color":{"text":"#3b4045"},"typography":{"fontSize":"22px","lineHeight":"1.6"},"spacing":{"margin":{"top":"0px","bottom":"16px"}}},"textAlign":"center"} -->
<h3 class="has-text-align-center has-text-color" style="color:#3b4045;font-size:22px;line-height:1.6;margin-top:0px;margin-bottom:16px">築18年・マンション　台所</h3>
<!-- /wp:heading -->
<!-- wp:wdl/lw-pr-before-after-3 {"beforeImageUrl":"https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/km_svc_04.webp","beforeImageAlt":"工事前","beforeText":"BEFORE","beforeDescription":"扉の建てつけが落ち、天板の継ぎ目が浮いていました。","afterImageUrl":"https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/km_req_01.webp","afterImageAlt":"工事後","afterText":"AFTER","afterDescription":"同じ寸法で入れ替え。手元の明かりを足しました。","beforeTextBgColor":"#3b4045","afterTextBgColor":"#cf4520","arrowBgColor":"#cf4520","maxWidth":900,"aspectRatioHeight":640,"hasImageShadow":true} -->
<div class="wp-block-wdl-lw-pr-before-after-3 lw-pr-before-after-3"><div class="this_wrap" style="max-width:900px"><div class="image-area"><div class="image has-shadow" style="aspect-ratio:800 / 640"><img src="https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/km_svc_04.webp" alt="工事前"/><div class="text" style="background-color:#3b4045" data-lw_font_set="Montserrat">BEFORE</div></div><div class="arrow-right" style="border-left:20px solid #cf4520"></div><div class="image has-shadow" style="aspect-ratio:800 / 640"><img src="https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/km_req_01.webp" alt="工事後"/><div class="text" style="background-color:#cf4520" data-lw_font_set="Montserrat">AFTER</div></div></div><div class="desc-area"><p class="desc">扉の建てつけが落ち、天板の継ぎ目が浮いていました。</p><p class="desc">同じ寸法で入れ替え。手元の明かりを足しました。</p></div></div></div>
<!-- /wp:wdl/lw-pr-before-after-3 -->
<!-- wp:paragraph {"align":"center","style":{"color":{"text":"#545b62"},"typography":{"fontSize":"14px","lineHeight":"1.9"},"spacing":{"margin":{"top":"16px","bottom":"0px"}}}} -->
<p class="has-text-align-center has-text-color" style="color:#545b62;font-size:14px;line-height:1.9;margin-top:16px;margin-bottom:0px">工期 3日／費用 89万円（税込）　※ 追加費用はありませんでした。</p>
<!-- /wp:paragraph -->
<!-- wp:wdl/lw-space-1 {"pcHeight":80,"tbHeight":64,"spHeight":40} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:80px"></div><div class="tb" style="height:64px"></div><div class="sp" style="height:40px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:heading {"level":3,"style":{"color":{"text":"#3b4045"},"typography":{"fontSize":"22px","lineHeight":"1.6"},"spacing":{"margin":{"top":"0px","bottom":"16px"}}},"textAlign":"center"} -->
<h3 class="has-text-align-center has-text-color" style="color:#3b4045;font-size:22px;line-height:1.6;margin-top:0px;margin-bottom:16px">築45年・戸建て　和室を洋室に</h3>
<!-- /wp:heading -->
<!-- wp:wdl/lw-pr-before-after-3 {"beforeImageUrl":"https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/km_ba_before.webp","beforeImageAlt":"工事前","beforeText":"BEFORE","beforeDescription":"畳が沈み、押し入れの中にかびが出ていました。","afterImageUrl":"https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/km_ba_after.webp","afterImageAlt":"工事後","afterText":"AFTER","afterDescription":"床を組み直して無垢の板に。押し入れはクローゼットにしました。","beforeTextBgColor":"#3b4045","afterTextBgColor":"#cf4520","arrowBgColor":"#cf4520","maxWidth":900,"aspectRatioHeight":640,"hasImageShadow":true} -->
<div class="wp-block-wdl-lw-pr-before-after-3 lw-pr-before-after-3"><div class="this_wrap" style="max-width:900px"><div class="image-area"><div class="image has-shadow" style="aspect-ratio:800 / 640"><img src="https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/km_ba_before.webp" alt="工事前"/><div class="text" style="background-color:#3b4045" data-lw_font_set="Montserrat">BEFORE</div></div><div class="arrow-right" style="border-left:20px solid #cf4520"></div><div class="image has-shadow" style="aspect-ratio:800 / 640"><img src="https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/km_ba_after.webp" alt="工事後"/><div class="text" style="background-color:#cf4520" data-lw_font_set="Montserrat">AFTER</div></div></div><div class="desc-area"><p class="desc">畳が沈み、押し入れの中にかびが出ていました。</p><p class="desc">床を組み直して無垢の板に。押し入れはクローゼットにしました。</p></div></div></div>
<!-- /wp:wdl/lw-pr-before-after-3 -->
<!-- wp:paragraph {"align":"center","style":{"color":{"text":"#545b62"},"typography":{"fontSize":"14px","lineHeight":"1.9"},"spacing":{"margin":{"top":"16px","bottom":"0px"}}}} -->
<p class="has-text-align-center has-text-color" style="color:#545b62;font-size:14px;line-height:1.9;margin-top:16px;margin-bottom:0px">工期 12日／費用 156万円（税込）　※ 下地の組み直しを含みます。壁紙はお客様のお選びになったものです。</p>
<!-- /wp:paragraph -->
<!-- wp:wdl/lw-space-1 {"pcHeight":80,"tbHeight":64,"spHeight":40} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:80px"></div><div class="tb" style="height:64px"></div><div class="sp" style="height:40px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/custom-title-1 {"mainTitle":"お客様の言葉","subTitle":"VOICE","headingLevel":2} -->
<h2 class="wp-block-wdl-custom-title-1 custom-title-1" style="--custom-title-sub-margin-top-pc:0.2em;--custom-title-sub-margin-top-sp:0.2em"><span class="main">お客様の言葉</span><span class="sub">VOICE</span></h2>
<!-- /wp:wdl/custom-title-1 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":16,"tbHeight":16,"spHeight":12} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:16px"></div><div class="tb" style="height:16px"></div><div class="sp" style="height:12px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-pr-comment-3 {"comment3ImageUrl":"https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/km_voice_01.webp","comment3ImageAlt":"お客様","comment3ImageWidthPc":200,"comment3ImageWidthSp":110,"comment3TextBdColorPc":"#dde1e4","comment3TextInnerBg":"#f2f4f5","comment3Bg":"#ffffff","comment3BdColor":"#dde1e4","comment3MaxWidth":940,"comment3TextDfPc":16,"comment3TextDfSp":14,"comment3SpClm":true,"comment3AlignItems":"end"} -->
<div class="wp-block-wdl-lw-pr-comment-3 lw-pr-comment-3" style="--comment-3-bd-color:#dde1e4;--comment-3-bg:#ffffff;--comment-3-max-width:940px"><div class="lw-pr-comment-3__wrap sp_clm_1" style="--comment-3-image-width-pc:200px;--comment-3-image-width-sp:110px;--comment-3-text-bd-color-pc:#dde1e4;--comment-3-text-inner-bg:#f2f4f5;--comment-3-text-df-pc:16px;--comment-3-text-df-sp:14px;--comment-3-text-inner-gap-pc:8px;--comment-3-text-inner-gap-sp:8px"><div class="lw-pr-comment-3__text"><div class="lw-pr-comment-3__text_inner"><!-- wp:heading {"level":3,"style":{"color":{"text":"#3b4045"},"typography":{"fontSize":"18px","lineHeight":"1.6"},"spacing":{"margin":{"top":"0px","bottom":"16px"}}},"textAlign":"left"} -->
<h3 class="has-text-align-left has-text-color" style="color:#3b4045;font-size:18px;line-height:1.6;margin-top:0px;margin-bottom:16px">浴室を直された方（60代・戸建て）</h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"style":{"color":{"text":"#3a4046"},"typography":{"fontSize":"16px","lineHeight":"1.9"}}} -->
<p class="has-text-color" style="color:#3a4046;font-size:16px;line-height:1.9">壊してみたら下が傷んでいた、と写真で見せてもらいました。追加のお金がかかると聞いたときは正直がっかりしましたが、直さずに蓋をされるほうが怖かったので、見せてもらえてよかったです。</p>
<!-- /wp:paragraph --><div class="lw-pr-comment-3__text_arrow"></div></div></div><div class="lw-pr-comment-3__image"><img src="https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/km_voice_01.webp" alt="お客様"/></div></div></div>
<!-- /wp:wdl/lw-pr-comment-3 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":24,"tbHeight":20,"spHeight":16} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:24px"></div><div class="tb" style="height:20px"></div><div class="sp" style="height:16px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-pr-comment-3 {"comment3ImageUrl":"https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/km_voice_02.webp","comment3ImageAlt":"お客様","comment3ImageWidthPc":200,"comment3ImageWidthSp":110,"comment3TextBdColorPc":"#dde1e4","comment3TextInnerBg":"#f2f4f5","comment3Bg":"#ffffff","comment3BdColor":"#dde1e4","comment3MaxWidth":940,"comment3TextDfPc":16,"comment3TextDfSp":14,"comment3SpClm":true,"comment3AlignItems":"end"} -->
<div class="wp-block-wdl-lw-pr-comment-3 lw-pr-comment-3" style="--comment-3-bd-color:#dde1e4;--comment-3-bg:#ffffff;--comment-3-max-width:940px"><div class="lw-pr-comment-3__wrap sp_clm_1" style="--comment-3-image-width-pc:200px;--comment-3-image-width-sp:110px;--comment-3-text-bd-color-pc:#dde1e4;--comment-3-text-inner-bg:#f2f4f5;--comment-3-text-df-pc:16px;--comment-3-text-df-sp:14px;--comment-3-text-inner-gap-pc:8px;--comment-3-text-inner-gap-sp:8px"><div class="lw-pr-comment-3__text"><div class="lw-pr-comment-3__text_inner"><!-- wp:heading {"level":3,"style":{"color":{"text":"#3b4045"},"typography":{"fontSize":"18px","lineHeight":"1.6"},"spacing":{"margin":{"top":"0px","bottom":"16px"}}},"textAlign":"left"} -->
<h3 class="has-text-align-left has-text-color" style="color:#3b4045;font-size:18px;line-height:1.6;margin-top:0px;margin-bottom:16px">外壁を塗り替えた方（50代）</h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"style":{"color":{"text":"#3a4046"},"typography":{"fontSize":"16px","lineHeight":"1.9"}}} -->
<p class="has-text-color" style="color:#3a4046;font-size:16px;line-height:1.9">雨で3日延びましたが、その都度どこまで進んだか連絡がありました。留守がちなので、写真で残してもらえたのが助かりました。</p>
<!-- /wp:paragraph --><div class="lw-pr-comment-3__text_arrow"></div></div></div><div class="lw-pr-comment-3__image"><img src="https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/km_voice_02.webp" alt="お客様"/></div></div></div>
<!-- /wp:wdl/lw-pr-comment-3 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":80,"tbHeight":64,"spHeight":40} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:80px"></div><div class="tb" style="height:64px"></div><div class="sp" style="height:40px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-bg-1 {"backgroundType":"image","imagePc":"","imageSp":"","isFullWidth":true,"maxWidth":1040,"minHeightPc":"min-h-pc-150px","minHeightTb":"min-h-tb-160px","minHeightSp":"min-h-sp-160px","innerPaddingTopPc":80,"innerPaddingBottomPc":80,"innerPaddingLeftPc":40,"innerPaddingRightPc":40,"innerPaddingTopTb":64,"innerPaddingBottomTb":64,"innerPaddingLeftTb":32,"innerPaddingRightTb":32,"innerPaddingTopSp":48,"innerPaddingBottomSp":48,"innerPaddingLeftSp":20,"innerPaddingRightSp":20,"filterTypePc":"solid","filterColorPc":"#3b4045","opacityPc":1,"filterTypeTb":"solid","filterColorTb":"#3b4045","opacityTb":1,"filterTypeSp":"solid","filterColorSp":"#3b4045","opacitySp":1} -->
<div class="wp-block-wdl-lw-bg-1 lw-bg-1 min-h-pc-150px min-h-tb-160px min-h-sp-160px bg_all" style="--lw-bg-color-filter-pc:#3b4045;--lw-bg-opacity-pc:1;--lw-bg-color-filter-tb:#3b4045;--lw-bg-opacity-tb:1;--lw-bg-color-filter-sp:#3b4045;--lw-bg-opacity-sp:1;--lw-bg-position-pc:50% 50%;--lw-bg-position-sp:50% 50%;--lw-bg-wrap-centering-pc:center;--lw-bg-wrap-align-pc:center;--lw-bg-wrap-centering-tb:center;--lw-bg-wrap-align-tb:center;--lw-bg-wrap-centering-sp:center;--lw-bg-wrap-align-sp:center"><div class="lw-bg-1-wrap" style="--lw-bg-padding-top-pc:80px;--lw-bg-padding-bottom-pc:80px;--lw-bg-padding-left-pc:40px;--lw-bg-padding-right-pc:40px;--lw-bg-padding-top-tb:64px;--lw-bg-padding-bottom-tb:64px;--lw-bg-padding-left-tb:32px;--lw-bg-padding-right-tb:32px;--lw-bg-padding-top-sp:48px;--lw-bg-padding-bottom-sp:48px;--lw-bg-padding-left-sp:20px;--lw-bg-padding-right-sp:20px;--lw-bg-max-width:1040px"><!-- wp:heading {"level":3,"style":{"color":{"text":"#ffffff"},"typography":{"fontSize":"26px","lineHeight":"1.6"},"spacing":{"margin":{"top":"0px","bottom":"16px"}}},"textAlign":"center"} -->
<h3 class="has-text-align-center has-text-color" style="color:#ffffff;font-size:26px;line-height:1.6;margin-top:0px;margin-bottom:16px">似た工事の例があります</h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"style":{"color":{"text":"#dde1e4"},"typography":{"fontSize":"16px","lineHeight":"2"}},"align":"center"} -->
<p class="has-text-align-center has-text-color" style="color:#dde1e4;font-size:16px;line-height:2">お住まいの築年数と気になっている場所を教えていただければ、近い条件の事例を金額つきでお持ちします。その場で契約を迫ることはありません。</p>
<!-- /wp:paragraph -->
<!-- wp:wdl/lw-space-1 {"pcHeight":24,"tbHeight":20,"spHeight":16} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:24px"></div><div class="tb" style="height:20px"></div><div class="sp" style="height:16px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-pr-button-4 {"textMain":"000-000-0000","textSub":"受付時間 8:00〜18:00（日曜休）","btnUrl":"tel:0000000000","btnAlign":"center","bgColor":"#cf4520","bgColorHover":"#a53517","textColorMain":"#ffffff","borderWidth":0,"borderRadius":6} -->
<div class="wp-block-wdl-lw-pr-button-4 lw-pr-button-4"><div class="wrap_btn center"><a href="tel:0000000000" class="lw_btn_a " style="--hover-bg:#a53517;--transition-duration:0.3s;--max-width-sp:480px;--shake-interval:3s;--font-size-main:28px;--font-size-main-sp:18px;--font-size-sub:14px;--letter-spacing:0.05em;max-width:580px;padding:1.2em 1.5em;background:#cf4520;border:0px solid #000000;border-radius:6px;box-shadow:0px 0px 6px rgba(0, 0, 0, 0.2)"><span class="text_main" style="color:#ffffff;font-weight:500;font-size:28px;letter-spacing:0.05em" data-lw_font_set=""><span class="icon" style="fill:#ffffff;width:32px;margin-right:8px;margin-left:-8px"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M164.9 24.6c-7.7-18.6-28-28.5-47.4-23.2l-88 24C12.1 30.2 0 46 0 64C0 311.4 200.6 512 448 512c18 0 33.8-12.1 38.6-29.5l24-88c5.3-19.4-4.6-39.7-23.2-47.4l-96-40c-16.3-6.8-35.2-2.1-46.3 11.6L304.7 368C234.3 334.7 177.3 277.7 144 207.3L193.3 167c13.7-11.2 18.4-30 11.6-46.3l-40-96z"/></svg></span>000-000-0000</span><span class="text_sub" style="color:#ffffff;font-weight:500;font-size:14px" data-lw_font_set="">受付時間 8:00〜18:00（日曜休）</span></a></div></div>
<!-- /wp:wdl/lw-pr-button-4 --></div></div>
<!-- /wp:wdl/lw-bg-1 -->