<!-- wp:wdl/fv-4 {"backgroundImage":"https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/workplace_02.webp","backgroundImageSp":"","mainTitle":"車検のご質問","subTitle":"いつの疑問かで、探せます","description":"「預ける前」「預けている日」「返ってきたあと」の3つに分けています。\nいま知りたいところから読んでください。","filterBackgroundColor":"#3a1218","filterOpacity":0.62,"textColor":"#fff","minHeightPc":"min-h-pc-440px","minHeightTb":"min-h-tb-380px","minHeightSp":"min-h-sp-320px","maxWidth":1040,"textAlignPc":"pc_left","textAlignSp":"sp_left","headingLevel":1} -->
<div class="wp-block-wdl-fv-4 fv-4 min-h-pc-440px min-h-tb-380px min-h-sp-320px"><div class="fv-4_inner pc_left sp_left" style="max-width:1040px"><h1 class="ttl" style="color:#fff"><span class="sub" style="color:#fff">いつの疑問かで、探せます</span><span class="main" style="color:#fff">車検のご質問</span></h1><p style="color:#fff">「預ける前」「預けている日」「返ってきたあと」の3つに分けています。
いま知りたいところから読んでください。</p></div><div class="filter" style="background-color:#3a1218;opacity:0.62"></div><picture class="bg_image"><source srcSet="" media="(max-width: 800px)"/><source srcSet="https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/workplace_02.webp" media="(min-width: 801px)"/><img src="https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/workplace_02.webp" alt="背景画像" loading="eager" fetchpriority="high"/></picture></div>
<!-- /wp:wdl/fv-4 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":80,"tbHeight":64,"spHeight":40} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:80px"></div><div class="tb" style="height:64px"></div><div class="sp" style="height:40px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-pr-custom-title-15 {"subTitle":"BEFORE","mainTitle":"預ける前","headingLevel":2,"showSubTitle":true,"afterColor":"#b03a48","afterWidthPc":56,"afterWidthSp":44,"afterHeightPc":3,"afterHeightSp":3,"fontSizePc":15,"fontSizeSp":14,"positionPc":"position_center","positionSp":"position_center"} -->
<h2 class="wp-block-wdl-lw-pr-custom-title-15 lw-pr-custom-title-15 position_center position_center" style="--custom-title-sub-margin-top-pc:0.2em;--custom-title-sub-margin-top-sp:0.2em;--title-15-after-color:#b03a48;--title-15-after-mt-pc:1em;--title-15-after-mt-sp:0.8em;--title-15-after-h-pc:3px;--title-15-after-h-sp:3px;--title-15-after-w-pc:56px;--title-15-after-w-sp:44px;--title-15-font-size_pc:15px;--title-15-font-size_sp:14px"><span class="main">預ける前</span><span class="sub">BEFORE</span></h2>
<!-- /wp:wdl/lw-pr-custom-title-15 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":16,"tbHeight":16,"spHeight":12} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:16px"></div><div class="tb" style="height:16px"></div><div class="sp" style="height:12px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:paragraph {"align":"center","style":{"color":{"text":"#2f2a2b"},"typography":{"fontSize":"16px","lineHeight":"2"},"spacing":{"margin":{"top":"28px","bottom":"24px"}}}} -->
<p class="has-text-align-center has-text-color" style="color:#2f2a2b;font-size:16px;line-height:2;margin-top:28px;margin-bottom:24px">お問い合わせのときにいただくご質問です。</p>
<!-- /wp:paragraph -->
<!-- wp:wdl/lw-pr-qa-3 {"maxWidth":940,"qLabelColor":"#7f2a34","aLabelColor":"#655b5c","lineColor":"#e8d8da"} -->
<div class="wp-block-wdl-lw-pr-qa-3 lw-pr-qa-3" style="--qa3-max-w:940px;--qa3-gap:24px;--qa3-label-w:32px;--qa3-q-color:#7f2a34;--qa3-a-color:#655b5c;--qa3-line:#e8d8da;--qa3-label-size-pc:18px;--qa3-label-size-sp:16px;--qa3-q-size-pc:17px;--qa3-q-size-sp:15px;--qa3-a-size-pc:15px;--qa3-a-size-sp:14px"><dl class="qa-3__item"><dt><span class="label" data-lw_font_set="Roboto">Q</span><p class="qa-3__q_text">予約は必要ですか</p></dt><dd><span class="label" data-lw_font_set="Roboto">A</span><p class="qa-3__a_text">必要です。代車の数に限りがあるためです。1週間前までにいただけると、ご希望の日にお受けできます。</p></dd></dl><dl class="qa-3__item"><dt><span class="label" data-lw_font_set="Roboto">Q</span><p class="qa-3__q_text">車検が切れそうです</p></dt><dd><span class="label" data-lw_font_set="Roboto">A</span><p class="qa-3__a_text">切れていても入庫できます。ただし公道を走れないので、こちらから引き取りに伺います（市内無料）。</p></dd></dl><dl class="qa-3__item"><dt><span class="label" data-lw_font_set="Roboto">Q</span><p class="qa-3__q_text">何を持っていけば</p></dt><dd><span class="label" data-lw_font_set="Roboto">A</span><p class="qa-3__a_text">車検証・自賠責保険証・自動車税の納税証明書の3点です。納税証明書は電子確認できることが多く、無くても進められます。</p></dd></dl><dl class="qa-3__item"><dt><span class="label" data-lw_font_set="Roboto">Q</span><p class="qa-3__q_text">見積りだけ欲しい</p></dt><dd><span class="label" data-lw_font_set="Roboto">A</span><p class="qa-3__a_text">無料でお出しします。15分ほどお預かりして、その場で金額をお伝えします。お断りいただいて構いません。</p></dd></dl><dl class="qa-3__item"><dt><span class="label" data-lw_font_set="Roboto">Q</span><p class="qa-3__q_text">他店の見積りより高い</p></dt><dd><span class="label" data-lw_font_set="Roboto">A</span><p class="qa-3__a_text">内訳をお見せいただければ、どこが違うのかご説明します。安いほうがよければ、そちらをお勧めすることもあります。</p></dd></dl><dl class="qa-3__item"><dt><span class="label" data-lw_font_set="Roboto">Q</span><p class="qa-3__q_text">ローンは組めますか</p></dt><dd><span class="label" data-lw_font_set="Roboto">A</span><p class="qa-3__a_text">分割払いをご用意しています。3回までは手数料をいただきません。</p></dd></dl></div>
<!-- /wp:wdl/lw-pr-qa-3 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":80,"tbHeight":64,"spHeight":40} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:80px"></div><div class="tb" style="height:64px"></div><div class="sp" style="height:40px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-bg-1 {"backgroundType":"image","imagePc":"","imageSp":"","isFullWidth":true,"maxWidth":1040,"minHeightPc":"min-h-pc-150px","minHeightTb":"min-h-tb-160px","minHeightSp":"min-h-sp-160px","innerPaddingTopPc":80,"innerPaddingBottomPc":80,"innerPaddingLeftPc":40,"innerPaddingRightPc":40,"innerPaddingTopTb":64,"innerPaddingBottomTb":64,"innerPaddingLeftTb":32,"innerPaddingRightTb":32,"innerPaddingTopSp":48,"innerPaddingBottomSp":48,"innerPaddingLeftSp":20,"innerPaddingRightSp":20,"filterTypePc":"solid","filterColorPc":"#fbf1f2","opacityPc":1,"filterTypeTb":"solid","filterColorTb":"#fbf1f2","opacityTb":1,"filterTypeSp":"solid","filterColorSp":"#fbf1f2","opacitySp":1} -->
<div class="wp-block-wdl-lw-bg-1 lw-bg-1 min-h-pc-150px min-h-tb-160px min-h-sp-160px bg_all" style="--lw-bg-color-filter-pc:#fbf1f2;--lw-bg-opacity-pc:1;--lw-bg-color-filter-tb:#fbf1f2;--lw-bg-opacity-tb:1;--lw-bg-color-filter-sp:#fbf1f2;--lw-bg-opacity-sp:1;--lw-bg-position-pc:50% 50%;--lw-bg-position-sp:50% 50%;--lw-bg-wrap-centering-pc:center;--lw-bg-wrap-align-pc:center;--lw-bg-wrap-centering-tb:center;--lw-bg-wrap-align-tb:center;--lw-bg-wrap-centering-sp:center;--lw-bg-wrap-align-sp:center"><div class="lw-bg-1-wrap" style="--lw-bg-padding-top-pc:80px;--lw-bg-padding-bottom-pc:80px;--lw-bg-padding-left-pc:40px;--lw-bg-padding-right-pc:40px;--lw-bg-padding-top-tb:64px;--lw-bg-padding-bottom-tb:64px;--lw-bg-padding-left-tb:32px;--lw-bg-padding-right-tb:32px;--lw-bg-padding-top-sp:48px;--lw-bg-padding-bottom-sp:48px;--lw-bg-padding-left-sp:20px;--lw-bg-padding-right-sp:20px;--lw-bg-max-width:1040px"><!-- wp:wdl/lw-pr-custom-title-15 {"subTitle":"THE DAY","mainTitle":"預けている日","headingLevel":2,"showSubTitle":true,"afterColor":"#b03a48","afterWidthPc":56,"afterWidthSp":44,"afterHeightPc":3,"afterHeightSp":3,"fontSizePc":15,"fontSizeSp":14,"positionPc":"position_center","positionSp":"position_center"} -->
<h2 class="wp-block-wdl-lw-pr-custom-title-15 lw-pr-custom-title-15 position_center position_center" style="--custom-title-sub-margin-top-pc:0.2em;--custom-title-sub-margin-top-sp:0.2em;--title-15-after-color:#b03a48;--title-15-after-mt-pc:1em;--title-15-after-mt-sp:0.8em;--title-15-after-h-pc:3px;--title-15-after-h-sp:3px;--title-15-after-w-pc:56px;--title-15-after-w-sp:44px;--title-15-font-size_pc:15px;--title-15-font-size_sp:14px"><span class="main">預けている日</span><span class="sub">THE DAY</span></h2>
<!-- /wp:wdl/lw-pr-custom-title-15 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":16,"tbHeight":16,"spHeight":12} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:16px"></div><div class="tb" style="height:16px"></div><div class="sp" style="height:12px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:paragraph {"style":{"color":{"text":"#2f2a2b"},"typography":{"fontSize":"16px","lineHeight":"1.9"}},"align":"center"} -->
<p class="has-text-align-center has-text-color" style="color:#2f2a2b;font-size:16px;line-height:1.9">朝お預かりして、夕方にお返しするのが基本です。</p>
<!-- /wp:paragraph -->
<!-- wp:wdl/lw-space-1 {"pcHeight":24,"tbHeight":20,"spHeight":16} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:24px"></div><div class="tb" style="height:20px"></div><div class="sp" style="height:16px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/paid-block-lw-step-3 {"ulMaxWidth":1040,"fontSizeClass":"font_size_m","bgGradient":"#b03a48","colorH3":"#6e1f2a","colorP":"#2f2a2b","noWidthEm":3.2,"noFontSizeEm":0.95} -->
<div class="wp-block-wdl-paid-block-lw-step-3 paid-block-lw-step-3 font_size_m" style="--step3-no-w:3.2em;--step3-no-fs:0.95em"><ul class="lw-step-2__inner" style="max-width:1040px"><li class="lw-step-2__li" style="border-color:#b03a48"><div class="lw-step-2__li_no" data-lw_font_set="Murecho" style="font-weight:600;background:#b03a48">9時</div><div class="lw-step-2__li_in"><h3 class="lw-step-2__li_title ttl" data-lw_font_set="" style="color:#6e1f2a">お預かり</h3><p class="lw-step-2__li_text" data-lw_font_set="" style="color:#2f2a2b">代車の鍵をお渡しします。免許証を拝見します。</p></div></li><li class="lw-step-2__li" style="border-color:#b03a48"><div class="lw-step-2__li_no" data-lw_font_set="Murecho" style="font-weight:600;background:#b03a48">10時</div><div class="lw-step-2__li_in"><h3 class="lw-step-2__li_title ttl" data-lw_font_set="" style="color:#6e1f2a">点検</h3><p class="lw-step-2__li_text" data-lw_font_set="" style="color:#2f2a2b">56項目を見ます。写真を撮りながら進めます。</p></div></li><li class="lw-step-2__li" style="border-color:#b03a48"><div class="lw-step-2__li_no" data-lw_font_set="Murecho" style="font-weight:600;background:#b03a48">12時</div><div class="lw-step-2__li_in"><h3 class="lw-step-2__li_title ttl" data-lw_font_set="" style="color:#6e1f2a">ご連絡</h3><p class="lw-step-2__li_text" data-lw_font_set="" style="color:#2f2a2b">交換が必要なものが出たら、写真を送ってお電話します。</p></div></li><li class="lw-step-2__li" style="border-color:#b03a48"><div class="lw-step-2__li_no" data-lw_font_set="Murecho" style="font-weight:600;background:#b03a48">15時</div><div class="lw-step-2__li_in"><h3 class="lw-step-2__li_title ttl" data-lw_font_set="" style="color:#6e1f2a">整備</h3><p class="lw-step-2__li_text" data-lw_font_set="" style="color:#2f2a2b">ご了解いただいた分だけ手を入れます。勝手には替えません。</p></div></li><li class="lw-step-2__li" style="border-color:#b03a48"><div class="lw-step-2__li_no" data-lw_font_set="Murecho" style="font-weight:600;background:#b03a48">17時</div><div class="lw-step-2__li_in"><h3 class="lw-step-2__li_title ttl" data-lw_font_set="" style="color:#6e1f2a">お引き渡し</h3><p class="lw-step-2__li_text" data-lw_font_set="" style="color:#2f2a2b">交換した部品の現物をお見せします。お支払いはこのときです。</p></div></li></ul></div>
<!-- /wp:wdl/paid-block-lw-step-3 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":24,"tbHeight":20,"spHeight":16} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:24px"></div><div class="tb" style="height:20px"></div><div class="sp" style="height:16px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-pr-qa-3 {"maxWidth":900,"qLabelColor":"#7f2a34","aLabelColor":"#655b5c","lineColor":"#ffffff"} -->
<div class="wp-block-wdl-lw-pr-qa-3 lw-pr-qa-3" style="--qa3-max-w:900px;--qa3-gap:24px;--qa3-label-w:32px;--qa3-q-color:#7f2a34;--qa3-a-color:#655b5c;--qa3-line:#ffffff;--qa3-label-size-pc:18px;--qa3-label-size-sp:16px;--qa3-q-size-pc:17px;--qa3-q-size-sp:15px;--qa3-a-size-pc:15px;--qa3-a-size-sp:14px"><dl class="qa-3__item"><dt><span class="label" data-lw_font_set="Roboto">Q</span><p class="qa-3__q_text">当日じゅうに終わりますか</p></dt><dd><span class="label" data-lw_font_set="Roboto">A</span><p class="qa-3__a_text">9割の車は当日にお返しできています。部品の取り寄せが要る場合だけ、2〜3日お預かりします。</p></dd></dl><dl class="qa-3__item"><dt><span class="label" data-lw_font_set="Roboto">Q</span><p class="qa-3__q_text">代車はありますか</p></dt><dd><span class="label" data-lw_font_set="Roboto">A</span><p class="qa-3__a_text">軽自動車を6台ご用意しています。無料です。ガソリンは減ったぶんだけお願いします。</p></dd></dl><dl class="qa-3__item"><dt><span class="label" data-lw_font_set="Roboto">Q</span><p class="qa-3__q_text">追加の整備は勝手にしますか</p></dt><dd><span class="label" data-lw_font_set="Roboto">A</span><p class="qa-3__a_text">しません。必要が出たら必ずお電話し、写真をお送りしてからご判断いただきます。</p></dd></dl><dl class="qa-3__item"><dt><span class="label" data-lw_font_set="Roboto">Q</span><p class="qa-3__q_text">断ったら車検に通りませんか</p></dt><dd><span class="label" data-lw_font_set="Roboto">A</span><p class="qa-3__a_text">通らないものと、通るけれど交換をお勧めするものは、分けてご説明します。混ぜません。</p></dd></dl></div>
<!-- /wp:wdl/lw-pr-qa-3 --></div></div>
<!-- /wp:wdl/lw-bg-1 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":80,"tbHeight":64,"spHeight":40} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:80px"></div><div class="tb" style="height:64px"></div><div class="sp" style="height:40px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-pr-custom-title-15 {"subTitle":"AFTER","mainTitle":"返ってきたあと","headingLevel":2,"showSubTitle":true,"afterColor":"#b03a48","afterWidthPc":56,"afterWidthSp":44,"afterHeightPc":3,"afterHeightSp":3,"fontSizePc":15,"fontSizeSp":14,"positionPc":"position_center","positionSp":"position_center"} -->
<h2 class="wp-block-wdl-lw-pr-custom-title-15 lw-pr-custom-title-15 position_center position_center" style="--custom-title-sub-margin-top-pc:0.2em;--custom-title-sub-margin-top-sp:0.2em;--title-15-after-color:#b03a48;--title-15-after-mt-pc:1em;--title-15-after-mt-sp:0.8em;--title-15-after-h-pc:3px;--title-15-after-h-sp:3px;--title-15-after-w-pc:56px;--title-15-after-w-sp:44px;--title-15-font-size_pc:15px;--title-15-font-size_sp:14px"><span class="main">返ってきたあと</span><span class="sub">AFTER</span></h2>
<!-- /wp:wdl/lw-pr-custom-title-15 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":16,"tbHeight":16,"spHeight":12} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:16px"></div><div class="tb" style="height:16px"></div><div class="sp" style="height:12px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:paragraph {"align":"center","style":{"color":{"text":"#2f2a2b"},"typography":{"fontSize":"16px","lineHeight":"2"},"spacing":{"margin":{"top":"28px","bottom":"24px"}}}} -->
<p class="has-text-align-center has-text-color" style="color:#2f2a2b;font-size:16px;line-height:2;margin-top:28px;margin-bottom:24px">お引き渡しのあとに、よくいただくご連絡です。</p>
<!-- /wp:paragraph -->
<!-- wp:wdl/lw-pr-qa-3 {"maxWidth":940,"qLabelColor":"#7f2a34","aLabelColor":"#655b5c","lineColor":"#e8d8da"} -->
<div class="wp-block-wdl-lw-pr-qa-3 lw-pr-qa-3" style="--qa3-max-w:940px;--qa3-gap:24px;--qa3-label-w:32px;--qa3-q-color:#7f2a34;--qa3-a-color:#655b5c;--qa3-line:#e8d8da;--qa3-label-size-pc:18px;--qa3-label-size-sp:16px;--qa3-q-size-pc:17px;--qa3-q-size-sp:15px;--qa3-a-size-pc:15px;--qa3-a-size-sp:14px"><dl class="qa-3__item"><dt><span class="label" data-lw_font_set="Roboto">Q</span><p class="qa-3__q_text">調子が変わった気がする</p></dt><dd><span class="label" data-lw_font_set="Roboto">A</span><p class="qa-3__a_text">すぐお持ちください。整備したところが原因なら、無料で見ます。日数は関係ありません。</p></dd></dl><dl class="qa-3__item"><dt><span class="label" data-lw_font_set="Roboto">Q</span><p class="qa-3__q_text">シールはいつ貼りますか</p></dt><dd><span class="label" data-lw_font_set="Roboto">A</span><p class="qa-3__a_text">お引き渡しのときにこちらで貼ります。新しい車検証は書類入れに入れておきます。</p></dd></dl><dl class="qa-3__item"><dt><span class="label" data-lw_font_set="Roboto">Q</span><p class="qa-3__q_text">交換した部品はもらえますか</p></dt><dd><span class="label" data-lw_font_set="Roboto">A</span><p class="qa-3__a_text">お渡しします。ご希望をおっしゃっていただければ、袋に入れてお車に積んでおきます。</p></dd></dl><dl class="qa-3__item"><dt><span class="label" data-lw_font_set="Roboto">Q</span><p class="qa-3__q_text">次はいつ来ればいいですか</p></dt><dd><span class="label" data-lw_font_set="Roboto">A</span><p class="qa-3__a_text">半年後に無料の点検をしています。時期が近づいたらハガキをお送りします。</p></dd></dl><dl class="qa-3__item"><dt><span class="label" data-lw_font_set="Roboto">Q</span><p class="qa-3__q_text">領収書を分けたいのですが</p></dt><dd><span class="label" data-lw_font_set="Roboto">A</span><p class="qa-3__a_text">法定費用と整備費用で分けてお出しできます。会社名でのお宛名も承ります。</p></dd></dl></div>
<!-- /wp:wdl/lw-pr-qa-3 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":80,"tbHeight":64,"spHeight":40} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:80px"></div><div class="tb" style="height:64px"></div><div class="sp" style="height:40px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-pr-custom-title-15 {"subTitle":"PRICE","mainTitle":"費用の内訳","headingLevel":2,"showSubTitle":true,"afterColor":"#b03a48","afterWidthPc":56,"afterWidthSp":44,"afterHeightPc":3,"afterHeightSp":3,"fontSizePc":15,"fontSizeSp":14,"positionPc":"position_center","positionSp":"position_center"} -->
<h2 class="wp-block-wdl-lw-pr-custom-title-15 lw-pr-custom-title-15 position_center position_center" style="--custom-title-sub-margin-top-pc:0.2em;--custom-title-sub-margin-top-sp:0.2em;--title-15-after-color:#b03a48;--title-15-after-mt-pc:1em;--title-15-after-mt-sp:0.8em;--title-15-after-h-pc:3px;--title-15-after-h-sp:3px;--title-15-after-w-pc:56px;--title-15-after-w-sp:44px;--title-15-font-size_pc:15px;--title-15-font-size_sp:14px"><span class="main">費用の内訳</span><span class="sub">PRICE</span></h2>
<!-- /wp:wdl/lw-pr-custom-title-15 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":16,"tbHeight":16,"spHeight":12} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:16px"></div><div class="tb" style="height:16px"></div><div class="sp" style="height:12px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:paragraph {"align":"center","style":{"color":{"text":"#2f2a2b"},"typography":{"fontSize":"16px","lineHeight":"2"},"spacing":{"margin":{"top":"28px","bottom":"24px"}}}} -->
<p class="has-text-align-center has-text-color" style="color:#2f2a2b;font-size:16px;line-height:2;margin-top:28px;margin-bottom:24px">「車検代」とひとまとめにせず、分けて書いています。<span class="lw-br on_500px"></span>上の2つはどこで受けても同じ金額です。</p>
<!-- /wp:paragraph -->
<!-- wp:wdl/lw-pr-table-2 {"dtFixedPc":true,"dtWidthPc":190,"dtWidthSp":150,"defaultSpClm1":true,"dlBorderColor":"#e8d8da","rowBorderColor":"#e8d8da","dtBorderColor":"#e8d8da","dtBgColor":"#fbf1f2","dtTextColor":"#6e1f2a","ddTextColor":"#2f2a2b","dtFontWeight":"600","fontSizePc":17,"fontSizeSp":15,"cellPaddingPc":16,"rows":[{"dtText":"自賠責保険料","ddText":"国が決めている金額です。どこで受けても同じです（軽自動車 17,540円／普通車 17,650円・24か月）","pcClm1":null,"spClm1":null,"bgColor":"","textColor":""},{"dtText":"自動車重量税","ddText":"同じく国が決めています。車の重さと年式で変わります","pcClm1":null,"spClm1":null,"bgColor":"","textColor":""},{"dtText":"印紙代","ddText":"1,800円前後。これも決まっています","pcClm1":null,"spClm1":null,"bgColor":"","textColor":""},{"dtText":"当店の車検基本料","ddText":"19,800円（軽自動車 16,500円）。点検と書類の代行です","pcClm1":null,"spClm1":null,"bgColor":"","textColor":""},{"dtText":"整備費用","ddText":"かかった分だけ。何もなければ 0円です","pcClm1":null,"spClm1":null,"bgColor":"","textColor":""}]} -->
<div class="wp-block-wdl-lw-pr-table-2 lw-pr-table-2" style="--table-2-dl-width-pc:100%;--table-2-dl-width-sp:100%;--table-2-grid-columns-pc:190px calc(100% - 190px);--table-2-grid-columns-sp:1fr 1fr;--table-2-dl-border-color:#e8d8da;--table-2-dl-border-style:solid;--table-2-dl-border-width:1px;--table-2-dl-border-individual:0;--table-2-dl-border-top-color:#e8d8da;--table-2-dl-border-top-style:solid;--table-2-dl-border-top-width:1px;--table-2-dl-border-bottom-color:#e8d8da;--table-2-dl-border-bottom-style:solid;--table-2-dl-border-bottom-width:1px;--table-2-dl-border-left-color:#e8d8da;--table-2-dl-border-left-style:solid;--table-2-dl-border-left-width:1px;--table-2-dl-border-right-color:#e8d8da;--table-2-dl-border-right-style:solid;--table-2-dl-border-right-width:1px;--table-2-row-border-color:#e8d8da;--table-2-row-border-style:solid;--table-2-row-border-width:1px;--table-2-dt-border-color:#e8d8da;--table-2-dt-border-style:solid;--table-2-dt-border-width:1px;--table-2-dt-bg-color:#fbf1f2;--table-2-cell-padding-pc:16px;--table-2-cell-padding-sp:16px;--table-2-font-size-pc:17px;--table-2-font-size-sp:15px;--table-2-dt-align-pc:left;--table-2-dt-align-sp:left;--table-2-dd-align-pc:left;--table-2-dd-align-sp:left;--table-2-dt-text-color:#6e1f2a;--table-2-dd-text-color:#2f2a2b"><dl class="table-2__dl"><div class="table-2__row sp_clm_1"><dt class="table-2__dt"><p data-lw_font_set="" style="font-weight:600">自賠責保険料</p></dt><dd class="table-2__dd"><p data-lw_font_set="">国が決めている金額です。どこで受けても同じです（軽自動車 17,540円／普通車 17,650円・24か月）</p></dd></div><div class="table-2__row sp_clm_1"><dt class="table-2__dt"><p data-lw_font_set="" style="font-weight:600">自動車重量税</p></dt><dd class="table-2__dd"><p data-lw_font_set="">同じく国が決めています。車の重さと年式で変わります</p></dd></div><div class="table-2__row sp_clm_1"><dt class="table-2__dt"><p data-lw_font_set="" style="font-weight:600">印紙代</p></dt><dd class="table-2__dd"><p data-lw_font_set="">1,800円前後。これも決まっています</p></dd></div><div class="table-2__row sp_clm_1"><dt class="table-2__dt"><p data-lw_font_set="" style="font-weight:600">当店の車検基本料</p></dt><dd class="table-2__dd"><p data-lw_font_set="">19,800円（軽自動車 16,500円）。点検と書類の代行です</p></dd></div><div class="table-2__row sp_clm_1"><dt class="table-2__dt"><p data-lw_font_set="" style="font-weight:600">整備費用</p></dt><dd class="table-2__dd"><p data-lw_font_set="">かかった分だけ。何もなければ 0円です</p></dd></div></dl></div>
<!-- /wp:wdl/lw-pr-table-2 -->
<!-- wp:paragraph {"align":"center","style":{"color":{"text":"#655b5c"},"typography":{"fontSize":"14px","lineHeight":"1.9"},"spacing":{"margin":{"top":"16px","bottom":"0px"}}}} -->
<p class="has-text-align-center has-text-color" style="color:#655b5c;font-size:14px;line-height:1.9;margin-top:16px;margin-bottom:0px">※ 上の3つを合わせて「法定費用」と呼びます。当店の取り分ではありません。</p>
<!-- /wp:paragraph -->
<!-- wp:wdl/lw-space-1 {"pcHeight":80,"tbHeight":64,"spHeight":40} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:80px"></div><div class="tb" style="height:64px"></div><div class="sp" style="height:40px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-bg-1 {"backgroundType":"image","imagePc":"","imageSp":"","isFullWidth":true,"maxWidth":1040,"minHeightPc":"min-h-pc-150px","minHeightTb":"min-h-tb-160px","minHeightSp":"min-h-sp-160px","innerPaddingTopPc":80,"innerPaddingBottomPc":80,"innerPaddingLeftPc":40,"innerPaddingRightPc":40,"innerPaddingTopTb":64,"innerPaddingBottomTb":64,"innerPaddingLeftTb":32,"innerPaddingRightTb":32,"innerPaddingTopSp":48,"innerPaddingBottomSp":48,"innerPaddingLeftSp":20,"innerPaddingRightSp":20,"filterTypePc":"solid","filterColorPc":"#fbf1f2","opacityPc":1,"filterTypeTb":"solid","filterColorTb":"#fbf1f2","opacityTb":1,"filterTypeSp":"solid","filterColorSp":"#fbf1f2","opacitySp":1} -->
<div class="wp-block-wdl-lw-bg-1 lw-bg-1 min-h-pc-150px min-h-tb-160px min-h-sp-160px bg_all" style="--lw-bg-color-filter-pc:#fbf1f2;--lw-bg-opacity-pc:1;--lw-bg-color-filter-tb:#fbf1f2;--lw-bg-opacity-tb:1;--lw-bg-color-filter-sp:#fbf1f2;--lw-bg-opacity-sp:1;--lw-bg-position-pc:50% 50%;--lw-bg-position-sp:50% 50%;--lw-bg-wrap-centering-pc:center;--lw-bg-wrap-align-pc:center;--lw-bg-wrap-centering-tb:center;--lw-bg-wrap-align-tb:center;--lw-bg-wrap-centering-sp:center;--lw-bg-wrap-align-sp:center"><div class="lw-bg-1-wrap" style="--lw-bg-padding-top-pc:80px;--lw-bg-padding-bottom-pc:80px;--lw-bg-padding-left-pc:40px;--lw-bg-padding-right-pc:40px;--lw-bg-padding-top-tb:64px;--lw-bg-padding-bottom-tb:64px;--lw-bg-padding-left-tb:32px;--lw-bg-padding-right-tb:32px;--lw-bg-padding-top-sp:48px;--lw-bg-padding-bottom-sp:48px;--lw-bg-padding-left-sp:20px;--lw-bg-padding-right-sp:20px;--lw-bg-max-width:1040px"><!-- wp:heading {"level":3,"style":{"color":{"text":"#6e1f2a"},"typography":{"fontSize":"24px","lineHeight":"1.6"},"spacing":{"margin":{"top":"0px","bottom":"16px"}}},"textAlign":"center"} -->
<h3 class="has-text-align-center has-text-color" style="color:#6e1f2a;font-size:24px;line-height:1.6;margin-top:0px;margin-bottom:16px">分からないことは電話で</h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"style":{"color":{"text":"#2f2a2b"},"typography":{"fontSize":"16px","lineHeight":"1.9"}},"align":"center"} -->
<p class="has-text-align-center has-text-color" style="color:#2f2a2b;font-size:16px;line-height:1.9">車のことを知らなくて当たり前です。専門用語は使いません。</p>
<!-- /wp:paragraph -->
<!-- wp:wdl/lw-space-1 {"pcHeight":24,"tbHeight":20,"spHeight":16} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:24px"></div><div class="tb" style="height:20px"></div><div class="sp" style="height:16px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-pr-list-7 {"colorLiSvg":"#7f2a34","textColor":"#2f2a2b","colClass":"clm_1","columnWidths":[1],"columnWidthsSp":[1],"fontSizePc":16,"bgColor":"transparent","listGroups":[{"contents":[{"text":"お電話 000-0000-0000（8:30〜18:30・日曜休み）"},{"text":"見積りは無料。お車を15分お預かりします"},{"text":"車検が切れていても引き取りに伺います（市内無料）"}]}]} -->
<div class="wp-block-wdl-lw-pr-list-7 lw-pr-list-7" style="--list-7-gtc-pc:1fr;--list-7-gtc-sp:1fr;--list-7-inner-row-gap-pc:20px;--list-7-inner-column-gap-pc:20px;--list-7-inner-row-gap-sp:20px;--list-7-inner-column-gap-sp:20px;--list-7-row-gap-pc:20px;--list-7-column-gap-pc:20px;--list-7-row-gap-sp:20px;--list-7-column-gap-sp:20px;--list-7-font-size-pc:16px;--list-7-font-size-sp:16px"><div class="custom_inner"><ul class="lw-pr-list-7__inner clm_1" style="background-color:transparent"><li class="lw-pr-list-7__li"><span class="icon" style="width:1.2em"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" style="fill:#7f2a34"><path d="M64 80c-8.8 0-16 7.2-16 16l0 320c0 8.8 7.2 16 16 16l320 0c8.8 0 16-7.2 16-16l0-320c0-8.8-7.2-16-16-16L64 80zM0 96C0 60.7 28.7 32 64 32l320 0c35.3 0 64 28.7 64 64l0 320c0 35.3-28.7 64-64 64L64 480c-35.3 0-64-28.7-64-64L0 96zM337 209L209 337c-9.4 9.4-24.6 9.4-33.9 0l-64-64c-9.4-9.4-9.4-24.6 0-33.9s24.6-9.4 33.9 0l47 47L303 175c9.4-9.4 24.6-9.4 33.9 0s9.4 24.6 0 33.9z"></path></svg></span><span class="lw-pr-list-7__text"><p data-lw_font_set="" style="color:#2f2a2b;width:calc(100% - 1.2em)">お電話 000-0000-0000（8:30〜18:30・日曜休み）</p></span></li><li class="lw-pr-list-7__li"><span class="icon" style="width:1.2em"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" style="fill:#7f2a34"><path d="M64 80c-8.8 0-16 7.2-16 16l0 320c0 8.8 7.2 16 16 16l320 0c8.8 0 16-7.2 16-16l0-320c0-8.8-7.2-16-16-16L64 80zM0 96C0 60.7 28.7 32 64 32l320 0c35.3 0 64 28.7 64 64l0 320c0 35.3-28.7 64-64 64L64 480c-35.3 0-64-28.7-64-64L0 96zM337 209L209 337c-9.4 9.4-24.6 9.4-33.9 0l-64-64c-9.4-9.4-9.4-24.6 0-33.9s24.6-9.4 33.9 0l47 47L303 175c9.4-9.4 24.6-9.4 33.9 0s9.4 24.6 0 33.9z"></path></svg></span><span class="lw-pr-list-7__text"><p data-lw_font_set="" style="color:#2f2a2b;width:calc(100% - 1.2em)">見積りは無料。お車を15分お預かりします</p></span></li><li class="lw-pr-list-7__li"><span class="icon" style="width:1.2em"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" style="fill:#7f2a34"><path d="M64 80c-8.8 0-16 7.2-16 16l0 320c0 8.8 7.2 16 16 16l320 0c8.8 0 16-7.2 16-16l0-320c0-8.8-7.2-16-16-16L64 80zM0 96C0 60.7 28.7 32 64 32l320 0c35.3 0 64 28.7 64 64l0 320c0 35.3-28.7 64-64 64L64 480c-35.3 0-64-28.7-64-64L0 96zM337 209L209 337c-9.4 9.4-24.6 9.4-33.9 0l-64-64c-9.4-9.4-9.4-24.6 0-33.9s24.6-9.4 33.9 0l47 47L303 175c9.4-9.4 24.6-9.4 33.9 0s9.4 24.6 0 33.9z"></path></svg></span><span class="lw-pr-list-7__text"><p data-lw_font_set="" style="color:#2f2a2b;width:calc(100% - 1.2em)">車検が切れていても引き取りに伺います（市内無料）</p></span></li></ul></div></div>
<!-- /wp:wdl/lw-pr-list-7 --></div></div>
<!-- /wp:wdl/lw-bg-1 -->