<!-- wp:wdl/fv-7 {"subTitle":"SUPPORT","mainTitle":"動かないとき","description":"まず3つだけ確かめてください。それでも直らなければ、下の窓口へ。","buttonText":"窓口を見る","buttonUrl":"#madoguchi","showButton":true,"videoType":"media","videoUrl":"https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/v/fv7_default.mp4","filterColor":"#161a1f","filterOpacity":0.62,"videoSpeed":1,"headingLevel":1,"minHeightPc":"min-h-pc-480px","minHeightTb":"min-h-tb-400px","minHeightSp":"min-h-sp-340px"} -->
<div class="wp-block-wdl-fv-7 fv-7 min-h-pc-480px min-h-tb-400px min-h-sp-340px"><div class="fv-7__inner"><h1 class="title"><div class="sub">SUPPORT</div><div class="main">動かないとき</div></h1><p class="description">まず3つだけ確かめてください。それでも直らなければ、下の窓口へ。</p><div class="btn"><a href="#madoguchi" class="btn-text">窓口を見る</a></div></div><div class="bg_image"><video autoplay="" muted="" loop="" playsinline="" data-playback-rate="1" class="lazy-video" style="display:none"><source src="https://liteword-assets.bigi-ishikawa.workers.dev/t/fv/v/fv7_default.mp4" type="video/mp4"/></video><div class="filter" style="background-color:#161a1f;opacity:0.62"></div><script>
                                    document.addEventListener('DOMContentLoaded', function() {
                                        const video = document.querySelector('.fv-7 .lazy-video');
                                        if (video) {
                                            video.style.display = 'block';
                                            video.playbackRate = video.getAttribute('data-playback-rate');
                                        }
                                    });
                                    </script></div></div>
<!-- /wp:wdl/fv-7 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":80,"tbHeight":64,"spHeight":40} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:80px"></div><div class="tb" style="height:64px"></div><div class="sp" style="height:40px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/paid-block-custom-title-8 {"subTitle":"STEP 1","mainTitle":"まず、この3つ","headingLevel":2,"mainTitleColor":"#c2562c","borderLeftColor":"#c2562c","borderRightColor":"#c2562c","borderLeftOpacity":100,"borderRightOpacity":20,"borderRadius":10,"sizeClass":"size_m","positionClass":"position_left"} -->
<div class="wp-block-wdl-paid-block-custom-title-8 paid-block-custom-title-8 size_m  position_left"><h2 class="ttl"><span class="sub" style="color:#c2562c">STEP 1</span><span class="main">まず、この3つ</span><span class="border_wrap"><span class="border_inner" style="border-radius:10px"><span class="border left" style="background-color:#c2562c;opacity:1"></span><span class="border right" style="background-color:#c2562c;opacity:0.2"></span></span></span></h2></div>
<!-- /wp:wdl/paid-block-custom-title-8 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":16,"tbHeight":16,"spHeight":12} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:16px"></div><div class="tb" style="height:16px"></div><div class="sp" style="height:12px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:paragraph {"style":{"color":{"text":"#2c3138"},"typography":{"fontSize":"16px","lineHeight":"1.9"}}} -->
<p class="has-text-color" style="color:#2c3138;font-size:16px;line-height:1.9">お問い合わせいただくご相談の<strong>6割ちかく</strong>が、この3つのどれかで直っています。1分で終わりますので、先にお試しください。</p>
<!-- /wp:paragraph -->
<!-- wp:wdl/lw-space-1 {"pcHeight":24,"tbHeight":20,"spHeight":16} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:24px"></div><div class="tb" style="height:20px"></div><div class="sp" style="height:16px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-pr-list-7 {"colorLiSvg":"#363d47","textColor":"#2c3138","colClass":"clm_1","columnWidths":[1],"columnWidthsSp":[1],"fontSizePc":16,"bgColor":"transparent","listGroups":[{"contents":[{"text":"アプリをいったん閉じて、開き直す（裏で止まっていることがあります）"},{"text":"通信を切り替える（Wi-Fi ↔ モバイル回線）"},{"text":"アプリの更新があるか確かめる（古いままだと動かない機能があります）"}]}]} -->
<div class="wp-block-wdl-lw-pr-list-7 lw-pr-list-7" style="--list-7-gtc-pc:1fr;--list-7-gtc-sp:1fr;--list-7-inner-row-gap-pc:20px;--list-7-inner-column-gap-pc:20px;--list-7-inner-row-gap-sp:20px;--list-7-inner-column-gap-sp:20px;--list-7-row-gap-pc:20px;--list-7-column-gap-pc:20px;--list-7-row-gap-sp:20px;--list-7-column-gap-sp:20px;--list-7-font-size-pc:16px;--list-7-font-size-sp:16px"><div class="custom_inner"><ul class="lw-pr-list-7__inner clm_1" style="background-color:transparent"><li class="lw-pr-list-7__li"><span class="icon" style="width:1.2em"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" style="fill:#363d47"><path d="M64 80c-8.8 0-16 7.2-16 16l0 320c0 8.8 7.2 16 16 16l320 0c8.8 0 16-7.2 16-16l0-320c0-8.8-7.2-16-16-16L64 80zM0 96C0 60.7 28.7 32 64 32l320 0c35.3 0 64 28.7 64 64l0 320c0 35.3-28.7 64-64 64L64 480c-35.3 0-64-28.7-64-64L0 96zM337 209L209 337c-9.4 9.4-24.6 9.4-33.9 0l-64-64c-9.4-9.4-9.4-24.6 0-33.9s24.6-9.4 33.9 0l47 47L303 175c9.4-9.4 24.6-9.4 33.9 0s9.4 24.6 0 33.9z"></path></svg></span><span class="lw-pr-list-7__text"><p data-lw_font_set="" style="color:#2c3138;width:calc(100% - 1.2em)">アプリをいったん閉じて、開き直す（裏で止まっていることがあります）</p></span></li><li class="lw-pr-list-7__li"><span class="icon" style="width:1.2em"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" style="fill:#363d47"><path d="M64 80c-8.8 0-16 7.2-16 16l0 320c0 8.8 7.2 16 16 16l320 0c8.8 0 16-7.2 16-16l0-320c0-8.8-7.2-16-16-16L64 80zM0 96C0 60.7 28.7 32 64 32l320 0c35.3 0 64 28.7 64 64l0 320c0 35.3-28.7 64-64 64L64 480c-35.3 0-64-28.7-64-64L0 96zM337 209L209 337c-9.4 9.4-24.6 9.4-33.9 0l-64-64c-9.4-9.4-9.4-24.6 0-33.9s24.6-9.4 33.9 0l47 47L303 175c9.4-9.4 24.6-9.4 33.9 0s9.4 24.6 0 33.9z"></path></svg></span><span class="lw-pr-list-7__text"><p data-lw_font_set="" style="color:#2c3138;width:calc(100% - 1.2em)">通信を切り替える（Wi-Fi ↔ モバイル回線）</p></span></li><li class="lw-pr-list-7__li"><span class="icon" style="width:1.2em"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" style="fill:#363d47"><path d="M64 80c-8.8 0-16 7.2-16 16l0 320c0 8.8 7.2 16 16 16l320 0c8.8 0 16-7.2 16-16l0-320c0-8.8-7.2-16-16-16L64 80zM0 96C0 60.7 28.7 32 64 32l320 0c35.3 0 64 28.7 64 64l0 320c0 35.3-28.7 64-64 64L64 480c-35.3 0-64-28.7-64-64L0 96zM337 209L209 337c-9.4 9.4-24.6 9.4-33.9 0l-64-64c-9.4-9.4-9.4-24.6 0-33.9s24.6-9.4 33.9 0l47 47L303 175c9.4-9.4 24.6-9.4 33.9 0s9.4 24.6 0 33.9z"></path></svg></span><span class="lw-pr-list-7__text"><p data-lw_font_set="" style="color:#2c3138;width:calc(100% - 1.2em)">アプリの更新があるか確かめる（古いままだと動かない機能があります）</p></span></li></ul></div></div>
<!-- /wp:wdl/lw-pr-list-7 -->
<!-- wp:paragraph {"align":"center","style":{"color":{"text":"#5c6570"},"typography":{"fontSize":"14px","lineHeight":"1.9"},"spacing":{"margin":{"top":"32px","bottom":"0px"}}}} -->
<p class="has-text-align-center has-text-color" style="color:#5c6570;font-size:14px;line-height:1.9;margin-top:32px;margin-bottom:0px">※ 端末の再起動まではしていただかなくて結構です。</p>
<!-- /wp:paragraph -->
<!-- wp:wdl/lw-space-1 {"pcHeight":80,"tbHeight":64,"spHeight":40} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:80px"></div><div class="tb" style="height:64px"></div><div class="sp" style="height:40px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/paid-block-custom-title-8 {"subTitle":"STEP 2","mainTitle":"症状からさがす","headingLevel":2,"mainTitleColor":"#c2562c","borderLeftColor":"#c2562c","borderRightColor":"#c2562c","borderLeftOpacity":100,"borderRightOpacity":20,"borderRadius":10,"sizeClass":"size_m","positionClass":"position_left"} -->
<div class="wp-block-wdl-paid-block-custom-title-8 paid-block-custom-title-8 size_m  position_left"><h2 class="ttl"><span class="sub" style="color:#c2562c">STEP 2</span><span class="main">症状からさがす</span><span class="border_wrap"><span class="border_inner" style="border-radius:10px"><span class="border left" style="background-color:#c2562c;opacity:1"></span><span class="border right" style="background-color:#c2562c;opacity:0.2"></span></span></span></h2></div>
<!-- /wp:wdl/paid-block-custom-title-8 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":16,"tbHeight":16,"spHeight":12} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:16px"></div><div class="tb" style="height:16px"></div><div class="sp" style="height:12px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:paragraph {"style":{"color":{"text":"#2c3138"},"typography":{"fontSize":"16px","lineHeight":"1.9"}}} -->
<p class="has-text-color" style="color:#2c3138;font-size:16px;line-height:1.9">よくいただく症状と、その場でできることです。</p>
<!-- /wp:paragraph -->
<!-- wp:wdl/lw-space-1 {"pcHeight":24,"tbHeight":20,"spHeight":16} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:24px"></div><div class="tb" style="height:20px"></div><div class="sp" style="height:16px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-pr-qa-3 {"maxWidth":940,"qLabelColor":"#363d47","aLabelColor":"#5c6570","lineColor":"#dde1e6"} -->
<div class="wp-block-wdl-lw-pr-qa-3 lw-pr-qa-3" style="--qa3-max-w:940px;--qa3-gap:24px;--qa3-label-w:32px;--qa3-q-color:#363d47;--qa3-a-color:#5c6570;--qa3-line:#dde1e6;--qa3-label-size-pc:18px;--qa3-label-size-sp:16px;--qa3-q-size-pc:17px;--qa3-q-size-sp:15px;--qa3-a-size-pc:15px;--qa3-a-size-sp:14px"><dl class="qa-3__item"><dt><span class="label" data-lw_font_set="Roboto">Q</span><p class="qa-3__q_text">ログインできない</p></dt><dd><span class="label" data-lw_font_set="Roboto">A</span><p class="qa-3__a_text">パスワードを3回間違えると、15分のあいだ入れなくなります。時間をおいてからお試しください。メールアドレスをお忘れの場合は、窓口でお調べします。</p></dd></dl><dl class="qa-3__item"><dt><span class="label" data-lw_font_set="Roboto">Q</span><p class="qa-3__q_text">画面が真っ白のまま</p></dt><dd><span class="label" data-lw_font_set="Roboto">A</span><p class="qa-3__a_text">通信が切れかけていることがほとんどです。Wi-Fi を切ってお試しください。それでも変わらなければ、こちら側で止まっている可能性があります（下の障害情報をご覧ください）。</p></dd></dl><dl class="qa-3__item"><dt><span class="label" data-lw_font_set="Roboto">Q</span><p class="qa-3__q_text">データが消えた</p></dt><dd><span class="label" data-lw_font_set="Roboto">A</span><p class="qa-3__a_text">ご自身で消された場合をのぞき、30日間はこちらに残っています。窓口へご連絡いただければ戻せます。ご自身での復元はできません。</p></dd></dl><dl class="qa-3__item"><dt><span class="label" data-lw_font_set="Roboto">Q</span><p class="qa-3__q_text">通知が来ない</p></dt><dd><span class="label" data-lw_font_set="Roboto">A</span><p class="qa-3__a_text">端末の設定で通知が切られていることが多いです。アプリ内の設定と、端末の設定の<strong>両方</strong>を確かめてください。</p></dd></dl><dl class="qa-3__item"><dt><span class="label" data-lw_font_set="Roboto">Q</span><p class="qa-3__q_text">文字が入力できない</p></dt><dd><span class="label" data-lw_font_set="Roboto">A</span><p class="qa-3__a_text">一部の日本語入力アプリと相性の悪い画面があります。入力アプリを変えるか、窓口へ「どの画面か」をお知らせください。</p></dd></dl><dl class="qa-3__item"><dt><span class="label" data-lw_font_set="Roboto">Q</span><p class="qa-3__q_text">解約したい</p></dt><dd><span class="label" data-lw_font_set="Roboto">A</span><p class="qa-3__a_text">アプリの設定 → お客さま情報 → 解約 から、いつでも手続きできます。引き止めのご連絡はいたしません。日割りの返金はありません。</p></dd></dl></div>
<!-- /wp:wdl/lw-pr-qa-3 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":80,"tbHeight":64,"spHeight":40} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:80px"></div><div class="tb" style="height:64px"></div><div class="sp" style="height:40px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/paid-block-custom-title-8 {"subTitle":"STEP 3","mainTitle":"それでも直らないとき","headingLevel":2,"mainTitleColor":"#c2562c","borderLeftColor":"#c2562c","borderRightColor":"#c2562c","borderLeftOpacity":100,"borderRightOpacity":20,"borderRadius":10,"sizeClass":"size_m","positionClass":"position_left"} -->
<div class="wp-block-wdl-paid-block-custom-title-8 paid-block-custom-title-8 size_m  position_left" id="madoguchi"><h2 class="ttl"><span class="sub" style="color:#c2562c">STEP 3</span><span class="main">それでも直らないとき</span><span class="border_wrap"><span class="border_inner" style="border-radius:10px"><span class="border left" style="background-color:#c2562c;opacity:1"></span><span class="border right" style="background-color:#c2562c;opacity:0.2"></span></span></span></h2></div>
<!-- /wp:wdl/paid-block-custom-title-8 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":16,"tbHeight":16,"spHeight":12} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:16px"></div><div class="tb" style="height:16px"></div><div class="sp" style="height:12px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:paragraph {"style":{"color":{"text":"#2c3138"},"typography":{"fontSize":"16px","lineHeight":"1.9"}}} -->
<p class="has-text-color" style="color:#2c3138;font-size:16px;line-height:1.9">窓口は3つあります。<strong>どれも同じ担当が見ています</strong>ので、いちばん使いやすいものをお選びください。</p>
<!-- /wp:paragraph -->
<!-- wp:wdl/lw-space-1 {"pcHeight":24,"tbHeight":20,"spHeight":16} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:24px"></div><div class="tb" style="height:20px"></div><div class="sp" style="height:16px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-pr-table-2 {"dtFixedPc":true,"dtWidthPc":180,"dtWidthSp":150,"defaultSpClm1":true,"dlBorderColor":"#dde1e6","rowBorderColor":"#dde1e6","dtBorderColor":"#dde1e6","dtBgColor":"#f1f3f5","dtTextColor":"#22272e","ddTextColor":"#2c3138","dtFontWeight":"600","fontSizePc":17,"fontSizeSp":15,"cellPaddingPc":16,"rows":[{"dtText":"アプリ内から","ddText":"設定 → お問い合わせ。\u003cstrong\u003eいちばん早く解決します\u003c/strong\u003e（お使いの端末と、いつ何が起きたかが自動で送られるため）。受付24時間・返信は平日中に。","pcClm1":null,"spClm1":null,"bgColor":"","textColor":""},{"dtText":"メール","ddText":"support@example.com。24時間お受けします。返信は1営業日以内。\u003cstrong\u003e件名にご登録のメールアドレス\u003c/strong\u003eを入れていただけると早くなります。","pcClm1":null,"spClm1":null,"bgColor":"","textColor":""},{"dtText":"お電話","ddText":"000-0000-0000（平日 10:00〜17:00）。お急ぎのとき向けです。お手元に端末をご用意ください。","pcClm1":null,"spClm1":null,"bgColor":"","textColor":""}]} -->
<div class="wp-block-wdl-lw-pr-table-2 lw-pr-table-2" style="--table-2-dl-width-pc:100%;--table-2-dl-width-sp:100%;--table-2-grid-columns-pc:180px calc(100% - 180px);--table-2-grid-columns-sp:1fr 1fr;--table-2-dl-border-color:#dde1e6;--table-2-dl-border-style:solid;--table-2-dl-border-width:1px;--table-2-dl-border-individual:0;--table-2-dl-border-top-color:#dde1e6;--table-2-dl-border-top-style:solid;--table-2-dl-border-top-width:1px;--table-2-dl-border-bottom-color:#dde1e6;--table-2-dl-border-bottom-style:solid;--table-2-dl-border-bottom-width:1px;--table-2-dl-border-left-color:#dde1e6;--table-2-dl-border-left-style:solid;--table-2-dl-border-left-width:1px;--table-2-dl-border-right-color:#dde1e6;--table-2-dl-border-right-style:solid;--table-2-dl-border-right-width:1px;--table-2-row-border-color:#dde1e6;--table-2-row-border-style:solid;--table-2-row-border-width:1px;--table-2-dt-border-color:#dde1e6;--table-2-dt-border-style:solid;--table-2-dt-border-width:1px;--table-2-dt-bg-color:#f1f3f5;--table-2-cell-padding-pc:16px;--table-2-cell-padding-sp:16px;--table-2-font-size-pc:17px;--table-2-font-size-sp:15px;--table-2-dt-align-pc:left;--table-2-dt-align-sp:left;--table-2-dd-align-pc:left;--table-2-dd-align-sp:left;--table-2-dt-text-color:#22272e;--table-2-dd-text-color:#2c3138"><dl class="table-2__dl"><div class="table-2__row sp_clm_1"><dt class="table-2__dt"><p data-lw_font_set="" style="font-weight:600">アプリ内から</p></dt><dd class="table-2__dd"><p data-lw_font_set="">設定 → お問い合わせ。<strong>いちばん早く解決します</strong>（お使いの端末と、いつ何が起きたかが自動で送られるため）。受付24時間・返信は平日中に。</p></dd></div><div class="table-2__row sp_clm_1"><dt class="table-2__dt"><p data-lw_font_set="" style="font-weight:600">メール</p></dt><dd class="table-2__dd"><p data-lw_font_set="">support@example.com。24時間お受けします。返信は1営業日以内。<strong>件名にご登録のメールアドレス</strong>を入れていただけると早くなります。</p></dd></div><div class="table-2__row sp_clm_1"><dt class="table-2__dt"><p data-lw_font_set="" style="font-weight:600">お電話</p></dt><dd class="table-2__dd"><p data-lw_font_set="">000-0000-0000（平日 10:00〜17:00）。お急ぎのとき向けです。お手元に端末をご用意ください。</p></dd></div></dl></div>
<!-- /wp:wdl/lw-pr-table-2 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":40,"tbHeight":32,"spHeight":24} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:40px"></div><div class="tb" style="height:32px"></div><div class="sp" style="height:24px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-pr-waku-1 {"waku1MaxWidthPc":900,"waku1PaddingTopPc":28,"waku1PaddingBottomPc":28,"waku1PaddingLeftPc":32,"waku1PaddingRightPc":32,"waku1PaddingTopSp":20,"waku1PaddingBottomSp":20,"waku1PaddingLeftSp":16,"waku1PaddingRightSp":16,"waku1BorderWidthPc":1,"waku1BorderColorPc":"#c2562c","waku1BorderRadiusPc":[8,8,8,8],"waku1BgColorPc":"#f1f3f5"} -->
<div class="wp-block-wdl-lw-pr-waku-1 lw-pr-waku-1" style="--waku-1-justify-content-pc:center;--waku-1-justify-content-sp:center"><div class="lw-pr-waku-1__custom_wrap" style="--waku-1-max-width-pc:900px;--waku-1-max-width-sp:900px;--waku-1-padding-pc:28px 32px 28px 32px;--waku-1-padding-sp:20px 16px 20px 16px;--waku-1-bd-width-pc:1px;--waku-1-bd-width-sp:1px;--waku-1-bd-style-pc:solid;--waku-1-bd-style-sp:solid;--waku-1-bd-color-pc:#c2562c;--waku-1-bd-color-sp:#c2562c;--waku-1-bdr-pc:8px 8px 8px 8px;--waku-1-bdr-sp:8px 8px 8px 8px;--waku-1-bg-pc:#f1f3f5;--waku-1-bg-sp:#f1f3f5;--waku-1-bg-opacity-pc:1;--waku-1-bg-opacity-sp:1;--waku-1-blend-mode-pc:normal;--waku-1-blend-mode-sp:normal;--waku-1-bg-img-pc:none;--waku-1-bg-img-sp:none;--waku-1-img-filter-pc:none;--waku-1-img-filter-sp:none;--waku-1-min-height-pc:auto;--waku-1-min-height-sp:auto;--waku-1-aspect-ratio-pc:auto;--waku-1-aspect-ratio-sp:auto"><!-- wp:heading {"level":3,"style":{"color":{"text":"#22272e"},"typography":{"fontSize":"18px","lineHeight":"1.6"},"spacing":{"margin":{"top":"0px","bottom":"12px"}}},"textAlign":"center"} -->
<h3 class="has-text-align-center has-text-color" style="color:#22272e;font-size:18px;line-height:1.6;margin-top:0px;margin-bottom:12px">お知らせいただけると早いこと</h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"style":{"color":{"text":"#2c3138"},"typography":{"fontSize":"16px","lineHeight":"1.9"},"spacing":{"margin":{"top":"0px","bottom":"0px"}}}} -->
<p class="has-text-color" style="color:#2c3138;font-size:16px;line-height:1.9;margin-top:0px;margin-bottom:0px"><strong>いつ</strong>（日付と、だいたいの時刻）</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"style":{"color":{"text":"#2c3138"},"typography":{"fontSize":"16px","lineHeight":"1.9"},"spacing":{"margin":{"top":"14px","bottom":"0px"}}}} -->
<p class="has-text-color" style="color:#2c3138;font-size:16px;line-height:1.9;margin-top:14px;margin-bottom:0px"><strong>どの画面で</strong>（画面の名前か、スクリーンショット1枚）</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"style":{"color":{"text":"#2c3138"},"typography":{"fontSize":"16px","lineHeight":"1.9"},"spacing":{"margin":{"top":"14px","bottom":"0px"}}}} -->
<p class="has-text-color" style="color:#2c3138;font-size:16px;line-height:1.9;margin-top:14px;margin-bottom:0px"><strong>何をしたら</strong>そうなったか</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"style":{"color":{"text":"#2c3138"},"typography":{"fontSize":"16px","lineHeight":"1.9"},"spacing":{"margin":{"top":"14px","bottom":"0px"}}}} -->
<p class="has-text-color" style="color:#2c3138;font-size:16px;line-height:1.9;margin-top:14px;margin-bottom:0px">お使いの端末（iPhone / Android / パソコン）</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:wdl/lw-pr-waku-1 -->
<!-- wp:paragraph {"align":"center","style":{"color":{"text":"#5c6570"},"typography":{"fontSize":"14px","lineHeight":"1.9"},"spacing":{"margin":{"top":"16px","bottom":"0px"}}}} -->
<p class="has-text-align-center has-text-color" style="color:#5c6570;font-size:14px;line-height:1.9;margin-top:16px;margin-bottom:0px">※ 分かる範囲で構いません。「よく分からない」でもお受けします。</p>
<!-- /wp:paragraph -->
<!-- wp:wdl/lw-space-1 {"pcHeight":80,"tbHeight":64,"spHeight":40} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:80px"></div><div class="tb" style="height:64px"></div><div class="sp" style="height:40px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-bg-1 {"backgroundType":"image","imagePc":"","imageSp":"","isFullWidth":true,"maxWidth":1040,"minHeightPc":"min-h-pc-150px","minHeightTb":"min-h-tb-160px","minHeightSp":"min-h-sp-160px","innerPaddingTopPc":80,"innerPaddingBottomPc":80,"innerPaddingLeftPc":40,"innerPaddingRightPc":40,"innerPaddingTopTb":64,"innerPaddingBottomTb":64,"innerPaddingLeftTb":32,"innerPaddingRightTb":32,"innerPaddingTopSp":48,"innerPaddingBottomSp":48,"innerPaddingLeftSp":20,"innerPaddingRightSp":20,"filterTypePc":"solid","filterColorPc":"#22272e","opacityPc":1,"filterTypeTb":"solid","filterColorTb":"#22272e","opacityTb":1,"filterTypeSp":"solid","filterColorSp":"#22272e","opacitySp":1} -->
<div class="wp-block-wdl-lw-bg-1 lw-bg-1 min-h-pc-150px min-h-tb-160px min-h-sp-160px bg_all" style="--lw-bg-color-filter-pc:#22272e;--lw-bg-opacity-pc:1;--lw-bg-color-filter-tb:#22272e;--lw-bg-opacity-tb:1;--lw-bg-color-filter-sp:#22272e;--lw-bg-opacity-sp:1;--lw-bg-position-pc:50% 50%;--lw-bg-position-sp:50% 50%;--lw-bg-wrap-centering-pc:center;--lw-bg-wrap-align-pc:center;--lw-bg-wrap-centering-tb:center;--lw-bg-wrap-align-tb:center;--lw-bg-wrap-centering-sp:center;--lw-bg-wrap-align-sp:center"><div class="lw-bg-1-wrap" style="--lw-bg-padding-top-pc:80px;--lw-bg-padding-bottom-pc:80px;--lw-bg-padding-left-pc:40px;--lw-bg-padding-right-pc:40px;--lw-bg-padding-top-tb:64px;--lw-bg-padding-bottom-tb:64px;--lw-bg-padding-left-tb:32px;--lw-bg-padding-right-tb:32px;--lw-bg-padding-top-sp:48px;--lw-bg-padding-bottom-sp:48px;--lw-bg-padding-left-sp:20px;--lw-bg-padding-right-sp:20px;--lw-bg-max-width:1040px"><!-- wp:heading {"level":3,"style":{"color":{"text":"#ffffff"},"typography":{"fontSize":"24px","lineHeight":"1.6"},"spacing":{"margin":{"top":"0px","bottom":"16px"}}},"textAlign":"center"} -->
<h3 class="has-text-align-center has-text-color" style="color:#ffffff;font-size:24px;line-height:1.6;margin-top:0px;margin-bottom:16px">こちらで止まっているとき</h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"style":{"color":{"text":"#ffffff"},"typography":{"fontSize":"16px","lineHeight":"1.9"}},"align":"center"} -->
<p class="has-text-align-center has-text-color" style="color:#ffffff;font-size:16px;line-height:1.9">多くの方に同時に起きている場合は、お問い合わせをいただく前にこちらから出しています。まずご確認ください。</p>
<!-- /wp:paragraph -->
<!-- wp:wdl/lw-space-1 {"pcHeight":24,"tbHeight":20,"spHeight":16} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:24px"></div><div class="tb" style="height:20px"></div><div class="sp" style="height:16px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-pr-button-6 {"button6Buttons":[{"text":"障害情報を見る","url":"#","isBlank":false},{"text":"メンテナンスの予定","url":"#","isBlank":false}],"button6MaxWidthPc":640,"button6ColumnsPc":2,"button6ColumnsSp":1,"button6MinHeightPc":62,"button6MinHeightSp":56,"button6FontSizePc":16,"button6FontSizeSp":15,"button6BorderWidthPc":0,"button6BorderColor":"#ffffff","button6TextColor":"#ffffff","button6BgColor":"#c2562c","button6BorderRadiusPc":4,"button6ShowArrow":true,"button6ArrowColor":"#ffffff","button6PositionPc":"center"} -->
<div class="wp-block-wdl-lw-pr-button-6 lw-pr-button-6"><div class="lw-pr-button-6__wrap" style="--button-6-max-width-pc:640px;--button-6-max-width-sp:640px;--button-6-gtc-pc:2;--button-6-gtc-sp:1;--button-6-row-gap-pc:16px;--button-6-row-gap-sp:16px;--button-6-column-gap-pc:24px;--button-6-column-gap-sp:8px;--button-6-item-padding-pc:12px 12px 12px 12px;--button-6-item-padding-sp:12px 12px 12px 12px;--button-6-item-min-height-pc:62px;--button-6-item-min-height-sp:56px;--button-6-item-position-pc:center;--button-6-item-position-sp:center;--button-6-item-fontsize-pc:16px;--button-6-item-fontsize-sp:15px;--button-6-item-bd-width-pc:0px;--button-6-item-bd-width-sp:1px;--button-6-item-border-style:solid;--button-6-item-border-color:#ffffff;--button-6-item-text-color:#ffffff;--button-6-item-border-radius-pc:4px;--button-6-item-border-radius-sp:4px;--button-6-item-bg-color:#c2562c;--button-6-item-text-align:center"><a href="#" class="lw-pr-button-6__item"><div class="lw-pr-button-6__item_text" data-lw_font_set="">障害情報を見る</div><span class="icon" style="fill:#ffffff"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 640"><path d="M471.1 297.4C483.6 309.9 483.6 330.2 471.1 342.7L279.1 534.7C266.6 547.2 246.3 547.2 233.8 534.7C221.3 522.2 221.3 501.9 233.8 489.4L403.2 320L233.9 150.6C221.4 138.1 221.4 117.8 233.9 105.3C246.4 92.8 266.7 92.8 279.2 105.3L471.2 297.3z"></path></svg></span></a><a href="#" class="lw-pr-button-6__item"><div class="lw-pr-button-6__item_text" data-lw_font_set="">メンテナンスの予定</div><span class="icon" style="fill:#ffffff"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 640"><path d="M471.1 297.4C483.6 309.9 483.6 330.2 471.1 342.7L279.1 534.7C266.6 547.2 246.3 547.2 233.8 534.7C221.3 522.2 221.3 501.9 233.8 489.4L403.2 320L233.9 150.6C221.4 138.1 221.4 117.8 233.9 105.3C246.4 92.8 266.7 92.8 279.2 105.3L471.2 297.3z"></path></svg></span></a></div></div>
<!-- /wp:wdl/lw-pr-button-6 -->
<!-- wp:paragraph {"style":{"color":{"text":"#d7dbe0"},"typography":{"fontSize":"14px","lineHeight":"1.9"},"spacing":{"margin":{"top":"16px","bottom":"0px"}}},"align":"center"} -->
<p class="has-text-align-center has-text-color" style="color:#d7dbe0;font-size:14px;line-height:1.9;margin-top:16px;margin-bottom:0px">※ 障害のご報告をいただいた場合も、復旧まで個別のお返事はできません。ご了承ください。</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:wdl/lw-bg-1 -->