<!-- wp:wdl/fv-4 {"mainTitle":"この店を始めた理由","subTitle":"2018年、駅から離れた通りで","description":"花が好きだから、という話ではありません。始めてからのほうが、分からないことばかりでした。","backgroundImage":"https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/fl_cta.webp","backgroundImageSp":"","filterBackgroundColor":"#3f2018","filterOpacity":0.66,"textColor":"#ffffff","textAlignPc":"pc_left","textAlignSp":"sp_left","maxWidth":1040,"headingLevel":1,"mainFontSizePc":42,"mainFontSizeSp":28,"minHeightPc":"min-h-pc-440px","minHeightTb":"min-h-tb-380px","minHeightSp":"min-h-sp-320px"} -->
<div class="wp-block-wdl-fv-4 fv-4 min-h-pc-440px min-h-tb-380px min-h-sp-320px"><div class="fv-4_inner pc_left sp_left" style="max-width:1040px;--fv4-main-pc:42px;--fv4-main-sp:28px"><h1 class="ttl" style="color:#ffffff"><span class="sub" style="color:#ffffff">2018年、駅から離れた通りで</span><span class="main" style="color:#ffffff">この店を始めた理由</span></h1><p style="color:#ffffff">花が好きだから、という話ではありません。始めてからのほうが、分からないことばかりでした。</p></div><div class="filter" style="background-color:#3f2018;opacity:0.66"></div><picture class="bg_image"><source srcSet="" media="(max-width: 800px)"/><source srcSet="https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/fl_cta.webp" media="(min-width: 801px)"/><img src="https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/fl_cta.webp" alt="背景画像" loading="eager" fetchpriority="high"/></picture></div>
<!-- /wp:wdl/fv-4 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":80,"tbHeight":64,"spHeight":40} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:80px"></div><div class="tb" style="height:64px"></div><div class="sp" style="height:40px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/paid-block-custom-title-8 {"subTitle":"THE BEGINNING","mainTitle":"この店のはじまり","headingLevel":2,"mainTitleColor":"#6a3123","borderLeftColor":"#b0604a","borderRightColor":"#b0604a","borderLeftOpacity":100,"borderRightOpacity":25,"borderRadius":4,"sizeClass":"size_m","positionClass":"position_left","sizeSpClass":"size_s"} -->
<div class="wp-block-wdl-paid-block-custom-title-8 paid-block-custom-title-8 size_m size_s position_left"><h2 class="ttl"><span class="sub" style="color:#6a3123">THE BEGINNING</span><span class="main">この店のはじまり</span><span class="border_wrap"><span class="border_inner" style="border-radius:4px"><span class="border left" style="background-color:#b0604a;opacity:1"></span><span class="border right" style="background-color:#b0604a;opacity:0.25"></span></span></span></h2></div>
<!-- /wp:wdl/paid-block-custom-title-8 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":16,"tbHeight":16,"spHeight":12} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:16px"></div><div class="tb" style="height:16px"></div><div class="sp" style="height:12px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:paragraph {"align":"center","style":{"color":{"text":"#3b342f"},"typography":{"fontSize":"16px","lineHeight":"2"},"spacing":{"margin":{"top":"28px","bottom":"24px"}}}} -->
<p class="has-text-align-center has-text-color" style="color:#3b342f;font-size:16px;line-height:2;margin-top:28px;margin-bottom:24px">花が好きだったから、ではありません。</p>
<!-- /wp:paragraph -->
<!-- wp:wdl/paid-block-content-5 {"pcImage":"https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/fl_owner.webp","spImage":"","imgAlt":"店主","pcTitle":"いつも花があった家","spTitle":"はじまり","pcBody":"実家は花とは関係のない仕事でした。花が身近にあったのは、祖母の家です。玄関にいつも一輪だけ挿してあって、それが枯れる前に必ず入れ替わっていました。子どものころは何とも思っていませんでしたが、祖母が入院して家に誰もいなくなったとき、玄関の花瓶が空のままになっているのを見て、はじめて意味が分かった気がしました。\u003cbr\u003e\u003cbr\u003e会社勤めをしていた28歳のとき、休みの日に花屋で働かせてもらうようになりました。3年たって「自分の店をやりたい」と言ったら、そこの店主に「まず在庫で泣きなさい」と言われました。その意味も、始めてから分かりました。","textColumns":"2","headingLevel":2,"verticalCenter":false,"aspectRatioHeight":650,"contsMaxWidth":1200,"pcTitleColor":"#6a3123","spTitleColor":"#ffffff","imgLabel":"店主","spImageBottom":true} -->
<div class="wp-block-wdl-paid-block-content-5 paid-block-content-5 is_sp_img_bottom"><div class="conts" style="max-width:1200px"><figure class="image"><img class="none_800px" style="aspect-ratio:500 / 650" src="https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/fl_owner.webp" alt="店主"/><img class="on_800px" src="https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/fl_owner.webp" alt="店主"/><h2 class="ttl" style="font-weight:500;color:#ffffff" data-lw_font_set="">はじまり</h2><span class="img_label">店主</span></figure><div class="cont"><h2 class="ttl" style="color:#6a3123">いつも花があった家</h2><div class="in"><p style="column-count:2;column-gap:1.5em">実家は花とは関係のない仕事でした。花が身近にあったのは、祖母の家です。玄関にいつも一輪だけ挿してあって、それが枯れる前に必ず入れ替わっていました。子どものころは何とも思っていませんでしたが、祖母が入院して家に誰もいなくなったとき、玄関の花瓶が空のままになっているのを見て、はじめて意味が分かった気がしました。<br><br>会社勤めをしていた28歳のとき、休みの日に花屋で働かせてもらうようになりました。3年たって「自分の店をやりたい」と言ったら、そこの店主に「まず在庫で泣きなさい」と言われました。その意味も、始めてから分かりました。</p></div></div></div></div>
<!-- /wp:wdl/paid-block-content-5 -->
<!-- wp:wdl/paid-block-custom-title-8 {"subTitle":"THE FIRST YEAR","mainTitle":"思っていたのと違ったこと","headingLevel":2,"mainTitleColor":"#6a3123","borderLeftColor":"#b0604a","borderRightColor":"#b0604a","borderLeftOpacity":100,"borderRightOpacity":25,"borderRadius":4,"sizeClass":"size_m","positionClass":"position_left","sizeSpClass":"size_s"} -->
<div class="wp-block-wdl-paid-block-custom-title-8 paid-block-custom-title-8 size_m size_s position_left"><h2 class="ttl"><span class="sub" style="color:#6a3123">THE FIRST YEAR</span><span class="main">思っていたのと違ったこと</span><span class="border_wrap"><span class="border_inner" style="border-radius:4px"><span class="border left" style="background-color:#b0604a;opacity:1"></span><span class="border right" style="background-color:#b0604a;opacity:0.25"></span></span></span></h2></div>
<!-- /wp:wdl/paid-block-custom-title-8 -->
<!-- wp:wdl/paid-block-content-6 {"alignRight":false,"imageUrl":"https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/fl_shop.webp","imageAlt":"店内の様子","textContent":"\u003cstrong style=\"display:block;font-size:20px;margin-bottom:10px;color:#6a3123\"\u003e半分を捨てていました\u003c/strong\u003e開けて最初の年は、仕入れた花の半分近くを捨てていました。売れる本数が読めないので、足りないよりはと多めに取ってしまうのです。朝に水を替えて、夕方にだめになったものを抜いて、閉店後に数えて、その数字を見るのが毎日いちばんつらい時間でした。\u003cbr\u003e\u003cbr\u003e「花が好き」で始めたのに、いちばん長く向き合っていたのは捨てる作業でした。","showButton":false,"buttonText":"","buttonUrl":"","buttonRadius":0} -->
<div class="wp-block-wdl-paid-block-content-6 paid-block-content-6"><div class="this_wrap left_img"><div class="image"><figure><img src="https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/fl_shop.webp" alt="店内の様子"/></figure></div><div class="cont"><p><strong style="display:block;font-size:20px;margin-bottom:10px;color:#6a3123">半分を捨てていました</strong>開けて最初の年は、仕入れた花の半分近くを捨てていました。売れる本数が読めないので、足りないよりはと多めに取ってしまうのです。朝に水を替えて、夕方にだめになったものを抜いて、閉店後に数えて、その数字を見るのが毎日いちばんつらい時間でした。<br><br>「花が好き」で始めたのに、いちばん長く向き合っていたのは捨てる作業でした。</p></div></div></div>
<!-- /wp:wdl/paid-block-content-6 -->
<!-- wp:wdl/paid-block-custom-title-8 {"subTitle":"THE TURNING POINT","mainTitle":"やり方を変えた日","headingLevel":2,"mainTitleColor":"#6a3123","borderLeftColor":"#b0604a","borderRightColor":"#b0604a","borderLeftOpacity":100,"borderRightOpacity":25,"borderRadius":4,"sizeClass":"size_m","positionClass":"position_left","sizeSpClass":"size_s"} -->
<div class="wp-block-wdl-paid-block-custom-title-8 paid-block-custom-title-8 size_m size_s position_left"><h2 class="ttl"><span class="sub" style="color:#6a3123">THE TURNING POINT</span><span class="main">やり方を変えた日</span><span class="border_wrap"><span class="border_inner" style="border-radius:4px"><span class="border left" style="background-color:#b0604a;opacity:1"></span><span class="border right" style="background-color:#b0604a;opacity:0.25"></span></span></span></h2></div>
<!-- /wp:wdl/paid-block-custom-title-8 -->
<!-- wp:wdl/paid-block-content-6 {"alignRight":true,"imageUrl":"https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/fl_work.webp","imageAlt":"花を束ねているところ","textContent":"\u003cstrong style=\"display:block;font-size:20px;margin-bottom:10px;color:#6a3123\"\u003e「今日は無い」と言うことにした\u003c/strong\u003e2年目の春、常連の方に「明日、母に持っていきたい」と言われて、その場で在庫を見て「今日は良いものが無いので、明日の朝に入る分でよろしいですか」とお伝えしました。断ったつもりでした。\u003cbr\u003e\u003cbr\u003eその方は翌朝に来てくださって、「そう言ってもらえるほうが安心する」とおっしゃいました。そこから、置く量を思い切って減らして、無いときは無いと言うようにしました。捨てる量は5分の1になり、常連の方はむしろ増えました。","showButton":false,"buttonText":"","buttonUrl":"","buttonRadius":0} -->
<div class="wp-block-wdl-paid-block-content-6 paid-block-content-6"><div class="this_wrap right_img"><div class="image"><figure><img src="https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/fl_work.webp" alt="花を束ねているところ"/></figure></div><div class="cont"><p><strong style="display:block;font-size:20px;margin-bottom:10px;color:#6a3123">「今日は無い」と言うことにした</strong>2年目の春、常連の方に「明日、母に持っていきたい」と言われて、その場で在庫を見て「今日は良いものが無いので、明日の朝に入る分でよろしいですか」とお伝えしました。断ったつもりでした。<br><br>その方は翌朝に来てくださって、「そう言ってもらえるほうが安心する」とおっしゃいました。そこから、置く量を思い切って減らして、無いときは無いと言うようにしました。捨てる量は5分の1になり、常連の方はむしろ増えました。</p></div></div></div>
<!-- /wp:wdl/paid-block-content-6 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":80,"tbHeight":64,"spHeight":40} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:80px"></div><div class="tb" style="height:64px"></div><div class="sp" style="height:40px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/paid-block-custom-title-8 {"subTitle":"OUR RULES","mainTitle":"いま決めていること","headingLevel":2,"mainTitleColor":"#6a3123","borderLeftColor":"#b0604a","borderRightColor":"#b0604a","borderLeftOpacity":100,"borderRightOpacity":25,"borderRadius":4,"sizeClass":"size_m","positionClass":"position_left","sizeSpClass":"size_s"} -->
<div class="wp-block-wdl-paid-block-custom-title-8 paid-block-custom-title-8 size_m size_s position_left"><h2 class="ttl"><span class="sub" style="color:#6a3123">OUR RULES</span><span class="main">いま決めていること</span><span class="border_wrap"><span class="border_inner" style="border-radius:4px"><span class="border left" style="background-color:#b0604a;opacity:1"></span><span class="border right" style="background-color:#b0604a;opacity:0.25"></span></span></span></h2></div>
<!-- /wp:wdl/paid-block-custom-title-8 -->
<!-- wp:wdl/lw-space-1 {"pcHeight":16,"tbHeight":16,"spHeight":12} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:16px"></div><div class="tb" style="height:16px"></div><div class="sp" style="height:12px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:paragraph {"align":"center","style":{"color":{"text":"#3b342f"},"typography":{"fontSize":"16px","lineHeight":"2"},"spacing":{"margin":{"top":"28px","bottom":"24px"}}}} -->
<p class="has-text-align-center has-text-color" style="color:#3b342f;font-size:16px;line-height:2;margin-top:28px;margin-bottom:24px">大きな理念ではなく、毎日守れることだけを3つ決めています。</p>
<!-- /wp:paragraph -->
<!-- wp:wdl/lw-list-4 {"colorLiSvg":"#7f4535","borderColor":"#eddfd8","borderWidth":1,"textColor":"#3b342f","bgColor":"#ffffff","maxWidth":760,"colClass":"clm_1"} -->
<div class="wp-block-wdl-lw-list-4 lw-list-4"><ul class="lw-list-4__inner clm_1 " style="border-color:#eddfd8;border-width:1px;border-style:solid;border-radius:0.5em;max-width:760px;background-color:#ffffff"><li class="lw-list-4__li size_m"><span class="icon" style="width:1.2em"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" style="fill:#7f4535"><path d="M64 80c-8.8 0-16 7.2-16 16l0 320c0 8.8 7.2 16 16 16l320 0c8.8 0 16-7.2 16-16l0-320c0-8.8-7.2-16-16-16L64 80zM0 96C0 60.7 28.7 32 64 32l320 0c35.3 0 64 28.7 64 64l0 320c0 35.3-28.7 64-64 64L64 480c-35.3 0-64-28.7-64-64L0 96zM337 209L209 337c-9.4 9.4-24.6 9.4-33.9 0l-64-64c-9.4-9.4-9.4-24.6 0-33.9s24.6-9.4 33.9 0l47 47L303 175c9.4-9.4 24.6-9.4 33.9 0s9.4 24.6 0 33.9z"></path></svg></span><span class="lw-list-4__text"><p data-lw_font_set="" style="color:#3b342f;width:calc(100% - 1.2em)">無いときは無いと言う（良い状態で無い日は、そのままお伝えします）</p></span></li><li class="lw-list-4__li size_m"><span class="icon" style="width:1.2em"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" style="fill:#7f4535"><path d="M64 80c-8.8 0-16 7.2-16 16l0 320c0 8.8 7.2 16 16 16l320 0c8.8 0 16-7.2 16-16l0-320c0-8.8-7.2-16-16-16L64 80zM0 96C0 60.7 28.7 32 64 32l320 0c35.3 0 64 28.7 64 64l0 320c0 35.3-28.7 64-64 64L64 480c-35.3 0-64-28.7-64-64L0 96zM337 209L209 337c-9.4 9.4-24.6 9.4-33.9 0l-64-64c-9.4-9.4-9.4-24.6 0-33.9s24.6-9.4 33.9 0l47 47L303 175c9.4-9.4 24.6-9.4 33.9 0s9.4 24.6 0 33.9z"></path></svg></span><span class="lw-list-4__text"><p data-lw_font_set="" style="color:#3b342f;width:calc(100% - 1.2em)">置く量を増やさない（店に並ぶ本数は開店当初の3分の1です）</p></span></li><li class="lw-list-4__li size_m"><span class="icon" style="width:1.2em"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" style="fill:#7f4535"><path d="M64 80c-8.8 0-16 7.2-16 16l0 320c0 8.8 7.2 16 16 16l320 0c8.8 0 16-7.2 16-16l0-320c0-8.8-7.2-16-16-16L64 80zM0 96C0 60.7 28.7 32 64 32l320 0c35.3 0 64 28.7 64 64l0 320c0 35.3-28.7 64-64 64L64 480c-35.3 0-64-28.7-64-64L0 96zM337 209L209 337c-9.4 9.4-24.6 9.4-33.9 0l-64-64c-9.4-9.4-9.4-24.6 0-33.9s24.6-9.4 33.9 0l47 47L303 175c9.4-9.4 24.6-9.4 33.9 0s9.4 24.6 0 33.9z"></path></svg></span><span class="lw-list-4__text"><p data-lw_font_set="" style="color:#3b342f;width:calc(100% - 1.2em)">値段を先に言う（束ね始める前に、必ず金額をお伝えします）</p></span></li></ul></div>
<!-- /wp:wdl/lw-list-4 -->
<!-- wp:paragraph {"align":"center","style":{"color":{"text":"#63584f"},"typography":{"fontSize":"14px","lineHeight":"1.9"},"spacing":{"margin":{"top":"16px","bottom":"0px"}}}} -->
<p class="has-text-align-center has-text-color" style="color:#63584f;font-size:14px;line-height:1.9;margin-top:16px;margin-bottom:0px">※ 代わりのご提案はしますが、無理にはお勧めしません。少なく見える日もありますが、そのぶん最後まで持ちます。</p>
<!-- /wp:paragraph -->
<!-- wp:wdl/lw-space-1 {"pcHeight":80,"tbHeight":64,"spHeight":40} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:80px"></div><div class="tb" style="height:64px"></div><div class="sp" style="height:40px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-bg-1 {"backgroundType":"image","imagePc":"","imageSp":"","isFullWidth":true,"maxWidth":1040,"minHeightPc":"min-h-pc-150px","minHeightTb":"min-h-tb-160px","minHeightSp":"min-h-sp-160px","innerPaddingTopPc":80,"innerPaddingBottomPc":80,"innerPaddingLeftPc":40,"innerPaddingRightPc":40,"innerPaddingTopTb":64,"innerPaddingBottomTb":64,"innerPaddingLeftTb":32,"innerPaddingRightTb":32,"innerPaddingTopSp":48,"innerPaddingBottomSp":48,"innerPaddingLeftSp":20,"innerPaddingRightSp":20,"filterTypePc":"solid","filterColorPc":"#fbf3ef","opacityPc":1,"filterTypeTb":"solid","filterColorTb":"#fbf3ef","opacityTb":1,"filterTypeSp":"solid","filterColorSp":"#fbf3ef","opacitySp":1} -->
<div class="wp-block-wdl-lw-bg-1 lw-bg-1 min-h-pc-150px min-h-tb-160px min-h-sp-160px bg_all" style="--lw-bg-color-filter-pc:#fbf3ef;--lw-bg-opacity-pc:1;--lw-bg-color-filter-tb:#fbf3ef;--lw-bg-opacity-tb:1;--lw-bg-color-filter-sp:#fbf3ef;--lw-bg-opacity-sp:1;--lw-bg-position-pc:50% 50%;--lw-bg-position-sp:50% 50%;--lw-bg-wrap-centering-pc:center;--lw-bg-wrap-align-pc:center;--lw-bg-wrap-centering-tb:center;--lw-bg-wrap-align-tb:center;--lw-bg-wrap-centering-sp:center;--lw-bg-wrap-align-sp:center"><div class="lw-bg-1-wrap" style="--lw-bg-padding-top-pc:80px;--lw-bg-padding-bottom-pc:80px;--lw-bg-padding-left-pc:40px;--lw-bg-padding-right-pc:40px;--lw-bg-padding-top-tb:64px;--lw-bg-padding-bottom-tb:64px;--lw-bg-padding-left-tb:32px;--lw-bg-padding-right-tb:32px;--lw-bg-padding-top-sp:48px;--lw-bg-padding-bottom-sp:48px;--lw-bg-padding-left-sp:20px;--lw-bg-padding-right-sp:20px;--lw-bg-max-width:1040px"><!-- wp:heading {"level":3,"style":{"color":{"text":"#6a3123"},"typography":{"fontSize":"24px","lineHeight":"1.6"},"spacing":{"margin":{"top":"0px","bottom":"16px"}}},"textAlign":"center"} -->
<h3 class="has-text-align-center has-text-color" style="color:#6a3123;font-size:24px;line-height:1.6;margin-top:0px;margin-bottom:16px">ご予算だけ決めてください</h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"style":{"color":{"text":"#3b342f"},"typography":{"fontSize":"16px","lineHeight":"1.9"}},"align":"center"} -->
<p class="has-text-align-center has-text-color" style="color:#3b342f;font-size:16px;line-height:1.9">「3,000円くらいで、母の退院祝いに」だけで十分です。その日にいちばん良い花で束ねます。お渡しする相手とその日の天気をうかがえれば、もう少し合わせられます。</p>
<!-- /wp:paragraph -->
<!-- wp:wdl/lw-space-1 {"pcHeight":24,"tbHeight":20,"spHeight":16} -->
<div class="wp-block-wdl-lw-space-1 lw_space_1"><div class="pc" style="height:24px"></div><div class="tb" style="height:20px"></div><div class="sp" style="height:16px"></div></div>
<!-- /wp:wdl/lw-space-1 -->
<!-- wp:wdl/lw-pr-qa-3 {"maxWidth":860,"qLabelColor":"#7f4535","aLabelColor":"#63584f","lineColor":"#eddfd8"} -->
<div class="wp-block-wdl-lw-pr-qa-3 lw-pr-qa-3" style="--qa3-max-w:860px;--qa3-gap:24px;--qa3-label-w:32px;--qa3-q-color:#7f4535;--qa3-a-color:#63584f;--qa3-line:#eddfd8;--qa3-label-size-pc:18px;--qa3-label-size-sp:16px;--qa3-q-size-pc:17px;--qa3-q-size-sp:15px;--qa3-a-size-pc:15px;--qa3-a-size-sp:14px"><dl class="qa-3__item"><dt><span class="label" data-lw_font_set="Roboto">Q</span><p class="qa-3__q_text">花の種類を指定できますか。</p></dt><dd><span class="label" data-lw_font_set="Roboto">A</span><p class="qa-3__a_text">できます。ただ、その日に良い状態のものが無ければ正直にお伝えします。どうしてもという花があるときは、3日前までにお知らせいただければ市場で探します。</p></dd></dl><dl class="qa-3__item"><dt><span class="label" data-lw_font_set="Roboto">Q</span><p class="qa-3__q_text">予算だけ伝えて、あとはおまかせでもいいですか。</p></dt><dd><span class="label" data-lw_font_set="Roboto">A</span><p class="qa-3__a_text">いちばん多いご注文の仕方です。お渡しする相手とその場面だけうかがえれば、こちらで束ねます。色の好き嫌いがあればそれも教えてください。</p></dd></dl><dl class="qa-3__item"><dt><span class="label" data-lw_font_set="Roboto">Q</span><p class="qa-3__q_text">当日に取りに行けますか。</p></dt><dd><span class="label" data-lw_font_set="Roboto">A</span><p class="qa-3__a_text">16時までのご連絡なら、その日のうちにご用意します。大きな花束や、鉢もののご注文は前日までにお願いしています。</p></dd></dl></div>
<!-- /wp:wdl/lw-pr-qa-3 --></div></div>
<!-- /wp:wdl/lw-bg-1 -->
<!-- wp:wdl/cta-2 {"phoneNumber":"000-000-0000","mailUrl":"mailto:info@example.com","backgroundImage":"https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/fl_fv.webp","filterColor":"rgba(63, 32, 24, 0.70)","buttonBackgroundColor":"#ffffff","buttonTextColor":"#6a3123"} -->
<div class="wp-block-wdl-cta-2 wp-block-wdl-cta-2 "><div class="cta-2" style="background-image:url(https://liteword-assets.bigi-ishikawa.workers.dev/t/sec/fl_fv.webp)"><div class="cta-2__wrap"><h2 class="title">ご注文・ご相談</h2><p class="address">〒000-0000 ◯◯県◯◯市◯◯町0-0-0／定休日 月曜・第3火曜</p><nav><a href="tel:000-000-0000" class="tel" data-lw_font_set="Roboto"><div class="no"><div class="small">TEL:</div><div class="big">000-000-0000</div></div><p class="tel_text">（受付時間／10:00〜18:30　当日のご注文は16:00まで）</p></a><a href="mailto:info@example.com" class="mail" style="background-color:#ffffff;color:#6a3123"><div class="icon" style="fill:#6a3123"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M64 112c-8.8 0-16 7.2-16 16l0 22.1L220.5 291.7c20.7 17 50.4 17 71.1 0L464 150.1l0-22.1c0-8.8-7.2-16-16-16L64 112zM48 212.2L48 384c0 8.8 7.2 16 16 16l384 0c8.8 0 16-7.2 16-16l0-171.8L322 328.8c-38.4 31.5-93.7 31.5-132 0L48 212.2zM0 128C0 92.7 28.7 64 64 64l384 0c35.3 0 64 28.7 64 64l0 256c0 35.3-28.7 64-64 64L64 448c-35.3 0-64-28.7-64-64L0 128z"/></svg></div><div class="mail_text">メールで相談する</div></a></nav></div><div class="bg_filter" style="background-color:rgba(63, 32, 24, 0.70)"></div></div></div>
<!-- /wp:wdl/cta-2 -->